### ISSUE TITLE
Usage examples in documentation

### ISSUE THREAD

**Issue by srameshr** [ant-design/ant-design-mobile-rn#100]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
Mac OS 10.13.2, N/A, 0.55

### Reproduction link
[https://rn.mobile.ant.design/components/popover/](https://rn.mobile.ant.design/components/popover/)

### Steps to reproduce
The documentation does not include any demo code on how to use the component along with GIF or pictures of the component. 

### What is expected?
Include simple component usage info along with GIF/Pictures for every component

### What is actually happening?
The documentation does not include any demo code on how to use the component along with GIF or pictures of the component.

**Comment by bang88** [comment]
@srameshr I have updated a working example of Button component. It use sandbox and `react-native-web` for preview. If you have interest in this PR are always welcome.

😄

**Comment by bang88** [comment]
Master branch

**Comment by bang88** [comment]
Track #119
