### ISSUE TITLE
Popover 动画闪烁

### ISSUE THREAD

**Issue by helsonxiao** [ant-design/ant-design-mobile-rn#1003]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/toast-cn/](https://rn.mobile.ant.design/components/toast-cn/)

### Steps to reproduce
- 在安卓系统初次点击 Popover，弹出时会闪一下，然后再正常显示。第二次以后点击正常。
- 在 iOS 中点击 Popover 正常，但是在关闭时也有闪烁问题。
- 在关闭时会看到 Pop 倒过来，好像和使用的 easing 有关系，这点没有非常确认。

### What is expected?
正常显示动画

### What is actually happening?
有 bug 无法开启动画

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 0.61.4 |
| System | Android 8.0 |
| Browser | null |

---
初步浏览了代码，问题在于 react-native-modal-popover。从 issues 来看这个库已经没人维护了。可以的话我 fork 以后尝试修复然后发个新包，或者直接拖进这个项目，因为代码量不多，主要是基于 Modal 的封装。

已经在两个系统上跑过 demo 代码了，问题是一样的，下面是业务场景的 GIF（可能不够清楚，在 tab 切换之后第一次点击 popover 会闪一下），实际体验很差所以只能把动画关掉了。

![Gif_20200827_163939](https://user-images.githubusercontent.com/26411634/91418086-4342cd80-e884-11ea-97f1-4cdf92692e25.gif)

**Comment by 1uokun** [comment]
还有这个问题顺便修复下✌️

![Aug-28-2020 10-11-45](https://user-images.githubusercontent.com/28673261/91513447-f1975300-e916-11ea-9c2e-29ce22440ed2.gif)

**Comment by helsonxiao** [comment]
> 还有这个问题顺便修复下✌️
> 
> ![Aug-28-2020 10-11-45](https://user-images.githubusercontent.com/28673261/91513447-f1975300-e916-11ea-9c2e-29ce22440ed2.gif)

这个怎么复现呢？

另外我反馈的这个问题在当前项目环境下（ RN `0.62.2` ）没法复现了 ... 可能是 RN Modal 的 bug，因为我在 `0.61.4` 里直接复制了这个 demo 跑的，确定有 bug。

**Comment by helsonxiao** [comment]
> 还有这个问题顺便修复下✌️
> 
> ![Aug-28-2020 10-11-45](https://user-images.githubusercontent.com/28673261/91513447-f1975300-e916-11ea-9c2e-29ce22440ed2.gif)

已经确定升级 `0.62` 后没有问题，这个 issue 我先 close 了？
