### ISSUE TITLE
Toast display time is much shorter than the set duration

### ISSUE THREAD

**Issue by PinelliaTime** [ant-design/ant-design-mobile-rn#1004]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
Toast.success('录入成功！', 2)

### What is expected?
What I expect is Toast display time is 2 seconds

### What is actually happening?
Toast display time is only a few hundred milliseconds

| Environment | Info |
|---|---|
| antd | 3.2.2 |
| React | react-native 0.59.10 |
| System | android |
| Browser | chrome 84.0.4147.105 |

**Comment by 1uokun** [comment]
no debugger and upgrade RN

https://github.com/facebook/react-native/issues/4470
