### ISSUE TITLE
设置 activeStyle 不起作用

### ISSUE THREAD

**Issue by youngjuning** [ant-design/ant-design-mobile-rn#101]
https://github.com/ant-design/ant-design-mobile-rn/blob/39ce4e51d1d4fd8af555122ae49de21fa257f15b/components/button/demo/basic.native.tsx#L32

**Comment by youngjuning** [comment]
@sorrycc

**Comment by youngjuning** [comment]
@popomore @yesmeck @afc163 @ibigbug

**Comment by davidzhang12138** [comment]
same

**Comment by zhaozhiming** [comment]
我看了源码，里面只把activeStyle这个属性当boolean来用，并不能设置对象  
https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/button/index.native.tsx#L107-L109

**Comment by youngjuning** [comment]
我自己发了一个库，暴露了一些有用的属性。。antd-mobile-rn-responsive。可以参考下实现方式，npm publish 一个符合自己需求的库

**Comment by bang88** [comment]
try 2.3.0
