### ISSUE TITLE
RN 0.6版本可以自动加载字体了吧

### ISSUE THREAD

**Issue by qianzhangsheng** [ant-design/ant-design-mobile-rn#1016]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-native-community/cli/blob/master/docs/autolinking.md](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md)

### Steps to reproduce
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.

### What is expected?
能不能在文档上加一下RN0.60版本取消了link，改为自动加载的提示

### What is actually happening?
能不能在文档上加一下RN0.60版本取消了link，改为自动加载的提示

| Environment | Info |
|---|---|
| antd | undefined |
| React | 0.63.2 |
| System | macOS 10.15.6 (19G2021) |
| Browser | chrome 85.0.4183.102 |

**Comment by 1uokun** [comment]
@ant-design/icons-react-native@2.2.1 以下版本还不能自动link(assets文件类型都不支持自动link)
## 链接字体图标
```diff
- react-native link @ant-design/icons-react-native
+ react-native link @ant-design/react-native
```

**Comment by wgh970312** [comment]
@1uokun 2.2.1的好像也没有自动链接，我这还是显示的X

**Comment by 1uokun** [comment]
@bang88 文档里“链接字体图标”提供的命令无效，（提了PR，review一下:https://github.com/ant-design/ant-design-icons/pull/429)

> @ant-design/icons-react-native@2.2.1 **及**以下版本还不能自动link(assets文件类型都不支持自动link)
> 
> ## 链接字体图标
> ```diff
> - react-native link @ant-design/icons-react-native
> + react-native link @ant-design/react-native
> ```
