### ISSUE TITLE
ActionSheet 弹出时，按下 android 的 back 键，ActionSheet 没有关闭/When ActionSheet  pops up, press android's back key, ActionSheet  is not closed

### ISSUE THREAD

**Issue by Cupidor** [ant-design/ant-design-mobile-rn#1017]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
 ActionSheet.showActionSheetWithOptions(
      {
        title: '更多操作',
        message: '',
        options: BUTTONS,
        cancelButtonIndex: 2,
        destructiveButtonIndex: 1,
      },
      (buttonIndex) => {
    
      },
    );
// 按下安卓返回键回到上一个页面，而  ActionShee 任然存在。
// Press the Android Back button to go back to the previous page, and the  ActionSheet will still exist.

### What is expected?
期望当 ActionSheet弹起时，按下安卓返回键可以拦截 ActionSheet状态，关闭 modal。
It is expected that when the ActionSheet pops up, pressing the Android return key will intercept the ActionSheet state and close the ActionSheet.

### What is actually happening?
返回上个页面， ActionSheet仍然存在
static close() - programmatically close. is nit work

| Environment | Info |
|---|---|
| antd | undefined |
| React | 3.3.0 |
| System | Android 8.1.0 |
| Browser | 无 |

**Comment by 1uokun** [comment]
您可以外部添加代码实现
监听返回键，并执行ActionSheet有开放的`close()`方法

**Comment by Cupidor** [comment]
> 您可以外部添加代码实现
> 监听返回键，并执行ActionSheet有开放的`close()`方法

ActionSheet.close()么，我在组件卸载的时候调用了，没有效果

**Comment by 1uokun** [comment]
> > 您可以外部添加代码实现
> > 监听返回键，并执行ActionSheet有开放的`close()`方法
> 
> ActionSheet.close（）么，我在组件卸载的时候调用了，没有效果

非常抱歉 3.x版本确实是有这个bug，请及时更新ant-design版本或者使用其他库代替
