### ISSUE TITLE
not found react-native-safe-area-view模块

### ISSUE THREAD

**Issue by Evan-Future** [ant-design/ant-design-mobile-rn#1023]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce
从antd-rn版本3.x升级到4.0.5后，重新npm 及 pod 后无法运行了，提示错误：react-native-safe-area-view无法找到，我看其他小伙伴的测试都是在RN的最新版本下测试的，demo中的版本也是^0.62.2以上版本。是不是antd4.x对RN有最低版本要求？如果特别说明下。

此次升级主要是解决 Tabs在Android下卡顿及underline错位问题。如果无法升级RN版本，有什么好的方法可以解决Tabs问题？

### What is expected?
解决Tabs在Android系统下卡顿和错位问题

### What is actually happening?
无法运行，缺少react-native-safe-area-view组件库

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 0.61.3 |
| System | macOS |
| Browser | chrome |

**Comment by Evan-Future** [comment]
另外说明下，Tabs升级到4.0.5的版本下，切换还是有问题，RN版本是从0.61.3升级到0.63.2了，去掉了Flipper，感觉Tabs的切换在IOS上也感觉无动画，卡卡的。之前0.61.3 antd3.x版本下IOS是流畅的

**Comment by 1uokun** [comment]
Duplicate of https://github.com/ant-design/ant-design-mobile-rn/issues/907
