### ISSUE TITLE
ImagePicker exception in Expo Project - Cannot read Property 'getPhotos' of undefined

### ISSUE THREAD

**Issue by aungkyawpike** [ant-design/ant-design-mobile-rn#1033]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
Open the app in Andriod
Click the Image Picker button to choose a photo
Exception throw Cannot read Property 'get photos' of undefined

### What is expected?
Expect Image Picker RN is working for Expo Project too

### What is actually happening?
Expect Image Picker RN is working for Expo Project too

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz |
| System | Window |
| Browser | Andriod Emulator, Andriod |

![k4TsdKl1QJ](https://user-images.githubusercontent.com/2571577/94126168-da05a880-fe89-11ea-8061-edc51348855e.png)

**Comment by 1uokun** [comment]
Same issue https://github.com/react-native-community/react-native-cameraroll/issues/106
