### ISSUE TITLE
The Model has a slight wobble on Android and iPhone

### ISSUE THREAD

**Issue by caijiami** [ant-design/ant-design-mobile-rn#1038]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://apps.apple.com/cn/app/%E4%B9%A0%E6%83%AF%E5%85%AC%E7%A4%BE-%E5%AD%A6%E6%A0%A1%E7%89%88/id1526087997](https://apps.apple.com/cn/app/%E4%B9%A0%E6%83%AF%E5%85%AC%E7%A4%BE-%E5%AD%A6%E6%A0%A1%E7%89%88/id1526087997)

### Steps to reproduce
The Model has a slight wobble on Android and iPhone

### What is expected?
The Model has a slight wobble on Android and iPhone

### What is actually happening?
The model not shake

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React |  "react": "16.11.0",     "react-native": "0.62.0", |
| System | 华为和苹果高版本手机 |
| Browser | app |

---
AntModal.prompt(
      I18n.t('editBranchName'),
      '',
      password => {
       
      },
      'default',
      null,
      [I18n.t('pleaseEnterBranchName')],
    )

**Comment by 1uokun** [comment]
So designed
设计如此
