### ISSUE TITLE
SearchBar的wrapper的背景色无法修改

### ISSUE THREAD

**Issue by zhazihong** [ant-design/ant-design-mobile-rn#1075]
我的App页面上的背景色是'#f9f9f9'，SearchBar的wrapper的背景色是theme.search_bar_fill,
`
 wrapper: {
            backgroundColor: theme.search_bar_fill,
            height: theme.search_bar_height,
            paddingLeft: theme.h_spacing_md,
            paddingRight: theme.h_spacing_md,
            flexDirection: 'row',
            alignItems: 'center'
        },

// search_bar
    search_bar_fill: '#efeff4',
`
能否可以将wrapper的样式也设置成可配置的？

**Comment by Jidahan** [comment]
这个问题有解决方案吗，我也有这个问题
