### ISSUE TITLE
SearchBar包装器背景色无法修改

### ISSUE THREAD

**Issue by PhoenixLeeSin** [ant-design/ant-design-mobile-rn#1080]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
SearchBar包装器背景色无法修改，导致和App本身背景色不同

### What does the proposed API look like?
SearchBar包装器背景色可以修改

**Comment by Jidahan** [comment]
这个有解决方案吗，我也有这个问题

**Comment by Jidahan** [comment]
@1uokun @PhoenixLeeSin
