### ISSUE TITLE
点击推送进入其他页面，DatePicker没有消失，依然显示在跳转后页面中

### ISSUE THREAD

**Issue by action456789** [ant-design/ant-design-mobile-rn#1081]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/action456789/pen/NWrJdKe](https://codepen.io/action456789/pen/NWrJdKe)

### Steps to reproduce
1. 页面A打开时间选择器
2. 收到推送消息，点击推送进入页面B

### What is expected?
页面B，下方时间选择器应该关闭

### What is actually happening?
页面B，下方时间选择器没有关闭

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.61.5 |
| System | iOS 13.6 |
| Browser | 无 |

---
页面路由变化，DatePicker应该在内部关闭自己

**Comment by 1uokun** [comment]
# props: visible & onVisibleChange
1.如果是按照demo里面的使用方式的话，需要`onVisibleChange`和`visible`配合使用

```diff
          <DatePicker
+           visible={this.state.visible}
+           onVisibleChange={(visible:boolean)=>{this.setState({visible})}}
            value={this.state.value}
            mode="date"
            defaultDate={new Date()}
            minDate={new Date(2015, 7, 6)}
            maxDate={new Date(2026, 11, 3)}
            onChange={this.onChange}
            format="YYYY-MM-DD"
          >
            <List.Item arrow="horizontal" >Select Date</List.Item>
          </DatePicker>
```
1.1 在路由跳转或者`unmount`时将`this.state.visible`改为`false`
```js
          componentWillUnmount(){
            this.setState({visible:false})
          }
```


2. 如果`<DatePicker/>`这种用法，似乎一个`visible`就可以了
# Picker
所有Picker都适用这种操作
