### ISSUE TITLE
ListView 无法获取getRows方法

### ISSUE THREAD

**Issue by lengqingfeng** [ant-design/ant-design-mobile-rn#1086]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/list-view-cn/](https://rn.mobile.ant.design/components/list-view-cn/)

### Steps to reproduce
ref 后 获取getRows

### What is expected?
获取到方法

### What is actually happening?
获取不到getRows方法

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React |     "react": "16.13.1",     "react-native": "0.63.3", |
| System | iOS  |
| Browser | 谷歌 |

**Comment by 1uokun** [comment]
在这里面：`listview.ulv`
```
<ListView ref="listview">

this.refs.listview.ulv.getRows()
```
