### ISSUE TITLE
InputItem 怎么修改字体大小？？？这个项目还维护吗？

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile-rn#109]
这个项目还维护吗？
InputItem 怎么修改字体大小？？？

**Comment by youngjuning** [comment]
@suwu150 我有一个不成熟的小建议，要么弃坑，要么使用 antd-mobile-rn-responsive。我不会ts，是基于编译后的js代码修改的，你的这个需求我会考虑的。

**Comment by bang88** [comment]
@suwu150 Please tracking #119 which have a plan for Theming improvements
