### ISSUE TITLE
modal兼容性问题 会在屏幕上抖动  无法提供连接

### ISSUE THREAD

**Issue by looklookcode** [ant-design/ant-design-mobile-rn#1095]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/issues/new](https://github.com/ant-design/ant-design-mobile-rn/issues/new)

### Steps to reproduce
直接使用modal

### What is expected?
modal不会抖动

### What is actually happening?
modal会抖动

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 0.59.9 |
| System | iphone xs max |
| Browser | 无 |

**Comment by looklookcode** [comment]
不好意思 因为在移动产品上 无法提供具体的复现链接  简单的步骤就是使用modal就会抖动

**Comment by zim-lee** [comment]
@1uokun 也遇到了，真机环境下footer部分会抖动，大佬能否发个patch包？

**Comment by bang88** [comment]
@zim-lee 4.0.7

**Comment by looklookcode** [comment]
> @zim-lee 4.0.7
感谢 ant design mobile rn的官网好像挂了 我想再咨询一下这个官网的框架是使用的什么呀？

**Comment by looklookcode** [comment]
> @zim-lee 4.0.7

@bang88 hi 感谢，现在ant designmobile rn的官网是不是挂了 ，想咨询一下官网是用什么搭建的呀
