### ISSUE TITLE
Toast在Modal中看不见

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile-rn#110]
Toast在Modal中看不见，当我弹出一个react-native中的Modal之后，我再去弹Toast的时候，Toast看不见？

**Comment by bang88** [comment]
这个目前好像用js做不了， Modal的层级太高，等react-native的后续版本看看有没有办法。

**Comment by wSLecHayfIeNdock** [comment]
把 `Modal` **封装装一层**后，`InputItem` 作为 `children` 传入使用，`clear` 配置项无效。

@bang88 请问这是什么问题呢？

**Comment by bang88** [comment]
没有报错吗？这个应该跟Modal没什么关系吧。

**Comment by youngjuning** [comment]
请问如何实现 Toast 在Modal之上显示 @bang88 
![image](https://user-images.githubusercontent.com/13204332/57447117-da97a200-7288-11e9-9393-aa4c5b18455f.png)

**Comment by hanwenbo** [comment]
@youngjuning 实现那不了的  文档虽然写的可以  但是真正测试是不存在的

**Comment by hanwenbo** [comment]
@bang88 @sorrycc 请问这个Toast 支持在Modal之上显示如何做到？  我测试了好多种方法都不可以

**Comment by youngjuning** [comment]
@hanwenbo 我把 `title` props 设置成 `Text` 标签，然后在 `Text` 的 `onPress` props 中 Toast。就可以符合文档描述了。但是这好像没什么用啊

**Comment by youngjuning** [comment]
@bang88 求解释，这个的正确打开方式

**Comment by bang88** [comment]
Modal是使用Ant里面的Modal吗？

**Comment by youngjuning** [comment]
是原生的Modal

**Comment by bang88** [comment]
原生现在都没有办法的，之前写了一个解决原生Modal上显示 Toast的模块，https://github.com/merryjs/toast

**Comment by wubo49494** [comment]
https://juejin.im/post/5dd49dc96fb9a01fe5201408

**Comment by wubo49494** [comment]
3.0.0 以上的版本要把组件放在 Provider 标签中，不然Toast 不会出现

**Comment by adouwt** [comment]
Toast 提示可以指定容器，可以指定modal 中的body
Toast.show({
        content: '操作成功',
        getContainer: document.querySelector('#modalBody')
})
