### ISSUE TITLE
Picker 选择器的头部和选中的itme是否有方法更改他们的样式

### ISSUE THREAD

**Issue by yfs-2000** [ant-design/ant-design-mobile-rn#1100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这个要求我觉得是很普遍的需求 因为头部的2个确定和取消占据的位置过大 应该是直接flex：1导致的？导致中间可用位置被严重压缩，选中的样式最好可以更改  这样更符合高定制化的需求

### What does the proposed API look like?
头部组件是否可以直接自定义传入一个组件覆盖？选中的item加上一个新api？  这些应该非常轻松

**Comment by yfs-2000** [comment]
自己写了一个  放弃使用这个组件了

**Comment by 1uokun** [comment]
Duplicate of https://github.com/ant-design/ant-design-mobile-rn/issues/1072
