### ISSUE TITLE
add rtl support 

### ISSUE THREAD

**Issue by amirjr1378** [ant-design/ant-design-mobile-rn#1106]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
rtl development for rtl languages like arabic or ...

### What does the proposed API look like?
in ant design web i can achieve this goal by wrapping my app inside of a config provider like this:

import { ConfigProvider } from 'antd';
return <ConfigProvider locale={faIR} direction="rtl"><App /></ConfigProvider >

**Comment by 1uokun** [comment]
# 如何自定义本地化语言

- 最外层**必须**由`<Provider>`包裹着
- 然后自定义`locale`数据，数据结构**必须**参考 [Locale interface](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/locale-provider/index.tsx#L2)
    ```JavaScript
    <Provider locale={
       {
          locale: "rtl",
          Pagination: {
            /** 上一页 */
            prevText: " الصفحة السابقة ",
            /** 下一页 */
            nextText: "الصفحة التالية"
         }
      }
    }>
     <Pagination total={5} current={1} />
   </Provider>
   ```
- **内部组件**（仅部分内部组件支持）
   自定义`locale`props（优先级高于Provider提供的数据）
   ```JavaScript
    <Pagination locale={{prevText:"prev",nextText:"next"}} total={5} current={1} />
    ```
- **自定义组件**
   可通过添加`contextType`内的`antLocale`获得本地化语言（老版本）
   ```JavaScript
   class A extends React.Component {
       static contextTypes = {
           antLocale: PropTypes.object,
       };
       render(){
           console.log(this.context) // {antLocale: {...Locale interface}}
           return (
               <View />
           )
       }
   }
   ```
   或者引入并注册`LocaleContext`(⚠️新版本未更新https://github.com/ant-design/ant-design-mobile-rn/pull/1094)
   ```JavaScript
    import { LocaleContext } form “@ant-design/react-native/lib/locale-provider”

    static contextType = LocaleContext;
   ```
  
> 💗help:needs to translate if you find this comment useful plz
