### ISSUE TITLE
ios真机 InputItem组建 type=number状态输入数字软键盘闪烁

### ISSUE THREAD

**Issue by wanxue0804** [ant-design/ant-design-mobile-rn#1107]
![真机上问题实际效果](https://user-images.githubusercontent.com/35684234/102953184-ad564100-450b-11eb-9622-aba955c325f4.jpeg)
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/input-item-cn/](https://rn.mobile.ant.design/components/input-item-cn/)

官方demo使用ios真机微信打开也会有此问题

### Steps to reproduce
前提：页面有两个输入框 一个手机号码输入框，一个密码输入框
ios真机上
1.先聚焦密码输入框，不用输入任何东西
2.再聚焦手机号码输入框，此时弹起的数字软键盘多了"密码"字样
3.手机号码输入框输入数字，此时可以看到软键盘一闪一闪

### What is expected?
期望数字输入框输入时软键盘不闪烁
我尝试用native原组建TextInput 设置为keyboardType= numeric ｜ number-pad 弹起的软键盘都没有“密码”字样，且输入时软键盘不会闪烁

### What is actually happening?
ios真机输入时软键盘闪烁

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.11.0 |
| React Native | 0.62.2 |
| System | ios 13.4 |
| Browser | app |

**Comment by erichua23** [comment]
@wanxue0804 方便的话直接贴一下你可以复现的代码吧，省去点构造复现问题的成本。

**Comment by wanxue0804** [comment]
> @wanxue0804 方便的话直接贴一下你可以复现的代码吧，省去点构造复现问题的成本。

```js
<InputItem
  placeholder='手机号码'
  type='number'
/>
<InputItem
  placeholder="请输入登录密码"
  type="password"
/>
```

<img width="753" alt="QQ20211103-142359@2x" src="https://user-images.githubusercontent.com/35684234/140017243-9f407cd6-89e8-4429-9146-8dd29ac70bc5.png">
图片红色框内区域会闪烁，这个闪烁的问题目前我们暂时解决了，方法如下
```
<InputItem
  placeholder='手机号码'
  type='number'
  textContentType='oneTimeCode'
/>
<InputItem
  placeholder="请输入登录密码"
  type="password"
  secureTextEntry
  textContentType="oneTimeCode"
/>
```




另外最近发现InputItem 输入长一点的文本换行问题，想设置不换行都不行也隐藏不了，效果如下
![QQ20211103-142625](https://user-images.githubusercontent.com/35684234/140017725-e882f839-a4ec-4e32-84f8-9b43812f1b41.png)
```
<InputItem
  placeholder="请输入搜索内容"
/>
```

此问题暂未解决，通过设置行高，父级设置高度、超出隐藏不能解决问题，只能说预览下还算正常，或者设置length，但中英文，设备宽等因素不能确定一行字数
官方的TextInput 已确认并无此问题 还望能一起修复，谢谢🙏
@erichua23

**Comment by 1uokun** [comment]
第一个「强密码」行为是rn的bug，这里有一个答案能帮你解决
https://stackoverflow.com/a/68039177/10506271

第二个InputItem不再维护了，请改用`Input`
