### ISSUE TITLE
这个项目还有人维护吗？

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design-mobile-rn#111]

**Comment by anchengjian** [comment]
哎，https://github.com/ant-design/ant-design-mobile-rn/commit/0b09e4e53bd5091823bc19ac7395568444ff1963 真是一件遗憾的事情啊

**Comment by youngjuning** [comment]
推荐使用 antd-mobile-rn-responsive：yarn add antd-mobile-rn-responsive ,我将接盘

**Comment by stonecold123** [comment]
@youngjuning 
antd-mobile-rn-responsive
typescript 很方便啊，不应该删掉

**Comment by youngjuning** [comment]
你这会ts 的话，可以拉出去啊，我当时是因为这个库暴露的属性太少了，自己加了一些属性

**Comment by murrayee** [comment]
可惜了

**Comment by xiaohuoni** [comment]
@bang88 没看到你的修改

**Comment by bang88** [comment]
没在这 😩

**Comment by esseak** [comment]
如果社区自己维护的话我觉得可以不用和antd-mobile api保持一致了，维护bug和社区投票新功能，如果大家愿意的话。 @youngjuning  @bang88

**Comment by stonecold123** [comment]
Forked了，刚动手试试，
在Accordion,List.Item 和 SegmentedControl 加了些我想要的改能

https://github.com/stonecold123/ant-design-mobile-rn/blob/master/CHANGELOG.en-US.md

**Comment by xiaohuoni** [comment]
i你们的没有报type错误？

**Comment by warmhug** [comment]
作为主要 owner，没想到社区需求这么大... 很抱歉我没时间投入维护。

> 要保持跟web版一样的API

这个肯定不是完全一样的、已有 API 也有不少不一样、按 native 自己的特点来设计 API 就好啊。
不过做的时候对照下能一样就一样也还好吧。

很欢迎 @bang88  @youngjuning 和所有有余力感兴趣的人，能一起把这个库继续维护下去，开源协作 合力拿到好成果、利人利己啊！🤝🤝💪💪

**Comment by bang88** [comment]
@warmhug 是继续在这个repo里面维护还是可以转移到别的org

**Comment by xiaohuoni** [comment]
@bang88 我觉得可以直接pr

**Comment by warmhug** [comment]
赞同 @xiaohuoni ，继续在这里吧、开新坑不方便，老用户都在这里的。
@bang88 能否作为新的 owner ？来管理版本迭代和发布，随后有更多人参与 也能像 antd 一样轮值起来。

**Comment by ztMalone** [comment]
@bang88 还有微信群？拉一下了，zt864589453。这么好的一个项目，我们应该维护起来！

**Comment by bang88** [comment]
@xiaohuoni @ztMalone 
![2018-10-15 09 54 57](https://user-images.githubusercontent.com/433259/46925794-78fbb600-d060-11e8-967e-70d05dc8395c.jpg)

**Comment by warmhug** [comment]
大大地赞 @bang88 ，微信群可以发一下，欢迎所有想 提交 commit 的朋友加入 😆😆

**Comment by pearpai** [comment]
阿里系 经常干这样的事情，还是别坚持了 免得害了自己

**Comment by bang88** [comment]
尽量利用空闲时间来维护吧，有bug急需修复的可以PR，有新功能的可以开issue讨论。
