### ISSUE TITLE
依赖包 @react-native-community/picker 更名为 @react-native-picker/picker

### ISSUE THREAD

**Issue by Yuanfang-fe** [ant-design/ant-design-mobile-rn#1120]
Reproduction link
https://www.npmjs.com/package/@react-native-community/picker

Steps to reproduce
![image](https://user-images.githubusercontent.com/11530201/103338611-e9644580-4ab9-11eb-8258-8edc52e4e541.png)

"@ant-design/react-native": "^4.0.6",
"react": "^17.0.1",
"react-native": "^0.63.4",

**Comment by mm-webx** [comment]
Same for me. Maybe related: https://github.com/oblador/react-native-vector-icons/issues/1193

<img width="440" alt="image" src="https://user-images.githubusercontent.com/34196239/104529650-7fe04d00-560a-11eb-8e9c-fe88092fe4f2.png">

"@ant-design/react-native": "^4.0.6",
"react-native": "0.63.3",
"react": "^17.0.1",

**Comment by mm-webx** [comment]
@Yuanfang-fe so Ive solution for that.

Change `@react-native-community/picker` to `@react-native-picker/picker`, because it was renamed. Now application built without any problems.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/34196239/104641083-9b4e6500-56a9-11eb-8f50-f4fdeb37b4b4.png">

**Comment by mm-webx** [comment]
Hey, when we can get new version?

**Comment by bang88** [comment]
@mm-webx I think you can use https://www.npmjs.com/package/patch-package for a quickly fixes. I don't like the react-native community changes package name one to another and that will make a breaking change for us.

**Comment by 1uokun** [comment]
@mm-webx git reset temporarily😅

**Comment by burabure** [comment]
this breaks the ios build, when will this be released? it doesn't a patch version get released every week? it has been 45 days since the last release =(

**Comment by mm-webx** [comment]
In Appcenter, patch doesn’t work correctly, so we drop ant-design for now, too many problems.

**Comment by burabure** [comment]
> @mm-webx I think you can use https://www.npmjs.com/package/patch-package for a quickly fixes. I don't like the react-native community changes package name one to another and that will make a breaking change for us.

What? it was a react native change they've been announcing for more than a year now, it's not a matter of personal preference, this is **breaking** iOS builds for everyone that's using ant-design on current react native!

this is a very bad omen for the future of this library =( I honestly wish my team didn't decide to gamble on using it, now we're stuck with a UI library that's full of issues and maintained in a very poor way

**Comment by mm-webx** [comment]
> @mm-webx I think you can use https://www.npmjs.com/package/patch-package for a quickly fixes. I don't like the react-native community changes package name one to another and that will make a breaking change for us.

The problem is, when I patch this lib, I've both `@react-native-community/picker` and `@react-native-picker/picker`, so while generating Pods we have an error - duplicate classes, because both libs using same classes. Its break a lot of things and require a lot of effort to fix it.

:+1: to upgrade version, because Ant Design Mobile RN not working atm at all.

**Comment by 1uokun** [comment]
This is problem👍

Don’t worry, we will keep updating @burabure 
if you have any valuable suggestions, please mention them on pinned issues ♥️

> > @mm-webx I think you can use https://www.npmjs.com/package/patch-package for a quickly fixes. I don't like the react-native community changes package name one to another and that will make a breaking change for us.
> 
> The problem is, when I patch this lib, I've both `@react-native-community/picker` and `@react-native-picker/picker`, so while generating Pods we have an error - duplicate classes, because both libs using same classes. Its break a lot of things and require a lot of effort to fix it.
> 
> 👍 to upgrade version, because Ant Design Mobile RN not working atm at all.

**Comment by burabure** [comment]
still no fix. iOS builds are still broken.
