### ISSUE TITLE
Can DatePicker just only be used with List? What if I wanna make a date range picker with two DatePicker in a row, and without label text, just showing date value selected?

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design-mobile-rn#113]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
mac, react-native

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
`
<Flex>
			      <Flex.Item style={{backgroundColor:'#f00'}} direction='column'>
			      	<DatePicker
			        	mode='date'
			          value={this.state.startValue}
			          onChange={this.onChange}
			          onValueChange={this.onValueChange}
			          style={{backgroundColor:'#ff0'}}
			        >
			        	<List.Item style={{backgroundColor:'#f90'}}/>
			        </DatePicker>
			      </Flex.Item>
			      <Text>到</Text>
			      <Flex.Item style={{backgroundColor:'#0f0'}}>
			      	<DatePicker
			        	mode='date'
			          value={this.state.endValue}
			          onChange={this.onChange}
			          onValueChange={this.onValueChange}
			        >
			        	<List.Item/>
			        </DatePicker>
			      </Flex.Item>
			    </Flex>
`

### What is expected?
Make a date range picker with two DatePickers in a row, and without label text, just showing date value selected.

### What is actually happening?
DatePicker seems has to be used with List, and must have a label text sharing half space?

**Comment by bang88** [comment]
Please use https://github.com/wix/react-native-calendars or others instead.
