### ISSUE TITLE
手风琴 源代码

### ISSUE THREAD

**Issue by lvwenrui12** [ant-design/ant-design-mobile-rn#1133]
class AccordionPanel extends React.Component<AccordionPanelProps, any> {
  render() {
    return null;
  }
}
panel 怎么返回是 null？

**Comment by dingziqi** [comment]
Panel 组件起到的是语义化用途，它实际的属性是在 Accordion 组件里使用的， 可以看看[这段代码](https://github.com/ant-design/ant-design-mobile-rn/blob/9ba93b043168f6576f1842570e19b5e61e3ee2ad/components/accordion/index.tsx#L78)
