### ISSUE TITLE
Debug模式下 Button onPress事件不响应（安卓）

### ISSUE THREAD

**Issue by laplacehey** [ant-design/ant-design-mobile-rn#1135]
"dependencies": {
    "@ant-design/react-native": "^4.0.7",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/cameraroll": "^4.0.2",
    "@react-native-community/segmented-control": "^2.2.2",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-community/viewpager": "^4.2.2",
    "@react-native-picker/picker": "^1.9.10",
    "react": "16.13.1",
    "react-native": "0.63.4"
  }

测试代码：
  import React from 'react'
import {View, Text} from 'react-native'
import {Button, Provider, Toast} from '@ant-design/react-native'

const App = () => (
    <Provider>
        <View style={{justifyContent: 'center', alignItems: 'center'}}>
            <Text>hello jj</Text>

            <Button
                onPress={() => {
                    console.log('点击事件')
                    Toast.info('This is a toast tips')
                }}
                type="primary">
                Start
            </Button>
        </View>
    </Provider>
)

export default App

**Comment by laplacehey** [comment]
调研进度： Button基于  TouchableHighlight 实现。 TouchableHighlight 在Debug下不响应。

**Comment by laplacehey** [comment]
Android 6.0 调试模式无法响应。Android7.1就可以了。

**Comment by jswangtao** [comment]
实测

> Android 6.0 调试模式无法响应。Android7.1就可以了。

我在安卓10之后的版本还是一样的无法响应
