### ISSUE TITLE
tabs onChange多次触发问题

### ISSUE THREAD

**Issue by lexoops** [ant-design/ant-design-mobile-rn#1142]
首先给page指定了值，然后用onChange来改变page,
但是出现滑动过快鬼畜现象，求解

**Comment by lexoops** [comment]
找到解决办法了，我猜测是指定page的缘故，我发现每次改变page的时候onChange事件总是执行2次，于是我去掉page值。
`        <Tabs
                    ref={(ref)=>{this.TabsRef =ref;}}
                    tabs={tabMeun}
                    onChange={(obj,index)=>{this.selectTab(index)}}
                    renderTabBar={()=>{return <View/>;}}>`
外部改变page使用     
  `    try {this.TabsRef.scrollTo(index);}catch (e) {}`

**Comment by 1uokun** [comment]
这类”如何起巧使用“问题建议发送到https://segmentfault.com/t/antd 和大家一起讨论
