### ISSUE TITLE
ListView 下拉刷新的时候ios不会显示loading状态，因为下拉之后回弹回去了，但触发了刷新事件

### ISSUE THREAD

**Issue by Coder108** [ant-design/ant-design-mobile-rn#1144]
![image](https://user-images.githubusercontent.com/30209569/108797954-7feb4980-75c7-11eb-8f24-25749bab451b.png)
![image](https://user-images.githubusercontent.com/30209569/108797964-8679c100-75c7-11eb-90fb-e35ab134b900.png)
放手之后刷新那个loading不会停留

**Comment by hdjhdjhdj** [comment]
大佬，下拉刷新，要怎么设置
