### ISSUE TITLE
请问下如何自定义主题

### ISSUE THREAD

**Issue by EdivenH** [ant-design/ant-design-mobile-rn#1169]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如题，全局自定义主题

### What does the proposed API look like?
如题

**Comment by 1uokun** [comment]
https://rn.mobile.ant.design/components/provider-cn/#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98%EF%BC%9F
