### ISSUE TITLE
Picker 有三列数据，其中有一列或者两列数据过长，会出现偏移问题，导致不在同一行

### ISSUE THREAD

**Issue by yuzhiyi** [ant-design/ant-design-mobile-rn#117]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
"react-native": "0.51.0"

### Reproduction link
[https://user-images.githubusercontent.com/16812579/47061309-87360780-d203-11e8-90a9-545317d3460a.png](https://user-images.githubusercontent.com/16812579/47061309-87360780-d203-11e8-90a9-545317d3460a.png)

### Steps to reproduce
https://user-images.githubusercontent.com/16812579/47061309-87360780-d203-11e8-90a9-545317d3460a.png

### What is expected?
上图的青海省/海北藏族自治区/门源回族自治区在同一条直线

### What is actually happening?
上图的青海省/海北藏族自治区/门源回族自治区没有在同一条直线上，位置出现了偏差

**Comment by sifengqingsu** [comment]
Picker这个组件，ios端用的是react-native官方的Picker组件，安卓端是用scrollview view text这几个组件来模拟的
在安卓端的Text有一个includeFontPadding属性，默认会为文字的周围添加一些padding，但是文字超出范围被省略以后，这个includeFontPadding的默认padding就消失了，会造成不起效果

**Comment by yuzhiyi** [comment]
> Picker这个组件，ios端用的是react-native官方的Picker组件，安卓端是用scrollview view text这几个组件来模拟的
> 在安卓端的Text有一个includeFontPadding属性，默认会为文字的周围添加一些padding，但是文字超出范围被省略以后，这个includeFontPadding的默认padding就消失了，会造成不起效果
> <img alt="de08151c-5db3-4abd-a057-963c51d4636e" width="406" src="https://user-images.githubusercontent.com/44091033/47075210-a5fdc380-d22e-11e8-9258-e9bf2def1bda.png">

所以解决办法是什么，麻烦提供一下解决方案

**Comment by yuzhiyi** [comment]
所以解决办法是什么，可以提供一下解决方案吗

**Comment by sifengqingsu** [comment]
> 所以解决办法是什么，可以提供一下解决方案吗

是antd-mobile-rn依赖的rmc-picker，我需要给那个库提一个pr

**Comment by yuzhiyi** [comment]
> > 所以解决办法是什么，可以提供一下解决方案吗
> 
> 是antd-mobile-rn依赖的rmc-picker，我需要给那个库提一个pr
大神，pr 有提交吗
