### ISSUE TITLE
NoticeBar是否支持horizontal，或者支持上下滚动的场景。

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#1171]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.NoticeBar目前不支持有换行文字的loop滚动，所以想到是否有考虑支持这个功能
2.有没有上下翻滚的情况？

### What does the proposed API look like?
增加一个属性horizontal，设置为 true 则变为水平布局模式。

**Comment by yrjwcharm** [comment]
他如何实现上下滚动呢
