### ISSUE TITLE
ant mobile 安装并link字体图标后   仍不显示图标问题

### ISSUE THREAD

**Issue by 15045698784** [ant-design/ant-design-mobile-rn#1175]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/checkbox-q33mv?from-embed=&file=/src/App.js)

### Steps to reproduce
调用ant mobile组件中的checkbox方法  多选框不显示   检查后发现是图标不显示。

### What is expected?
能够正确加载图标

### What is actually happening?
系统图标不显示

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | react-native: 0.64.0 |
| System | android |
| Browser | Android 模拟器 |

---
组件的代码复制到我的代码中  文字正常显示  唯独图标加载不出来

**Comment by wgh970312** [comment]
一样的问题

**Comment by bang88** [comment]
link 成功后要重新运行，xcode 或者 android
