### ISSUE TITLE
How to use navbar in react-native app

### ISSUE THREAD

**Issue by sewerrat** [ant-design/ant-design-mobile-rn#118]
I'm using **antd-mobile-rn** for my react native app. However, I cannot find **navbar** in this library. Only find **navbar** component in **antd-mobile** library , but I can't use it in my react native app. Anyone has experience about this issue? Need to use **navbar** of **other library**?

**Comment by xiaohuoni** [comment]
you can use react-navigation

**Comment by sewerrat** [comment]
It mean that currently Ant has no navbar / header component for react-native? :(

**Comment by bang88** [comment]
Yep.  you can use `react-navigation` which export a `Header` component
