### ISSUE TITLE
Install fails with react@17.0.1

### ISSUE THREAD

**Issue by owencraston** [ant-design/ant-design-mobile-rn#1180]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/owencraston/MyTestApp](https://github.com/owencraston/MyTestApp)

### Steps to reproduce
In above repo run the following install command...
- `npm install @ant-design/react-native --save`

### What is expected?
It should successfully install the package as a dependency on my app

### What is actually happening?
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: mytestapp@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8" from @react-native-community/async-storage@1.12.1
npm ERR! node_modules/@react-native-community/async-storage
npm ERR!   peer @react-native-community/async-storage@">= 1.11.0" from @ant-design/react-native@4.1.0
npm ERR!   node_modules/@ant-design/react-native
npm ERR!     @ant-design/react-native@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 17.0.1 |
| React native | 0.64.1 |
| System | MacOS Big Sur version 11.3.1 |
| Browser | Chrome |

---
`npm version 7.16.0`

**Comment by owencraston** [comment]
<img width="854" alt="Screen Shot 2021-06-07 at 7 31 45 PM" src="https://user-images.githubusercontent.com/22918444/121102679-36b4b380-c7cc-11eb-83d3-1bdd58e4f4bd.png">

**Comment by bang88** [comment]
Please check your async-storage version at first. Thank you.
