### ISSUE TITLE
Hi I am facing this issue, could you please help me

### ISSUE THREAD

**Issue by luyouwei66** [ant-design/ant-design-mobile-rn#1183]
Hi I am facing this issue, could you please help me
![image](https://user-images.githubusercontent.com/42136170/122416194-29ef4700-cfa6-11eb-9be7-558203278f23.png)

_Originally posted by @asoni14593 in https://github.com/ant-design/ant-design-mobile-rn/issues/689#issuecomment-863286883_

  render() {
    return (
      《Provider》

**Comment by lmxyjy** [comment]
看报错应该是你没有使用Provider包裹吧
