### ISSUE TITLE
Document  demo, code error

### ISSUE THREAD

**Issue by thomas-void0** [ant-design/ant-design-mobile-rn#1184]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/flex-cn/](https://rn.mobile.ant.design/components/flex-cn/)

### Steps to reproduce
open this link: https://rn.mobile.ant.design/components/flex-cn/ .you can find Demo Source Code error.
![image](https://user-images.githubusercontent.com/48620706/123024240-50303f00-d40b-11eb-9afa-9d65e40a6785.png)

### What is expected?
Normal display Demo

### What is actually happening?
TypeError
Cannot read property 'style' of undefined

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | none |
| System | macOs Big Sur 11.0.1 (20B29) |
| Browser | chrome 版本 91.0.4472.77（正式版本） (x86_64) |

**Comment by lsabbagh** [comment]
How to help in making an issue more noticeable? adding a comment? this bug existing on all the components! I believe it's urgent

**Comment by 1uokun** [comment]
4.2.0用了 `react-native-pager-view`,暂时不支持在sandbox/web中预览
见：https://github.com/callstack/react-native-pager-view/issues/377#event-4909210661

我把sandbox的`@ant-design/react-native`版本改回`3.1.15`了，
@bang88 如果需要优先保证能预览的话，合一下mr https://github.com/ant-design/ant-design-mobile-rn/pull/1186
