### ISSUE TITLE
新版计划(The new plan) 3.0.0 - Discussion

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design-mobile-rn#119]
- General
   - [x] Upgrade react-native and other dependencies to the latest version
   - [x] bug fixes
   - [x] ~~Improve the documentation (use expo to preview or provide Gif)~~ CodeSandBox

- Refactoring
   - [x] File naming (remove the native suffix)
   - [x] More friendly theme support, user-friendly
   - [x] Improve TypeScript type definitions
   - [x] Split the components in `react-component` (previously shared with the Web)

-------------------------------

- 常规
   - [x] 升级 react-native 以及其他依赖到最新版
   - [x] bug修复
   - [x] ~~完善文档（看是否可以使用expo来预览，不然就只能提供Gif了）~~ CodeSandBox

- 重构
   - [x] 文件命名（去掉native后缀）
   - [x] 更友好的主题支持，方便用户自定义
   - [x] 完善TypeScript 类型定义
   - [x] 拆分`react-component`里面的组件（之前是跟Web共用的）

**Comment by Manweill** [comment]
能换个帅气的包名吗

**Comment by bang88** [comment]
这个应该可以吧 cc @warmhug

**Comment by warmhug** [comment]
先想想什么包名比较好啊？要不投个票~ 换的话 影响还是比较大的

**Comment by bang88** [comment]
@Manweill 换的话是会有不同意见的. 换成什么也是问题.  后面开一个issue然后看看反馈可好? 这里还是先讨论一下主要问题

**Comment by Manweill** [comment]
@bang88 好
那提一个全局自定义样式的配置吧，类似Nativebase

**Comment by bang88** [comment]
想用 React 16 的context来做. 实现一个自定义的ThemeContext

**Comment by youngjuning** [comment]
主要是提供能自定义配色的功能。现在改按钮颜色太麻烦了。

**Comment by youngjuning** [comment]
主要是提供能自定义配色的功能。现在改按钮颜色太麻烦了。

**Comment by youngjuning** [comment]
还有就是 List 组件的上下border，很多场景是不需要的，grid的图片大小需要自定义，item的thumb尺寸也太小，需要自定义

**Comment by bang88** [comment]
计划里面已经有了 

> 更友好的主题支持，方便用户自定义

**Comment by bang88** [comment]
@youngjuning 可以整理一下列表这些看起来问题都不大.

**Comment by youngjuning** [comment]
期待，主要是很多有用的props都没有暴露，希望能给开发者更多的自定义权限

**Comment by 1111mp** [comment]
能支持tree组织架构树的组件吗

**Comment by Manweill** [comment]
我觉得APP上展示树结构不显示，可以做个类似文件目录那样的导航会好点

**Comment by GreatAuk** [comment]
expo 的 demo 无法查看了，还有官网怎么会这么慢😂

**Comment by afc163** [comment]
如果换包名，可以用 `@ant-design/react-native`

**Comment by yxh10** [comment]
> expo 的 demo 无法查看了，还有官网怎么会这么慢😂

可以使用，今天刚测。

**Comment by tabfed** [comment]
modal使用原生动画，还有建议动画单独整一个配置文件，现在动画还会回弹一下，不友好

**Comment by gianpaj** [comment]
For:
> Improve the documentation (use expo to preview or provide Gif)

may I suggest [Storybook](https://github.com/storybooks/storybook)?
https://storybook.js.org/basics/guide-react-native/

maybe this to automate the screenshots of all the components? 😎
https://github.com/oblador/loki

**Comment by bang88** [comment]
Thanks @gianpaj 

Will use `CodeSandbox` after this get fixed https://github.com/CompuIves/codesandbox-client/issues/1293

**Comment by SexySix** [comment]
像portal这种组件也可以export出来，想借助这个做一些自定义的modal层

**Comment by bang88** [comment]
> 像portal这种组件也可以export出来，想借助这个做一些自定义的modal层

对，而且加了两种方式创建自定义的层。方便自己扩展

**Comment by bang88** [comment]
Install the beta version with `yarn add @ant-design/react-native@next`

If you haven't used `Provider` before, you need to add `Provider` to the `app` entry to support the latest version of the theme.

eg:

```js
import { Provider } from '@ant-design/react-native'
return (
      <IntlProvider
        locale={locale}
        textComponent={Text}
        messages={translatedMessages[locale]}
      >
        <AppThemeProvider value={theme}>
          {t => (
            <Provider >
              ...
            </Provider>
          )}
        </AppThemeProvider>
      </IntlProvider>
    )
```

Feedback is the best support for me. and documentation also needs more help too. 😄

**Comment by jiangxia** [comment]
tabs 组件有一个很普遍的问题，就是某个选项卡的内容比较长，另一个选项卡内容区域的底部就会留下很长的空白，这个有办法解决么？

**Comment by bang88** [comment]
Please file an issue directly.

**Comment by Tosiwe** [comment]
调用 
 ```
Modal.operation([
        { text: "标为未读", onPress: () => console.log("标为未读被点击了") },
        { text: "置顶聊天", onPress: () => console.log("置顶聊天被点击了") }
 ])
```
报错：
Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

This error is located at:
    in RCModal
    in RCTView (at View.js:60)
    in View
    in WithTheme (created by AntmModal)
    in AntmModal
    in WithTheme (created by OperationContainer)
    in OperationContainer
    in RCTView (at View.js:60)
    in View (created by PortalManager)
    in PortalManager (created by Portal.Host)
    in Portal.Host (created by Provider)
    in ThemeProvider (created by Provider)
    in LocaleProvider (created by Provider)
    in Provider (at router.js:150)
    in Router (created by Connect(Router))
    in Connect(Router) (at index.js:18)
    in Provider (at dva.js:17)
    in Unknown (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

**Comment by SexySix** [comment]
> tabs 组件有一个很普遍的问题，就是某个选项卡的内容比较长，另一个选项卡内容区域的底部就会留下很长的空白，这个有办法解决么？

两个内容都用ScrollView包一下

**Comment by klaZzz** [comment]
请问 3.x如何自定义样式

**Comment by hamxiaoz** [comment]
@bang88 3.0可以用custom font吗？ 貌似default theme里面没有'fontFamily' variable

**Comment by bang88** [comment]
抱歉这个没有，配置起来太麻烦现在用的是ant icon 有太多自定义需求的可以自己 使用icon font


________________________________
发件人: Andrew Zheng <notifications@github.com>
发送时间: 星期三, 二月 6, 2019 08:50
收件人: ant-design/ant-design-mobile-rn
抄送: 启邦; Mention
主题: Re: [ant-design/ant-design-mobile-rn] 新版计划(The new plan) 3.0.0 - Discussion (#119)


@bang88<https://github.com/bang88> 3.0可以用custom font吗？ 貌似default theme里面没有'fontFamily' variable

―

**Comment by tourze** [comment]
> 调用
> 
> ```
> Modal.operation([
>        { text: "标为未读", onPress: () => console.log("标为未读被点击了") },
>        { text: "置顶聊天", onPress: () => console.log("置顶聊天被点击了") }
> ])
> ```
> 
> 报错：
> Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
> 
> This error is located at:
> in RCModal
> in RCTView (at View.js:60)
> in View
> in WithTheme (created by AntmModal)
> in AntmModal
> in WithTheme (created by OperationContainer)
> in OperationContainer
> in RCTView (at View.js:60)
> in View (created by PortalManager)
> in PortalManager (created by Portal.Host)
> in Portal.Host (created by Provider)
> in ThemeProvider (created by Provider)
> in LocaleProvider (created by Provider)
> in Provider (at router.js:150)
> in Router (created by Connect(Router))
> in Connect(Router) (at index.js:18)
> in Provider (at dva.js:17)
> in Unknown (at renderApplication.js:33)
> in RCTView (at View.js:60)
> in View (at AppContainer.js:102)
> in RCTView (at View.js:60)
> in View (at AppContainer.js:122)
> in AppContainer (at renderApplication.js:32)

请问你这个问题解决了吗。。我也遇到了

**Comment by liyanfei1004774105** [comment]
3.1.5 版本怎么改变主题,要做一个夜间模式效果,谢谢大家

**Comment by liyanfei1004774105** [comment]
>     * General
>       
>       * [x]  Upgrade react-native and other dependencies to the latest version
>       * [x]  bug fixes
>       * [x]  ~Improve the documentation (use expo to preview or provide Gif)~ CodeSandBox
> 
>     * Refactoring
>       
>       * [x]  File naming (remove the native suffix)
>       * [x]  More friendly theme support, user-friendly
>       * [x]  Improve TypeScript type definitions
>       * [x]  Split the components in `react-component` (previously shared with the Web)
> 
> 
>     * 常规
>       
>       * [x]  升级 react-native 以及其他依赖到最新版
>       * [x]  bug修复
>       * [x]  ~完善文档（看是否可以使用expo来预览，不然就只能提供Gif了）~ CodeSandBox
> 
>     * 重构
>       
>       * [x]  文件命名（去掉native后缀）
>       * [x]  更友好的主题支持，方便用户自定义
>       * [x]  完善TypeScript 类型定义
>       * [x]  拆分`react-component`里面的组件（之前是跟Web共用的）

现在的改变主题,怎么用的,我想要动态改变主题,做夜间模式,求大神指点
