### ISSUE TITLE
SearchBar的wrapper的背景色无法修改

### ISSUE THREAD

**Issue by Jidahan** [ant-design/ant-design-mobile-rn#1194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://xxx](http://xxx)

### Steps to reproduce
xxx

### What is expected?
能够修改wrapper的backgroundcolor

### What is actually happening?
能够修改wrapper的backgroundcolor

| Environment | Info |
|---|---|
| @ant-design/react-native | 4.2 |
| React | 17 |
| System | ios14.5 |
| Browser | google |

**Comment by 1uokun** [comment]
```jsx
<SearchBar 
  ...
  styles={{
    wrapper:{{backgroundColor:'red'}}
  }}
/>
```

文档在这：

**更多增强 (非必须):**
> [自定义 RN 主题和单个组件样式](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui#antd-mobile-with-rn-custom-ui) 比如 https://github.com/ant-design/ant-design-mobile/issues/1853

**Comment by Jidahan** [comment]
styles={{
                wrapper: {backgroundColor: 'white'}
              }}
