### ISSUE TITLE
Toast 能不能自定义弹出方向呢

### ISSUE THREAD

**Issue by wcldyx** [ant-design/ant-design-mobile-rn#1199]
Toast 能不能自定义弹出方向呢

**Comment by erichua23** [comment]
你具体是什么场景可以详细说说吗？要做这个倒是不难，现在是个faceIn动画，增加一些动画类型就好，但是目前市面上Toast基本都是用fade动画，还比较少见有其他方向的呢。

**Comment by wcldyx** [comment]
> 你具体是什么场景可以详细说说吗？要做这个倒是不难，现在是个faceIn动画，增加一些动画类型就好，但是目前市面上Toast基本都是用fade动画，还比较少见有其他方向的呢。

安卓的 Toast  提示一般是在页面底部的，所以我也想调整它居于页面底部

**Comment by 20170911** [comment]
希望支持Toast 提示在页面底部显示
