### ISSUE TITLE
Warning: Portal组件 EventEmitter.removeListener方法已被弃用

### ISSUE THREAD

**Issue by SoonIter** [ant-design/ant-design-mobile-rn#1200]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这个方法将被废弃，总是报警告，希望修改一下 
Console Warning 
EventEmitter.removeListener(' ANT_ DESIGN_ MOBILE_ RN_ REMOVE_ PORTAL', Method has been deprecated.Please instead use remove() on the subscription returned by EventEmitter.addListener'.

### What does the proposed API look like?
{
    key: "componentWillUnmount",
    value: function componentWillUnmount() {
      this._mountSubscription.remove();
      this._unmountSubscription.remove();
      // TopViewEventEmitter.removeListener(addType, this._mount);
      // TopViewEventEmitter.removeListener(removeType, this._unmount);
    },
  },

**Comment by 809388027** [comment]
I also encountered the same problem, and now the prompt is obsolete
