### ISSUE TITLE
Attempted import error: 'ActionSheetIOS' is not exported from 'react-native'

### ISSUE THREAD

**Issue by alphazhe** [ant-design/ant-design-mobile-rn#1208]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/alphazhe/AntDesignTest](https://github.com/alphazhe/AntDesignTest)

### Steps to reproduce
Execute these commands one by one, once https://github.com/alphazhe/AntDesignTest repo is cloned
1. git checkout master
2. yarn
3. yarn web

### What is expected?
ActionSheetIOS error should not come if the project is run on web using react-native-web.

### What is actually happening?
Even if we use single component from ant design on web, it does give ActionSheetIOS error. I have used only Button from ant, but it still gives the same error.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 0.66.3 |
| System | macOS Monterey 12.0.1 |
| Browser | Chrome |

---
Please provide either fix or workaround to solve react-native-web related issues.

**Comment by 1uokun** [comment]
We do not support `react-native-web` at the moment

**Comment by alphazhe** [comment]
@1uokun Is there any workaround for this? 
Or can we use ant-design-mobile in react native project for mobile app and web app?

**Comment by 1uokun** [comment]
Import Component on demand loading([🔗按需加载](https://ant.design/docs/react/introduce#Use-modularized-antd))
And do not import component who not support `react-native-web`
```diff
- import {Button} from '@ant-design/react-native';
   ↓    ↓    ↓    ↓    ↓    
+ import Button from '@ant-design/react-native/lib/button';
```
