### ISSUE TITLE
Toast轻提示不能用了吗?

### ISSUE THREAD

**Issue by BadtzMaru** [ant-design/ant-design-mobile-rn#1209]
RN: 0.66.4 Toast.info("测试"); 无效

**Comment by lucaslz2020** [comment]
怎么关掉了，真的用不了啊。

**Comment by HuChaoyong** [comment]
"react-native": "0.73.2",    也用不了.   T_T
"@ant-design/react-native": "^5.0.5"

**Comment by xiaobc1234** [comment]
"react-native": "0.74.2", 也用不了
"@ant-design/react-native": "^5.2.3"

**Comment by xiaobc1234** [comment]
解决了，最外层应用入口需要加<Provider>包一下
