### ISSUE TITLE
Picker 级联无法选择到最后两项

### ISSUE THREAD

**Issue by yorickshan** [ant-design/ant-design-mobile-rn#1211]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://sqb-qa.oss-cn-hangzhou.aliyuncs.com/4b184bb5-d011-4f84-9be0-d141b1cb055c_SVID_20211223_201504_1_1640314707_1640314707530_26cb2a%20(1).mp4](https://sqb-qa.oss-cn-hangzhou.aliyuncs.com/4b184bb5-d011-4f84-9be0-d141b1cb055c_SVID_20211223_201504_1_1640314707_1640314707530_26cb2a%20(1).mp4)

### Steps to reproduce
重现视频：https://sqb-qa.oss-cn-hangzhou.aliyuncs.com/4b184bb5-d011-4f84-9be0-d141b1cb055c_SVID_20211223_201504_1_1640314707_1640314707530_26cb2a%20(1).mp4

### What is expected?
可以选择到最后两项

### What is actually happening?
无法选择到最后两项

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | rn 0.63.4 |
| System | HONOR-PCT-AL10 Android 10 |
| Browser | 无 |

**Comment by yorickshan** [comment]
any updates?

**Comment by yorickshan** [comment]
所以，这个项目还维护吗？

**Comment by 1uokun** [comment]
try 5.1.0
