### ISSUE TITLE
Support react-native init apps too

### ISSUE THREAD

**Issue by AyushG3112** [ant-design/ant-design-mobile-rn#122]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The current docs say that antd mobile only works with apps created with CRNA. We should also support RNInit created apps for greater flexibity.

### What does the proposed API look like?
No API changes proposed, end user/dev API should probably remain the same

**Comment by bang88** [comment]
Whats your problem when work with `react native init` project. And I don't know where the docs said we only support CRNA. This is an ui framework that works with react native. 😄
