### ISSUE TITLE
使用https://reactnative.dev/ 向导命令安装的项目，在载入import { Button} from '@ant-design/react-native' 时崩溃

### ISSUE THREAD

**Issue by fschenkun22** [ant-design/ant-design-mobile-rn#1226]
### Reproduction link

[https://rn.mobile.ant.design/components/button-cn/](https://rn.mobile.ant.design/components/button-cn/) 此处(包括其他的组件)官方给出的按键示例的演示页面也是报错状态 ，错误如下```Error
Could not fetch dependencies, please try again in a couple seconds: Dependency @babel/plugin-transform-flow-strip-types not found```

### Steps to reproduce

https://reactnative.dev/docs/environment-setup 使用此向导进行安装，配置好后AwesomeProject在手机上运行一切正常；确认一切都能按照reactnative正确配置并在手机上再次确认示例程序可成功运行后，使用yarn add @ant-design/react-native安装antd插件，安装之后只要使用import { Button} from '@ant-design/react-native'导入任何Button Tag ...或任何一个ant-design模块 ，AwesomeProject就完全崩溃。提示的错误如下：```  at ModuleResolver.resolveDependency (C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
    at Object.resolve (C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at async addDependency (C:\phpstudy_pro\WWW\nativeApp\AwesomeProject\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
    at async Promise.all (index 11)``` ，这时候如果把载入import { Button} from '@ant-design/react-native'删除掉，程序又能正常运行。

### What is expected?

https://rn.mobile.ant.design/docs/react/introduce-cn  上面所有的组件演示程序都会报错误
Error
Could not fetch dependencies, please try again in a couple seconds: Dependency @babel/plugin-transform-flow-strip-types not found，跟着 https://rn.mobile.ant.design/docs/react/introduce-cn 上面的步骤仔细进行操作 得到的是更多的错误。希望官方给出的文档或向导，能够明确该如何使用

### What is actually happening?

根据官方向导得到的却是各种没有头绪的报错

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React |   "dependencies": {     "@ant-design/react-native": "^5.0.0",     "@reduxjs/toolkit": "^1.8.1",     "choco": "^0.2.1",     "react": "17.0.2",     "react-native": "0.68.0",     "react-native-camera": "^4.2.1",     "react-native-permissions": "^3.3.1",     "react-native-qrcode": "^0.2.7",     "react-native-qrcode-scanner": "^1.5.5",     "react-redux": "^7.2.8"   }, |
| System | Windows 11 专业版 22H2 |
| Browser | Chrome 版本 100.0.4896.60（正式版本） （64 位） |

以下是package.json
```{
  "name": "awesomeproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@ant-design/react-native": "^5.0.0",
    "@reduxjs/toolkit": "^1.8.1",
    "choco": "^0.2.1",
    "react": "17.0.2",
    "react-native": "0.68.0",
    "react-native-camera": "^4.2.1",
    "react-native-permissions": "^3.3.1",
    "react-native-qrcode": "^0.2.7",
    "react-native-qrcode-scanner": "^1.5.5",
    "react-redux": "^7.2.8"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by Es-Rell** [comment]
一样的问题 +1

**Comment by 1uokun** [comment]
似乎是`metro`配置问题，可否贴一下`metro.config.js`文件

**Comment by 1uokun** [comment]
![image](https://user-images.githubusercontent.com/28673261/212027956-0f7890fc-68fb-4e50-b2e2-79be98730986.png)
