### ISSUE TITLE
官方文档中位于CodeSandbox的DEMO全部失效

### ISSUE THREAD

**Issue by cw1997** [ant-design/ant-design-mobile-rn#1227]
### Reproduction link

[https://rn.mobile.ant.design/components/pagination-cn/](https://rn.mobile.ant.design/components/pagination-cn/)

### Steps to reproduce

无

### What is expected?

预期能够正常访问demo

### What is actually happening?

实际访问会报错，例如在pagination组件的文档页面 https://rn.mobile.ant.design/components/pagination-cn/ 中，查看DEMO会报错，提示

![image](https://user-images.githubusercontent.com/11588555/163251847-9f60dda1-21a6-4d40-b65a-9c140bf5ce46.png)

Error
Could not fetch dependencies, please try again in a couple seconds: Dependency @babel/plugin-transform-flow-strip-types not found
▼ 4 stack frames were expanded.
re
https://codesandbox.io/static/js/sandbox.e7b2d388a.js:1:168458
(anonymous function)
https://codesandbox.io/static/js/sandbox.e7b2d388a.js:1:171956
(anonymous function)
https://codesandbox.io/static/js/sandbox.e7b2d388a.js:1:172203
i
https://codesandbox.io/static/js/sandbox.e7b2d388a.js:1:169394

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 17.0.2 |
| System | Windows 10 21H1 |
| Browser | Chrome Version 100.0.4896.88 (Official Build) (64-bit) |

**Comment by 1uokun** [comment]
`codesandbox` not support react-native@0.60+, we will fix soon🙏

**Comment by cw1997** [comment]
> `codesandbox` not support react-native@0.60+, we will fix soon🙏

Roger that! Thanks for your reply!

**Comment by 1uokun** [comment]
H5 preview : https://1uokun.github.io/ant-design-mobile-rn/index.html

> **Preview in [ 🔗 Web Platform](https://1uokun.github.io/ant-design-mobile-rn/index.html)**. or<br>
**Download our Expo demo app** <br>
[<img width="250" alt="expo/ant-design-mobile-rn" src="https://qr.expo.dev/expo-go?owner=1uokun&slug=ant-design-mobile-rn&releaseChannel=default&host=exp.host" />](https://expo.dev/@1uokun/ant-design-mobile-rn) <br>
> Open the camera app on your device and scan the code above, <br>
need install expo app: https://expo.io/tools

**Comment by Qimingyang1998** [comment]
expoSnack  中的代码示例无法预览 也无法加载
