### ISSUE TITLE
在Modal中，使用TextInput时，无法输入中文

### ISSUE THREAD

**Issue by lucaslz2020** [ant-design/ant-design-mobile-rn#1230]

**Comment by 1uokun** [comment]
Same issue : https://github.com/facebook/react-native/issues/18403

**Comment by lucaslz2020** [comment]
我用了rn提供的modal没有问题的，rn版本.067.4

**Comment by jetengine** [comment]
有解决办法吗

**Comment by ljh257110** [comment]
我也遇到这个问题，当时使用antd的modal是因为toast无法在rn提供的modal上显示，会被遮盖住，但后续测出了无法输入中文的bug，没找到解决方案，只能和产品商量把toast换成alert了，虽然很丑。。

**Comment by 1uokun** [comment]
> 我也遇到这个问题，当时使用antd的modal是因为toast无法在rn提供的modal上显示，会被遮盖住，但后续测出了无法输入中文的bug，没找到解决方案，只能和产品商量把toast换成alert了，虽然很丑。。

@ljh257110 antd的modal不是用原生Modal实现的，用的View模拟动画实现的，所以Toast不会被覆盖
