### ISSUE TITLE
Picker line style dislocation

### ISSUE THREAD

**Issue by Nice-zrd** [ant-design/ant-design-mobile-rn#1234]
**Operating environment：**
"@ant-design/icons-react-native": "^2.3.2",
"@ant-design/react-native": "^5.0.0",
"react": "17.0.2",
"react-native": "0.67.3",

**Problems encountered：**
Picker line style dislocation

**Project code snippet:**
`
<View style={styles.container}>
        <Text>{data.label + ':'}</Text>
        <Picker
          data={this.areaList}
          cols={this.columns}
          value={this.state.areaCode}
          onChange={this.onChange}>
          <TouchableOpacity style={styles.selectInputBox} onPress={() => { }}>
            <View style={styles.selectContentBox}>
              <Text style={styles.selectContent}>{this.state.areaName}</Text>
            </View>
            <Image
              source={require('../../../../image/component/arrow-down.png')}
              resizeMode="contain"
              style={styles.selectImg}
            />
          </TouchableOpacity>
        </Picker>
      </View>
`
![WechatIMG362](https://user-images.githubusercontent.com/39508123/167776742-6e0a79c1-ba37-4c3a-8c24-ec0d49125821.jpeg)
![WechatIMG363](https://user-images.githubusercontent.com/39508123/167776746-ec6f97d4-565b-4d0f-9784-1cf6be3fb4d4.jpeg)

**Comment by caijiami** [comment]
+1
