### ISSUE TITLE
安卓模拟器 复选框 无法点击 Android Emulator checkbox cannot click

### ISSUE THREAD

**Issue by zs7779** [ant-design/ant-design-mobile-rn#1235]
### Reproduction link

[https://rn.mobile.ant.design/components/checkbox-cn/](https://rn.mobile.ant.design/components/checkbox-cn/)

### Steps to reproduce

在任何view中创造controlled checkbox组件。载入到安卓模拟器。

Ant Design RN 文档中 Checkbox 复选框 的代码展示，如果选择安卓系统，也会出现同样问题。

### What is expected?

复选框可以点击，onChange在点击时被触发。checked=true对勾在框的中央。

### What is actually happening?

安卓模拟器中复选框无法点击，onChange不被触发，checked=true时对勾向左偏移，复选框包括的文字可以正常点击。Web和ios模拟器复选框依然可以正常点击，对勾显示正常。

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 17.0.1 |
| System | Win10 core i5, Mac 12.2 M1 |
| Browser | Android emulator |

---
之前使用4.2.0版本复选框使用正常。升级到5.0.0版本之后仅在安卓模拟机（win10 intel和mac m1）出现问题，web和iOS模拟机测试正常。

**Comment by 1uokun** [comment]
我的疏忽，有兴趣提交一个pr吗
