### ISSUE TITLE
tabBar组件最外层为SafeAreaView,在苹果手机上无法实现沉浸式布局

### ISSUE THREAD

**Issue by wangi4myself** [ant-design/ant-design-mobile-rn#1236]
### What problem does this feature solve?

tabBar在app首页设计时经常要求实现沉浸式布局，但是tabBar最外层包裹了SafeAreaView，无法实现该效果

### What does the proposed API look like?

移除最外层SafeAreaView组件。或者通过属性，控制SafeAreaView是否移除

**Comment by 1uokun** [comment]
@bang88 mobile的V5版本放弃了**固定底部**的功能，要不要对齐mobile的V5版本
https://mobile.ant.design/zh/components/tab-bar#faq

**Comment by bang88** [comment]
可以。你看着搞

**Comment by 1uokun** [comment]
> 从demo的使用场景来看，已经实现了渗透式布局
> 
> <img alt="图片" width="150" src="https://user-images.githubusercontent.com/28673261/181055535-cf3a3fe2-e112-4b00-9baa-07db5d7551fa.png">
> 
> 如果无法满足某些场景，建议将 TabBar 作为按钮，参考https://mobile.ant.design/zh/components/tab-bar#faq

@wangi4myself
