### ISSUE TITLE
请问项目如何pub

### ISSUE THREAD

**Issue by xbdtb** [ant-design/ant-design-mobile-rn#1239]
### Reproduction link

[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce

执行npm run pub失败，

### What is expected?

能够成功执行antd-tools run dist

### What is actually happening?

执行报错，报webpack.config.js文件不是对象

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | 17 |
| System | macOS |
| Browser | Chrome 98 |

---
原因是执行antd-tools run dist步骤时报错，进一步原因是webpack.config.js导出的是异步函数的原因

**Comment by 1uokun** [comment]
着急用的话先改成下面这样的
```js
const getWebpackConfig = require('@ant-design/tools/lib/getWebpackConfig.js')
const webpackConfig = getWebpackConfig(false)

module.exports = webpackConfig
```

**Comment by 1uokun** [comment]
TODO：之前的webpack配置还是要保留，新支持的expo开发环境要做分离

**Comment by xbdtb** [comment]
好的，成功了！多谢大侠的迅速回复和指教！
