### ISSUE TITLE
请问支持PullToRefresh 拉动刷新吗？

### ISSUE THREAD

**Issue by JeremyDa** [ant-design/ant-design-mobile-rn#124]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通过触发上拉下拉，立刻重新加载内容，也希望支持定期刷新

### What does the proposed API look like?
| 属性              | 说明                                                         | 类型       | 默认值 |
| ----------------- | ------------------------------------------------------------ | ---------- | ------ |
| direction         | 拉动方向，可以是 `up` 或 `down`                              | String     | `down` |
| distanceToRefresh | 刷新距离                                                     | number     | 25     |
| refreshing        | 是否显示刷新状态                                             | bool       | false  |
| onRefresh         | 必选, 刷新回调函数                                           | () => void | -      |
| indicator         | 指示器配置 `{ activate: ReactNode, deactivate: ReactNode, release: ReactNode, finish: ReactNode }` | Object     | -      |
| damping           | 拉动距离限制, 建议小于 200                                   | number     | 100    |

**Comment by kangkang721** [comment]
请问上拉刷新实现了么？有例子么

**Comment by bang88** [comment]
> 请问上拉刷新实现了么？有例子么

看看ListView能不能满足你的需求，这个暂时没有单独做
