### ISSUE TITLE
Document display error - Picker element

### ISSUE THREAD

**Issue by yyyyyyounger** [ant-design/ant-design-mobile-rn#1240]
### Reproduction link

[https://rn.mobile.ant.design/components/picker/](https://rn.mobile.ant.design/components/picker/)

### Steps to reproduce

Open any browser and directly open the document link. The expo-web error will happen. 
"Unable to resolve module 'antd-mobile-demo-data.js'
  Evaluating antd-mobile-demo-data.js
  Evaluating App.js
  Loading App.js"

### What is expected?

It should no error showed as a official document website. 

### What is actually happening?

Expo-web display window had occur the error. 

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 0.68.2 |
| System | Android 11 |
| Browser | Chrome 102.0.5005.115 |

---
Is that due to the Expo platform? That really influence the document viewing experience.

**Comment by yyyyyyounger** [comment]
![image](https://user-images.githubusercontent.com/55580370/173264948-27f94988-11a4-47e0-ac8b-2279b728c23e.png)

**Comment by yyyyyyounger** [comment]
Even though open in the web editor. It also occur. 
![image](https://user-images.githubusercontent.com/55580370/173265077-c2327f04-fcf1-4126-9ece-f0201c9eaa9d.png)

**Comment by nimeshkavinda** [comment]
Any planned fixes for this?

**Comment by yyyyyyounger** [comment]
May be that is caused by the Expo Platform. Hoping a Expo expert can handle that. 😥
This issue is just a suggestion for the showing component demo.

**Comment by 1uokun** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/28673261/177091191-724a3a1c-b7fd-4834-a18e-03c56bbffa93.png">

My mistake, recently busy with the "mid-year" assessment.
We provide h5 demo: https://1uokun.github.io/ant-design-mobile-rn/index.html

**Comment by yyyyyyounger** [comment]
Thank you very much. 👍

**Comment by 1uokun** [comment]
fixed now
