### ISSUE TITLE
集成antd 运行报错 提示没有node_modules

### ISSUE THREAD

**Issue by wuzhijianMr** [ant-design/ant-design-mobile-rn#1244]

**Comment by wuzhijianMr** [comment]
提示“@ant-design\react-native\node_modules” Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by 1uokun** [comment]
maybe `react-native start --reset-cache` or [try google🔗](https://www.google.com/search?q=%E6%8F%90%E7%A4%BA%E2%80%9C%40ant-design%5Creact-native%5Cnode_modules%E2%80%9D+Invariant+Violation%3A+Module+AppRegistry+is+not+a+registered+callable+module+(calling+runApplication).+A+frequent+cause+of+the+error+is+that+the+application+entry+file+path+is+incorrect.+This+can+also+happen+when+the+JS+bundle+is+corrupt+or+there+is+an+early+initialization+error+when+loading+React+Native.&oq=%E6%8F%90%E7%A4%BA%E2%80%9C%40ant-design%5Creact-native%5Cnode_modules%E2%80%9D+Invariant+Violation%3A+Module+AppRegistry+is+not+a+registered+callable+module+(calling+runApplication).+A+frequent+cause+of+the+error+is+that+the+application+entry+file+path+is+incorrect.+This+can+also+happen+when+the+JS+bundle+is+corrupt+or+there+is+an+early+initialization+error+when+loading+React+Native.&aqs=chrome..69i64j69i57j69i60l3j69i58j69i60j69i65.1381j0j4&sourceid=chrome&ie=UTF-8)
