### ISSUE TITLE
classnames could not be found within the project or in these directories:

### ISSUE THREAD

**Issue by wuzhijianMr** [ant-design/ant-design-mobile-rn#1245]

**Comment by wuzhijianMr** [comment]
error Unable to resolve module classnames from F:\react\fyt\node_modules\@ant-design\react-native\lib\tag\index.js: classnames could not be found within the project or in these directories:
  node_modules\@ant-design\react-native\node_modules
  node_modules

**Comment by 1uokun** [comment]
Duplicate of #1229
