### ISSUE TITLE
Grid can't use local images?

### ISSUE THREAD

**Issue by KuoKongQingYun** [ant-design/ant-design-mobile-rn#125]
```
const orderGridData = [
  { icon:require('../resource/img/icon/xxx.png'), text: 'xxx' }
]

...
...
...

<Grid data={orderGridData} />
```

It doesn't work.
I have no good idea to use Grid with local images.
I think Grid should support both images online and local images,but it seems like that Grid only support using URL and can not use "require" to show local images.

**Comment by KuoKongQingYun** [comment]
解决了，icon可以是组件，文档里没写清楚，看源码才知道……

**Comment by HellsingMatt** [comment]
> 解决了，icon可以是组件，文档里没写清楚，看源码才知道……

找不见呢，麻烦指点一下？

**Comment by SiJieMa** [comment]
`const icon = [<Image source={require('../../assets/img/12.png')}/>,
'https://www.easyicon.net/api/resizeApi.php?id=1145835&size=64',
'https://www.easyicon.net/api/resizeApi.php?id=1145841&size=64',
'https://www.easyicon.net/api/resizeApi.php?id=1145848&size=64',
'https://www.easyicon.net/api/resizeApi.php?id=1145839&size=64',
'https://www.easyicon.net/api/resizeApi.php?id=1145837&size=64'];
`
icon中可以直接写入image组件或者是url
