### ISSUE TITLE
Using a deprecated package (@react-native-community/cameraroll), causing Android build errors

### ISSUE THREAD

**Issue by SamMakesThings** [ant-design/ant-design-mobile-rn#1261]
### Reproduction link

[https://en.wikipedia.org/wiki/N/A](https://en.wikipedia.org/wiki/N/A)

### Steps to reproduce

Look at the package.json, see that it's deprecated

### What is expected?

That @ant-design/react-native uses the non-deprecated version of the package (@react-native-camera-roll/camera-roll) instead of the deprecated version (@react-native-community/camera-roll)

### What is actually happening?

Other packages require the non-deprecated version, @react-native-camera-roll/camera-roll. However, ant-design errors without the deprecated version (@react-native-community/cameraroll). If I try to use both, the build script fails, saying "BuildConfig is defined multiple times". Please update to the non-deprecated package.

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 0.65.2 |
| System | Android & iOS, any version |
| Browser | N/A |

**Comment by RayanAbid** [comment]
Hi @SamMakesThings did you try replacing the package in the node_modules folder? 

I tried replacing it and it seems to have started working. Can I look into this issue and solve it as I've already solved it? @mcallisto

**Comment by SamMakesThings** [comment]
Honestly I just created a patch that removed it from package.json and removed the file that used it. It's frustrating that was necessary.

**Comment by RayanAbid** [comment]
Glad to hear it was fixed I did the same.

**Comment by RayanAbid** [comment]
@aidan2129 I've got it to work by just replacing it with the [@react-native-camera-roll/camera-roll](https://www.npmjs.com/package/@react-native-camera-roll/camera-roll) in the ``node_modules/@ant-design`` I opened it up separately searched for the ``@react-native-camera-roll/camera-roll`` in the whole project and replaced it with ``@react-native-community/cameraroll`` and it's working fine now. Let me know if you need some more clarification.

**Comment by aidan2129** [comment]
Yup I fixed it locally by removing the ImagePicker and saving the change with [patch-package](https://github.com/ds300/patch-package) as I dont use it. But I do not believe that is the ideal step you want everyone to have to go through each time they this module. I'm can maybe try and get a pull request submitted later to replace the old versions across the app.

**Comment by RayanAbid** [comment]
That is one downside of using open-source packages, but that would be great if you can do that do let me know if you need any help we can figure it out together. @aidan2129

**Comment by MitarSpasicc** [comment]
Hello, I have the similar problem with @react-native-community/cameraroll.
I'm using React 18.1.0.
Is there any working solution ?

I've managed to make it work with --legacy-peer-deps, but then the expo build crashed with the same error.

Thanks in advance.

ERROR:
Could not resolve dependency:
npm ERR! peer react@"16 || 17" from @react-native-community/cameraroll@4.1.2
npm ERR! node_modules/@react-native-community/cameraroll
npm ERR!   peer @react-native-community/cameraroll@">= 1.5.2" from @ant-design/react-native@5.0.2
npm ERR!   node_modules/@ant-design/react-native
npm ERR!     @ant-design/react-native@"*" from the root project

**Comment by MitarSpasicc** [comment]
@RayanAbid 
Thank you for the quick reply.
Honestly, I will re-think about using library. Patch is a temporary solution. Don't want to have similar problem in the future :).
Best regards!

**Comment by MitarSpasicc** [comment]
Hi @RayanAbid .
You’ve mentioned that you have patch for new release, so i wanted to ask you if there are chances to share it here.
I’ve tried it on my own but I didn’t manage it to work.
My company wants to use antd at any costs :)
Thank you in advance

**Comment by RayanAbid** [comment]
@MitarSpasicc Sorry for the late reply. Do you still want it? I'll share the files here you can add it in a folder call it ``patches``. 

then all you have to do is install this [package](https://www.npmjs.com/package/patch-package) and run the command and it should start working. 

[@ant-design+react-native+5.0.2.patch](https://github.com/ant-design/ant-design-mobile-rn/files/10313421/%40ant-design%2Breact-native%2B5.0.2.patch)

if you have any further questions and I'm not able to reply. You can dm on [twitter](https://twitter.com/rayanDoesTech)

Once again sorry for the late reply.
