### ISSUE TITLE
引入组件报错

### ISSUE THREAD

**Issue by mac-boss** [ant-design/ant-design-mobile-rn#1262]
### Reproduction link

[http://无连接](http://无连接)

### Steps to reproduce

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1262247/194507051-97ceecb0-17a3-40ee-90d9-528499e5d7f7.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1262247/194507083-476d2b7d-8e77-4b54-9cbc-46bc2e86a528.png">

### What is expected?

不报错

### What is actually happening?

报错
<img width="452" alt="image" src="https://user-images.githubusercontent.com/1262247/194507011-5a285bbf-2db2-4a87-a37e-03dcc7ef37ef.png">

| Environment | Info |
| --- | --- |
| antd | 5.0.1 |
| React | 18.1.0/0.70.2 |
| System | macOS |
| Browser | iOS模拟器 |

**Comment by 1uokun** [comment]
![image](https://user-images.githubusercontent.com/28673261/212024992-ff818d59-dfba-4945-b935-b6dc303d0e77.png)
