### ISSUE TITLE
Modal组件 ios下 Modal.prompt无法输入中文 

### ISSUE THREAD

**Issue by lishiyanlishiyan** [ant-design/ant-design-mobile-rn#1263]
### Version of antd-mobile

5.0.1

### Operating system and its version

ios15.2

### What happened?
https://rn.mobile.ant.design/components/modal-cn/
输入法26键 ios下 无法输入中文

https://user-images.githubusercontent.com/43063974/194700092-7d16b7d4-170b-48e5-8028-f5963fe87d06.mov

**Comment by 1uokun** [comment]
fixed in `5.0.2`
