### ISSUE TITLE
[docs] expo qrcode 需要刷新, 最新的不能支持sdk 44 的版本

### ISSUE THREAD

**Issue by radiorz** [ant-design/ant-design-mobile-rn#1269]
### Reproduction link

[https://github.com/ant-design/ant-design-mobile-rn#readme](https://github.com/ant-design/ant-design-mobile-rn#readme)

### Steps to reproduce

使用expoapp 扫描二维码, 但是提示进入不了

### What is expected?

expo 可以正常进入

### What is actually happening?

expo 进入不了应用

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 0.70 |
| System | android |
| Browser | latest |

**Comment by radiorz** [comment]
https://github.com/ant-design/ant-design-mobile-rn#readme

**Comment by stevekuznetsov** [comment]
Looks like it was built with a very old SDK, and needs to be re-built.

**Comment by sgshy1995** [comment]
How to resolve it?

**Comment by 1uokun** [comment]
fixed
