### ISSUE TITLE
引入ant-design-icon 出现乱码

### ISSUE THREAD

**Issue by kelvinleungv** [ant-design/ant-design-mobile-rn#1272]
"react-native": "0.60.5",
@ant-design/icons-react-native": "2.2.1",

问题：重新安装依赖后，icon出现了乱码
![image](https://user-images.githubusercontent.com/21992834/204719614-b5a59441-357a-4e81-bd26-307fb14e97b4.png)

![image](https://user-images.githubusercontent.com/21992834/204719687-4a734098-ce26-4444-a57b-045b905e1e6d.png)
![image](https://user-images.githubusercontent.com/21992834/204719700-6609b2f9-c866-4314-94e5-2b78701031de.png)

**Comment by BANG88** [comment]
看看是不是icon 名称对不上。
