### ISSUE TITLE
warn dependency.assets is not allowed

### ISSUE THREAD

**Issue by 5i77** [ant-design/ant-design-mobile-rn#1276]
version: 
  "react-native": "0.70.6",
  "@ant-design/react-native": "5.0.3",

当我运行"yarn android"时, 得到下面警告, 并且项目中不显示图标;

warn Package @ant-design/react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**Comment by evan0204** [comment]
link问题，直接手动添加字体文件即可

**Comment by yuanjiexuan** [comment]
怎么添加字体文件

**Comment by inkcrazy666** [comment]
> 怎么添加字体文件

不知道怎么改文件，我是手动添加的

android

![截屏2023-09-02 17 19 43](https://github.com/ant-design/ant-design-mobile-rn/assets/130324703/9b5d5de5-038d-4e99-8b63-1e114a23d66e)

iOS项目
![截屏2023-09-02 17 19 26](https://github.com/ant-design/ant-design-mobile-rn/assets/130324703/a9659df5-9ea5-4212-8668-d35d28e92042)
![截屏2023-09-02 17 19 33](https://github.com/ant-design/ant-design-mobile-rn/assets/130324703/ad1dc5c6-1e85-4cbc-98f3-448189ec8bf7)
