### ISSUE TITLE
官网不能预览了

### ISSUE THREAD

**Issue by crly** [ant-design/ant-design-mobile-rn#1279]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/17537229/209634703-3bddfdbb-1d18-4a9c-aa27-326e71098f71.png">

**Comment by HKH01** [comment]
Try this website 'https://rn.mobile.ant.design/components/modal-cn/' on PC

**Comment by 1uokun** [comment]
你这个snack.expo.dev链接是从哪里来的呢
