### ISSUE TITLE
请问是怎么做适配的

### ISSUE THREAD

**Issue by jswangtao** [ant-design/ant-design-mobile-rn#1280]
### What problem does this feature solve?

你好，请问我看源码里面都是写死的数字，比如在主题文件里面  icon_size_xxs: 15   这种导致在不同的大小的屏幕下面表现不一致，实际上应该根据屏幕大小按比例缩放

### What does the proposed API look like?

目前项目里面用的适配方案是按照750的比例去转每个UI设计图的尺寸    类似px2dp

**Comment by 1uokun** [comment]
有提供主题样式适配
你要自己去把所有固定数值的都配置一遍
```css
 icon_size_xxs: 15 * px
```

**Comment by jswangtao** [comment]
> 有提供主题样式适配 你要自己去把所有固定数值的都配置一遍
> 
> ```css
>  icon_size_xxs: 15 * px
> ```
谢谢，我试试
