### ISSUE TITLE
在安卓 modal中使用TextInput或者InputItem 绑定value，光标 在删除，添加，会异常

### ISSUE THREAD

**Issue by lzp666666** [ant-design/ant-design-mobile-rn#1282]
`
import { Modal } from '@ant-design/react-native';
import React, { FC, useState } from 'react';
import { Button, TextInput } from 'react-native';
//TODO
interface IProps {}
/**
 * 一个组件/页面
 */
const TestPop: FC<IProps> = () => {
	const [val, setVal] = useState('');
	const addMember = () => {
		setVal(nowVal => nowVal + '@人员');
	};
	return (
		<Modal
			style={{ height: '60%' }}
			visible={true}
			maskClosable={true}
			popup
			animationType="slide-up"
		>
			<TextInput
				placeholder="输入文字"
				value={val}
				onChangeText={text => setVal(text)}
			/>
			<Button title="添加@人员" onPress={addMember}></Button>
		</Modal>
	);
};
export default TestPop;
`
在安卓
你们有遇到这个问题吗,输入8个中文，然后点击光标到第4个，开始添加删除操作，你会看到异常吗。
我是使用的hook封装modal，中使用TextInput，
我尝试使用defaultValue来解决，这暂时解决，但是我需求有通过按钮更改输入框，所以需要ref来更改，但我不知道怎么更改。

**Comment by 1uokun** [comment]
完整代码贴一下

**Comment by lzp666666** [comment]
> 完整代码贴一下
贴了，在标题下

**Comment by lzp666666** [comment]
`import { Modal } from '@ant-design/react-native';
import React, { FC, useState } from 'react';
import { Button, TextInput } from 'react-native';
//TODO
interface IProps {}
/**
 * 一个组件/页面
 */
const TestPop: FC<IProps> = () => {
	const [val, setVal] = useState('');
	const addMember = () => {
		setVal(nowVal => nowVal + '@人员');
	};
	return (
		<Modal
			style={{ height: '60%' }}
			visible={true}
			maskClosable={true}
			popup
			animationType="slide-up"
		>
			<TextInput
				placeholder="输入文字"
				value={val}
				onChangeText={text => setVal(text)}
			/>
			<Button title="添加@人员" onPress={addMember}></Button>
		</Modal>
	);
};
export default TestPop;
`

**Comment by lzp666666** [comment]
> 完整代码贴一下

贴了，在标题下

**Comment by 1uokun** [comment]
```js
this.inputRef.inputRef.inputRef.setNativeProps({ text: "change by ref })      
```

```jsx
<InputItem
  ref={(el: any) => (this.inputRef = el)}
>    
```

**Comment by 1uokun** [comment]
1. ref [setNativeProps](https://reactnative.dev/docs/direct-manipulation#setnativeprops-to-edit-textinput-value)修改input内部 value

2. input输入异常问题同 [#1230 ](https://github.com/ant-design/ant-design-mobile-rn/issues/1230#issuecomment-1106103597)

**Comment by lzp666666** [comment]
> 



> ```js
> this.inputRef.inputRef.inputRef.setNativeProps({ text: "change by ref })      
> ```
> 
> ```js
> <InputItem
>   ref={(el: any) => (this.inputRef = el)}
> >    
> ```

可以，可以更改输入框的值，inputRef.current.setNativeProps({ text: "change by ref })
