### ISSUE TITLE
为何目前searchbar的默认前缀图标使用的是security scan 不是传统search 可否自定义？

### ISSUE THREAD

**Issue by Vetich** [ant-design/ant-design-mobile-rn#1295]

**Comment by Vetich** [comment]
![image](https://user-images.githubusercontent.com/35763082/230902973-cbdf1628-8b14-4dc9-ac82-307c3a9b6506.png)

**Comment by 1uokun** [comment]
用 `@ant-design/icons-react-native@2.3.2`以上的版本
