### ISSUE TITLE
DatePicker 怎么item里面的样式

### ISSUE THREAD

**Issue by Zhouwenli** [ant-design/ant-design-mobile-rn#1297]

**Comment by wangvili** [comment]
+1,

**Comment by wangvili** [comment]
> 同问，如何设置Item，当日期现在mode设为‘datetime‘ 时 iOS无法展示具体时间，显示....

+1,

同问题
https://github.com/ant-design/ant-design-mobile-rn/issues/1316

**Comment by 1uokun** [comment]
`itemStyle` `itemHeight` in 5.1.0
