### ISSUE TITLE
"dependency.assets" is not allowed

### ISSUE THREAD

**Issue by zxwGH** [ant-design/ant-design-mobile-rn#1298]
warn Package @ant-design/icons-react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**Comment by zxwGH** [comment]
"@ant-design/react-native": "^5.0.4"
"react-native": "0.71.6",

**Comment by ZenChains** [comment]
我也遇到了这个问题，但是目前除了手动去处理没有看到好的解决方案了

**Comment by 1uokun** [comment]
fixed in 5.1.2
