### ISSUE TITLE
InputItem

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile-rn#13]
RN android 多个 InputItem 组合 焦点问题
https://github.com/ant-design/ant-design-mobile/issues/2618

三星手机InputItem的numeric属性键盘没有小数点
https://github.com/ant-design/ant-design-mobile/issues/2624

**Comment by jlsnake** [comment]
I think the focus issue is a question of use, and putting InputItem under ScrollView will come across this problem. 
So when used in this way, you should set the ScrollView's Keyboardshouldpersisttaps property to solve this problem.
