### ISSUE TITLE
[Bug] RN0.71 setNativeProps is not currently supported in Fabric

### ISSUE THREAD

**Issue by ShaoGongBra** [ant-design/ant-design-mobile-rn#1303]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

新架构Fabric，不支持直接setNativeProps，使用Picker安卓的时候，无法弹出，报这个错误

### 💻 运行环境

Android

### ⚫️ `npx react-native info`输出信息

OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 12.97 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1687225095799-0.44258577146659617/node
    Yarn: 1.22.18 - /var/folders/5j/t9hd6v1d3s902h5xb3g1rmv40000gn/T/yarn--1687225095799-0.44258577146659617/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.2.0 => 18.2.0 
    react-native: ^0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by 1uokun** [comment]
fixed in `5.1.0`+
