### ISSUE TITLE
[Bug] CocoaPods could not find compatible versions for pod "react-native-safe-area-context":

### ISSUE THREAD

**Issue by ismdcf** [ant-design/ant-design-mobile-rn#1306]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

Clone the repo 
cd rn-kitchen-sink/ios
pod install 

### 💻 Environment

iOS

### ⚫️ Output of `npx react-native info`

npx react-native info

info Fetching system and libraries information...

System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 74.03 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Additional comments

Trying to build the sample app on the latest version of xcode on apple silicon but unable to do it

**Comment by deokyeong93** [comment]
<img width="1508" alt="스크린샷 2024-02-23 오후 9 36 16" src="https://github.com/ant-design/ant-design-mobile-rn/assets/66895208/732eb11f-4192-4444-afbe-91564dc2f653">

@1uokun  

The same thing still happens, Is there anything I missed?
