### ISSUE TITLE
你好，请问picker 这个组件如何自定义高度呀

### ISSUE THREAD

**Issue by ikimiler** [ant-design/ant-design-mobile-rn#131]
![在这里插入图片描述](https://img-blog.csdnimg.cn/20181107182521534.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzI4MjY4NTA3,size_16,color_FFFFFF,t_70)

高度怎么定义，设置了style styles 属性均无效呀，还有header 的左右两个按钮，间距太大了，如何调整啊，求指教，谢谢了

```
export default {
    modal: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'flex-end'
    },
    header: {
        flexGrow: 1,
        height: 44,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#e7e7e7'
    },
    headerItem: {
        height: 44,
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
    actionText: {
        color: '#0ae',
        fontSize: 18,
        textAlign: 'center'
    },
    okText: {},
    dismissText: {},
    title: {
        color: '#666',
        fontSize: 18,
        textAlign: 'center'
    }
};
```

没有content 相关的属性，希望可以帮忙看一下

**Comment by bang88** [comment]
@andmizi 用的是`Picker` ？ 贴一下代码，有的自定义样式不一定支持，现在picker用的是 react-component里面的一些组件，期望3.0.0能把之前的拆分出来。

**Comment by bang88** [comment]
@andmizi 看了现在的代码确实不能自定义这个高度。

> 现在picker用的是 react-component里面的一些组件，期望3.0.0能把之前的拆分出来。

**Comment by eightHundreds** [comment]
> 可以使用 itemStyle 自定义内容样式

不能自定义选中的item样式吧
