### ISSUE TITLE
[Bug] image-picker 组件弹出的照片选择弹框没有兼容刘海屏安全边距，导致取消按钮难以点中

### ISSUE THREAD

**Issue by secreter** [ant-design/ant-design-mobile-rn#1310]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

image-picker 组件在弹出照片选择的Model 后，在刘海屏下，由于没有设置安全边距，导致上方的取消按钮十分难被点中，并且不支持传入样式覆盖。希望能兼容安全边距或提供样式覆盖能力。
```
<Modal
        animationType="slide"
        visible
        onRequestClose={() => {}}
        transparent={false}>
        <View style={{ flex: 1 }}>
          <StatusBar barStyle="light-content" />
          <View style={styles.statusBarBg} />
          <View style={[styles.naviBar]}>
            <Text style={[styles.barTitle]}>{title}</Text>
            <TouchableOpacity onPress={this.props.onCancel}>
              <Text style={styles.rightBtn}>{cancelText}</Text>
            </TouchableOpacity>
          </View>
          <CameraRollPicker
            selected={[]}
            callback={this.onSelected}
            maximum={1}
            {...cameraPickerProps}
          />
        </View>
      </Modal>
```

### 💻 Environment

iOS

### ⚫️ Output of `npx react-native info`

System:
  OS: macOS 12.5.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 98.56 MB / 32.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.10.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 8.19.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/chaoyang/.rubies/ruby-3.2.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "33"
      - "33"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.2
    System Images:
      - android-30 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.1
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/chaoyang/.rubies/ruby-3.2.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by 1uokun** [comment]
`<ImagePicker />` has been deprecated in 5.1.0
