### ISSUE TITLE
[Bug] Picker组件多列模式下传入data时，如果name的值的长度过长出现截断符号后，两个列会错位

### ISSUE THREAD

**Issue by DreamEVA** [ant-design/ant-design-mobile-rn#1311]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

Picker组件多列模式下传入data时，如果name的值的长度过长出现截断符号后，两个列会错位

### 💻 运行环境

Android

### ⚫️ `npx react-native info`输出信息

![af0e5d04df38cc2ae99a3f2e98e684b](https://github.com/ant-design/ant-design-mobile-rn/assets/57390572/89e6ecf8-2379-4d40-998a-848474be5d07)

**Comment by DreamEVA** [comment]
并且右侧列会无法滑动

**Comment by 1uokun** [comment]
如何复现"两个列会错位" @DreamEVA

**Comment by DreamEVA** [comment]
const data = [
  {
    label:'00000000超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label',
    value:'1',
    children:[
      {
        label:'0000超长的labell',
        value:'1-1',
      },
      {
        label:'超长的label',
        value:'1-2',
      }
    ]
  },
  {
    label:'00000000超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label超长的label',
    value:'2',
    children:[
      {
        label:'超长的label超长',
        value:'2-1',
      },
      {
        label:'超长的lab',
        value:'2-2',
      }
    ]
  }
];
// 在小屏幕的设备上能稳定复现<List&gt;
  <Picker
    data={data]}
    value={state.CKCode}
    cols={2}
    onChange={(value)=&gt;{
      setState({ CKCode:value });
    }}
    itemStyle={{
      paddingTop:8,
      paddingBottom:8,
    }}
  &gt;
    <List.Item arrow={'horizontal'}&gt;仓库仓区-库位</List.Item&gt;
  </Picker&gt;
&nbsp;


ぃ不幸少年℡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月19日(星期二) 晚上6:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design-mobile-rn] [Bug] Picker组件多列模式下传入data时，如果name的值的长度过长出现截断符号后，两个列会错位 (Issue #1311)





 
如何复现"两个列会错位" @DreamEVA

**Comment by 1uokun** [comment]
fixed in 5.1.0
