### ISSUE TITLE
[Bug] 初始化引资源警告

### ISSUE THREAD

**Issue by tomato728** [ant-design/ant-design-mobile-rn#1312]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

warn Package @ant-design/icons-react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.       
warn Package @ant-design/react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

### 💻 运行环境

react-native-windows

### ⚫️ `npx react-native info`输出信息

PS F:\app\xxx> yarn start
yarn run v1.22.19
$ react-native start
warn Package @ant-design/icons-react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.       
warn Package @ant-design/react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

### 补充说明

在运行的时候

**Comment by 1uokun** [comment]
fixed in 5.1.2

**Comment by Chenjiujiu** [comment]
> fixed in 5.1.2

It  exists in version 5.4.2
