### ISSUE TITLE
switch中checked属性设置

### ISSUE THREAD

**Issue by Torstentjh** [ant-design/ant-design-mobile-rn#1325]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

![image](https://github.com/ant-design/ant-design-mobile-rn/assets/75771172/90a76bbb-0f58-46c8-b2f5-088797e89510)
![image](https://github.com/ant-design/ant-design-mobile-rn/assets/75771172/8d6fb0cf-d3fc-4f0e-993e-040369801910)
你好，我在使用switch组件时，发现有checked和defaultchecked两个，貌似和文档中说明是一样的，都只能设置默认选中，为了方便观看，我将led灯位置和警报位置的checked设置为一样，还给led灯设置了loading，然后我用第一个按钮控制，测试发现loading和disable都能实现，但是就是无法控制开关的状态，是因为checked和defaultchecked这两个都只能设置默认状态，无法更改吗

### 💻 运行环境

Android

### ⚫️ `npx react-native info`输出信息

System:
  OS: Windows 11 10.0.22000
  CPU: "(12) x64 AMD Ryzen 5 4600H with Radeon Graphics         "
  Memory: 3.90 GB / 15.87 GB
Binaries:
  Node:
    version: 18.12.1
    path: E:\tnode\node.EXE
  Yarn:
    version: 1.22.21
    path: E:\tools\nvm\nvm\node_global\yarn.CMD       
  npm:
    version: 8.19.2
    path: E:\tnode\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled        
    AllowAllTrustedApps: Enabled
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.6
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by 1uokun** [comment]
历史设计如此，近期会修改更新

**Comment by 1uokun** [comment]
support in 5.1.0
