### ISSUE TITLE
[Bug]  Carousel - java.lang.Boolean cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by surya-inbasagaran** [ant-design/ant-design-mobile-rn#1328]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

import Carousel from '@ant-design/react-native/lib/carousel';
import Tabs from '@ant-design/react-native/lib/tabs';

Wherever I have used this component I faced this conversion issue, I am trying this in Expo.
When I tested in the web it worked fine, when I try to test this on the device, I am facing this conversion issue.
![Screenshot_20240229-113847](https://github.com/ant-design/ant-design-mobile-rn/assets/123365066/c94478d2-ab30-452e-8b19-f47156cd3c07)

### 💻 Environment

Android, Expo

### ⚫️ Output of `npx react-native info`

![Screenshot_20240229-113847](https://github.com/ant-design/ant-design-mobile-rn/assets/123365066/88567ca6-5cc7-4b87-929d-303e25d6d34d)

**Comment by surya-inbasagaran** [comment]
> [#1327 (comment)](https://github.com/ant-design/ant-design-mobile-rn/issues/1327#issuecomment-1970419406)

but I haven't used "react-native-gesture-handler" package in my project.
Is it mandatory to have that package for ant-design package to work ?

**Comment by cw1997** [comment]
Sorry, I try to add `"react-native-gesture-handler": "2.14.0"` to package.json@dependencies and package.json@peerDependencies, but they all don't work. 
Is there any way to fix this problem? Thank you!

![image](https://github.com/ant-design/ant-design-mobile-rn/assets/11588555/009ca7c6-5617-401b-92e2-339e18f6cb57)

**Comment by 1291862631** [comment]
什么问题。升级了就出现了。回退也不行

**Comment by cw1997** [comment]
> 什么问题。升级了就出现了。回退也不行

我也遇到了一模一样的BUG，但是回退到5.0.2版本(不要带任何语义化版本前缀)就好了

**Comment by surya-inbasagaran** [comment]
Even downgrading to a lower version also, it's not working, I think it's based on the node version they used in the package.

**Comment by 1uokun** [comment]
fixed in v5.1.1
