### ISSUE TITLE
[Bug] 关于antV 5.1.1无法连接问题

### ISSUE THREAD

**Issue by LyingDoc** [ant-design/ant-design-mobile-rn#1333]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

warn Package @ant-design/react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this. error: unknown command 'link'
包换icos

### 💻 运行环境

Android

### ⚫️ `npx react-native info`输出信息

尽管需要手动去修改弄node——modules相应的js修改，但是这样很容易被覆盖，不好处理，麻烦官方修复这个bug，能够自动连接

### 补充说明

https://github.com/ant-design/ant-design-mobile-rn/issues/1289（这是解决方案，但是这样不方便，不稳定
）

**Comment by 1uokun** [comment]
fixed in 5.1.2
