### ISSUE TITLE
[Bug] react-native-gesture-handler 改为 peerDependencies

### ISSUE THREAD

**Issue by zhiqingchen** [ant-design/ant-design-mobile-rn#1337]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

react-native-gesture-handler 锁定的版本，容易导致安装多个版本

### 💻 运行环境

iOS

### ⚫️ `npx react-native info`输出信息

System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 114.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.2/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.2 - /opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11330709
    Xcode: 15.3/15E204a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.21 - /opt/homebrew/opt/openjdk@11/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^18.1.0 => 18.2.0
    react-native: ^0.70.1 => 0.70.15
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by 1uokun** [comment]
done
