### ISSUE TITLE
[Bug] 使用5.1.1的版本的drawe组件会报错。react-native的版本是0.73

### ISSUE THREAD

**Issue by linhaibo147** [ant-design/ant-design-mobile-rn#1338]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

我是react-native 0.73的版本。我从5.0.5升级到5.1.1的时候Drawer组件会报错

### 💻 运行环境

Android, Expo

### ⚫️ `npx react-native info`输出信息

<img width="1042" alt="WechatIMG8851" src="https://github.com/ant-design/ant-design-mobile-rn/assets/20526897/16a66b79-6c48-4c14-854b-3e519d4b695f">
<img width="1064" alt="WechatIMG8837" src="https://github.com/ant-design/ant-design-mobile-rn/assets/20526897/a4ff8397-4b23-412c-9579-38e0b12c95ab">
![WechatIMG8810](https://github.com/ant-design/ant-design-mobile-rn/assets/20526897/9993304b-4014-426b-ba70-0bfa7a19d029)

**Comment by 1uokun** [comment]
# 错误来自react-native-gesture-handle
请升级到`5.1.2`，自主选择`react-native-gesture-handle@2.x.x`版本
