### ISSUE TITLE
All links to demo source code in documentation are broken

### ISSUE THREAD

**Issue by joelgetaction** [ant-design/ant-design-mobile-rn#134]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
macOS 10.13.6, react-native 0.57

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/demo/basic.native.tsx](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/demo/basic.native.tsx)

### Steps to reproduce
1. Go to page https://rn.mobile.ant.design/components/picker/#components-picker-demo-basic
2. Click on the demo source code link listed on this page, which is https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/demo/basic.native.tsx
3. Github serves up a 404 because the demo code is not there / cannot be found.

### What is expected?
Links to demo source code in the documentation should work

### What is actually happening?
Links to demo source code in the documentation do NOT work.

---
This makes it really hard to use Ant react native, because the documenation doesn't show any sample source and the links to demos are all broken ... So how am I supposed to use these components?

**Comment by joelgetaction** [comment]
Here is the correct link to the demo source code for this example: https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/demo/basic.tsx

```
# Correct link
https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/demo/basic.tsx

# Broken link
https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/demo/basic.native.tsx
```

So notice that the *correct/working* link ends in `basic.tsx` whereas the broken link ends in `basic.native.tsx`.  All of these links could probably be updated with sed or a global search and replace in a text editor.

I could help with a PR to fix the docs if you give me a hint how to do that?  Would you like me to help?  :-)

**Comment by bang88** [comment]
@joelgetaction PR are always welcome. The link has broken because I removed the '.native' suffix on master brunch. And the documentation needs update too. for more contexts please move to #119 .

**Comment by joelgetaction** [comment]
Thanks for responding @bang88 !  I would be happy to add a PR but I can't find where the documentation is ... Where would I make changes to the documentation to fix the broken links?

I checked out #119 but all the comments are in Chinese and unfortunately I don't speak Chinese ... Is there a way to see the comments in English or would this encourage broader participation - if the comments were in English?

Thanks again.

**Comment by bang88** [comment]
@joelgetaction sorry about that. The broken link has been fixed on local branch and not published yet. One more thing the issue was I renamed the files under master branch which not synced with the latest documentation.  Thanks for you help again. 😄

**Comment by bang88** [comment]
@joelgetaction Please refresh the documentation and you will see the latest version with link fixed.

**Comment by joelgetaction** [comment]
It works now!  Thanks @bang88 !  :-)
