### ISSUE TITLE
[Bug] Picker 组件的 PopupPicker 并未透传 actionTextActiveOpacity 和 actionTextUnderlayColor 属性，但在 Popup 组件的 props 类型中是存在的，导致使用时传入无实际效果

### ISSUE THREAD

**Issue by zengzjie** [ant-design/ant-design-mobile-rn#1342]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

<img width="765" alt="image" src="https://github.com/ant-design/ant-design-mobile-rn/assets/82022476/ecad54f7-c5d1-4c25-a039-59b50578b35d">
<img width="644" alt="image" src="https://github.com/ant-design/ant-design-mobile-rn/assets/82022476/6e37fd85-0f9d-4a25-9818-7da7a04e955c">

希望官方能将这两个属性补充透传下去，现在无法去修改点击时的底图颜色

### 🔴 版本

5.1.2

### 💻 运行环境

iOS, Android, Expo, react-native-web, react-native-windows, react-native-macos

### ⚫️ `npx react-native info`输出信息

System:
  OS: macOS 14.3.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 80.05 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: ~/.nvm/versions/node/v18.19.1/bin/node
  Yarn:
    version: 1.22.18
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.19.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "30"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.1
      - 33.0.2
      - 34.0.0
    System Images:
      - android-30 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by 1uokun** [comment]
fix: [Picker] add `okButtonProps`,`dismissButtonProps` in `@5.1.3`
