### ISSUE TITLE
[Bug] picker可否提供style传递

### ISSUE THREAD

**Issue by yubei826** [ant-design/ant-design-mobile-rn#1347]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

![WX20240626-134439@2x](https://github.com/ant-design/ant-design-mobile-rn/assets/4576565/75dc0319-b150-45de-8a08-6dfa7599aca3)

需要实现这样的UI设计，但目前样式无法更改popup

### 🔴 版本

18.20.2

### 💻 运行环境

iOS, Android

### ⚫️ `npx react-native info`输出信息

System:
  OS: macOS 14.5
  CPU: (11) arm64 Apple M3 Pro
  Memory: 137.77 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.2
    path: ~/.nvm/versions/node/v18.20.2/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v18.20.2/bin/yarn
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v18.20.2/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google APIs ATD ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

**Comment by 1uokun** [comment]
|属性|说明|类型|
|----|----|----|
| `styles` | 语义化结构 style | PickerViewStyle |


## PickerViewStyle 语义化样式
```typescript
interface PickerViewStyle {
  wrappper: ViewStyle
  wheelWrapper: ViewStyle
  mask: ViewStyle
  maskTop: ViewStyle
  maskMiddle: ViewStyle
  maskBottom: ViewStyle
}
```

**Comment by yubei826** [comment]
<img width="382" alt="image" src="https://github.com/ant-design/ant-design-mobile-rn/assets/4576565/8f79970e-ddc6-473f-a59f-60c6aa18c431">
我尝试过用这个ViewStyle更改样式，但只能改popup里面的内容的区域，无法更改最外层popup style
`styles={{ wrappper: { width: 200, height: 500, backgroundColor: '#ccc'}}}`

wheelWrapper 也用过，同样没办法更改popup

**Comment by 1uokun** [comment]
高度定制的UI只能用handleless UI来实现，可以基于本库的Wheel https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker-view/Wheel.tsx 组件
```js
import Wheel from '@ant-design/react-native/lib/picker-view/Wheel'
```

**Comment by yubei826** [comment]
好的，我研究一下，谢谢答复

**Comment by 1uokun** [comment]
https://rn.mobile.ant.design/docs/blog/what-is-styles-cn 文末有和你UI稿很相似的实现，可以参考一下
