### ISSUE TITLE
[Bug] DatePicker的defaultValue和defaultDate字段都没有生效

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#1351]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

```
<DatePicker
                value={this.state.customDate}
                // defaultValue={dayjs().subtract(2, 'day').toDate()}
                defaultValue={new Date()}
                minDate={new Date('2023-01-01')}
                maxDate={dayjs().subtract(2, 'day').toDate()} //最小是前天
                onOk={this.endTimeConfirm}
                onDismiss={this.endTimeCancel}
                precision="day"
                onChange={this.endTimeonChange}
                format="YYYY-MM-DD">
                <List.Item arrow="horizontal">
                  <View style={styles.datePickerListTitle}>
                    <Text style={styles.importFlag}>*</Text>
                    <Text style={styles.title}>自定义时间</Text>
                  </View>
                </List.Item>
              </DatePicker>
```

![image](https://github.com/ant-design/ant-design-mobile-rn/assets/12253453/e727dfd2-dabd-4688-987d-9376d159b559)

### 🔴 Version

9.8.1

### 💻 Environment

iOS, Android

### ⚫️ Output of `npx react-native info`

System:
OS: macOS 14.5
CPU: (10) arm64 Apple M2 Pro
Memory: 91.73 MB / 16.00 GB
Shell:
version: "5.9"
path: /bin/zsh
Binaries:
Node:
version: 20.0.0
path: /usr/local/bin/node
Yarn:
version: 1.22.19
path: /opt/homebrew/bin/yarn
npm:
version: 9.8.1
path: /opt/homebrew/bin/npm
Watchman:
version: 2024.01.22.00
path: /opt/homebrew/bin/watchman
Managers:
CocoaPods:
version: 1.14.3
path: /Users/inkcrazy/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
iOS SDK:
Platforms:
- DriverKit 23.5
- iOS 17.5
- macOS 14.5
- tvOS 17.5
- visionOS 1.2
- watchOS 10.5
Android SDK:
API Levels:
- "28"
- "29"
- "30"
- "31"
- "32"
- "33"
- "33"
- "34"
Build Tools:
- 28.0.3
- 29.0.2
- 29.0.3
- 30.0.2
- 30.0.3
- 31.0.0
- 33.0.0
- 33.0.1
- 33.0.2
- 34.0.0
- 34.0.0
System Images:
- android-31 | Android TV ARM 64 v8a
- android-33 | Google APIs ARM 64 v8a
- android-34 | Google APIs ARM 64 v8a
- android-UpsideDownCake | Google APIs ARM 64 v8a
Android NDK: Not Found
IDEs:
Android Studio: 2022.1 AI-221.6008.13.2211.9619390
Xcode:
version: 15.4/15F31d
path: /usr/bin/xcodebuild
Languages:
Java:
version: 11.0.22
path: /Users/inkcrazy/.sdkman/candidates/java/current/bin/javac
Ruby:
version: 3.0.0
path: /Users/inkcrazy/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.2.0
wanted: 18.2.0
react-native:
installed: 0.74.2
wanted: 0.74.2
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: false

**Comment by inkCrazy** [comment]
没问题了，maxDate限制了defaultValue，没注意,同时设置了value值是undefined或者null，会导致defaultValue失效，然后value就是最小日期

**Comment by Jhh910** [comment]
> 没问题了，maxDate限制了defaultValue，没注意,同时设置了value值是undefined或者null，会导致defaultValue失效，然后value就是最小日期

能否发下你改的代码，我参照下
