### ISSUE TITLE
[Bug] Toast不显示图标

### ISSUE THREAD

**Issue by Jhh910** [ant-design/ant-design-mobile-rn#1354]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

// 化验工单详情
import React, {useState, useEffect, useRef} from 'react';
import {
  ActivityIndicator,
} from 'react-native';
import {Toast, Provider} from '@ant-design/react-native';

  // 提交化验项目
  const submitLabItem = async () => {
    try {
      Promise.all(
        onChangeText.map(async item => {
          const response = await labItemHandleApi(item);
          // 在这里可以对每个元素的响应进行处理
        }),
      ).then(() => {
        // Alert.alert('提交成功', '', [{text: '知道了', style: 'cancel'}]);
        Toast.show({
          content: '提交成功',
          // icon: <Icon name="checkcircle" />,
          icon: <ActivityIndicator />,
          
        });
        // Toast.success('Success');
}
}
  return (
    <SafeAreaView style={styles.container}>
      <Provider>
       ........
      </Provider>
    </SafeAreaView>
  );
};

### 🔴 版本

8.19.2

### 💻 运行环境

Android

### ⚫️ `npx react-native info`输出信息

System:
OS: Windows 11 10.0.22621
CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
Memory: 2.10 GB / 15.73 GB
Binaries:
Node:
version: 18.12.1
path: D:\nodejs\node.EXE
Yarn: Not Found
npm:
version: 10.7.0
path: E:\SmartWater\SmartWaterAndroidApp\node_modules.bin\npm.CMD
Watchman: Not Found
SDKs:
Android SDK: Not Found
Windows SDK: Not Found
IDEs:
Android Studio: Not Found
Visual Studio:
- 17.9.34622.214 (Visual Studio Community 2022)
Languages:
Java: 17.0.11
Ruby: Not Found
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.2.0
wanted: 18.2.0
react-native:
installed: 0.74.0
wanted: 0.74.0
react-native-windows: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: Not found
newArchEnabled: Not found

### 补充说明

不显示图标  并且show方法被划掉了

**Comment by 1uokun** [comment]
检查一下`@ant-design/icons-react-native`是否安装成功
https://github.com/ant-design/ant-design-icons/tree/master/packages/icons-react-native

**Comment by Jhh910** [comment]
> 检查一下`@ant-design/icons-react-native`是否安装成功 https://github.com/ant-design/ant-design-icons/tree/master/packages/icons-react-native

 "@ant-design/icons-react-native": "^2.3.2",有的

**Comment by 1uokun** [comment]
如果是xcode环境，需要借助react-native-asset正确link字体文件
如果是expo环境，文档里有加载font的实例代码

**Comment by snowwindsand** [comment]
可以试一下网站上的这一步，我按这步操作了，仍然没显示
> 将字体资源路径配置到根目录下的 react-native.config.js 文件中 ( 如果没有，请创建 )

module.exports = {
  assets: ['node_modules/@ant-design/icons-react-native/fonts'],
};
然后执行[react-native-asset](https://github.com/unimonkiez/react-native-asset)的命令

npx react-native-asset

**Comment by 1uokun** [comment]
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/a9683392-6c64-4e12-b000-a198dee9d38e">

`icon`字段只在`5.2.0`版本才支持，注意一下版本，目前还在rc阶段

`5.1.3`版本之前只能通过

- `Toast.success(props)`
- `Toast.fail(props)`
- ...

执行带图标的toast

**Comment by Jhh910** [comment]
> <img alt="image" width="1005" src="https://private-user-images.githubusercontent.com/28673261/349385632-a9683392-6c64-4e12-b000-a198dee9d38e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDg4ODAsIm5iZiI6MTcyMjkwODU4MCwicGF0aCI6Ii8yODY3MzI2MS8zNDkzODU2MzItYTk2ODMzOTItNmM2NC00ZTEyLWIwMDAtYTE5OGRlZTlkMzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZDJmMjYxM2Y1ZDg0Yjg3ZDFhNTRiMzMxOTEyN2Q3ZGI4M2Q5YWRmZjUzYzIzNTU0ODIwOWRmY2IwY2Y1ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AS2sx0CpCRCVmydDFQFOx8y9jxGYDnZAaBxrgCeNOCc">
> `icon`字段只在`5.2.0`版本才支持，注意一下版本，目前还在rc阶段
> 
> `5.1.3`版本之前只能通过
> 
> * `Toast.success(props)`
> * `Toast.fail(props)`
> * ...
> 
> 执行带图标的toast

5.2.1版本了   toast图标还是不显示  就算是 Toast.success('Success')也不显示成功的图标
`

  //暂存
  const setLocalStorage = async () => {
    try {
      await AsyncStorage.setItem(
        `outbound_${route.params.id}`,
        JSON.stringify(Array.from(checkedList)),
      )
      Toast.success('success')
      // Toast.show({
      //   content: '上传中',
      //   icon: <ActivityIndicator />,
      // })
    } catch (error) {
      console.error('Error saving token:', error)
    }
  }
          <Button
            onPress={() => {
              setLocalStorage()
            }}
            style={[
              styles.button,
              styles.approveButton,
              {marginRight: 'auto', backgroundColor: 'rgb(100,150,255)'},
            ]}>
            <Text style={{color: 'white'}}>暂存</Text>
          </Button>`
          
          
![image](https://github.com/user-attachments/assets/f49ce6a6-9ee3-48a7-8f65-79034e985598)
