### ISSUE TITLE
[Bug] Form component background colour transparent 

### ISSUE THREAD

**Issue by kamprasad** [ant-design/ant-design-mobile-rn#1355]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

The Form component is adding default background colour white and no way to set it transparent.

Could you check and  make adjustment to remove default colour assign to Form component.

### 🔴 Version

5.2.0-rc.1

### 💻 Environment

iOS

### ⚫️ Output of `npx react-native info`

NA

**Comment by 1uokun** [comment]
Form defaults to `<List>` component rendering, in order to use the existing structure of List, So 
plan a :
```jsx
<Form
  styles={{
    Body: {
      backgroundColor: 'transparent',
    },
  }}
>
```

plan b:  set rendering element by `component` prop
```jsx
<Form component={View}>
```

**Comment by kamprasad** [comment]
Ok Thank you.
This solution works perfectly.

**Comment by kamprasad** [comment]
@1uokun  Is there a way to remove the margin around <Form.Item>?
If I use <Form.item noStyle={true}> which perfectly matches, but the error validation message no longer displayed in this case.

**Comment by 1uokun** [comment]
`<Form.Item>` is also based on the structure of `<List.Item>`, so

please continue to try using `styles` in `<Form.Item>`

eg: 
```jsx
<Form.Item
  styles={{
    Item: { paddingLeft: 0 },
    Line: { paddingRight: 0, paddingVertical: 0 },
  }}>

</Form.Item>
```

## Try More Semantic DOM style
```typescript
interface FormItemStyle extends ListItemStyle {
  formitemRow: ViewStyle
  formitemColumn: ViewStyle
  formItemExtra: ViewStyle | TextStyle  // default: { maxWidth: 50% } as ListItem['extra']
  formItemLabel: ViewStyle              // default: { minWidth: 65 }
  formItemLabelText: ViewStyle | TextStyle
  formItemControl: ViewStyle            // children style
  asterisk: TextStyle                   // required={true}
  optional: TextStyle                   // requiredMark="optional"
}
```

```typescript
interface ListItemStyle {
  underlayColor: ViewStyle
  Item: ViewStyle
  Line: ViewStyle
  Thumb: ImageStyle
  Content: TextStyle
  Extra: TextStyle
  Arrow: TextStyle
  ArrowV: TextStyle
  multipleLine: ViewStyle
  multipleThumb: ImageStyle
  column: ViewStyle
}
```

> Tips: antd is a **design & out-of-the-box**, it is in natural conflict with **customization**
> There will be a **headless UI** solution in the future, which may be suitable for you

**Comment by kamprasad** [comment]
Thank you
