### ISSUE TITLE
@bang88/react-native-ultimate-listview包报错找不到refreshableScrollView文件

### ISSUE THREAD

**Issue by xudan1** [ant-design/ant-design-mobile-rn#1361]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

版本升级到5.2.1，@bang88/react-native-ultimate-listview包报错找不到refreshableScrollView文件。旧版本4@bang88/react-native-ultimate-listview也缺少refreshableScrollView文件，但是运行不报错，新版本却报错

### 🔴 版本

v10.8.1

### 💻 运行环境

react-native-windows

### ⚫️ `npx react-native info`输出信息

warn Package @ant-design/icons-react-native contains invalid configuration: "dependency.assets" is not allowed. Please verify it's properly linked using "npx react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  Memory: 17.89 GB / 31.79 GB
Binaries:
  Node:
    version: 20.16.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.4
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 10.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.35122.118 (Visual Studio Enterprise 2022)
Languages:
  Java:
    version: 17.0.12
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-windows:
    installed: 0.74.12
    wanted: 0.74.12
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by 1uokun** [comment]
`@bang88/react-native-ultimate-listview@4.1.1`已更新，
 
重新install一下包即可

**Comment by xudan1** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design-mobile-rn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月8日(星期四) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design-mobile-rn] @bang88/react-native-ultimate-listview包报错找不到refreshableScrollView文件 (Issue #1361)





 
@***@***.***已更新，
 
重新install一下包即可
