### ISSUE TITLE
DatePicker 选中月份出现错位情况

### ISSUE THREAD

**Issue by yuzhiyi** [ant-design/ant-design-mobile-rn#137]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.3.1

### Environment
 react-native:0.57.5

### Reproduction link
[https://github.com/yuzhiyi/ant-design-mobile-rn/blob/master/datePickerError.png](https://github.com/yuzhiyi/ant-design-mobile-rn/blob/master/datePickerError.png)

### Steps to reproduce
DatePicker 月份先选择12月，然后滑动年份到下一年，就会出现错位的情况

### What is expected?
选中的日期应该在同一行

### What is actually happening?
选中的日期不在同一行

**Comment by yuzhiyi** [comment]
Android

**Comment by andmizi** [comment]
> IOS 还是Android ？



> IOS 还是Android ？

老哥，#131 帮我回答下吧，谢谢

**Comment by boonook** [comment]
请问一下我引入UI库怎么报错呢？_react2. default.createContext is not a function

**Comment by linjson** [comment]
@bang88 IOS也会出现错位情况

**Comment by SummerSMJ** [comment]
ios 在真机上不显示年份

**Comment by s349856186** [comment]
DatePicker有可能在优化下吗，升级到这版用不了了

**Comment by s349856186** [comment]
@yuzhiyi 你找到解决方法了吗？
@bang88 datepicker这个组件有时间再优化下吗？安卓选项错位，还有就是如果包裹在ScrollView里面没有办法滑动选择，会跟随ScrollView一起滑动，得不到焦点不知道为什么？谢谢

**Comment by JPSantistebanQ** [comment]
onOk not handled

**Comment by spencer741** [comment]
The original reproduction link is broken @yuzhiyi. New reproduction link? This issue has been open for some time.

**Comment by 1uokun** [comment]
fixed in 5.1.0
