### ISSUE TITLE
[Bug] Form表单的labelStyle，设置无效。版本v5.2.1

### ISSUE THREAD

**Issue by hdjhdjhdj** [ant-design/ant-design-mobile-rn#1371]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

官方文档的form案例
https://rn.mobile.ant.design/components/form-cn/

### 🔴 版本

5.2.1

### 💻 运行环境

Android

### ⚫️ `npx react-native info`输出信息

![image](https://github.com/user-attachments/assets/0f34f3df-7393-4776-b36d-010301e98f0b)

### 补充说明

![image](https://github.com/user-attachments/assets/05ca128b-00ab-41c4-84a7-602ec8519fca)

**Comment by jaydeep911** [comment]
Updated to the latest version, but it still doesn't work on the mobile side.
Added labelStyle in the form, but it has no impact.
```

<Form 
labelStyle={{
            minWidth:200,
             textAlign: component.label_align ? component.label_align:  'right',
             baackgroundColor:component.label_align ? 'red':  'blue' 
     }}

...
/>
```
