### ISSUE TITLE
[Bug] The Form element adding extra white border top of the page

### ISSUE THREAD

**Issue by kamprasad** [ant-design/ant-design-mobile-rn#1375]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

I'm using Antd Form element and there is a white colour border added automatically to the page.

<img width="428" alt="image" src="https://github.com/user-attachments/assets/948238a3-4e45-4e57-a850-709b93b20d02">

<img width="402" alt="image" src="https://github.com/user-attachments/assets/7216c3e1-94de-4682-a91c-e329941d97c0">

Could you suggest a solution for this? I want to remove this line from the UI.

### 🔴 Version

5.2.2

### 💻 Environment

iOS, Android

### ⚫️ Output of `npx react-native info`

NA

### Additional comments

NA

**Comment by 1uokun** [comment]
need show more code

**Comment by kamprasad** [comment]
Hi @1uokun,

I have very basic component as below. The Form element by default adding white color as background and I set it as transparent to see parent component bg color
Still one border line adding to the Form element as default which not sure how to get rid of. 

```
import React from 'react';
import {Text, View} from 'react-native';
import {Form} from '@ant-design/react-native';

export const AppScreen = () => {
  return (
    <React.Fragment>
      <View style={{height: 100, backgroundColor: 'gray', top: 100}}>
        <Form
          initialValues={{}}
          onFinish={() => {}}
          style={{backgroundColor: 'transparent', top: 10}}
          styles={{
            Body: {
              backgroundColor: 'transparent',
              borderColor: 'transparent',
              borderBlockColor: 'transparent',
            },
            List: {
              backgroundColor: 'transparent',
              borderColor: 'transparent',
              borderBlockColor: 'transparent',
            },
          }}>
          <Text>Name</Text>
        </Form>
      </View>
    </React.Fragment>
  );
};
```


![image](https://github.com/user-attachments/assets/1fd48c14-dbaa-4b41-8375-d61247db41f1)

**Comment by 1uokun** [comment]
```
styles={{
  BodyBottomLine: {
    height: 0,
  },
}}
```

**Comment by kamprasad** [comment]
Thank you ! 
It works perfectly.
