### ISSUE TITLE
[Bug] Modal  在使用transparent 背景透明的时候边距如何自定义以及编剧如何自定义？

### ISSUE THREAD

**Issue by chen834921478** [ant-design/ant-design-mobile-rn#1377]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

![12312313](https://github.com/user-attachments/assets/9047bb35-e698-4f36-8b6b-83243f1546d5)
 这里的边距如何自定义呢？
    <Modal
      visible={visible}
      animationType={'fade'}
      transparent
      maskClosable
 >
      <View style={styles.container}>
        <Image
          style={styles.headerImage}  />
        <Text style={styles.title}>登陆</Text>
      </View>
      {children}
    </Modal>

### 🔴 版本

5.2.1

### 💻 运行环境

iOS

### ⚫️ `npx react-native info`输出信息

System:
  OS: macOS 14.5
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 353.40 MB / 16.00 GB
  Shell:
    version: 3.2.57
    path: /bin/bash
Binaries:
  Node:
    version: 18.20.3
    path: ~/.nvm/versions/node/v18.20.3/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v18.20.3/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v18.20.3/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by 1uokun** [comment]
默认固定宽度并且flex居中的，没有边距，用宽度来控制余量

更多样式参考`styles`属性 [styles是什么？](https://rn.mobile.ant.design/docs/blog/what-is-styles-cn)
```jsx
interface ModalStyle {
  container: ViewStyle      // 设置了`z-index`
  wrap: ViewStyle           // 设置了modal的 垂直居中&水平居中
  innerContainer: ViewStyle // modal主要内容区域, 默认：`{ width:286 }`
}
```

**Comment by chen834921478** [comment]
感谢，可以了，
 style={{width: 350, paddingTop: 0}}
      bodyStyle={{
        paddingHorizontal: 0,
        paddingBottom: 0,
      }}
另外再咨询一个问题，这里的style={{width: 350, paddingTop: 0}} 这里的width 为什么不能使用 '90%' 这种？

**Comment by 1uokun** [comment]
父元素`styles.wrap`用的是flex弹性布局，用百分比会坍塌

改wrap样式可以实现
