### ISSUE TITLE
[Bug] Collapse的Collapse.Panel  无法使用

### ISSUE THREAD

**Issue by Jhh910** [ant-design/ant-design-mobile-rn#1378]
### 💬 前提强调

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 描述详情/重现步骤

   <Collapse accordion>
                <Collapse.Panel key="1" title="第一项">
                  手风琴模式只能同时展开一个
                </Collapse.Panel>
                <Collapse.Panel key="2" title="第二项">
                  手风琴模式只能同时展开一个
                </Collapse.Panel>
                <Collapse.Panel key="3" title="第三项">
                  手风琴模式只能同时展开一个
                </Collapse.Panel>
              </Collapse>
        问题：      当我加上Collapse.Panel部分之后  就报错TypeError: Cannot read property 'makeMutable' of undefined
              当我删除Collapse.Panel部分之后  就不报错
        尝试解决： 查资料说是在  babel.config.js文件中添加
  plugins: [
    /// This Plugin should be last
    'react-native-reanimated/plugin',
  ],
  我尝试添加重新运行仍然报错      TypeError: Cannot read property 'makeMutable' of undefined
              

### 🔴 版本

8.19.2

### 💻 运行环境

Android

### ⚫️ `npx react-native info`输出信息

System:
  OS: Windows 10 10.0.22621
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H
  Memory: 1.76 GB / 15.73 GB
Binaries:
  Node:
    version: 20.15.1
    path: D:\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: ~\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
  npm:
    version: 10.7.0
    path: D:\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.9.34622.214 (Visual Studio Community 2022)
Languages:
  Java:
    version: 17.0.11
    path: C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: ^18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by 1uokun** [comment]
提供一下package.json信息、
或者其中的
 - react-native-gesture-handler
 - react-native-reanimated

版本

**Comment by Jhh910** [comment]
> 提供一下package.json信息、 或者其中的
> 
> * react-native-gesture-handler
> * react-native-reanimated
> 
> 版本

这是我的版本![image](https://github.com/user-attachments/assets/7413dbec-4886-410e-9026-a1dce89ade2f)
我的项目不是expo创建的  expo-font这个依赖装不了  请问expo-font这个依赖必须要装吗

**Comment by 1uokun** [comment]
试一下别人提供的解决方案：https://github.com/software-mansion/react-native-reanimated/issues/5625#issuecomment-1926979262

不用expo就不用安装expo-font
