### ISSUE TITLE
SearchBar 怎么取消input后面的取消按钮和input的动画显示

### ISSUE THREAD

**Issue by usefuu** [ant-design/ant-design-mobile-rn#138]
SearchBar 怎么取消input后面的取消按钮和input的动画显示
![image](https://user-images.githubusercontent.com/30901983/48700560-3b71e600-ec27-11e8-8360-905d298e6a55.png)
![image](https://user-images.githubusercontent.com/30901983/48700585-4f1d4c80-ec27-11e8-89ea-dce1c1d4656f.png)
![image](https://user-images.githubusercontent.com/30901983/48700598-593f4b00-ec27-11e8-9a58-5dae82bdf8d6.png)

取消按钮用display设置成none了后，input上总是出现动画效果

**Comment by bang88** [comment]
You can use `showCancelButton` prop for hide `cancel` button.

> input上总是出现动画效果 ?
