### ISSUE TITLE
[Bug] 建议Modal添加动画持续时间，默认300毫秒太快了

### ISSUE THREAD

**Issue by LeeYuze** [ant-design/ant-design-mobile-rn#1386]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

![image](https://github.com/user-attachments/assets/64848d34-e9d1-4445-9718-0a0b1964457d)
![image](https://github.com/user-attachments/assets/6d97c898-132c-442d-b3f1-96b175ce32ef)

### 🔴 Version

5.2.3

### 💻 Environment

Android

### ⚫️ Output of `npx react-native info`

System:
  OS: Windows 10 10.0.19045
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
  Memory: 1.63 GB / 9.00 GB
Binaries:
  Node:
    version: 20.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.8.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio: Not Found
Languages:
  Java: 17.0.12
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by 1uokun** [comment]
fixed in `5.3.0` by `animationDuration`
