### ISSUE TITLE
modal 有内边距

### ISSUE THREAD

**Issue by axuan2015** [ant-design/ant-design-mobile-rn#139]
modal 有内边距问题,怎么去除啊？

**Comment by axuan2015** [comment]
styles={{
                    body: {
                        paddingTop: 0,
                        paddingBottom:0,
                        paddingHorizontal: 0,
                    }
                }}
这样可以实现,但是 又把其他样式破坏了

**Comment by bang88** [comment]
use `bodyStyle`
