### ISSUE TITLE
[Bug] 怎么修改DatePicker ，左边关闭和右边确定时，点击颜色啊

### ISSUE THREAD

**Issue by wulaizi** [ant-design/ant-design-mobile-rn#1403]
### 💬 Before You Start

- [X] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### 🙋 Description/Step to reproduce

<img width="343" alt="Snipaste_2024-12-12_16-39-48" src="https://github.com/user-attachments/assets/857bdbb8-f735-484a-8612-e5543ce65064" />
我找了好久都没有看到可以修改这个点击  颜色的属性

### 🔴 Version

^5.0.5

### 💻 Environment

iOS

### ⚫️ Output of `npx react-native info`

没有报错 就是不知道怎么自定义

### Additional comments

大佬们帮忙看看诶

**Comment by 1uokun** [comment]
`actionTextUnderlayColor` 或者 `underlayColor`

**Comment by wulaizi** [comment]
> underlayColor

非常感谢 actionTextUnderlayColor 确实可以使用，看了下好像是ts 没有暴露 会爆红，但是有效果
