### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by Joan1106web** [ant-design/ant-design-mobile-rn#143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通过Checkbox实现全选，和非全选，用户在选择文件时，可是点击全选按钮选择全部，也是自己选择多个，目前我只能分别去实现，分别使用checked、onChange，但联合使用时，onChange点击无效，请大神帮帮忙，谢谢

### What does the proposed API look like?
通过Checkbox实现全选，和非全选，用户在选择时，比较常见

**Comment by bang88** [comment]
操作数据 不要操作节点  

```jsx

const data = [{ checked: true, xxx},{checked: false},xxx]

data.map(d=> <Checkbox checked={d.checked} />)
...

```

每次全选的时候修改数据就好，数据变了会重新render这个时候应该能满足你的需求
