### ISSUE TITLE
Button组件activeStyle问题（2.3.0）

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design-mobile-rn#161]
2.3.0 修复Button组件activeStyle属性为对象时不起作用的问题.  #101 

修复后的版本，activeStyle不传值时，点击背景色变成了黑色，默认样式不起作用了。

==================================================
activeStyle 默认有个空对象

var underlayColor = StyleSheet.flatten(activeStyle ? activeStyle : _styles[type + 'Highlight']).backgroundColor;

Button.defaultProps = {
    ...,
    activeStyle: {},
   ...
};

**Comment by bang88** [comment]
2.3.3
