### ISSUE TITLE
Tabs宽度非全屏时样式存在问题（2.3.2）

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design-mobile-rn#162]
下图黑色框为设备宽度，橙色框为tabs宽度，这种情况下红圈内的样式有问题。红圈内的下划线的整个宽度始终是设备的宽度
![qq 20181213171850](https://user-images.githubusercontent.com/35723666/49928522-4143aa00-fefb-11e8-9599-56d935e836a8.png)
![qq 20181213172357](https://user-images.githubusercontent.com/35723666/49928799-e9f20980-fefb-11e8-8e0f-ec60edcf6595.png)

**Comment by bang88** [comment]
看看 #119 看你们怎么使用了。

是个不兼容的版本（针对样式，之前的style/index.tsx）3.0 重构了

**Comment by bang88** [comment]
Button的需要更新的话 晚点有个2.3.1

**Comment by bang88** [comment]
现在在准备3.0.0 如果顺利的话这周可以发布。

**Comment by jihfgz** [comment]
有新的app用新版本。我这不急，都是内部使用的系统。今天事不多来反馈下问题。tabs的先我现在是直接去掉的，能解决最好

**Comment by bang88** [comment]
tabs 的要看看之前的代码，估计之前是用了 window的宽度了。我等下更新一个 2.3.x的版本 修复button的问题

**Comment by bang88** [comment]
如果有空的话 可以尝试一下新版 @next  有问题反馈的话可以早点解决
