### ISSUE TITLE
the document is not right about the Toast.hide

### ISSUE THREAD

**Issue by JackClown** [ant-design/ant-design-mobile-rn#164]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.1

### Environment
react-native

### Reproduction link
[https://rn.mobile.ant.design/components/toast/](https://rn.mobile.ant.design/components/toast/)

### Steps to reproduce
just open it

### What is expected?
nothing about Toast.hide

### What is actually happening?
there is the method - Toast.hide

---
Toast.hide has been removed, and it's not in the source code actually,so the document is not right about it. But I think we maybe still need Toast.hide and now how can we cancel the Toast, use Portal?

**Comment by bang88** [comment]
@JackClown The hide method have been removed but the documentation not update yet. Now we use Portal for add and remove Toast or Modal.

**Comment by bang88** [comment]
Another word. We support multiple Toast at the same time from 3.0.0. and Toast.xxx now return a key and you can Portal.remove(key) to remove toast

**Comment by JackClown** [comment]
@bang88 I see, it's indeed a good idea for both Toast and Modal, Thanks

**Comment by bang88** [comment]
😄

**Comment by bang88** [comment]
> @bang88 I see, it's indeed a good idea for both Toast and Modal, Thanks

documentation not update yet. PR are welcome @JackClown
