### ISSUE TITLE
ListView加载问题paginationAllLoadedView

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design-mobile-rn#165]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.1

### Environment
react-native: 0.57.7  

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wq95m07vmw)

### Steps to reproduce
直接开启页面

### What is expected?
上拉列表触底时加载并显示loading状态，加载完毕显示全部加载的提示

### What is actually happening?
打开页面会自动触发多次onPaginate加载，加载完成不会显示allloadedtext

---
ListView中加入paginationAllLoadedView={undefined} 屏蔽antd中自定义的的paginationAllLoadedView可以解决该问题，可能需要调整封装的ListView中paginationAllLoadedView的样式定义或者去掉这个属性

**Comment by bang88** [comment]
@johnnylc 来个PR。
