### ISSUE TITLE
tabs 高度自适应

### ISSUE THREAD

**Issue by jiangxia** [ant-design/ant-design-mobile-rn#169]
tab组件有一个很普遍的问题，就是某个选项卡的内容比较长，另一个选项卡内容区域的底部就会留下很长的空白，这个有办法解决么？

预期效果是每个tabs的高度是自适应的

**Comment by sangningWEB** [comment]
<Tabs
                    tabs={tabs}
                    tabBarUnderlineStyle={{
                      display:'none' //下滑线取消
                    }}
                    swipeable={false} //滑动取消
                    destroyInactiveTab={true} //销毁不可见tab
                    prerenderingSiblingsNumber={0}//加载可见tab周围的tab数据0条
                    initialPage={0}//初始化tab 0
                    page={this.state.tabPage}//显示第几个tab
                    onTabClick={(tab,index)=>{//点击tab的回调
                      this.setState({
                        tabPage:index
                      })
                    }}
                >

**Comment by liuche692326532** [comment]
I wonder if this problem is solved？Height not adaptive
