### ISSUE TITLE
AntdMobileRN 2.x升级到3.02问题

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design-mobile-rn#172]
react-native 版本0.55.4      node版本8.9.4
-----------------------------------------------------------------
之前项目2.3 版本的 ，升级到3.0.2 。Icon相关的都不正常

执行 react-native link @ant-design/icons-react-native   没有错误提示，也没有成功提示。

--------------------------------------------------------------------
之后新建了一个测试App，新建的App里面Icon是正常的，但过程中有点问题

react-native init xxxxxxx 0.55.4            (正常，能成功启动)

npm install @ant-design/react-native --save         （不正常，提示删除了800多个包，不能启动，不能识别为react-native项目）

react-native link @ant-design/icons-react-native           （错误）

npm i                                   (重新运行了 npm i 后 之前删除了800多个包回来了)

react-native link @ant-design/icons-react-native             （正常，app启动,有图标显示）

-----------------------------------------------------------------------------
之后把测试app 安卓目录下的 字体文件移动到  老项目里面，老项目的图标也正常了

**Comment by bang88** [comment]
删掉 node_modules 重新安装一下。 这个问题应该是安装依赖的问题
