### ISSUE TITLE
SegmentedControl 默认样式问题（3.0.2）

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design-mobile-rn#173]
react-native 版本 0.55.4
SegmentedControl的默认主题颜色是写死的，修改主题样式中的颜色对这个组件不起作用。

SegmentedControl.defaultProps = {
    ...
    tintColor: '#108ee9',
    style: {}
};
-------------------------------------------------------------------
另外这个组件有个警告
Failed prop type:Invalid prop 'underlayColor' supplied to 'TouchableHighlight':277801293

**Comment by bang88** [comment]
来个 PR。
