### ISSUE TITLE
Toast.loading 不消失

### ISSUE THREAD

**Issue by axuan2015** [ant-design/ant-design-mobile-rn#175]
Toast.loading(xxx)
然后再Toast.success或者Toast.fail(xx)
toast 将不会消失
目标机型:iphonex 12.0
antd 3.0.3版本

**Comment by yuyongmao** [comment]
我遇到的问题是toast 不出来

**Comment by bang88** [comment]
用expo预览的没有看到你们说的问题。 你们也可以自己扫码看看

**Comment by bang88** [comment]
要么自己设置一个时间自动关闭，要么 
```js
const key = Toast.loading('xxx')

Portal.remove(key)

```
手动关闭

**Comment by gaoxiaosong1113** [comment]
我也遇到同样的问题
`
    const loading = Toast.loading('加载中', 0)
    Portal.remove(loading)
    Toast.success('设置成功', 1)
`
会导致Toast一直显示，不消失

**Comment by xiaohuoni** [comment]
同样不消失

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/83732464-a7d3ff00-a67e-11ea-8435-5cd2e0be6a10.png)

**Comment by bang88** [comment]
什么版本的 antd

**Comment by xiaohuoni** [comment]
"@ant-design/react-native": "^3.3.0",

**Comment by chj-damon** [comment]
@bang88 这里也一样，在调用Portal.remove(key)之后在安卓真机上Toast不会消失。模拟器和IOS上是正常地。
