### ISSUE TITLE
如何实现InputItem在iphone

### ISSUE THREAD

**Issue by xjl271314** [ant-design/ant-design-mobile-rn#177]

**Comment by xjl271314** [comment]
import InputItemStyle from 'antd-mobile-rn/lib/input-item/style/index.native'
let { height , ...otherInput} = InputItemStyle.container
let cInputStyle = {
  ...InputItemStyle,
  container: {
    height: 55,
    ...otherInput
  },
  text: {
    color: '#333',
    minWidth: 110,
    fontFamily: 'PingFangSC-Regular',
    fontSize:15,
  },
  extra:{
    fontFamily: 'PingFangSC-Regular',
  },
  input: Object.assign({}, InputItemStyle.input, {fontSize: 15,textAlign:'right',paddingRight:15})
}

这里的input样式字体大小会随用户iphone上设置的显示字体大小影响？如何让字体大小不受用户设置影响？

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/50196917-14224c00-0380-11e9-9733-cd5b8d55e52d.png)
