### ISSUE TITLE
In most cases, there will only be one Toast, and it is best to provide a portal.clearAll() . not pass key

### ISSUE THREAD

**Issue by pwz1985** [ant-design/ant-design-mobile-rn#181]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Development is simpler

### What does the proposed API look like?
PortalGuard add clearAll function

**Comment by bang88** [comment]
PR welcome

**Comment by bang88** [comment]
Thanks for your contribution please checkout #182 which we have discussed there. 

We need a better way to clear all Toast and should not affect other Portals.
