### ISSUE TITLE
Modal.alert 无法弹出

### ISSUE THREAD

**Issue by Evan-Future** [ant-design/ant-design-mobile-rn#204]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.1

### Environment
RN0.57.8, ant-design/react-native: 3.0.3, react: 16.6.3

### Reproduction link
[https://rn.mobile.ant.design/components/modal-cn/](https://rn.mobile.ant.design/components/modal-cn/)

### Steps to reproduce
Button 组件，onPress 后，到Modal.alert 无效，加了InteractionManager处理也无法弹出。应该为bug

### What is expected?
弹出确认框进行下一步操作

### What is actually happening?
无任何反应，debug 确实执行到 Modal.alert了，控制台也无任何报错和警告

**Comment by Evan-Future** [comment]
> Hello @Evan-Future. Please provide a re-producible demo: https://codesandbox.io/s/9ll8k8614p?module=%2Fsrc%2FApp.js or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.

updated code:
https://codesandbox.io/s/ll84zjpvyq

**Comment by bang88** [comment]
https://codesandbox.io/s/2pmj94mx80

**Comment by bang88** [comment]
Provider 是必须的 3.0.0 请查看升级文档
