### ISSUE TITLE
Carousel在Web和RN拖动功能无法使用

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design-mobile-rn#212]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.3

### Environment
react-native: 0.57.7  Chrome：70.0.3538.110

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k9o5yvrnjv)

### Steps to reproduce
左右或者上下拖动Carousel中的页面

### What is expected?
显示上一张或者下一张页面

### What is actually happening?
没有正确响应

**Comment by bang88** [comment]
Expo里面不能重现这个问题，另外web预览不支持拖动。

**Comment by johnnylc** [comment]
Sorry 是我使用的的问题，在Carousel的style中设置了height width导致的
