### ISSUE TITLE
希望内置表单校验功能

### ISSUE THREAD

**Issue by youngxiaoran** [ant-design/ant-design-mobile-rn#215]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表单校验

### What does the proposed API look like?
表单校验

**Comment by youngxiaoran** [comment]
希望内置 rc-form

**Comment by bang88** [comment]
1. 普通使用 请直接使用 `rc-form`
2. 如果要根据配置生成表单的话 单独讨论

**Comment by youngjuning** [comment]
请问如何参与开发，我在本地修复bug之后如何测试。我看了英文文档不是很清楚。望指教！还有，提交issues的限制过于严格

**Comment by bang88** [comment]
1. clone repo
2. checkout -b fixes-xxx
3. fixes bugs && run `yarn test`

**Comment by Tzng** [comment]
> 1. 克隆回购
> 2. checkout -b fixes-xxx
> 3. 修复错误&&运行 `yarn test`

您好，fixes-xxx这个后面的xxx是自己来取的名字吗，是从master分支创建新的分支吗
