### ISSUE TITLE
Provider 国际化不够简洁

### ISSUE THREAD

**Issue by 2248157705** [ant-design/ant-design-mobile-rn#221]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可能是我的使用方法有误，现在每个页面中ant-design-mobile-rn 组件外层都要包着Provider 才能实现国际化，代码很冗余，又臭又长的

### What does the proposed API look like?
应用内Provider 标签只需配置一次，而不是每个页面中ant-design-mobile-rn 组件外层都要包着Provider 才能实现国际化，就像react-redux 里面的Provider一样，应用只需配置一次，就可以再应用的任何位置全局使用

**Comment by bang88** [comment]
现在只需在APP入口处配置一次Provider就好了。
