### ISSUE TITLE
DatePicker mode=date display problem

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design-mobile-rn#23]
From https://github.com/ant-design/ant-design-mobile/issues/2602

**Comment by suwu150** [comment]
这个问题是在新的版本中解决了吗？我的版本是    "antd-mobile": "^2.1.8",还是不能够正常显示，请问能不能提供一点解决思路

**Comment by bang88** [comment]
@suwu150 看不到你问题的图片。

这是我本地的图片是不是正常的？
![image](https://user-images.githubusercontent.com/433259/49351939-94924d00-f6f0-11e8-96f0-ddaf337bc0c4.png)
