### ISSUE TITLE
Modal组件在react-native 0.55.4 版本下不正常

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design-mobile-rn#232]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.1

### Environment
react-native 0.55.4

### Reproduction link
[https://rn.mobile.ant.design/components/modal-cn/](https://rn.mobile.ant.design/components/modal-cn/)

### Steps to reproduce
react-native init demo --version 0.55.4
cd demo
npm i
npm install @ant-design/react-native --save
react-native link @ant-design/icons-react-native

修改App.js
```
import React, { Component } from 'react';
import {Provider,Button,Modal} from '@ant-design/react-native';
export default class App extends Component<Props> {
render() {
return (
<Provider>
<Button onPress={()=>Modal.alert('title')}>showModal</Button>
</Provider>
);
}
}
```

### What is expected?
显示Modal

### What is actually happening?
报错，死循环
![tim 20181227152256](https://user-images.githubusercontent.com/35723666/50473385-b7660780-09f7-11e9-93e0-2b0b699c38d7.png)

---
react-native 新版本一切正常

**Comment by huker** [comment]
Have the same problem

**Comment by jihfgz** [comment]
有谁找到原因了吗
在 portal-manager文件的update 方法里面套层setTimieout 后，就正常了。
原因不明
`_this.update = function (key, children) {`
`            setTimeout(function(){`
`                return _this.setState(function (state) {`
`                    return {`
`                        portals: state.portals.map(function (item) {`
`                            if (item.key === key) {`
`                                return (0, _extends3['default'])({}, item, { children: children });`
`                            }`
`                            return item;`
`                        })`
`                    };`
`                });`
`            },0)`
`        };`

**Comment by JadeTao** [comment]
version of the `@ant-design/react-native`?

**Comment by jihfgz** [comment]
@ant-design/react-native最新版本3.0.4  问题还在
react-native 新老版本 渲染生命周期机制有点差别
react-native新版本中,如下代码中，按下按钮后，MyComponent 的componentDidUpdate不会触发，也不会运行render方法，和web版的react一样的机制。但是在老版本中 ，父组件render，始终会触发MyComponent 的render.

```
class App extends Component {
     constructor() {
          this.myComponent  = <MyComponent />
     }
     render() {
           return (
            <View>
                  <Button onPress={()=>this.forceUpdate()}>button</Button>
                  { this.myComponent }
            </Text>
        );
     }
}
```

--------------------------------------------------------
然后在@ant-design/react-native中 对话框都放在 PortalManager 的 state.portals 中，如上面代码的写法。
使用 react-native 老版本时，PortalManager  render-> 对话框render（对话框包含子组件Portal）-> Portal render ->PortalConsumer render -> PortalConsumer componentDidUpdate 中调用 PortalManager 的update方法 -> update调用this.setState 刷新 PortalManager   引起死循环

使用react-native 新版本时，PortalManager  render 不会触发 对话框render 没有死循环

**Comment by bang88** [comment]
`3.0.0` 以后请更新 `react-native` 到 `0.57.x `以上
