### ISSUE TITLE
Grid property onClick has changed to onPress in the source code, but the doc doesn't

### ISSUE THREAD

**Issue by JackClown** [ant-design/ant-design-mobile-rn#233]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/blob/8373d9726d1a3d933f07d631024aa1bb622b90e0/components/grid/index.tsx#L38](https://github.com/ant-design/ant-design-mobile-rn/blob/8373d9726d1a3d933f07d631024aa1bb622b90e0/components/grid/index.tsx#L38)

### Steps to reproduce
just open it

### What is expected?
onClick

### What is actually happening?
onPress

| Environment | Info |
|---|---|
| antd | 3.0.3 |
| React | react-native@0.57.4 |
| System | macOS Mojave 10.14.2 |
| Browser | not in browser |

---
Change log and upgrade notes don't mention it. And I don't think this change is necessary.😕

**Comment by bang88** [comment]
Document not updated yet and help wanted.

> And I don't think this change is necessary.

More react native way 😄
