### ISSUE TITLE
upgrade from 2.x to 3.0.3  response error

### ISSUE THREAD

**Issue by tiyunchen** [ant-design/ant-design-mobile-rn#241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/docs/react/upgrade-notes-cn](https://rn.mobile.ant.design/docs/react/upgrade-notes-cn)

### Steps to reproduce
upgrade `antd-design-mobile-rn` from 2.x to 3.0.3 ，`import` method changed ，`package.json `delete old version name， then run `react-native run-android `

### What is expected?
working  well

### What is actually happening?
`undefined is not a function (evaluating'_react2['defaukt']'.crearecontent(null))`, i also delete `node_module` and run `react-native run-android `, it not  work , my native-version is `0.5.1`

|
![image](https://user-images.githubusercontent.com/24793416/50507378-420e3b80-0ab8-11e9-9e4c-54f20f481ada.png)
 Environment | Info |
|---|---|
| antd | 3.0.1 |
| React | 16.0 |
| System | Android |
| Browser | chrome |

**Comment by bang88** [comment]
Upgrade your `react` version to 16.3 +
