### ISSUE TITLE
Cannot do .focus for Input

### ISSUE THREAD

**Issue by gibbsfromncis** [ant-design/ant-design-mobile-rn#25]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
ant-mobile-rn `v2.2.0-beta.1`
react-native `v0.55.3`
### Steps to reproduce
```
<InputItem ref={(ref: any): void => {
  if (ref)
    ref.focus();
  }}/>
```
### What is expected?
Put focus on field

### What is actually happening?
i'm getting error ` _ref.focus is not function`

**Comment by warmhug** [comment]
Your usage seems not right?

**Comment by gibbsfromncis** [comment]
@warmhug can you provide an example how can I use it please?

**Comment by bang88** [comment]
@gibbsfromncis You can do it like this `<InputItem autoFocus />`
