### ISSUE TITLE
react-native 中ScrollView嵌套DatePicker，会产生DatePikcer不能滑动，rn中响应的是ScrollView中的上下滑动，

### ISSUE THREAD

**Issue by 986982229** [ant-design/ant-design-mobile-rn#256]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
关键代码： 
注意：模拟器中的元素一定要超过整过屏幕能够上下滑动
<ScrollView>
        <View>
                  <Provider locale="zhCN">
                    <DatePicker
                      value={this.state.value}
                      mode="date"
                      minDate={new Date(1900, 1, 1)}
                      maxDate={new Date(2100, 12, 31)}
                      onChange={this.onChangeDatePickerItem}
                      format="YYYY-MM-DD"
                    >
                      <List.Item arrow="horizontal">{this.state.datePickerValue}</List.Item>
                    </DatePicker>
                  </Provider>
       </View>
</ScrollView>

### What is expected?
日期选择器，能够在rn原生标签中ScrollView中使用

### What is actually happening?
不能使用，当在时间选择器上下滑动时，实际滑动响应的是ScrollView的onScroll事件

| Environment | Info |
|---|---|
| antd | 3.0.5 |
| React | react-native 0.57.8 |
| System | Windows |
| Browser | 模拟器 |

**Comment by s349856186** [comment]
@986982229 解决了吗？怎么处理的，最新版本"@ant-design/react-native": "^3.1.8",还是有这个问题

**Comment by yorickshan** [comment]
same issue

**Comment by yorickshan** [comment]
> @986982229 解决了吗？怎么处理的，最新版本"@ant-design/react-native": "^3.1.8",还是有这个问题 @BANG88

哈喽 请问这个问题后来解决了吗？

**Comment by 1uokun** [comment]
# react native scrollview inside scrollview not scrolling
> react-native ScrollView内嵌套ScrollView无法滑动问题

 add `_ScrollViewComponent` prop in `@5.1.1`

```jsx
import { ScrollView } from 'react-native'
import { ScrollView as GestureScrollView } from 'react-native-gesture-handler'


<ScrollView>

  <DatePicker 
    // To fix: Wheel not scrolling in Android ScrollView
    _ScrollViewComponent={GestureScrollView}
   
  />

</ScrollView>
```

**Comment by 1uokun** [comment]
# Use Scrollview `nestedScrollEnabled` in `@5.1.3+`
https://reactnative.dev/docs/scrollview#nestedscrollenabled-android

```xml
<Scrollview 
  nestedScrollEnabled={true}
>

  <PickerView />
  <DatePickerView />
  <Carousel />
  <Tabs />

</Scrollview>
```
