### ISSUE TITLE
Feature：丰富 Slider 可配置性

### ISSUE THREAD

**Issue by youngjuning** [ant-design/ant-design-mobile-rn#260]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
丰富 Slider 可配置性

### What does the proposed API look like?
就像这个库一样：https://www.npmjs.com/package/react-native-slider

**Comment by bang88** [comment]
这个现在还是保持使用默认的slider你有太多自定义需求的话建议直接使用这个库就好了
