### ISSUE TITLE
Tabs 设置tabBarUnderlineStyle 无法隐藏线条

### ISSUE THREAD

**Issue by axuan2015** [ant-design/ant-design-mobile-rn#267]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/issues/174](https://github.com/ant-design/ant-design-mobile-rn/issues/174)

### Steps to reproduce
https://github.com/ant-design/ant-design-mobile-rn/issues/174

### What is expected?
Tabs 设置tabBarUnderlineStyle 可以隐藏整体线条

### What is actually happening?
Tabs 设置tabBarUnderlineStyle 不可以隐藏整体线条

| Environment | Info |
|---|---|
| antd | 3.0.5 |
| React | 16.6.0-alpha.8af6728 |
| System | android |
| Browser | android |

**Comment by axuan2015** [comment]
![image](https://user-images.githubusercontent.com/14288893/51010781-b9e86580-1590-11e9-8239-a829e9e372d2.png)
![image](https://user-images.githubusercontent.com/14288893/51010797-c4a2fa80-1590-11e9-8134-ea90476caa79.png)
这条线始终无法去掉

**Comment by bang88** [comment]
从3.0.0 以后你可以覆盖样式
```jsx
<Tabs tabs={tabs} renderUnderline={() => null} styles={{
          topTabBarSplitLine: {
            borderBottomWidth: 0,
          },
        }}>
...
</Tabs>
```

**Comment by loveyuboy** [comment]
<Tabs tabs={tabs} tabBarPosition='bottom' renderUnderline={() => null} styles={{
          topTabBarSplitLine: {
            borderBottomWidth: 0,
          },
        }}>
...
</Tabs>
如果tabBarPosition='bottom' 则无法隐藏

**Comment by bang88** [comment]
PR welcome

**Comment by KingAmo** [comment]
请问一下你解决了这个问题了吗

**Comment by yezheny** [comment]
这样就可以解决了，在你的css中设置
 .am-tabs-default-bar-underline {
    border: none !important;
}

**Comment by ismdcf** [comment]
@NBXXF how where you able to set the underline color width (green color ) @BANG88 any help on this bit stuck

**Comment by ismdcf** [comment]
![image](https://github.com/ant-design/ant-design-mobile-rn/assets/16378404/fd2e2738-fdea-49bd-8ff5-f46510299c70)
I want to achieve something like the above where should I start
