### ISSUE TITLE
组件样式重写问题

### ISSUE THREAD

**Issue by jihfgz** [ant-design/ant-design-mobile-rn#279]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xv45zqzkw4)

### Steps to reproduce
自定义组件样式时，局部组件样式不能 deepmerge 。
假如需要调整边框颜色，只需要在styles的局部组件样式中增加一行样式，现在需要完整的输入整个局部组件样式。同时不像2.x版本那样把样式import进来手动合并

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.0.6 |
| React | react 16.4 |
| System |  /*react-native 0.57.8*/  失误 问题版本为  react-native 0.55.4 |
| Browser | - |
------------------------------------------------------------------
     补充： react-native版本引起  ，新版本0.57.8没问题
------------------------------------------------------------------
StyleSheet.create后，对象变成了id，deepmerge 就不起作用了

另外InputItem组件的style 属性同时作用于外层的View和里面的Input上应该也是个问题，看例子最后一个input

**Comment by jihfgz** [comment]
误删重现已回复，deepmerge没啥问题，主要是StyleSheet.create把对象变成了数字id，deepmerge不起作用了

**Comment by jihfgz** [comment]
其他样式不正常，默认的样式全丢失了。
比如左边距，比如input换行了

**Comment by bang88** [comment]
来个PR

**Comment by jihfgz** [comment]
这个怎么改，不是一个组件有这问题，所有组件都这样，结构上问题

**Comment by bang88** [comment]
在本地试了也有这个问题吗？我之前就在InputItem里面测试的。

**Comment by bang88** [comment]
来个PR更新下文档

**Comment by suwu150** [comment]
![image](https://user-images.githubusercontent.com/20339760/52189845-1da33d00-2876-11e9-9601-5cef9a736500.png)
我遇到这个问题,请问怎么解决?是版本的问题吗?
```
Environment:
  OS: macOS 10.14.2
  Node: 8.3.0
  Yarn: Not Found
  npm: 5.3.0
  Watchman: Not Found
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  react: ^16.7.0 => 16.7.0
  react-native: 0.51.0 => 0.51.0

```
