### ISSUE TITLE
antd-mobile-rn 的DataPicker在低分辨率手机的显示问题

### ISSUE THREAD

**Issue by forGao** [ant-design/ant-design-mobile-rn#28]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd-mobile-rn 版本：v2.2.0-beta.1
react-native 版本：0.46.4
操作系统及其版本：Android和IOS 低分辨率手机 

使用antd-moblie-rn的DataPicker，显示文字的大小能不能调整，默认文字太大，在分辨率低的手机上面会出现显示不全的情况，显示...

### What does the proposed API look like?
可以添加个设置显示文字大小的属性，或者支持自定义。

**Comment by bang88** [comment]
Track #199 datepicker或者其他组件 使用到的样式都可以自行覆盖了
