### ISSUE TITLE
Grid 宫格增加控制图片大小的属性

### ISSUE THREAD

**Issue by youngjuning** [ant-design/ant-design-mobile-rn#286]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Grid 宫格增加控制图片大小的属性

### What does the proposed API look like?
Grid 宫格增加控制图片大小的属性

**Comment by bang88** [comment]
请自行覆盖 `styles.icon` 样式以及调整`columnNum`

**Comment by HellsingMatt** [comment]
> 请自行覆盖 `styles.icon` 样式以及调整`columnNum`

在页面的 styles.icon 里添加 width 和 height 还是怎么个操作法，不需要在标签里引用么？我在 styles.icon 里定义了 width 和 height 没有作用。
