### ISSUE TITLE
What is the best way to set underline width of Tab component?

### ISSUE THREAD

**Issue by wangdicoder** [ant-design/ant-design-mobile-rn#292]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Current attribute **tabBarUnderlineStyle** is not easy to change the width of the underline. How can I achieve this feature? It seems only I overwrite the **DefaultTabBar** node?

### What does the proposed API look like?
underlineWidth: 70%

**Comment by bang88** [comment]
I am so sorry we don't have a better solution for this. If you want dig into it that will be awesome and PR are always welcome.

**Comment by WeldonLei** [comment]
你好，现在有什么解决方案吗？
