### ISSUE TITLE
修改主题样式后，相应的控件颜色没有变化

### ISSUE THREAD

**Issue by samuelltk** [ant-design/ant-design-mobile-rn#303]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/tree/master/rn-kitchen-sink](https://github.com/ant-design/ant-design-mobile-rn/tree/master/rn-kitchen-sink)

### Steps to reproduce
是 mobile 的版本，所以没有链接。我们研发人员修改了ant-design-mobile-rn中的主题色以后，有一些的控件的颜色并没有根据主题色而变化，但是这一现象在 web 端是可以正常变化的。

### What is expected?
是 mobile 的版本，所以没有链接。我们研发人员修改了ant-design-mobile-rn中的主题色以后，有一些的控件的颜色并没有根据主题色而变化，但是这一现象在 web 端是可以正常变化的。

### What is actually happening?
是 mobile 的版本，所以没有链接。我们研发人员修改了ant-design-mobile-rn中的主题色以后，有一些的控件的颜色并没有根据主题色而变化，但是这一现象在 web 端是可以正常变化的。

| Environment | Info |
|---|---|
| antd | 3.0.6 |
| React | React:16.7.0-alpha.2，React-native:0.57.7 |
| System | ios 12 |
| Browser | 无 |

---
是 mobile 的版本，所以没有链接。我们研发人员修改了ant-design-mobile-rn中的主题色以后，有一些的控件的颜色并没有根据主题色而变化，但是这一现象在 web 端是可以正常变化的。

**Comment by 7Charlotte** [comment]
如图，左边图中的“Finished”那里的对勾icon，没有变成绿色。应该右边图中一样变为绿色才对。

**Comment by samuelltk** [comment]
@ant-design-bot 您好，我们使用的是您官方的 DEMO 呀，地址是：https://github.com/ant-design/ant-design-mobile-rn/tree/master/rn-kitchen-sink   我们只是修改了这个文件（https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/style/themes/default.tsx）中的部分样式的颜色值，发现如上面的截图中的效果，有部分的控件的颜色并没有发生变化呢。我们修改后的文件default.tsx，我也上传了，见附件default.tsx.zip。
[default.tsx.zip](https://github.com/ant-design/ant-design-mobile-rn/files/2878093/default.tsx.zip)

**Comment by bang88** [comment]
不好意思 有重现的代码的话方便更快的解决问题。 我不能一个个 issue 一遍一遍的去问

**Comment by samuelltk** [comment]
@bang88 是的，我明白您的意思。但是我真的没有新增任何代码，仅仅只是修改了https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/style/themes/default.tsx   中的部分样式的颜色值，然后发现如上面的截图中的效果，有部分的控件的颜色并没有发生变化呢。

**Comment by bang88** [comment]
好的 待会我会看看的

**Comment by samuelltk** [comment]
好的，多谢您呐。

**Comment by bang88** [comment]
@samuelltk 你能不能直接使用Step的 styles 属性覆盖样式，这样就不需要修改什么。 默认就是三种颜色，从Theme里面也不是很好修改。

**Comment by bang88** [comment]
@samuelltk 这里有个例子你可以自定义颜色成类似你要的效果，如果绿色值不对自己修改一下即可。

```tsx
<WingBlank size="lg">
            <Steps
              size="small"
              current={1}
              direction="horizontal"
              styles={{
                head_blue_s: {
                  borderColor: 'green',
                  backgroundColor: 'green',
                },
                tail_blue: {
                  backgroundColor: 'green',
                },
                icon_s: {
                  color: 'white',
                },
              }}
            >
              {this.state.steps1.map((item: any, index: any) => (
                <Step
                  key={index}
                  title={
                    <View>
                      <Text>title:{item.title}</Text>
                    </View>
                  }
                  status={item.status}
                />
              ))}
            </Steps>
          </WingBlank>
```

根据尺寸不一样可以设置不同大小的Step的颜色


![image](https://user-images.githubusercontent.com/433259/52989145-1024b000-343d-11e9-9d10-6986fe70c067.png)
