### ISSUE TITLE
Module `babel-runtime/helpers/extends` does not exist in the Haste module map

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#309]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
npm install @ant-design/react-native --save
react-native link @ant-design/icons-react-native

### What is expected?
安装ant-design-mobile-rn成功

### What is actually happening?
实际报错信息：
Failed to load bundle(http://192.168.5.112:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `babel-runtime/helpers/extends` from `/xxx/node_modules/@ant-design/react-native/lib/accordion/index.js`: Module `babel-runtime/helpers/extends` does not exist in the Haste module map

| Environment | Info |
|---|---|
| antd | 3.1.0 |
| React | 0.57.8 |
| System | 10.14.1 (18B75) |
| Browser | 版本 71.0.3578.98（正式版本） （64 位） |

**Comment by bang88** [comment]
建议 `rm -rf node_modules` 后重新安装试试

**Comment by liberalisman** [comment]
同遇到了这个问题

**Comment by inkCrazy** [comment]
我现在临时解决方案是装了“antd-mobile-rn”来使用

**Comment by liberalisman** [comment]
> 我现在临时解决方案是装了“antd-mobile-rn”来使用

这几个库快把我弄蒙了，好乱啊

**Comment by bang88** [comment]
请完全删除 node_modules 后重新安装试一试，如果有问题请创建一个能重现的repo。

**Comment by un-hum** [comment]
> 同遇到了这个问题

请问你问题解决了吗，Mac os出现同样的问题

**Comment by bang88** [comment]
是不是用了 `babel-plugin-import`

**Comment by wSLecHayfIeNdock** [comment]
@bang88 也没有用

```
"dependencies": {
    "@ant-design/react-native": "^3.1.2",
    "react": "16.6.3",
    "react-native": "0.58.4"
  },
  "devDependencies": {
    "@types/react": "^16.8.3",
    "@types/react-native": "^0.57.36",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3",
    "typescript": "^3.3.3"
  },
```
node v10.11.0
npm 6.4.1
```

**Comment by bang88** [comment]
3.1.3 刚刚发布完成的 安装试一下


________________________________
发件人: O2 <notifications@github.com>
发送时间: 星期二, 二月 19, 2019 10:18
收件人: ant-design/ant-design-mobile-rn
抄送: 启邦; Mention
主题: Re: [ant-design/ant-design-mobile-rn] Module `babel-runtime/helpers/extends` does not exist in the Haste module map (#309)


@bang88<https://github.com/bang88> 也没有用

"dependencies": {

    "@ant-design/react-native": "^3.1.2",

    "react": "16.6.3",

    "react-native": "0.58.4"

  },

  "devDependencies": {

    "@types/react": "^16.8.3",

    "@types/react-native": "^0.57.36",

    "babel-core": "7.0.0-bridge.0",

    "babel-jest": "24.1.0",

    "jest": "24.1.0",

    "metro-react-native-babel-preset": "0.51.1",

    "react-test-renderer": "16.6.3",

    "typescript": "^3.3.3"

  },



node v10.11.0
npm 6.4.1

―

**Comment by wSLecHayfIeNdock** [comment]
更新后解决了！ 👍 @bang88

```
 yarn upgrade @ant-design/react-native@3.1.3
```

**Comment by un-hum** [comment]
同样搞定了 @bang88 👍

**Comment by bang88** [comment]
可以就行了 早上是因为另外一个问题 说加了 babel-plugin-import 才不行的。 这样我本地才重现出来，如果issue能更明确点的话 也方便解决。
