### ISSUE TITLE
js远程调试模式下，异常的卡顿

### ISSUE THREAD

**Issue by a49666** [ant-design/ant-design-mobile-rn#31]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
react-native 0.55 安卓真机 MI6 usb连接调试

### Reproduction link
纯净的新项目

### Steps to reproduce
引入Button组件，点击后松开，或调用Toast组件

### What is expected?
正常的反应，或是可接受的性能降低

### What is actually happening?
两个组件均出现超过3秒以上的异常卡顿，其他组件如react-navigation 或 react-native-elements 没有出现类似问题。  关闭 remote js debugging后反应正常

**Comment by bang88** [comment]
`react-native: 0.57.7` 我在 `Pixel 3 XL - 9`下面远程调试没有发现这个问题。 你那边在57 下面还会重现吗？
