### ISSUE TITLE
tabs在安卓上内容没有高度

### ISSUE THREAD

**Issue by wwvevy** [ant-design/ant-design-mobile-rn#322]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/issues/321](https://github.com/ant-design/ant-design-mobile-rn/issues/321)

### Steps to reproduce
ios正常,安卓无法显示内容

### What is expected?
安卓跟ios一样正常显示

### What is actually happening?
安卓content高度为空,无法显示

| Environment | Info |
|---|---|
| antd | 3.0.6 |
| React | 0.57 |
| System | mac mojave |
| Browser | Chrome |

**Comment by lihaoran0623** [comment]
> Hello @wwvevy. Please provide a re-producible demo: https://codesandbox.io/s/9ll8k8614p?module=%2Fsrc%2FApp.js or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.

https://codesandbox.io/s/qq9zjqly9j?fontsize=14

**Comment by xiaohuoni** [comment]
遇到同样的问题了

**Comment by MickeyMouse623** [comment]
动态计算高度解决
![image](https://user-images.githubusercontent.com/18524460/100081246-c4a8fc80-2e81-11eb-9a73-937dd1cdd11d.png)
