### ISSUE TITLE
ios 端的 drawer 组件，当返回的时候，会有短暂的停留在页面上

### ISSUE THREAD

**Issue by liuxiaofan** [ant-design/ant-design-mobile-rn#344]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://k0zxlwqrr7.codesandbox.io/)

### Steps to reproduce
要在iOS设备上，浏览器反应不出来这个问题。重现链接页面，Android 点击返回按钮没问题，iOS 点击返回按钮后，当前页面正常返回，但是drawer这个页面的内容会有短暂的停留

### What is expected?
iOS端 点击返回按钮 ，drawer 不显示，和Android端的页面一样

### What is actually happening?
iOS端 点击返回按钮，drawer 这个页面有短暂的停留

| Environment | Info |
|---|---|
| antd | 3.0.4 |
| React | 16.6.3 |
| System | MacOS |
| Browser | react native |

---
react native 0.57.8

**Comment by bang88** [comment]
Please track from https://github.com/react-native-community/react-native-drawer-layout/issues/50. We will update it after that PR landed
