### ISSUE TITLE
PickerView 的官方文档挂了    单击PickerView后报 create read property 'getPhotos' on undefined 错误

### ISSUE THREAD

**Issue by znnnnn** [ant-design/ant-design-mobile-rn#345]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/znnnnn/weixiao_fe/blob/master/app/page/mine/SetImfomation.tsx](https://github.com/znnnnn/weixiao_fe/blob/master/app/page/mine/SetImfomation.tsx)

### Steps to reproduce
1.  官方文档挂了
![image](https://user-images.githubusercontent.com/30922257/52870462-c49c9a00-30fc-11e9-8df1-636526d6e7b6.png)

2.  左键点击imagePick便会报错：`create read property 'getPhotos' on undefined。`
因为文档挂了，所以我即便使用了官方github仓库中的例子：[官方Demo传送门](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/image-picker/demo/basic.tsx)，还是会报错：create read property 'getPhotos' on undefined
![image](https://user-images.githubusercontent.com/30922257/52870478-cd8d6b80-30fc-11e9-8590-ada7b1b36579.png)

### What is expected?
点击能够正常选择图片

### What is actually happening?
error：create read property 'getPhotos' on undefined

| Environment | Info |
|---|---|
| antd | 3.1.1 |
| React | 16.6.3 |
| System | macos 10.13.6 |
| Browser | chrome  72.0.3626.109（正式版本） （64 位） |

**Comment by bang88** [comment]
有link过吗？

**Comment by znnnnn** [comment]
是：`react-native link @ant-design/icons-react-native`吗？这个link过了，在info.plist也有自动生成。
![image](https://user-images.githubusercontent.com/30922257/52896986-ad54bf80-3183-11e9-9ad1-fff1c2237642.png)

**Comment by bang88** [comment]
不是这个，要在iOS项目里面加入RCTCameraRoll https://github.com/ant-design/ant-design-mobile-rn/issues/90

**Comment by znnnnn** [comment]
非常感谢，已解决，抱歉由于电脑出了问题现在才测试完回复。
给楼下碰到相同问题的兄弟贴两个文档链接：
1. [CameraRoll](https://reactnative.cn/docs/linking-libraries-ios/)
2. [链接原生库](https://reactnative.cn/docs/linking-libraries-ios/)
