### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `babel-runtime/helpers/extends`

### ISSUE THREAD

**Issue by SuGod** [ant-design/ant-design-mobile-rn#346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/facebook/react-native/issues/4968](https://github.com/facebook/react-native/issues/4968)

### Steps to reproduce
使用` babel-plugin-import` 按需加载组件，使用任何组件都会出现错误
目前只是使用了 Icon 组件。
```
error: bundling failed: Error: Unable to resolve module `babel-runtime/helpers/extends` from `/Users/******/node_modules/@ant-design/react-native/lib/icon/index.js`: Module `babel-runtime/helpers/extends` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
```

### What is expected?
-

### What is actually happening?
```
error: bundling failed: Error: Unable to resolve module `babel-runtime/helpers/extends` from `/Users/******/node_modules/@ant-design/react-native/lib/icon/index.js`: Module `babel-runtime/helpers/extends` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
```

| Environment | Info |
|---|---|
| antd | 3.1.2 |
| React | "react": "16.6.3",     "react-native": "0.58.4", |
| System | macOS Mojave 10.14.3 |
| Browser | chrome 72 |

---
https://github.com/facebook/react-native/issues/4968 看了这个 issue 并没有解决问题。

**Comment by ZhaoRd** [comment]
同样遇到这个问题

**Comment by bang88** [comment]
`babel-plugin-import` 、React Native 什么版本

**Comment by bang88** [comment]
`3.1.3`

**Comment by bang88** [comment]
升级后可以用了吧？

**Comment by SuGod** [comment]
> 升级后可以用了吧？

可以，手动安装 `babel-runtime` 也是可以的。

**Comment by youngjuning** [comment]
如果我只用 icon 组件，就只能自己安装 babel-runtime
