### ISSUE TITLE
Grid 组件 Item 必须是 正方形，好像不是很合理。

### ISSUE THREAD

**Issue by SuGod** [ant-design/ant-design-mobile-rn#361]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
建议新增一个参数控制是否必须是正方形。

### What does the proposed API look like?
建议新增一个参数控制是否必须是正方形。

grid/index.js  line : 59

```javascript
        value: function getFlexItemStyle(columnNum) {
            return {
              // 不应该强制是正方形
                height: _reactNative.Dimensions.get('window').width / columnNum,
                borderRightWidth: this.props.hasLine ? _reactNative.StyleSheet.hairlineWidth : 0
            };
        }

```

**Comment by bang88** [comment]
特殊需求 请直接使用 `renderItem`

**Comment by SuGod** [comment]
> 特殊需求 请直接使用 `renderItem`

我是使用的renderItem，但是renderItem 是在 一个容器内，外层是个 正方形..
您可以看一下 代码。

**Comment by bang88** [comment]
你可以用 itemStyle 覆盖外面的样式
