### ISSUE TITLE
文档中提及到的Modal.alert()提供的外部关闭方法close()无效

### ISSUE THREAD

**Issue by jessietang** [ant-design/ant-design-mobile-rn#365]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/modal/](https://rn.mobile.ant.design/components/modal/)

### Steps to reproduce
先用Modal.alert()显示一个弹框，再调用Modal.alert().close()

### What is expected?
可以在外部提供一个关闭的方法

### What is actually happening?
文档中提到的关闭方法close()无效

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | 16.3.1 |
| System | android and ios |
| Browser | chrome |

**Comment by bang88** [comment]
```tsx

const key = Modal.alert()

Portal.remove(key)

```

**Comment by Wuguanghua** [comment]
@bang88 
```
const key = Modal.alert()
 // 这里拿到的 key 是 undefined ？？？
Portal.remove(key)
```

**Comment by Archer-Programmer** [comment]
同问，@Wuguanghua，你好，这个问题你解决了吗，我用的是Modal.prompt，官网文档上介绍可以用close关闭，我在prompt.js中发现prompt方法存在一个key但并没有返回，有其他方法解决吗，或者可以在不修改源码的前提下获取key值吗

**Comment by 1uokun** [comment]
> 同问，@Wuguanghua，你好，这个问题你解决了吗，我用的是Modal.prompt，官网文档上介绍可以用close关闭，我在prompt.js中发现prompt方法存在一个key但并没有返回，有其他方法解决吗，或者可以在不修改源码的前提下获取key值吗

https://github.com/ant-design/ant-design-mobile-rn/issues/524#issuecomment-504929129
