### ISSUE TITLE
Modal.prompt点击确认之后不自动关闭

### ISSUE THREAD

**Issue by luweiCN** [ant-design/ant-design-mobile-rn#367]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在使用Modal.prompt的时候，需要用户填写信息，当用户信息填写错误的时候，会Toast弹出提示消息，但是这时候不希望prompt关闭

### What does the proposed API look like?
prompt传入的action参数形式为({value, onClose})，然后可以手动去关闭prompt

**Comment by luweiCN** [comment]
@bang88 [示例](https://codesandbox.io/s/l4921wy4pq)我的callback传入的是checkName，并且会校验name的正确性，当name为空时，toast给出提示，但是这时候不希望promopt关闭。即使是name不为空时，比如这时候需要调一个接口，也希望接口调用成功才关闭prompt。所以希望prompt的关闭和显示是手动显示的。比如callback可以设计成callback(value, close)，然后在处理完业务之后自己调用close去关闭prompt

**Comment by bang88** [comment]
@luweiCN  callback 可以返回Promise https://codesandbox.io/s/yjzlzprn31

**Comment by luweiCN** [comment]
谢谢！可以了

**Comment by luweiCN** [comment]
@bang88 reject Promise确实可以不关闭prompt，但是我在实际使用中会有一个warning
![image](https://user-images.githubusercontent.com/25150291/53619757-74a8f180-3c2b-11e9-80bb-c124e70daa82.png)
我看源码里这部分确实没有处理reject的部分[源码](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/modal/PromptContainer.tsx#L109-L111 )这里并没有catch，不过这只是一个warning，没有影响代码运行

**Comment by bang88** [comment]
自行处理 Promise
