### ISSUE TITLE
ImagePicker multiple 属性不起作用

### ISSUE THREAD

**Issue by youngjuning** [ant-design/ant-design-mobile-rn#37]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
react-native 0.55.4

### Reproduction link
[https://github.com/youngjuning/myReactNativeApp/blob/master/views/AntDMobileRN/ImagePicker.js#L46](https://github.com/youngjuning/myReactNativeApp/blob/master/views/AntDMobileRN/ImagePicker.js#L46)

### Steps to reproduce
```js
<ImagePicker
   multiple
   files={this.state.files2}
   onChange={this.handleFile2Change}
/>
```

### What is expected?
ImagePicker multiple 属性不起作用

### What is actually happening?
ImagePicker multiple 属性不起作用

---
ImagePicker multiple 属性不起作用

**Comment by bang88** [comment]
不支持的属性。
