### ISSUE TITLE
SearchBar的Icon图标不适配

### ISSUE THREAD

**Issue by M45ter** [ant-design/ant-design-mobile-rn#374]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com没有连接，有现象截图](http://www.baidu.com没有连接，有现象截图)

### Steps to reproduce
                <SearchBar
                    value={this.state.key}
                    placeholder="搜索"
                    onSubmit={this.serchSubmit}
                    onCancel={this.clear}
                    onChange={this.onChange}
                    returnKeyType='search'
                    showCancelButton
                />

### What is expected?
正常显示

### What is actually happening?
左侧搜索图标太大，显示不正常

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | 0.57.4 |
| System | android |
| Browser | 5.1 |

---
有截图
![qq 20190301131128](https://user-images.githubusercontent.com/4351955/53618174-25f85900-3c25-11e9-9f05-e53487ed817a.jpg)
从源码看是这个Icon默认的size是md太大了，从style看是想设置为xxs，或者开放属性给用户可以自己设置一些SearchBar内部的属性
React.createElement(Icon, { name: 'search', style: _styles.search }),

**Comment by bang88** [comment]
现在都可以通过 styles 覆盖所有组件的样式。
