### ISSUE TITLE
DatePicker自定义组件的时候如何绑定时间弹出时间选择器

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#379]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
        let CustomChildren = ({ extra, onClick, children }) => (
            <View style={styles.xxx}>
                <TouchableOpacity activeOpacity={0.32} onPress={onClick}>
                    <View style={styles.yearMonthSelectView}>
                        <Text style={[styles.yearMonthText]}>{'2019-01'}</Text>
                        <Image style={styles.downArrowImage} source={require('../../res/img/down_arrow.png')} resizeMode={'stretch'}/>
                    </View>
                </TouchableOpacity>
            </View>
        );
<DatePicker
                    value={this.state.selectedTime}
                    onOk={this.startTimeConfirm}
                    onDismiss={this.startTimeCancel}
                    mode="date"
                    minDate={new Date(2018, 0, 1)}
                    maxDate={new Date(2050, 12, 31)}
                    format="YYYY-MM-DD"
                    title="Select Time"
                    extra="click to choose"
                    onChange={value => this.setState({ selectedTime: value })}
                >
                    <CustomChildren>With customized children</CustomChildren>
                </DatePicker>
点击onPress如何出发onClick事件，弹出时间轮盘的？

### What does the proposed API look like?
https://mobile.ant.design/components/date-picker参考这个demo，还是没有搞懂，哪里绑定onClick

**Comment by Wuguanghua** [comment]
从props中解构出的是`onPress` 而不是`onClick`，RN中只有` onPress`，官方文档应该没修正。

```
 <TouchableOpacity activeOpacity={0.32} onPress={onPress}>
                <View style={styles.yearMonthSelectView}>
                    <Text style={[styles.yearMonthText]}>{'2019-01'}</Text>
                    <Image style={styles.downArrowImage} source={require('../../res/img/down_arrow.png')} resizeMode={'stretch'}/>
                </View>
            </TouchableOpacity>
```

@inkCrazy

**Comment by inkCrazy** [comment]
好的，谢谢

**Comment by bang88** [comment]
看的是RN的文档吗？

**Comment by inkCrazy** [comment]
我是这样看的
![4753cc32-be1d-47d5-baff-c5d22f045ab9](https://user-images.githubusercontent.com/12253453/54002837-ebde0880-418a-11e9-947a-e3c87780ffff.png)
这个链接：
![image](https://user-images.githubusercontent.com/12253453/54002882-1b8d1080-418b-11e9-8585-0456ba36013d.png)

**Comment by inkCrazy** [comment]
https://mobile.ant.design/components/date-picker

**Comment by bang88** [comment]
链接错了 来个PR 修复下？

**Comment by wSLecHayfIeNdock** [comment]
@bang88 [Picker demo](https://rn.mobile.ant.design/components/picker/#components-picker-demo-basic) 出错

![image](https://user-images.githubusercontent.com/16831715/54677614-358d0280-4b3e-11e9-96d1-4a3ed9ae2d1c.png)

**Comment by bang88** [comment]
改错地方了。 你刷新看看。

**Comment by Luffyying** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> ```
>     let CustomChildren = ({ extra, onClick, children }) => (
>         <View style={styles.xxx}>
>             <TouchableOpacity activeOpacity={0.32} onPress={onClick}>
>                 <View style={styles.yearMonthSelectView}>
>                     <Text style={[styles.yearMonthText]}>{'2019-01'}</Text>
>                     <Image style={styles.downArrowImage} source={require('../../res/img/down_arrow.png')} resizeMode={'stretch'}/>
>                 </View>
>             </TouchableOpacity>
>         </View>
>     );
> ```
> 
> <DatePicker
> value={this.state.selectedTime}
> onOk={this.startTimeConfirm}
> onDismiss={this.startTimeCancel}
> mode="date"
> minDate={new Date(2018, 0, 1)}
> maxDate={new Date(2050, 12, 31)}
> format="YYYY-MM-DD"
> title="Select Time"
> extra="click to choose"
> onChange={value => this.setState({ selectedTime: value })}
> >
> With customized children
> 
> 点击onPress如何出发onClick事件，弹出时间轮盘的？
> 
> ### What does the proposed API look like?
> [https://mobile.ant.design/components/date-picker参考这个demo，还是没有搞懂，哪里绑定onClick](https://mobile.ant.design/components/date-picker%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AAdemo%EF%BC%8C%E8%BF%98%E6%98%AF%E6%B2%A1%E6%9C%89%E6%90%9E%E6%87%82%EF%BC%8C%E5%93%AA%E9%87%8C%E7%BB%91%E5%AE%9AonClick)

请问楼主这个问题解决了吗？
