### ISSUE TITLE
Tabs Swipeable={false} not working on android

### ISSUE THREAD

**Issue by batical** [ant-design/ant-design-mobile-rn#380]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8l43mj85j0?fontsize=14)

### Steps to reproduce
Launch on android device, try to swipe between tabs with  touch

### What is expected?
No swipe between tabs

### What is actually happening?
Changing from tabs to tabs

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | 0.57.8 |
| System | Android |
| Browser | Native app |

---
Add swipe action on list item. Cannot swipe the item

**Comment by bang88** [comment]
Does this happen in real device ?

**Comment by M45ter** [comment]
usePaged={false} works on android
@batical

**Comment by batical** [comment]
@ban88 yes, I discover this issue when testing on real device

@M45ter  thanks, usePaged={false} is working on simulator (have to try later on real device 

thanks guy for your help

**Comment by mynameisjoe666** [comment]
@BANG88 Thank you. You've really helped me out!
