### ISSUE TITLE
SwipeAction使用遇到的问题

### ISSUE THREAD

**Issue by haoxiaoxin** [ant-design/ant-design-mobile-rn#39]
FlatList 的renderItem中使用SwipeAction，打开一行右侧，再打开另一行时，之前打开的没有关闭，是怎么回事
![image](https://user-images.githubusercontent.com/25924575/41887296-9cd3fe0a-7932-11e8-8b71-5ee9d71f0ad5.png)
用法：
![image](https://user-images.githubusercontent.com/25924575/41887346-d2a5f1e6-7932-11e8-83e8-c56c98210a3e.png)

**Comment by meiqi1992** [comment]
我也遇到了 解决了吗？

**Comment by bang88** [comment]
暂时不支持 自动关闭之前的 请关注 https://github.com/dancormier/react-native-swipeout/issues/296

**Comment by StoneYuan** [comment]
@haoxiaoxin 请问，你这个问题解决了吗
