### ISSUE TITLE
icons-react-native 不能link成功

### ISSUE THREAD

**Issue by 2534290808** [ant-design/ant-design-mobile-rn#392]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/react-native没有重现代码](https://github.com/ant-design/ant-design-mobile-rn/react-native没有重现代码)

### Steps to reproduce
react-native link react-native link @ant-design/icons-react-native，同时好多图标出不来，比如List.Item的一些图标

### What is expected?
希望能够连接成功，同时组件的一些图标能够正确的显示出来

### What is actually happening?
图标没有显示出来，例如List.item的arrow属性设置为up是没有正确的图标显示出来

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | 16.3.1 |
| System | android 6.0 |
| Browser | 暂无 |

**Comment by bang88** [comment]
link 成功后，要重新 run一次

**Comment by 2534290808** [comment]
我认为这就是bug啊

**Comment by luomingsong** [comment]
请问一下怎么link
react-native link @ant-design/icons-react-native这个玩意儿
