### ISSUE TITLE
Card组件中的HeaderContent和Header在使用自定义组件时无法定制style

### ISSUE THREAD

**Issue by christtrc** [ant-design/ant-design-mobile-rn#395]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/card/CardHeader.tsx](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/card/CardHeader.tsx)

### Steps to reproduce
可以直接看代码，补充说明中的extra部分，style={{ flex: 1 }}

### What is expected?
Card.Header中title和extra属性使用自定义组件时，仍能够定制style属性，如flex

### What is actually happening?
因为title和extra的属性代码固化为{flex:1}， 无法定制style

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | 0.57 |
| System | Android、iOS |
| Browser | 72.0.3626.121 |

---
```
const extraDom =
 extra === undefined ? null : React.isValidElement(extra) ? (
 <View style={{ flex: 1 }}>{extra}</View>   <-------------------- 这里
 ) : (
   <Text style={[s.headerExtra]}>{extra}</Text>
 );
```

**Comment by bang88** [comment]
不过你可以在extra 里面自定义样式吧？ 这个外层的样式保证 extra显示正确。

如果确实有需要可以来个PR 在styles里面加个extra的容器样式。
