### ISSUE TITLE
Type error when using Tabs (react-native: 0.59.x)

### ISSUE THREAD

**Issue by hieupaul** [ant-design/ant-design-mobile-rn#403]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/BbrWRO](https://codepen.io/anon/pen/BbrWRO)

### Steps to reproduce
Import Tabs from @ant-design and use

### What is expected?
Tabs works well

### What is actually happening?
Occur error: 
TypeError: undefined is not an object (evaluating 'this._scrollResponder')

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | 16.8.3 / 0.59.0 |
| System | MacOS Mojave 10.14.2 |
| Browser | iOS |

![Simulator Screen Shot - iPhone X - 2019-03-15 at 17 13 54](https://user-images.githubusercontent.com/19374802/54424601-d433f080-4745-11e9-8f91-8a5946b8227a.png)

**Comment by bang88** [comment]
I think this is a `react-native` bug.

**Comment by marlon-wiprud** [comment]
Having the same issue. Has anybody been able to resolve this?

**Comment by bang88** [comment]
The error came from React-Native I dont konw what can i do here. If you guys want a work version please downgrade your react-native to 0.58.4 and try again.

**Comment by bang88** [comment]
I have searched the changelog of react-native but get nothing. PR are welcome if you found a solution for this bug.

**Comment by johnnylc** [comment]
same issue with version 3.1.4
React: 16.8.3
React-native: 0.59.1

**Comment by bang88** [comment]
You need use react-native 0.58.4 ATM.  This is a bug of react-native about `Animated.ScrollView `

**Comment by hieupaul** [comment]
Thank you @bang88

**Comment by bang88** [comment]
Sorry for that. If I change the scrollView to getNode(). it works on normal swipe (left & right). but the scrollTo method still not work. 😢

**Comment by bang88** [comment]
@hieupaul @marlon-wiprud @johnnylc Fixed in 3.1.5 by @bestv2.  What a bug...

**Comment by hieupaul** [comment]
Awesome @bang88 Thank you so much.
