### ISSUE TITLE
希望可更改Picker使用List以后extra的字体样式

### ISSUE THREAD

**Issue by MingRock** [ant-design/ant-design-mobile-rn#404]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
方便自定义组件

### What does the proposed API look like?
             <Picker  extraStyle={{fontSize:12}}>
                        <List.Item arrow="horizontal">
                            ...
                        </List.Item>
             </Picker>

**Comment by bang88** [comment]
你看看Picker的样式 现在应该有可以从styles的样式吧。
