### ISSUE TITLE
iPhone扫描官网组件文档中的二维码Demo后，页面会无限刷新

### ISSUE THREAD

**Issue by TianEnPang** [ant-design/ant-design-mobile-rn#413]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/kitchen-sink/?lang=zh-CN](https://rn.mobile.ant.design/kitchen-sink/?lang=zh-CN)

### Steps to reproduce
iPhone扫描官网组件文档中任意一个二维码Demo，网页都会无限刷新

### What is expected?
扫描官网组件文档中任意一个二维码Demo后可以正常预览

### What is actually happening?
iPhone扫描官网组件文档中任意一个二维码Demo，网页都会无限刷新

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | 0.59 |
| System | IOS |
| Browser | Chrome，Safari，WeChat |

**Comment by TianEnPang** [comment]
iPhone扫描官网组件文档中任意一个二维码Demo，网页都会无限刷新

**Comment by bang88** [comment]
后面会移除这个扫码的。
