### ISSUE TITLE
List Item 怎么去掉他的下划线

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design-mobile-rn#414]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望能随意设置

### What does the proposed API look like?
通过CSS去除默认的下划线

**Comment by JackClown** [comment]
用styles属性去覆盖特定的样式应该可以解决

**Comment by BelinChung** [comment]
@JackClown borderBottomWidth 在 List.Item 的内层 View 里面，无法直接通过  List.Item 的 styles 去控制 borderBottom 的属性。

**Comment by JackClown** [comment]
@BelinChung 
可以的，这个[样式](https://github.com/ant-design/ant-design-mobile-rn/blob/95a8733e8cb9b804754719102dd81945b046fa85/components/list/style/index.tsx#L64)就有对应的borderBottom的color,width，只要用styles去覆盖这个样式就可以
![image](https://user-images.githubusercontent.com/9284369/55082306-68a23980-50dc-11e9-9866-62cd2e3e38f9.png)

**Comment by 442376176** [comment]
@JackClown 现在这样也覆盖不掉了...

**Comment by yangshuyu** [comment]
@JackClown 我这里是不用加Line标记
![image](https://github.com/ant-design/ant-design-mobile-rn/assets/18401593/4c49acb1-8af9-43b4-b7a4-bbe36de83da0)
