### ISSUE TITLE
希望能出一个最新的Provider入口文件demo （react-navigation>3.5.0

### ISSUE THREAD

**Issue by htank-wang** [ant-design/ant-design-mobile-rn#415]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
无

### What is expected?
希望能出一个最新的Provider入口文件demo （react-navigation>3.5.0）

### What is actually happening?
文档和demo里的Provider配置示例太旧，已不能使用。

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | react-native  |
| System | ios |
| Browser | react-native |

---
希望能出一个新一些的。

**Comment by bang88** [comment]
这个跟 react-navigation 没什么关系。只是一个provider 你放到app入口出就好了。

**Comment by htank-wang** [comment]
我还是贴一下代码，希望能帮到其他人.

![1553567726549](https://user-images.githubusercontent.com/17918845/54967633-e538f900-4fb2-11e9-8936-b3b51a352836.jpg)

**Comment by inkCrazy** [comment]
时间久了，记不清了，我以为Provider没用，删除了之后用了anti就报错了，感谢提醒。
