### ISSUE TITLE
stepper 组件  不能调整他的宽度！ Rn版本

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design-mobile-rn#417]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2v2pm1o7yp)

### Steps to reproduce
就是组件设置了styles 和style 没有用  我希望能根据自身需要设置他的宽度和高度 

### What is expected?
希望能根据自身需要设置宽度和高度  目前设置的宽度在APP上面太宽了 太丑了

### What is actually happening?
实际结果是没有反应  我用了Flex  依然没有效果

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | 16.5.0 |
| System | windows |
| Browser | rn |

**Comment by yehoan** [comment]
希望能给个解决的办法  谢谢

**Comment by bang88** [comment]
在外层嵌套一个view设置宽度。

**Comment by donybin** [comment]
Steps的样式文件中，tail_default_xx增加flex:1即可。RN亲测有效
