### ISSUE TITLE
ImagePicker选择照片页面英语怎么修改为中文呢？

### ISSUE THREAD

**Issue by ZhangWei2008** [ant-design/ant-design-mobile-rn#42]
![qq 20180627172216](https://user-images.githubusercontent.com/19800003/41965330-e74f3574-7a2e-11e8-965a-bad29571f397.jpg)

**Comment by warmhug** [comment]
跟组件没关系吧，Android 系统是英文？

**Comment by kilidon** [comment]
难道没有其他人 是显示的英文？
