### ISSUE TITLE
在Drawer中使用tab是会出现样式错误

### ISSUE THREAD

**Issue by Tzng** [ant-design/ant-design-mobile-rn#423]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/w75v0l8lz8)

### Steps to reproduce
在模拟器或者真机上运行的时候，左右滑动，会有样式错误
![image](https://user-images.githubusercontent.com/26215888/55094113-b4f77480-50f0-11e9-952f-3a8150bea4d8.png)

### What is expected?
能正常滑动

### What is actually happening?
右侧有突出

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | 16.6.3/0.58.6 |
| System | win10 |
| Browser | 72.0 |

**Comment by Tzng** [comment]
已经将代码放上去了，只是Web端是显示正常的

**Comment by bang88** [comment]
@Tzng 这边（真机、线上）也在使用这个组件，没有发现你说的问题。
