### ISSUE TITLE
toast无法实现全屏覆盖

### ISSUE THREAD

**Issue by iOSHw** [ant-design/ant-design-mobile-rn#434]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
想使用Toast占位，不让触摸到别的区域，但是toast没有覆盖到导航上去，无法实现全屏

### What is expected?
实现toast全屏

### What is actually happening?
没有全屏

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | 0.58 |
| System | iOS |
| Browser | safari |

**Comment by iOSHw** [comment]
和  "react-navigation": "^3.3.2",一起使用

**Comment by JackClown** [comment]
ToastContainer本身就距离容器的顶部有一定高度，这从源码就可以看出呀[code](https://github.com/ant-design/ant-design-mobile-rn/blob/95a8733e8cb9b804754719102dd81945b046fa85/components/toast/style/index.tsx#L19)，但是这个高度有一定问题: 将Provider放在最外层时候，这个高度是不兼容iphoneX的，需要做额外的处理

**Comment by bang88** [comment]
@iOSHw 还有这需求吗？
简单点可以直接把top设置为0，或者使用SafeAreaView作为内容的外部容器，有需求就来个pr。

**Comment by youngjuning** [comment]
有需求啊，比如右上角的保存按钮，如果不挡住，就要手动控制按钮 disable
