### ISSUE TITLE
Tabs配置初始选择项无效，下划线会自动闪烁到第一个

### ISSUE THREAD

**Issue by oneroundseven** [ant-design/ant-design-mobile-rn#44]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
windows7  RN: 0.55.4

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
<Tabs tabs={this.state.tabs}
                          page={2}
                          initialPage={2}
                          renderTabBar={props=> <Tabs.DefaultTabBar {...props} page={3} />}
                          onChange={(tab, index)=> this._change(tab, index)} />

### What is expected?
选中第三个

### What is actually happening?
文字选中了第三个  下划线闪动到第一个

**Comment by bang88** [comment]
#50
