### ISSUE TITLE
请问入口处的Provider有用于react-redux时 如何处理

### ISSUE THREAD

**Issue by leehave** [ant-design/ant-design-mobile-rn#453]
![image](https://user-images.githubusercontent.com/16717693/56176081-79cfcd80-602c-11e9-9477-72e22bd16ef1.png)
![image](https://user-images.githubusercontent.com/16717693/56176084-7b999100-602c-11e9-909e-5d1d4f67644e.png)

**Comment by M45ter** [comment]
@leehave import时不是可以写Provider as AntProvider 这样的别名写法？
