### ISSUE TITLE
自定义icon不可用

### ISSUE THREAD

**Issue by ccgitgit** [ant-design/ant-design-mobile-rn#46]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
react-native 0.55.4       antd-mobile-rn 2.2.0

### Reproduction link
[http://rn.mobile.ant.design/components/icon-cn/](http://rn.mobile.ant.design/components/icon-cn/)

### Steps to reproduce
按照[官方文档](http://rn.mobile.ant.design/components/icon-cn/) 自定义icon使用<Icon type={'\ue6F1'} size={55} /> ， 此unicode来自 [antd icon](https://ant.design/components/icon-cn/#header)中的 global图标

### What is expected?
icon应该有效

### What is actually happening?
icon无效

---
大部分 [antd icon](https://ant.design/components/icon-cn/#header)中的unicode都可以，貌似靠后的icon都有问题。同时建议提供一个完整的自定义icon方式说明。

**Comment by bang88** [comment]
请按照 icon 文档下载最新版字体link到项目然后再试试。 3.0 版本将使用 `ant-design-icon`
