### ISSUE TITLE
theme 定制 在3.1.5无效

### ISSUE THREAD

**Issue by xuekew** [ant-design/ant-design-mobile-rn#465]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui](https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui)

### Steps to reproduce
https://github.com/ant-design/antd-mobile-samples/tree/master/rn-custom-ui

### What is expected?
正常定制主题

### What is actually happening?
没有

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | 16.8.3/0.59.4 |
| System | android |
| Browser | android |

**Comment by bang88** [comment]
这个定制是针对以前的版本，3.0重构后这一套不适用现在的 Theme了。

**Comment by liyanfei1004774105** [comment]
3.0重构后 用哪一套呢?
