### ISSUE TITLE
如何引用当前主题的theme参数

### ISSUE THREAD

**Issue by M45ter** [ant-design/ant-design-mobile-rn#472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
文档里没有找到如何获取当前theme的参数，比如我有一些自定义组件的样式（margin，颜色，字体等）想和ant design的风格一致，该如何引用当前theme里的参数 

### What does the proposed API look like?
比如theme.font_size_caption_sm

**Comment by bang88** [comment]
可以单独引用 `@ant-design/react-native/components/style` 里面的 `WithTheme` 具体使用方式可以找一个组件看看。

**Comment by M45ter** [comment]
@bang88 可能没写好，我是指我自定义的组件里想用到当前antd的theme里的某些值，你说的方法我看了下源码，确实好像可以，官方文档没有提，但是用起来好像不是很方便，比如，我一个style和组件无关的，可以在不同组件中引用，这时这个style里想设置antd theme的值好像就不方便了

**Comment by bang88** [comment]
@M45ter 我理解的是你想使用 `ant`里面的`theme` ，而不是设置里面的值，如果你要设置或者覆盖一些设置你需要使用 `Provider` 来覆盖部分`theme` 变量。


如果是想使用 ant 里面的theme 然后在自己的项目里面开发通用组件的话就可以用`WithTheme`而不是 `useTheme`

**Comment by M45ter** [comment]
@bang88 你说的使用场景是正确的，不过我想到一种场景，比如我app的一个page，里面用了一些antd组件和一些其他非ant的element，为了风格统一，我可能需要在这里定义一些style来修改本页的一些元素的style，使得风格和antd的组件统一，比如一条分割线的颜色，一个非ant element里的字体风格，这些值我想从antd的theme里取得，这种场景用`WithTheme`来做个人感觉有点奇怪

**Comment by bang88** [comment]
@M45ter 现在确实没有提供一个直接获取 `theme`的方式，都是通过`WithTheme`去获取，如果你觉得在每个组件里面都是用`WithTheme` 不舒服，可以在`entry`的地方使用一个`WithTheme` 然后把`theme`在通过 `screenProps`（如果你是用 `react-navigation`的话） 或者其他方式传递到自组件里面使用。

**Comment by M45ter** [comment]
@bang88 好的，感谢回复

**Comment by youngjuning** [comment]
WithTheme 如何取得呢，有代码示例吗？我想通过mobx-react 的provider传入，然后inject取出

**Comment by liyanfei1004774105** [comment]
WithTheme 到底怎么用的，求大神指点

**Comment by zhaochengxiang** [comment]
将default.js中的默认样式 全部拷贝到我们自定义的样式文件中来,  这样我们引用这个样式文件, 就可以调用了.
