### ISSUE TITLE
SegmentedControl 自定义样式后显示问题

### ISSUE THREAD

**Issue by M45ter** [ant-design/ant-design-mobile-rn#474]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/0416vyny8n)

### Steps to reproduce
SegmentedControl 设置高度后，圆角部分异常，内外圆角有空隙，自定义segment的borderWidth后，上下边框也有异常

### What is expected?
高度、边框with等可自定义

### What is actually happening?
自定义后显示异常
![QQ截图20190430132210](https://user-images.githubusercontent.com/4351955/56942200-ecbc6680-6b4b-11e9-9b61-287c14210c37.png)
截图是手机上的

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | 0.59.4 |
| System | android |
| Browser | 8.1 |

---
代码连接里有，web版的自定义稍有不同，好像不会合并默认antd的style

**Comment by bang88** [comment]
Android ？

**Comment by M45ter** [comment]
> Android ？

是的，ios没有测试，不过看源码ios是用的ios自带组件

**Comment by bang88** [comment]
试试

```jsx
styles={{
            segment: {
              borderWidth: 1,
              borderColor: "#108ee9",
              borderRadius: 5
            },
            itemLeftRadius: {
              borderTopLeftRadius: 0,
              borderBottomLeftRadius: 0,
            },
            itemRightRadius: {
              borderTopRightRadius: 0,
              borderBottomRightRadius: 0,
            },
          }}
        />
```
