### ISSUE TITLE
Difference ant-design-mobile ant-design-mobile-rn

### ISSUE THREAD

**Issue by apfz** [ant-design/ant-design-mobile-rn#488]
I have been scanning the internet but I am unable to find a difference between ant-design-mobile and ant-design-mobile-rn. 

As far as I can see, both I can use within my react native project. Can anyone tell me the difference between the two projects?

**Comment by devspacenine** [comment]
Can we get an answer to this question. I am also having a hard time seeing any major differences. There are a lot of minor differences between the components of each library, though. Are these two libraries intended to be maintained together or are there two totally separate groups of contributors?
