### ISSUE TITLE
add afterClose for Modal

### ISSUE THREAD

**Issue by jhmobile** [ant-design/ant-design-mobile-rn#490]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
developer can do something when the close animation finish

### What does the proposed API look like?
like modal in web，see https://mobile.ant.design/components/modal-cn/#API

**Comment by bang88** [comment]
Have a `onClose` props already.
