### ISSUE TITLE
Modal组件的朦层如何设置与顶部导航栏的间距

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#491]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
modal默认全屏显示

### What does the proposed API look like?
新增一个参数：topMargin单独设置modal朦层距离顶部的间距

预期效果：

![7BD24785C59579F3708C02B209F718AD](https://user-images.githubusercontent.com/12253453/57352601-75648380-7198-11e9-9c1c-e44cabd324aa.png)
实际效果：
![0714FF81C686D4CD58506C302F32EE26](https://user-images.githubusercontent.com/12253453/57352606-7b5a6480-7198-11e9-900c-90f0e8429d2c.png)

**Comment by bang88** [comment]
你先看一下能不能通过在 styles属性 里面的 container 设置top值。 你是想要一个距离顶部的距离？

**Comment by inkCrazy** [comment]
不管是在Modal下面的style还是里面container组件的style设置style={{top: 100}}，我发现顶部的留白一直都是存在的，设置了之后只是高度发生变化，并没有露出下层视图的内容

**Comment by bang88** [comment]
@inkCrazy 有空继续看看是哪个样式吗？

**Comment by hanwenbo** [comment]
@bang88 在Modal里push到另外一个界面，Modal会挡住新push的界面怎么处理呢？

**Comment by hanwenbo** [comment]
@bang88 我不知道怎么解决- - 请求帮助 我弄好几个小时了

**Comment by bang88** [comment]
> @bang88 在Modal里push到另外一个界面，Modal会挡住新push的界面怎么处理呢？

code ?

**Comment by inkCrazy** [comment]
> @inkCrazy 有空继续看看是哪个样式吗？

有具体的样式吗？不是要新增吗？
<Modal
          transparent={false}
          // closable={true}
          visible={this.state.visible1}
          animationType="fade"
          onClose={this.onClose1}>
          <View style={{marginTop: 50}}>//top只能调整内部视图在白色朦层顶部的间距
          </View>
        </Modal>

**Comment by inkCrazy** [comment]
> @bang88 我不知道怎么解决- - 请求帮助 我弄好几个小时了

我的解决方案是：跳转过去之前先让它隐藏，返回的时候在展示。

**Comment by bang88** [comment]
路由切换也应该隐藏Modal的吧。

**Comment by hanwenbo** [comment]
@bang88 您是指  我先隐藏Modal是吗？ 我Modal里是评论  如果关了  再回来 评论还需要重新加载 而且是多层级的  不好铺 O__O "…

**Comment by hanwenbo** [comment]
@inkCrazy 隐藏的话  再回来数据 再铺一遍吗？

**Comment by hanwenbo** [comment]
@inkCrazy 还有就是滚动的位置，以及第N页

**Comment by hanwenbo** [comment]
@inkCrazy 😆加我QQ一起探讨吧 这儿聊天老慢了  QQ 9476400

**Comment by bang88** [comment]
没有用Q好几年了，先说一下吧，这个属于业务相关的，如果新开的能够使用Modal的话最好使用Modal，因为使用路由的话返回之类的不好处理。使用多个Modal应该没有问题的。

**Comment by inkCrazy** [comment]
visible设置为false，因为路由堆栈里面上个页面还在，没有销毁，所以数据还在啊，跳转过去的页面pop返回的时候，再设置visible为true就好了。

**Comment by bang88** [comment]
嗯，或者你可以自定义一个评论的Modal，使用Portal去做

**Comment by hanwenbo** [comment]
@inkCrazy @bang88 我测试了下 数据销毁了  难道是我手法不对？

**Comment by hanwenbo** [comment]
@inkCrazy 你设置成visible设置为false，后内容还？我测试了下  false后 貌似是销毁了  我再侧测

**Comment by hanwenbo** [comment]
@inkCrazy @bang88 我又测试了  什么代码都不加  只要官方的组件 弄了个项目  同样，Modal要是隐藏，再显示都会重新渲染里面的所有子组件

**Comment by bang88** [comment]
是会啊。  😢  我的意思是你用两个Modal实现你的业务需求。用Portal自己实现

**Comment by hanwenbo** [comment]
@bang88 哈哈  哥  我要是知道怎么实现就好  您给简单给俺描述下吗，怎么用两个呢? 这个新的Modal要放在哪？Portal在您这个库里  我没找到 我在paper库里发现过

**Comment by bang88** [comment]
```jsx
import React from 'react';
import { Text, View } from 'react-native';
import { Button, Icon, Portal } from '@ant-design/react-native';
export default class PopoverExample extends React.Component {
    render() {
        let key;
        const contents = (<View style={{ backgroundColor: 'green', padding: 100 }}>
        <Button onPress={() => {
            Portal.remove(key);
        }} type="primary" style={{
            position: 'absolute',
            top: 100,
            right: 0,
        }}>
          <Icon name="close-circle"/>
        </Button>
        <View>
          <Text>自定义Portal</Text>
        </View>
      </View>);
        return (<View>
        <Button onPress={() => {
            key = Portal.add(contents);
        }}>
          Open Portal
        </Button>
      </View>);
    }
}
```

Copy 了一个例子

**Comment by hanwenbo** [comment]
@bang88 谢谢哥  你想喝什么  我给你点一杯   我去试试了

**Comment by hanwenbo** [comment]
@bang88 。。。你这个例子也太好了  好使  我懂liao 为什么你还私藏了一些   我在官网没找到 😆
