### ISSUE TITLE
Picker 选择器bug, 当在setInterval 中有 this.setState, Picker 无论怎么改都会还原

### ISSUE THREAD

**Issue by buffge** [ant-design/ant-design-mobile-rn#496]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/2x7vk1rxwp/)

### Steps to reproduce
1. 点击省市选择,选择安徽省 六安市 点击确定
2. 点击省市选择,选择 任意非 安徽省 六安市 地址. 此时还是会变为安徽省六安市

### What is expected?
无法选择其他选项,都是会变为第一次的选项

### What is actually happening?
无法选择其他选项,都是会变为第一次的选项

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | lastest |
| System | all |
| Browser | no brower, this is happen in app |

**Comment by bang88** [comment]
没看明白你要做什么。

**Comment by buffge** [comment]
@bang88  就是要切换城市啊,只要加了setInterval 中 添加任意 setState 就无法再切换城市了

**Comment by buffge** [comment]
![GIF](https://user-images.githubusercontent.com/24917906/57497571-c8f6de80-730a-11e9-822a-645937e3be59.gif)

**Comment by 1uokun** [comment]
每一次state更新都会重新渲染picker item，导致顺序又一次初始化。
详见源代码https://github.com/ant-design/ant-design-mobile-rn/blob/b684aceeaee5c629a9b06265906505e61e73a8b7/components/picker-view/PickerView.tsx#L78

如果你在打开picker时会有其他视图的更新，建议将<Picker>组件设置在一个自组件中，并将子组件设置为`PureCompoent`避免父组件更新时重新渲染了picker item

```
//PickerItem
class PickerItem extends React.PureComponent {
    render(){
        return (
            <Picker
                data={this.props.data}
                cols={this.props.cols}
                value={this.props.value}
                onChange={this.props.onChange}
            >
                <List.Item arrow="horizontal" onPress={this.props.onPress}>
                    省市选择
                </List.Item>
            </Picker>
        )
    }
}
```
替换之
```
<PickerItem
    data={data}
    cols={3}
    value={this.state.value}
    onChange={this.onChange}
/>
```
