### ISSUE TITLE
Typescript 无状态组件的 interface标注怎么写

### ISSUE THREAD

**Issue by 1123305308** [ant-design/ant-design-mobile-rn#497]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
最近rn集成typescript碰到一个问题，就是无状态组件该怎么表示，总不至于全部 any让 typescript 变成个摆设吧

### What does the proposed API look like?
为什么一个 return null 的 组件也要用 class 的形式进行标注。觉得某种程度上显得多余。

**Comment by bang88** [comment]
怎么用 typescript 写react的组件建议去看下文档

```tsx
interface Props {
  count: number;
}

const Count: React.FunctionComponent<Props> = (props) => {
  return <h1>{props.count}</h1>;
};
```
