### ISSUE TITLE
tabs 初始化initialPage 显示不正常

### ISSUE THREAD

**Issue by aqnaruto** [ant-design/ant-design-mobile-rn#50]
![image](https://user-images.githubusercontent.com/9067159/42267947-ecc1f3a6-7fac-11e8-8d47-02281ec5ce9a.png)
如图，初始化有问题。

**Comment by aqnaruto** [comment]
我初始化设置为1，显示的是0的内容和下划线。

**Comment by LovelyGirl4** [comment]
+1

**Comment by tiyunchen** [comment]
+1

**Comment by tiyunchen** [comment]
有人有解决方案吗？
