### ISSUE TITLE
最新版的 ant-design-mobile-rn （v3.1.8） 是否支持 android 4.x 和 ios 8.x

### ISSUE THREAD

**Issue by wang777777** [ant-design/ant-design-mobile-rn#504]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想问下，
1、最新版的 ant-design-mobile-rn（v3.1.8） 是否支持 android 4.x 和 ios 8.x，文档里没找到，也有可能是我眼拙，如果文档有的话，能否给出地址，谢谢，
2、另外 react-native 0.59.8 文档是说支持iOS 9.0 and Android 4.1，如果要支持 iso 8.0 需要做什么特殊的处理吗？我知道第二个问题不该在这提问，只是顺带一提，如果知道的话，望不吝赐教，感谢

### What does the proposed API look like?
无

**Comment by bang88** [comment]
ant 跟系统版本没啥关系，只要react-native  > 0.5x 应该都没问题

要怎样才能支持iOS8的话这个不清楚
