### ISSUE TITLE
Toast 

### ISSUE THREAD

**Issue by vivilauge** [ant-design/ant-design-mobile-rn#513]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/toast-p9948)

### Steps to reproduce
const key = Toast.loading('messsage')
Portal.remove(key)  

### What is expected?
const key = Toast.loading('messsage')
Portal.remove(key)  // 删除显示的toast

### What is actually happening?
const key = Toast.loading('messsage')
Portal.remove(key)  // 目前删除会提示， remove是undefined

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.3 |
| System | windows |
| Browser | 73.0.3683.86 |

**Comment by vivilauge** [comment]
已经解决了，

**Comment by 452MJ** [comment]
是因为哪里写错了？
