### ISSUE TITLE
Toast Android不显示图标

### ISSUE THREAD

**Issue by lihp2014** [ant-design/ant-design-mobile-rn#519]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/toast-cn/](https://rn.mobile.ant.design/components/toast-cn/)

### Steps to reproduce
package.json:

"dependencies": {
    "@ant-design/react-native": "^3.1.3",
    "babel-plugin-module-resolver": "^3.2.0",
    "install": "^0.12.2",
    "jcore-react-native": "^1.3.0",
    "jpush-react-native": "^2.4.0",
    "prop-types": "^15.6.2",
    "ramda": "^0.25.0",
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.3"
}

import {Toast } from '@ant-design/react-native';

Toast.success('test', 1)

### What is expected?
提示正常显示

### What is actually happening?
轻提示没有图标

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | "react-native": "0.57.3", |
| System | android |
| Browser | 无 |

![WechatIMG1](https://user-images.githubusercontent.com/6766825/58309548-20cb3480-7e37-11e9-979e-d203dc6b7718.jpeg)

**Comment by lihp2014** [comment]
升级之后正常了，抱歉

**Comment by Greendelwold** [comment]
还是不显示
