### ISSUE TITLE
DatePicker怎么初始化一个值？

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile-rn#52]
DatePicker怎么初始化一个值？
我在使用的时候发现，当我给了一个最小值的时候，不能够正常处理我给的最小值，当我上下滑动之后，才能够正常显示这个值。

举个例子：
我设置最小值为当前日期（2018-7-5），但是只显示年（2018）和月（1月），不能够正常显示，只有当我将年上下滑动，才会正常显示为（2018-7-5），请问有什么解决办法？

```
      <DatePicker
        maxDate={moment('2300-1-1', format).toDate()}
        minDate={moment('1970-1-1', format).toDate()}
        {...this.props}
        mode="date"
        format={format}
        title={label && label.length > 8 ? '选择日期' : label}
        value={value || new Date()}
        visible={this.state.visible}
        onChange={v => this._handleChange(v)}
        onOk={v => this._handleChange(v)}
        onDismiss={() => this.setState({ visible: false })}
      >
```

用上面的代码初始化之后，当我直接点击确定之后（不进行上下滑动操作），获取的值如下所示：
![datePicker值](https://github.com/suwu150/static-resource/blob/master/images/antDesignMobile/ant-design-rn-datepicker.png?raw=true)

**Comment by suwu150** [comment]
给默认值使用new Date(),如下面方法：
```
 value={this.state.value || new Date()}
```

**Comment by inkCrazy** [comment]
我想初始化一个时间，时间格式为YYYY-MM-DD HH:mm了，渲染的时候，直接报错了TypeError: TypeError: TypeError: date.getFullYear is not a function. (In 'date.getFullYear()', 'date.getFullYear' is undefined)，这里的时间格式具体支持什么样的？

**Comment by bang88** [comment]
Date 啊

________________________________

**Comment by inkCrazy** [comment]
服务端传过来的一个时间？不是new Date();

**Comment by bang88** [comment]
需要是一个有效的Date 对象，你把服务端返回来的格式处理一下
宝强 <notifications@github.com>于2019年2月20日 周三19:41写道：

**Comment by inkCrazy** [comment]
明白了，typeof发现是string格式，谢谢
