### ISSUE TITLE
SearchBar不能去掉输入框后的“取消”按钮，点击“取消”按钮后不能让输入框失去焦点。

### ISSUE THREAD

**Issue by tonlen** [ant-design/ant-design-mobile-rn#523]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
SearchBar不能去掉输入框后的“取消”按钮，点击“取消”按钮后不能让输入框失去焦点。

### What does the proposed API look like?
可以去掉“取消”按钮，或者 点击“取消”按钮后可以让输入框失去焦点。

**Comment by bang88** [comment]
之前的取消功能是清空，不知道改成清空并失去焦点会不会影响已有的项目。

**Comment by youngjuning** [comment]
现在清空要手动调 clear？

**Comment by youngjuning** [comment]
还有就是自动获取焦点怎么实现，我调用了 `searchBar.inputRef.focus()` 不起作用

**Comment by youngjuning** [comment]
使用了 `autoFocus` 属性实现了自动获取焦点

**Comment by bang88** [comment]
取消的时候 可以通过inputRef 手动清理当前值。

**Comment by zhazihong** [comment]
ref={ref => this.searchBarRef = ref}
onCancel={() => {
 this.setState({ searchName: '' });
 // 失去焦点
this.searchBarRef && this.searchBarRef.inputRef && this.searchBarRef.inputRef.blur()
}}
