### ISSUE TITLE
Modal 弹出时，按下 android 的 back 键，modal 没有关闭/When Modal pops up, press android's back key, modal is not closed

### ISSUE THREAD

**Issue by Wuguanghua** [ant-design/ant-design-mobile-rn#524]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
```
Modal.alert('title', 'des', [
                        { text: 'ok' },
                    ]);



// 按下安卓返回键回到上一个页面，而 modal 任然存在。
// Press the Android Back button to go back to the previous page, and the modal will still exist.
```

### What is expected?
期望当 modal 弹起时，按下安卓返回键可以拦截 modal 状态，关闭 modal。

It is expected that when the modal pops up, pressing the Android return key will intercept the modal state and close the modal.

### What is actually happening?
modal 没有监听 安卓的返回键

Modal does not listen Android back key

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React |  0.59.8 |
| System | mac os 10.14.4 |
| Browser | chrome 74.0.3729.169 |

---
试图 把 Modal 作为 key 值传给父组件，由父组件监听安卓返回建，在外部关闭 modal，但是传给父组件的 key 值总是 undefined。
```
// children.js

const key = Modal.alert('title', 'des', [
                        { text: 'ok' },
                    ]);

this.props.setModalkey(key);

// parent.js
componentDidMount() {
if(!IOS) {
            BackHandler.addEventListener('hardwareBackPress', this.handleBackAndroid);
        }
}

componentWillUnmount() {
        if(!IOS) {
            BackHandler.removeEventListener('hardwareBackPress');
        }
    }

 handleBackAndroid = () => {
         if(this.state.modalKey) Portal.remove(this.state.modalKey);
        this.props.navigation.goBack();
        return true;
    };

 setModalkey = (modalKey) => {
        console.log(modalKey); // => undefined ???
        this.setState({
            modalKey
        });
    };

```

**Comment by tomnotcat** [comment]
I have the same issues with ActionSheet.showActionSheetWithOptions and Modal.operation API,
I can't even handle 'back' press myself, since ActionSheet does not notify when ActionSheet closed.
Does anyone known how to solve this issue?

**Comment by tomnotcat** [comment]
另外发现antd mobile rn的expo demo里，安卓版本返回键能正常关闭ActionSheet和Modal.operation
但是找不到expo demo的代码，不知道是怎么实现的。

**Comment by bang88** [comment]
@Wuguanghua alert 没有返回值， 不能用那种方式关闭。如果确实需要那个key 的话可以来个PR，返回那个key。或者使用Portal添加一个自定义的modal 然后再用key关闭

**Comment by bang88** [comment]
@tomnotcat 好像没有特殊处理过

**Comment by lihp2014** [comment]
Modal.prompt 同样存在这个问题，想问下会更新版本修复这个问题吗？

**Comment by 1uokun** [comment]
In source code,We can use `Portal` to remove current modal.
We can also get The key ,see the detail in https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/portal/portal-host.tsx#L28
```
// ant-design-mobile-rn/components/modal/demo/basic.tsx

import { Modal, Portal } from '../../';
import { portal } from '../../portal/portal-host'

BackHandler.addEventListener('hardwareBackPress', ()=>{
      Portal.remove(portal.nextKey-1)
});
```

**Comment by bang88** [comment]
We can return the `alert` key if needed

**Comment by Archer-Programmer** [comment]
@1uokun，你好，我用的antd版本为3.1.5，我在prompt.js中发现prompt方法存在一个key但并没有返回，可以在不修改源码的前提下获取key值吗，另外，文档中没有Portal组件，但是在antd mobile rn的expo demo里有这个组件，希望能够补充

**Comment by 1uokun** [comment]
> @1uokun，你好，我用的antd版本为3.1.5，我在prompt.js中发现prompt方法存在一个key但并没有返回，可以在不修改源码的前提下获取key值吗，另外，文档中没有Portal组件，但是在antd mobile rn的expo demo里有这个组件，希望能够补充

```
import Portal from '@ant-design/react-native/lib/portal'
import Modal from '@ant-design/react-native/lib/modal'
import {portal} from '@ant-design/react-native/lib/portal/portal-host'

//TO DO : Get key
portal.nextKey-1

//TO DO: Manual close modal
Portal.remove(portal.nextKey-1)
```

**Comment by Tzng** [comment]
我加上了那个返回时间了，最新版本的是可以返回关闭了

**Comment by bang88** [comment]
> 我加上了那个返回时间了，最新版本的是可以返回关闭了

Please upgrade to the latest version
