### ISSUE TITLE
Rendering cards within responsive grids

### ISSUE THREAD

**Issue by Pranit-Harekar** [ant-design/ant-design-mobile-rn#525]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
My apologies! Link is not applicable but just putting a link to Grid documentation since the question is related to that.

[https://rn.mobile.ant.design/components/grid/](https://rn.mobile.ant.design/components/grid/)

### Steps to reproduce
I am designing a "product display screen" (similar to this page https://www.alibaba.com/catalog/Packaging-Machine_cid100009422?spm=a272h.12365639.jpaszdom.1.15b22f9141kqTJ) but in React Native app. I would like to render cards inside grids. I tried following things:
- wrap Card component inside Grid component, that didn't work since it didn't render the wrapped card component
- tried to pass card component to the "data" prop in grid component but that of course wouldn't work since its type is Array<{icon, text}>
- there isn't "row" "col" component in React Native just like React has otherwise I would have done something like [this](https://stackoverflow.com/questions/51091158/how-to-add-cards-in-grid-with-ant-design-using-react-js).

So how do I achieve this?

Please help! I am stuck.

### What is expected?
N/A

### What is actually happening?
N/A

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | React: 16.8.3, React-Native: 0.59.3 |
| System | MacOS |
| Browser | Chrome |

**Comment by bang88** [comment]
Hi @Pranit-Harekar I think you are finding something like this https://github.com/xudafeng/autoresponsive-react-native. but unfortunately we don't support responsive grid ATM. sorry for that.
