### ISSUE TITLE
DatePicker选择器点开滚轮时初始值显示当天new Date()

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#529]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
DatePicker选择器点开滚轮时初始值显示当天，现有API中minDate参数只能显示最小选择日期，那么之前的日期选择不上了

### What does the proposed API look like?
新增一个参数，滚轮默认选中到new Date()

**Comment by bang88** [comment]
`value`  属性不能用吗？

**Comment by MoQingYu** [comment]
假如一种场景，最小值1900年，不设置value的情况下，滚轮依然默认选中2000年，这样用户体验就不是很好了

**Comment by boonook** [comment]
> 假如一种场景，最小值1900年，不设置value的情况下，滚轮依然默认选中2000年，这样用户体验就不是很好了

这个室友解决方案的 value={this.state.createStartDates?this.state.createStartDates:new Date()}这不就完美的解决了吗？

**Comment by M45ter** [comment]
> `value` 属性不能用吗？

value属性指定的话，绑定的state就已经有值了，可否提供一个参数指定state没有值时进入默认选中一个想指定的日期或者当天，默认选中2000年感觉体验不好，能否提个pr？
