### ISSUE TITLE
@ant-design/react-native/lib/picker/demo/basic  ./data.json 不存在

### ISSUE THREAD

**Issue by hexiao-o** [ant-design/ant-design-mobile-rn#534]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/docs/react/introduce-cn](https://rn.mobile.ant.design/docs/react/introduce-cn)

### Steps to reproduce
```
require('@ant-design/react-native/lib/picker/demo/basic')
```

### What is expected?
调用@ant-design/react-native/lib/picker/demo/basic ./data.json 存在，demo时无错误

### What is actually happening?
```
The module `./data.json` could not be found from `/Users/hexiao/GGGGGGG
GG/coding/blog-rn/node_modules/@ant-design/react-native/lib/picker/demo/basic.js`.
```

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | react-native |
| System | mac |
| Browser | / |

**Comment by bang88** [comment]
这个文件不是lib的一部分，所以没有跟随npm一起发布。有需要的话可以看下Picker下的demo

https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/demo/basic.md

`const data = require('@bang88/china-city-data');
`
