### ISSUE TITLE
Android Carousel 走马灯垂直显示循环播放后第二项滚动变成了向下翻滚，其他项正常向上翻滚。

### ISSUE THREAD

**Issue by showtan001** [ant-design/ant-design-mobile-rn#538]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/carousel-cn/](https://rn.mobile.ant.design/components/carousel-cn/)

### Steps to reproduce
[https://rn.mobile.ant.design/components/carousel-cn/] 中的代码演示

### What is expected?
Android全部向上翻滚

### What is actually happening?
Android第二项向下翻滚

| Environment | Info |
|---|---|
| antd | 3.1.3 |
| React | 0.57.8 |
| System | mac os 10.13.6 |
| Browser | chrome 74.0.3729.169 |

**Comment by aweffr** [comment]
我的项目中也遇到了这个问题

**Comment by EngsShi** [comment]
部分设备横向轮播也会，第二张图向左滚动，跳动了一下

**Comment by dq77** [comment]
这个问题其实就是组件首次加载的时候默认渲染的是最后一张，就导致动画错位了。
官网上的DEMO就有这个BUG。 233333.....  https://rn.mobile.ant.design/components/carousel-cn/
坐等修复
