### ISSUE TITLE
0.55.4 该用哪个版本呢？

### ISSUE THREAD

**Issue by Manjiz** [ant-design/ant-design-mobile-rn#540]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 0.55.4 运行，我看 2.x 的 RN 版本是 49 的，3.x 又到了 57，这中间的版本该用哪个呢

### What does the proposed API look like?
在 0.55.4 运行

**Comment by bang88** [comment]
可以试一下3.x。
