### ISSUE TITLE
Icon组件如何使用自定义的ttf库

### ISSUE THREAD

**Issue by aijason** [ant-design/ant-design-mobile-rn#543]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile-rn](http://new-issue.ant.design/?repo=ant-design-mobile-rn)

### Steps to reproduce
Icon组件如何使用自定义的ttf库

### What is expected?
Icon组件如何使用自定义的ttf库

### What is actually happening?
Icon组件如何使用自定义的ttf库

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | react-native 0.59.9 |
| System | Icon组件如何使用自定义的ttf库 |
| Browser | Icon组件如何使用自定义的ttf库 |

---
Icon组件如何使用自定义的ttf库

**Comment by bang88** [comment]
现在不支持自定义的字体 https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/icon/index.tsx#L1

如果有需要可以使用自己的iconfont。

**Comment by aijason** [comment]
能支持自定义图片吗

**Comment by aijason** [comment]
![image](https://user-images.githubusercontent.com/13975853/59436306-f232ef00-8e21-11e9-8e57-be42a771086a.png)
以前的自定义图库icon，升级ant-design版本后无法使用

**Comment by bang88** [comment]
@aijason 3.0 后统一使用ant-icons了， 所以不支持之前的 写法。  😢

**Comment by aijason** [comment]
ant-icons支持新增矢量图的使用吗？没找到使用方法😿

**Comment by bang88** [comment]
不支持的， 你可以定义自己的字体图标（例如从iconfont上面下载后）在本地项目使用ttf，可以看看

https://github.com/oblador/react-native-vector-icons#generating-your-own-icon-set-from-a-css-file
