### ISSUE TITLE
There are errors in the display page of the official website

### ISSUE THREAD

**Issue by kavience** [ant-design/ant-design-mobile-rn#545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/result-cn/](https://rn.mobile.ant.design/components/result-cn/)

### Steps to reproduce
open the official website

### What is expected?
I want to see the ant-design-mobile-ru components

### What is actually happening?
error

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | 0.59.8 |
| System | macOS Mojave |
| Browser | chrome |

**Comment by bang88** [comment]
Missing demo.
