### ISSUE TITLE
I can not access to the website of ant-design-mobile-rn? and I have discovered the update log of antd-mobile. the divided record has been delete from the update history?Why, it will not be maintaince?

### ISSUE THREAD

**Issue by jackjj12** [ant-design/ant-design-mobile-rn#55]

**Comment by jackjj12** [comment]
Can not visit the website of rn. please response to me.

**Comment by silentcloud** [comment]
use proxy ?

**Comment by jackjj12** [comment]
Sorry to response to you so late. It is okay now. Maybe some network problems, maybe you need to use a method to keep the website online. It is part of alibaba, I think your group can handle it. Thank u.
