### ISSUE TITLE
DatePicker 在 onValueChange 方法里调用 setState 滑动日期  回弹 初始值

### ISSUE THREAD

**Issue by fightingljm** [ant-design/ant-design-mobile-rn#550]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce

```js
<DatePicker
                            title={`${this.state.test}`}
                            mode={'datetime'}
                            itemStyle={{ fontSize: 18 }}
                            onChange={v => {
                                this.setState({
                                    time: v,
                                })
                            }}
                            onValueChange={(vals)=>{
                                this.setState({
                                    test: vals
                                })
                            }}
                        >
                            <CustomItem />
                        </DatePicker>
```

### What is expected?
DatePicker 在 onValueChange 方法里调用 setState 可以正常滑动选择日期

### What is actually happening?
DatePicker 在 onValueChange 方法里调用 setState 滑动日期 回弹 初始值

| Environment | Info |
|---|---|
| antd | 3.1.5 |
| React | react-native |
| System | OSX |
| Browser | - |

**Comment by buffge** [comment]
https://github.com/ant-design/ant-design-mobile-rn/issues/496

**Comment by fightingljm** [comment]
> #496

![image](https://user-images.githubusercontent.com/24884434/60064489-2c11c880-9733-11e9-8032-608f13deb026.png)

![image](https://user-images.githubusercontent.com/24884434/60064451-10a6bd80-9733-11e9-8a42-615b0f90708d.png)

It's didn't work

**Comment by wangfpp** [comment]
这个问题我也遇到了
