### ISSUE TITLE
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native/Libraries/StyleSheet/normalizeColor` from `/Volumes/WORK/react-native-app/node_modules/antd-mobile-rn/lib/segmented-control/segmented.android.js`: Module `react-native/Libraries/StyleSheet/normalizeColor` does not exist in the Haste module map

### ISSUE THREAD

**Issue by zhangchenna** [ant-design/ant-design-mobile-rn#56]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `react-native/Libraries/StyleSheet/normalizeColor` from `/Volumes/WORK/react-native-app/node_modules/antd-mobile-rn/lib/segmented-control/segmented.android.js`: Module `react-native/Libraries/StyleSheet/normalizeColor` does not exist in the Haste module map

RN 56  ANTUI 2.20版本 react 16.4.1

**Comment by CodingPapi** [comment]
https://github.com/necolas/react-native-web/issues/308
https://github.com/necolas/react-native-web/commit/c56b472258acee7d5bfa8b0fcd485e9b383fc897
使用的normalizeColor 在新的react-native中被移动到了独立的npm包中

**Comment by zhangchenna** [comment]
貌似没有动静

**Comment by CodingPapi** [comment]
@zhangchenna 不要引用和使用SegmentedControl控件，可以编译通过，暂时只能这样了

**Comment by zhangchenna** [comment]
@CodingPapi 看来大家都更新新版本吧，这么致命的问题都没人关注 RN 感觉药丸了

**Comment by DavidNorena** [comment]
can you guys please use english ?

**Comment by DavidNorena** [comment]
any workaround guys ?

**Comment by z-android** [comment]
遇到了同样的问题

**Comment by zhangchenna** [comment]
@warmhug c

**Comment by DavidNorena** [comment]
@zhangchenna @z-android for now just make a diff from [here](https://github.com/ant-design/ant-design-mobile-rn/pull/57/commits/6f21ee288a83200c0972905dd4a810a32a779b3d), thanks to @CodingPapi ! It's a good workaround until an official update.

Note: It doesn't matter if you don't import SegmentedControl, at least for me it's crashing the whole app, without using it !

**Comment by DavidNorena** [comment]
**Update:**

A better workaround for now: (Thanks to @CodingPapi):

* Add normalize-css-color package dependency:

   `$ yarn add normalize-css-color -D`

* Place [this patch](https://gist.github.com/DavidNorena/c42abc8d1e2d6d1b871814c203b5fff0) at the root directory of your project.
* Add a **postinstall** script in your package.json, so the file will get patched everytime you install something:

```
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "postinstall": "patch -p0 < segmented.android.js.patch"
  },
```
**Note:** You should change the **patch** command if you are working on windows.

**Comment by zhangchenna** [comment]
The problem has been fixed
