### ISSUE TITLE
Typography Components

### ISSUE THREAD

**Issue by phillip055** [ant-design/ant-design-mobile-rn#560]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allowing apps to have a consistent text font and style

### What does the proposed API look like?
<Title>Feature</Title>

**Comment by phillip055** [comment]
Or is there a way currently, because we actually import the fonts, not sure where we actually use it by default.

**Comment by bang88** [comment]
There is no Typography Component yet.
