### ISSUE TITLE
@ant-design/icons-react-native give deprecation warning about rnpm

### ISSUE THREAD

**Issue by joshuaavalon** [ant-design/ant-design-mobile-rn#561]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
Install @ant-design/icons-react-native

### What is expected?
No warning

### What is actually happening?
warn The following packages use deprecated "rnpm" config that will stop working from next release:

@ant-design/icons-react-native: https://npmjs.com/package/@ant-design/icons-react-native
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | 0.60.0 |
| System | Window 10 |
| Browser | N/A |

**Comment by bang88** [comment]
Thanks for report it here. Will have a fix in next version.
