### ISSUE TITLE
Picker,请返回 label的值

### ISSUE THREAD

**Issue by QShengW** [ant-design/ant-design-mobile-rn#562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Backend requires label values

### What does the proposed API look like?
(value, label) => console.log([1,2,3],['one','two','three'])

**Comment by bang88** [comment]
Sorry .  

This was by design. You have to get it via value
