### ISSUE TITLE
ViewPagerAndroid has been extracted from react-native core and will be removed in a future release. 

### ISSUE THREAD

**Issue by xinbowang** [ant-design/ant-design-mobile-rn#568]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://jlzq6957pv.codesandbox.io/)

### Steps to reproduce
`
<Tabs styles={{topTabBarSplitLine: {
          // borderBottomColor: theme.border_color_base,
          borderBottomWidth: 0
        }}} tabs={this.state.tabs}
              animated={false}
              tabBarUnderlineStyle={{backgroundColor: '#4475FD'}}
              tabBarActiveTextColor="#4475FD"
              tabBarInactiveTextColor="#999">
          <ScrollView>
            <Text>1</Text>
          </ScrollView>
          <ScrollView>
            <Text>2</Text>
          </ScrollView>
          <ScrollView>
            <Text>3</Text>
          </ScrollView>
 </Tabs>
`

### What is expected?
1. yarn add @react-native-community/viewpager
2. react-native link @react-native-community/viewpager
3. import ViewPagerAndroid from '@react-native-community/viewpager';

### What is actually happening?
import {ViewPagerAndroid} from 'react-native';

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | react-native 0.59.9 |
| System | android  |
| Browser | android 9.0(google apis) x86 |

**Comment by TonyYang9527** [comment]
the same issue. Please resolve it.

**Comment by bang88** [comment]
3.2.0
