### ISSUE TITLE
button 内部字体style功能

### ISSUE THREAD

**Issue by xinbowang** [ant-design/ant-design-mobile-rn#569]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
、
<Button type="ghost"
                  styles={{largeRawText: {fontSize: 12}, ghostRawText: {color: '#4475FD'}}}
                  onPress={this.goDiagnosis.bind(this)}
                  style={styles.loginBtn}>中断检测</Button>
、

### What does the proposed API look like?
、
<Button type="ghost"
                  fontStyle={{fontSize: 12,color: '#4475FD'}}
                  onPress={this.goDiagnosis.bind(this)}
                  style={styles.loginBtn}>中断检测</Button>
、

**Comment by bang88** [comment]
Please overwrite text style.

**Comment by xinbowang** [comment]
怎么复写？没有提供接口吧？

**Comment by xinbowang** [comment]
> 请覆盖文字样式。



> Please overwrite text style.

怎么复写？没有提供接口吧？

**Comment by arfaWong** [comment]
@xinbowang 问题解决了吗？
