### ISSUE TITLE
Toast 的 ActivityIndicator 的color可以做成全局theme的配置吗？

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [ant-design/ant-design-mobile-rn#571]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Toast 的 ActivityIndicator 的color可配置

### What does the proposed API look like?
theme的配置

**Comment by M45ter** [comment]
@zjjjjjjjjjjd 
这个应该可以自定义组件封装下ActivityIndicator，默认指定color属性就可以了，自己业务里用这个自定义组件
