### ISSUE TITLE
react-native version = 0.59.8  Tabs component is not working .

### ISSUE THREAD

**Issue by HeWenKe** [ant-design/ant-design-mobile-rn#574]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://reactnative.cn/docs/using-a-listview/](https://reactnative.cn/docs/using-a-listview/)

### Steps to reproduce
react-native cli  创建的项目

### What is expected?
正常

### What is actually happening?
正常

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | 0.59.8 |
| System | android |
| Browser | app |

**Comment by guihouchang** [comment]
0.59.10版本也不行
