### ISSUE TITLE
ActionSheet点击无法弹出，官网文档中的实例同样无法弹出。

### ISSUE THREAD

**Issue by zhuxinhuan** [ant-design/ant-design-mobile-rn#576]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
ActionSheet.showActionSheetWithOptions(
            {
                options: [
                    '拍摄照片',
                    '选择照片',
                    '取消',
                ],
            },
            buttonIndex => {
                switch (buttonIndex) {
                    case 0:
                        //拍摄照片
                        break;
                    case 1:
                        //选择照片
                        break;
                    case 2:
                        //取消
                        break;
                    default :
                        break;
                }
            }
        );

### What is expected?
弹出选项框

### What is actually happening?
选项框无法弹出

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | 0.57.8 |
| System | win10 |
| Browser | chorome |

**Comment by M45ter** [comment]
我猜是不是这个没加
如果需要使用Modal以及Toast还需要在 App 的入口处加上Provider
```
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';
import { Button, Provider, Toast } from '@ant-design/react-native';

class HelloWorldApp extends Component {
  render() {
    return (
      <Provider>
        <Button onPress={() => Toast.info('This is a toast tips')}>
          Start
        </Button>
      </Provider>
    );
  }
}
```
