### ISSUE TITLE
在antd-mobile-rn中使用grid组件的最后一行多出一些空白点.

### ISSUE THREAD

**Issue by kaykie** [ant-design/ant-design-mobile-rn#58]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
0.51.0

### Reproduction link
[https://jsfiddle.net/kaykie/9m7hx8jz/](https://jsfiddle.net/kaykie/9m7hx8jz/)

### Steps to reproduce
代码如上,只需要把render里的代码复制便可轻松复现,最主要是在itemStyle中修改高度

### What is expected?
最后一排不对,怎么有空?

### What is actually happening?
最后一排与上一排是无缝对接的
![image](https://user-images.githubusercontent.com/26200899/42561624-2b919ea4-852c-11e8-9bc1-487b9bb86d26.png)

**Comment by youngjuning** [comment]
grid 如何自定义图片大小

**Comment by yejing2017** [comment]
原因是 6 7 8 那里 空着，会渲染默认高度（同宽），这有bug

**Comment by kaykie** [comment]
那是不是我只要把高度设置为默认的高度即可? @yejing2017

**Comment by yejing2017** [comment]
设置为默认高度是OK的

我的解决办法 填充 678 为空白
ItemStyle 里面的自定义 height 就会起作用了 
  @kaykie

**Comment by kaykie** [comment]
3Q
