### ISSUE TITLE
TextareaItem 输入带有中文多行后排版会来回变动

### ISSUE THREAD

**Issue by 601724080** [ant-design/ant-design-mobile-rn#581]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/textarea-item-cn/](https://rn.mobile.ant.design/components/textarea-item-cn/)

### Steps to reproduce
1.首行输入 ‘12321312哈哈哈12312312111111111’。
2.然后输入非中文将第一行填充满，此时排版将会变动，第一行结尾回事最后一个 ‘哈’字，数字移到第二行。
3.第二第三行均可输入‘12321312哈哈哈12312312111111111’然后将整行使用非中文填充满，整个编辑过程中文字排版将会不停发生变动。

### What is expected?
文字排版固定

### What is actually happening?
文字排版发生变动

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React |  react-native |
| System | Android 8.1.0 |
| Browser |  chrome 75.0.3770.80 |

**Comment by bang88** [comment]
这个不是ant的组件问题
