### ISSUE TITLE
InputItem组件取不到isFocused方法

### ISSUE THREAD

**Issue by BigBigWen** [ant-design/ant-design-mobile-rn#588]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jv45o5jjp9?from-embed)

### Steps to reproduce
1.写一个InputItem组件
2. 绑定ref
3.取isFocused 拿不到

### What is expected?
能拿到当前是否聚焦的结果

### What is actually happening?
拿不到

| Environment | Info |
|---|---|
| antd | 3.1.17 |
| React | 0.55.4 |
| System | win 10 |
| Browser | chrom |

**Comment by bang88** [comment]
```jsx
ref.inputRef
```

**Comment by deathemperor** [comment]
> ```js-jsx
> ref.inputRef
> ```

How do I use it? I can't seem to access the correct API. `ref.inputRef.current.isFocused()` doesn't work. This is the InputItem ref when I console.log it out: https://snipboard.io/ZMHLv7.jpg

**Comment by bang88** [comment]
@deathemperor You can access it via `ref.inputRef.isFocused()` but you should check `inputRef` isn't `null`.
