### ISSUE TITLE
Modal.alert 在横屏时会抖动

### ISSUE THREAD

**Issue by louisV7** [ant-design/ant-design-mobile-rn#597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Modal.alert('SERVICE ERROR', event.message, [{text: 'OK'}])

### What is expected?
正常显示OK,没有抖动

### What is actually happening?
footer中文字和borderTop会不断抖动 

| Environment | Info |
|---|---|
| antd | 3.1.12 |
| React | 0.59 |
| System | android 7.0 |
| Browser | chrome 74.0.3729.157 |

---
这个问题只在安卓平板横屏时发生，模拟器，真机竖屏均没有出现此问题，安卓手机没有试过

**Comment by bang88** [comment]
没有Android 平板 :cry:
