### ISSUE TITLE
react-native link @ant-design/icons-react-native failed

### ISSUE THREAD

**Issue by innocces** [ant-design/ant-design-mobile-rn#598]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://没有repo](https://没有repo)

### Steps to reproduce
1 yarn add @ant-design/react-native
2 react-native link @ant-design/icons-react-native

### What is expected?
success linked

### What is actually happening?
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.

| Environment | Info |
|---|---|
| antd | 3.1.12 |
| React | 0.60.4 |
| System | macOSMojave 10.14.6 |
| Browser | simulator 12.4 |

**Comment by innocces** [comment]
Added: '@ant-design/react-native' already exists in package.json

**Comment by innocces** [comment]
![image](https://user-images.githubusercontent.com/38065966/62693639-78744780-ba05-11e9-8682-7e5879dfb81e.png)

**Comment by MarnoDev** [comment]
应该是还不支持 0.60 的自动 link

**Comment by Joursion** [comment]
![image](https://user-images.githubusercontent.com/10599678/62821253-b065c100-bba4-11e9-9139-10bf21ec52ad.png)
XCode 已经配置了，也遇到这个问题

**Comment by innocces** [comment]
> ![image](https://user-images.githubusercontent.com/10599678/62821253-b065c100-bba4-11e9-9139-10bf21ec52ad.png)
> XCode 已经配置了，也遇到这个问题

The steps I took to solve the problem：
1. Manually add'@ant-design/icons-react-native'to'package.json'
2. Re-execute'link'
It's silly, but it solves the current problem.

**Comment by Joursion** [comment]
> > ![image](https://user-images.githubusercontent.com/10599678/62821253-b065c100-bba4-11e9-9139-10bf21ec52ad.png)
> > XCode 已经配置了，也遇到这个问题
> 
> The steps I took to solve the problem：
> 
> 1. Manually add'@ant-design/icons-react-native'to'package.json'
> 2. Re-execute'link'
>    It's silly, but it solves the current problem.
看来是我的环境不行，我试过 N 次 删除 node_modules , 重新 install，重新 link，而且 link 也是提示成功的，但是就是运行之后，就会报这个错。

react-native link @ant-design/icons-react-native
info Linking assets to ios project
info Linking assets to android project
success Assets have been successfully linked to your project

**Comment by anfalch6** [comment]
It worked for me,try:
1.yarn add @ant-design/icons-react-native or npm install @ant-design/icons-react-native
2.react-native link @ant-design/icons-react-native
