### ISSUE TITLE
RN 0.60.4 链接字体图标报错

### ISSUE THREAD

**Issue by KingAmo** [ant-design/ant-design-mobile-rn#599]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design-mobile-rn](http://new-issue.ant.design/?repo=ant-design-mobile-rn)

### Steps to reproduce
```
npm install @ant-design/react-native --save // 这一步成功
```
```
react-native link @ant-design/icons-react-native //这一步报错
```

### What is expected?
链接字体库成功

### What is actually happening?
```
error Unknown dependency. Make sure that the package you are trying to link is already 
installed in your "node_modules" and present in your "package.json" dependencies. Run CLI 
with --verbose flag for more details.
```

| Environment | Info |
|---|---|
| antd | 3.1.12 |
| React | RN 0.60.4 |
| System | 无 |
| Browser | 无 |

**Comment by bang88** [comment]
#598

**Comment by AlvinMi** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> http://new-issue.ant.design/?repo=ant-design-mobile-rn
> 
> ### Steps to reproduce
> ```
> npm install @ant-design/react-native --save // 这一步成功
> ```
> 
> ```
> react-native link @ant-design/icons-react-native //这一步报错
> ```
> 
> ### What is expected?
> 链接字体库成功
> 
> ### What is actually happening?
> ```
> error Unknown dependency. Make sure that the package you are trying to link is already 
> installed in your "node_modules" and present in your "package.json" dependencies. Run CLI 
> with --verbose flag for more details.
> ```
> 
> Environment	Info
> antd	3.1.12
> React	RN 0.60.4
> System	无
> Browser	无

I had the same problem: 
```bash
$ react-native link @ant-design/icons-react-native --verbose
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies.
```

try this: 
```bash
$ react-native link @ant-design/react-native
info Linking assets to ios project
warn Group 'Resources' does not exist in your Xcode project. We have created it automatically for you.
info Linking assets to android project
success Assets have been successfully linked to your project
$ react-native run-android
```

![image](https://user-images.githubusercontent.com/21032217/65217115-b45efa00-dae5-11e9-88ca-158bfc40b24a.png)
