### ISSUE TITLE
search bar增加支持clearbtn

### ISSUE THREAD

**Issue by 7Charlotte** [ant-design/ant-design-mobile-rn#600]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一键清除输入的关键字

### What does the proposed API look like?
当用户输入关键字是，显示clearbtn，点击clearbtn，清除关键字。如附件
[clearbtn.pdf](https://github.com/ant-design/ant-design-mobile-rn/files/3490839/clearbtn.pdf)

**Comment by bang88** [comment]
已经有了
