### ISSUE TITLE
tabs设置完 initialPage之后，点击tabs切换时，page会自动切换回initialPage的值

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#603]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
1.initialPage设置为1
2.点击tab切换到2，此时page为2，突然又变回initialPage了，导致tab只有抖动，没有切换tab 

### What is expected?
点击tabs切换时，不喜欢tabs重制为initialPage

### What is actually happening?
1.initialPage设置为1
2.点击tab切换到2，此时page为2，突然又变回initialPage了，导致tab只有抖动，没有切换tab 

| Environment | Info |
|---|---|
| antd | 3.1.12 |
| React | 16.8.3 |
| System | iOS12.4 |
| Browser | 版本 71.0.3578.98（正式版本） （64 位） |

---
说明：tabPage属性用于设置tabs组件page属性
<Tabs
          tabs={this.allShops}
          style={{flex: 1}}
          swipeable={false} //是否可以滑动内容切换
          useOnPan={false} //使用跟手滚动
          usePaged={true} //是否启用分页模式
          initialPage={this.initialPage}
          page={tabPage} //当前Tab, index or key
          onChange={this.onChange}
          onTabClick={this.onTabClick}
          tabBarInactiveTextColor={'#303030'}
          tabBarActiveTextColor={'#FF5300'}
          tabBarTextStyle={styles.tabBarTextStyle}
          tabBarUnderlineStyle={styles.tabBarUnderlineStyle}>
          {this.allShops.map((item, index) => {
            return (
              <FlatList
                contentContainerStyle={{flexGrow: 1}}
                ListEmptyComponent={() => <EmptyView />}
                refreshing={refreshing}
                onRefresh={this.handleRefresh.bind(this, item, index)}
                onEndReached={this.loadMoreData.bind(this, item, index)}
                ItemSeparatorComponent={() => <View style={{height: 1}} />}
                onEndReachedThreshold={0.01}
                data={data[index]}
                renderItem={this.renderItem}
              />
            );
          })}
        </Tabs>
onChange = (tab, index) => {
    console.log('onChange', tab, index);
    this.setState({
      tabPage: index,
    });
  };

再给关键方法打断点之后就能正常显示。例如：onMomentumScrollEnd
1.初始化状态
![image](https://user-images.githubusercontent.com/12253453/63069387-3ee19600-bf49-11e9-900a-7167e03ae210.png)
2.点击tab的index=1栏
onMomentumScrollEnd方法会回调两次，打了断点能正常跳转，没打断点就不行
![image](https://user-images.githubusercontent.com/12253453/63069431-5fa9eb80-bf49-11e9-8020-e51efce91f3e.png)
![image](https://user-images.githubusercontent.com/12253453/63069439-69335380-bf49-11e9-8659-9954b365d054.png)

**Comment by bang88** [comment]
先用 `initialPage` 不要同时使用 `page` 看看，不设置page 应该也能满足需求吧。

**Comment by inkCrazy** [comment]
是的，不使用page，视图效果上是一样的
