### ISSUE TITLE
How to close popover?

### ISSUE THREAD

**Issue by Pranit-Harekar** [ant-design/ant-design-mobile-rn#614]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/popover](https://rn.mobile.ant.design/components/popover)

### Steps to reproduce
NA

### What is expected?
NA

### What is actually happening?
NA

| Environment | Info |
|---|---|
| antd | 3.1.12 |
| React | 16.8.3 |
| System | MacOS |
| Browser | Chrome |

---
How to close popover from `Popover` and `PopoverItem` component? Please provide an example.

**Comment by bang88** [comment]
We don't have an api for that. It will close automatically after user tapped someplace.
