### ISSUE TITLE
 http://new-issue.ant.design?repo=ant-design-mobile-rn

### ISSUE THREAD

**Issue by EliYenn** [ant-design/ant-design-mobile-rn#618]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/toast-cn/#components-toast-demo-basic](https://mobile.ant.design/components/toast-cn/#components-toast-demo-basic)

### Steps to reproduce
想要设置Toast全局config

### What is expected?
设置成功

### What is actually happening?
Toast.config is not a funtion

| Environment | Info |
|---|---|
| antd | 3.1.14 |
| React | react:16.8.6 / RN:0.61   |
| System | mac os  |
| Browser | ios9    |

**Comment by bang88** [comment]
This is RN not mobile version.

**Comment by EliYenn** [comment]
肯定是rn啊，就是rn设置无效
