### ISSUE TITLE
node_modules/antd-mobile-rn/lib/drawer/index.native.d.ts(3,26): error TS7016: Could not find a declaration file for module 'react-native-drawer-layout'. '/Volumes/Work/react-native-app/node_modules/react-native-drawer-layout/dist/DrawerLayout.js' implicitly has an 'any' type.   Try `npm install @types/react-native-drawer-layout` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-drawer-layout';`

### ISSUE THREAD

**Issue by zhangchenna** [ant-design/ant-design-mobile-rn#62]
node_modules/antd-mobile-rn/lib/drawer/index.native.d.ts(3,26): error TS7016: Could not find a declaration file for module 'react-native-drawer-layout'. '/Volumes/Work/react-native-app/node_modules/react-native-drawer-layout/dist/DrawerLayout.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-drawer-layout` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-drawer-layout';`

typescript Prompt for this error
"@types/react-native": "0.55.4",
"react-native": "0.55.4",
"typescript": "2.7.2"

**Comment by silentcloud** [comment]
![image](https://user-images.githubusercontent.com/1698185/42916781-67a4c1e2-8b39-11e8-8962-f44b2f0d6748.png)

![image](https://user-images.githubusercontent.com/1698185/42916787-6d714320-8b39-11e8-9ab5-adad62534500.png)


Pls reinstall node_modules
