### ISSUE TITLE
希望 DatePicker 提供 一个onPress回调函数

### ISSUE THREAD

**Issue by QShengW** [ant-design/ant-design-mobile-rn#622]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在我的项目中我能使用这个回调函数解决软键盘关闭的问题。

### What does the proposed API look like?
一个回调函数就好

**Comment by bang88** [comment]
可以在 onDismiss 里面处理

**Comment by wangfpp** [comment]
确实需要点击时间选择器的时候作一些操作　　有什么方法自定义加上吗？ @bang88
