### ISSUE TITLE
popover not working? 

### ISSUE THREAD

**Issue by nishant-dani** [ant-design/ant-design-mobile-rn#624]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6xqz4z3x2z?from-embed)

### Steps to reproduce
Run the example on the react - native site.  No popover shows.  It is not clear if the example is working as intended.

### What is expected?
Popover should show when clicking on the list items

### What is actually happening?
No popover

| Environment | Info |
|---|---|
| antd | 3.1.15 |
| React | react-native  |
| System | ios |
| Browser | chrome, safari |

**Comment by bang88** [comment]
It may not working inside browser but it work as expected in react native.
