### ISSUE TITLE
Background color setting of barStyle in Progress is invalid

### ISSUE THREAD

**Issue by autumnleaves1** [ant-design/ant-design-mobile-rn#625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/progress-cn/#components-progress-demo-basic](https://rn.mobile.ant.design/components/progress-cn/#components-progress-demo-basic)

### Steps to reproduce
<Progress 
          percent={5} 
          style={{backgroundColor:'red'}}
          barStyle={{backgroundColor:'#fff'}}
/>

### What is expected?
barStyle works

### What is actually happening?
barStyle does not work

| Environment | Info |
|---|---|
| antd | 3.1.15 |
| React | 0.59.8 |
| System | android 9 |
| Browser | Google Chrome  73.0.3683.75 |

**Comment by bang88** [comment]
Please use borderColor instead.

```jsx
<Progress
percent={5}
style={{backgroundColor:'red'}}
barStyle={{borderColor:'#fff'}}
/>
```
