### ISSUE TITLE
官网示例与本地安卓模拟器显示不一致

### ISSUE THREAD

**Issue by 549830579** [ant-design/ant-design-mobile-rn#626]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/picker-cn/](https://rn.mobile.ant.design/components/picker-cn/)

### Steps to reproduce
打开网页-点击任一picker

### What is expected?
从底部弹出滚动选择组件

### What is actually happening?
官网显示是一个个下拉框

| Environment | Info |
|---|---|
| antd | 3.1.15 |
| React | 16.0.0 |
| System | win 7 |
| Browser | Google Chrome  76.0.3809.132 |

**Comment by 549830579** [comment]
多个示例都有这种情况

**Comment by bang88** [comment]
web 用的是 react native web 表现不一致比较正常
