### ISSUE TITLE
Tabs not working inside a ScrollView (ONLY android)

### ISSUE THREAD

**Issue by neneji** [ant-design/ant-design-mobile-rn#629]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
1) create a ScrollView
2) add Tabs inside

### What is expected?
correct functioning tabs only in ios, it doesnt work neither on android emulator nor android real device

### What is actually happening?
the tab content is collapsed, the tab header not responding, by switching view with react-navigation app crashes

| Environment | Info |
|---|---|
| antd | 3.1.15 |
| React | {"react": "16.8.6","react-native": "0.60.5"} |
| System | macOS Mojave 10.14.6 |
| Browser | chrome 76.0.3809.100 |

**Comment by bang88** [comment]
Can you link me a demo of React Native version.

**Comment by cxfamily** [comment]
node_modules/@ant-design/react-native/lib/tabs/Tabs.js 源码中page94行代码中  ViewPagerAndroid 标签导致 更改源码增加判断 或者注释掉整个if条件判断（page92-111）一下代码：
if (_reactNative.Platform.OS === 'android') {
                return _react2['default'].createElement(
                    _reactNative.ViewPagerAndroid,
                    { key: '$content', keyboardDismissMode: 'on-drag', initialPage: currentTab, scrollEnabled: _this.props.swipeable || usePaged, onPageScroll: function onPageScroll(e) {
                            _this.state.scrollX.setValue(e.nativeEvent.position * _this.state.containerWidth);
                        }, style: { flex: 1 }, onPageSelected: function onPageSelected(e) {
                            var index = e.nativeEvent.position;
                            _this.setState({
                                currentTab: index
                            }, function () {
                                // tslint:disable-next-line:no-unused-expression
                                _this.props.onChange && _this.props.onChange(tabs[index], index);
                            });
                            _this.nextCurrentTab = index;
                        }, ref: function ref(_ref) {
                            return _this.viewPager = _ref;
                        } },
                    content
                );
            }

**Comment by hieupaul** [comment]
Hello any update here?

**Comment by bang88** [comment]
I have fixed an issue related to this will publish it until  the tests passed.

**Comment by MickeyMouse623** [comment]
### 环境
```
"@ant-design/react-native": "^4.0.5",    
"react": "16.13.1",
"react-native": "0.63.3",
```
在这个版本中我并未找到 ```ViewPagerAndroid```，且 ```ScrollView``` 中嵌套 ```Tabs``` 任然不显示

**Comment by CoderJWYang** [comment]
scrollview中嵌套tabs，tabs中嵌套flatlist，同样不显示flatlist内容，请问如何解决？

**Comment by gainskills** [comment]
```
    "@ant-design/react-native": "^4.0.7",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-native": "0.63.4",
```
using Tab in Scrollview, Text, Image which is defined inside of Tab doesn't work

Exceptional:
Text, Image as Tab element should work

**Comment by gainskills** [comment]
> ```
>     "@ant-design/react-native": "^4.0.7",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "react-native": "0.63.4",
> ```
> 
> using Tab in Scrollview, Text, Image which is defined inside of Tab doesn't work
> 
> Exceptional:
> Text, Image as Tab element should work

Ignore my previous comment, figured it out by adding a style: height the Tab's partner <View>
