### ISSUE TITLE
InputItem当type="phone"时值不应被格式化

### ISSUE THREAD

**Issue by chengky** [ant-design/ant-design-mobile-rn#63]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
获取到表单项的值应为正确格式的手机号码，而不应是用于显示的被分段的格式。例如：输入13800013800时获取的表单值不应为138 0001 3800

### What does the proposed API look like?
InputItem当type="phone"时输入13800013800获取到的值也是13800013800

**Comment by huangdou0204** [comment]
+1

**Comment by bang88** [comment]
@chengky  你可以先自己格式化一下. 如果现在改了可能会影响使用。
```js
const phone = text.replace(/\s/g,'')
```
