### ISSUE TITLE
tabs custom width

### ISSUE THREAD

**Issue by autumnleaves1** [ant-design/ant-design-mobile-rn#630]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 Usually,for the beauty of the webpage, we try to ensure that the spacing between tabs and tabs is the same,but wen can't guarantee that the content in tabs is similar. When the number of the words in tabs is different, the spacing between tabs and tabs will be different. At this time, the page designed with tabs do not meet the design requirement.

### What does the proposed API look like?
Sorry,I don't konw how to describe it, maybe just like TabBar.Item. but TabBar.Item does not satisfy this design.

**Comment by bang88** [comment]
Um could you give me a screenshot so I can check it later

**Comment by autumnleaves1** [comment]
![image](https://user-images.githubusercontent.com/23214175/64307650-5b617300-cfc9-11e9-9f8e-8cb56d5fce0c.png)

**Comment by bang88** [comment]
Please check out the demo a few minutes later.  and modify the style to fit your needs.
