### ISSUE TITLE
DatePicker getDefaultMinDate | getDefaultMaxDate 方法的最小月份应该是0，如果为1，则显示2月

### ISSUE THREAD

**Issue by SunAnle** [ant-design/ant-design-mobile-rn#631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/date-picker/datepicker/DatePicker.tsx](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/date-picker/datepicker/DatePicker.tsx)

### Steps to reproduce
DatePicker getDefaultMinDate | getDefaultMaxDate 方法的最小月份应该是0，如果为1，则显示2月

### What is expected?
最小日期：2000-1-1 0:0
最大日期：2030-1-1 0:0

### What is actually happening?
最小日期：2000-2-1 0:0
最大日期：2030-2-1 0:0

| Environment | Info |
|---|---|
| antd | 3.0.6 |
| React | 0.57.8 |
| System | MacOS 10.14.6 |
| Browser | IOS、Android |

**Comment by bang88** [comment]
这个用户端自行修复了。改了会导致线上代码问题
