### ISSUE TITLE
Picker能否根据平台自动选择

### ISSUE THREAD

**Issue by hu382337381** [ant-design/ant-design-mobile-rn#633]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的Picker使用的是react-native中IOS版的，当有picker被点击时，在android上按返回键会直接退出当前页面而不是隐藏选项框，这点在android上体验不够好

### What does the proposed API look like?
可以增加一个prop，是否启用android版picker（只在android平台有效）

**Comment by bang88** [comment]
Android 加一个返回关闭？

**Comment by hu382337381** [comment]
效果上Android是需要按物理返回键隐藏点击picker时屏幕底部弹出的选项框的，现在的picker做不到这点，或者有什么我不知道的处理办法？望告知

**Comment by WMXPY** [comment]
@hu382337381 https://facebook.github.io/react-native/docs/backhandler
