### ISSUE TITLE
Modal popup状态下点击遮罩层不能关闭

### ISSUE THREAD

**Issue by songs777** [ant-design/ant-design-mobile-rn#642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/modal-cn/](https://rn.mobile.ant.design/components/modal-cn/)

### Steps to reproduce
<Modal> popup状态下点击遮罩层不能关闭，closable和maskClosable不起作用

### What is expected?
点击遮罩层关闭

### What is actually happening?
点击这招不能关闭

| Environment | Info |
|---|---|
| antd | 3.1.15 |
| React | expo 34.0.1 |
| System | Mac OS |
| Browser | iOS 12.4 |

**Comment by Lxxyx** [comment]
缺少明确的复现路径

**Comment by NeilSong** [comment]
> 缺少明确的复现路径

复线路径：https://codesandbox.io/s/modal-ywywu?fontsize=14

**Comment by Lxxyx** [comment]
> > 缺少明确的复现路径
> 
> 复线路径：[codesandbox.io/s/modal-ywywu?fontsize=14](https://codesandbox.io/s/modal-ywywu?fontsize=14)

https://codesandbox.io/s/modal-zc9qq

添加 maskClosable 属性后问题解决 @NeilSong

**Comment by NeilSong** [comment]
@Lxxyx 真机测试不起作用，点击遮罩层不能关闭，还有弹出层有时抖动。设备：iPhone XS  iOS12.3.1，

**Comment by MarxZhou** [comment]
> @Lxxyx 真机测试不起作用，点击遮罩层不能关闭，还有弹出层有时抖动。设备：iPhone XS iOS12.3.1，

我在安卓上测试也不管用，连关闭按钮也无法展示出来

**Comment by Mr-sunyijie** [comment]
和楼上一样的问题，现在是没人维护了吗

**Comment by moyuchuangtianya** [comment]
aaa

**Comment by JohnsonChow** [comment]
依然存在这个问题 升级到4.x也是如此

**Comment by 1uokun** [comment]
> 依然存在这个问题 升级到4.x也是如此

@JohnsonChow 具体版本是多少呢，我在[4.0.7](https://github.com/ant-design/ant-design-mobile-rn/releases/tag/4.0.7)解决了这个bug

**Comment by JohnsonChow** [comment]
谢谢你的回复，我们将更新最新版本





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 罗坤 ***@***.***&gt;
发送时间: 2021年8月11日 12:01
收件人: ant-design/ant-design-mobile-rn ***@***.***&gt;
抄送: Johnson Chow ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[ant-design/ant-design-mobile-rn] Modal popup状态下点击遮罩层不能关闭 (#642)
