### ISSUE TITLE
Expo demo app crashes

### ISSUE THREAD

**Issue by pybuche** [ant-design/ant-design-mobile-rn#647]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
When you scan the README's QR code, the expo app crashes, with an error log saying:
> Uncaught Error: 31.0.0 is not a valid SDK version. Options are 35, 34, 33 and UNVERSIONNED

### What is expected?
The expo app used to worked to demo components. Now it seems that it is impossible to see them working before implementing them.

### What is actually happening?
I'm currently benchmarking UI libs for a RN app. Is this lib stable enough to be used in production ?
I'm declining my website to an app version, which is currently using Ant Design web that work like a charm (even though a few things are not very stable ;))
I wonder if the native version is also usable. 
If it is, how can I browse components demo  ?

Thanks!

| Environment | Info |
|---|---|
| antd | 3.1.15 |
| React | react-native |
| System | OSX 10.13 |
| Browser | Chrome latest |

**Comment by bang88** [comment]
We have use it for a long time and working as expected. 

The expo error may come from different expo client version. Will look at it later.

**Comment by pybuche** [comment]
Yes, that's it indeed, thanks!
Actually the Expo app is not very easy to use: almost every project present on it are impossible to launch due to the unmatching version of Expo :/

**Comment by bang88** [comment]
Yeah...

**Comment by bang88** [comment]
Does expo support ViewPagerAndroid natively ? All expo related settings are at expo branch.  You can checkout that branch and test it locally if anyone want help.

**Comment by bang88** [comment]
Close it due to there is no app can running at expo without linking.
