### ISSUE TITLE
RN 0.61.1版本   React-Navigation Toast 组件Android在某些情况下黑色背景消失,导致loading看不到

### ISSUE THREAD

**Issue by fallenner** [ant-design/ant-design-mobile-rn#650]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fallenner/ant-design-rn-bug](https://github.com/fallenner/ant-design-rn-bug)

### Steps to reproduce
1、安装react-navigation，配置两个StackRoute页面。
2、在一个页面先调用Toast.loading,然后跳转到第二个页面。
3、返回后再调用Toast.loading的黑色背景消失。

正常图
![正常情况](https://github.com/fallenner/ant-design-rn-bug/blob/master/pic/before.png)

bug图
![正常情况](https://github.com/fallenner/ant-design-rn-bug/blob/master/pic/after.jpg)

### What is expected?
Toast组件在任意情况背景应该是黑色。

### What is actually happening?
Toast组件在一些情况黑色背景会消失。

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 0.61.1 |
| System | MacOS 10.14.6 |
| Browser | 无 |

**Comment by MaxWu2013** [comment]
Have the same issue in Android

**Comment by yjb2020** [comment]
发现在RN 0.61.1版本下 ，
antd  3.2.0,android下的actionsheet也显示不了

**Comment by bang88** [comment]
Ant Provider 是放在最外层的吗？

**Comment by 1uokun** [comment]
复现之后，我遇到2个问题：
1.跳转路由返回后，**第一次的点击是无效的，第二次点击才能响应到**
2.portal的设计过于复杂，为什么不继续使用`rn-topview`或者说继续使用`AppRegistry.registerComponent`动态修改根组件呢？

**Comment by fallenner** [comment]
@1uokun  你说的跳转返回后，第一次点击无效，会不会是触发了loading变透明导致点击没反应吧？  已经做了好几个基于此结构的app了。并没有发现第一次点击无效的问题呢。

**Comment by fallenner** [comment]
@bang88  只有android上面会这样。

**Comment by bang88** [comment]
我在重现 卡在100% 好久了。 :cry:

**Comment by bang88** [comment]
@fallenner 你能不能试试除了loading之外的其他 Toast组件

**Comment by fallenner** [comment]
@bang88 一样的，估计你是卡在gradle依赖的下载中把。。 我感觉不是ant-design的问题，可能是RN 0.61 对Android的View的实现出现问题了。 可以看看这个[issuse](https://github.com/facebook/react-native/issues/26574)

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/66362421-49eafc80-e9b5-11e9-8627-83a8dc3b14a4.png)

应该是React Native的问题，View的样式也还在。只是不显示了

**Comment by fallenner** [comment]
@bang88 嗯，我试下0.61.2看是否修复了。

**Comment by fallenner** [comment]
RN 0.61.2已修复此问题。
