### ISSUE TITLE
Modal.alert 在iOS上会出现抖动问题

### ISSUE THREAD

**Issue by chenqi777** [ant-design/ant-design-mobile-rn#659]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
当`actions`数组长度为奇数时, 例如长度为3或5时, 在iOS上会出现轻微地上下抖动, 需要仔细看才能看出来. 示例代码:  ` Modal.alert('标题', '信息', [{ text: 'action1' }, {text: 'action2'}, {text: 'action3'}])`

### What is expected?
不抖动

### What is actually happening?
抖动

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 0.6.0 |
| System | iOS 12 |
| Browser | iOS 12 |

**Comment by xiaoyongchen** [comment]
解决了吗，最新版本还是有
