### ISSUE TITLE
checkBox能够提供正方形的选中图标吗？

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile-rn#66]
checkBox能够提供正方形的选中图标吗？现在我看了在源码中是使用的圆形图片，请问能不能够提供正方形的或者能够提供一种方式让用户能够自定义图标？

我使用的版本是："antd-mobile": "2.1.8",

**Comment by bang88** [comment]
fixed on master branch

**Comment by suwu150** [comment]
现在默认是方形图标还是圆形图标,该怎么使用?使用方法能不能进行http://rn.mobile.ant.design/docs/react/introduce-cn 能不能麻烦更新下

**Comment by bang88** [comment]
> fixed on master branch

`3.0` 才支持，现在还在开发中， 如果你急着用可以用自己的图片先替换调antd的， 3.0 使用的是字体图标。

**Comment by suwu150** [comment]
我现在已经用图片换了在使用,使用字体图标好

**Comment by bang88** [comment]
嗯 后面留意一下 #119
