### ISSUE TITLE
Badge setting size attribute is useless

### ISSUE THREAD

**Issue by autumnleaves1** [ant-design/ant-design-mobile-rn#661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/badge-cn/](https://rn.mobile.ant.design/components/badge-cn/)

### Steps to reproduce
setting the value of size, just like this:
<Badge text={9} size='small'>
    <Text
        style={{
            color: tabProps.activeTab === i ? '#31bd48' : undefined,
            borderBottomWidth: 2,
            paddingBottom:6,
            borderBottomColor:tabProps.activeTab === i ? '#31bd48' : '#fff',
         }}
    >
        {tab.title}
    </Text>
</Badge>

### What is expected?
The round logo can be smaller, it is too big

### What is actually happening?
It is to big，There are two pictures below, the first one is on the webpage, the second one is on the virtual machine, and the effect is not good.
![image](https://user-images.githubusercontent.com/23214175/66698118-be9f9d00-ed0d-11e9-8327-288fc8f22fc6.png)

![image](https://user-images.githubusercontent.com/23214175/66698172-3077e680-ed0e-11e9-9b2a-5b60d0a435b0.png)

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 0.59.8 |
| System | windows10 |
| Browser | google chrome |

---
I want to be able to customize the size of the Badge, or to make the Badge smaller

**Comment by bang88** [comment]
You can override system style by pass a `styles` prop to `Badge` component. The full style can found from https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/badge/style/index.tsx

You can overwrite parts of  it  to fit your needs.

**Comment by autumnleaves1** [comment]
I tried to modify the textCornerlarge property of the badge, but it didn't work. Then I tried to rewrite the textCornerlarge property of the badge. The result I got was that size is not a valid style property. I used another method to achieve this effect. Anyway, I have to thank you for your help.




------------------ 原始邮件 ------------------
发件人: "启邦"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 晚上10:00
收件人: "ant-design/ant-design-mobile-rn"<ant-design-mobile-rn@noreply.github.com>;
抄送: "鬼谷子"<2418356743@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design-mobile-rn] Badge setting size attribute isuseless (#661)




You can override system style by pass a styles prop to Badge component. The full style can found from https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/badge/style/index.tsx
 
You can overwrite parts of  it  to fit your needs.
