### ISSUE TITLE
when I set  the props:mode='time' in the DatePicker component,it only displays 'hours','minutes',not 'secounds'

### ISSUE THREAD

**Issue by chocolateonly** [ant-design/ant-design-mobile-rn#662]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I think the DatePicker should display detailed time information,includes 'hours','minutes','secounds'

### What does the proposed API look like?
I think the DatePicker should display detailed time information,includes 'hours','minutes','secounds'

**Comment by bang88** [comment]
Sorry about that. but only support minutes at the moment.
