### ISSUE TITLE
requireNativeComponent: 'RNCVIewPager' was not found in the UIManager

### ISSUE THREAD

**Issue by LouiseDylan** [ant-design/ant-design-mobile-rn#663]
![image](https://user-images.githubusercontent.com/22739465/66832456-8954b280-ef8c-11e9-9d38-807673df9668.png)
使用Tabs组件，iOS是好的， Android报这个错。注释掉Tabs组件是OK的。

环境：
"react-native": "0.61.2",
"@ant-design/react-native": "^3.2.0",

怀疑是ViewPagerAndroid的问题， 但是看了一下node_modules里Tabs.d.ts文件是用了@react-native-community/viewpager。
![image](https://user-images.githubusercontent.com/22739465/66832805-34fe0280-ef8d-11e9-8885-3892af6bea21.png)

所以不确定是哪出的问题

**Comment by JuniorFirster** [comment]
我也遇到了一模一样的问题，'RNCVIewPager' was not found in the UIManager

**Comment by Time-coding** [comment]
> 我也遇到了一模一样的问题，'RNCVIewPager' was not found in the UIManager

我也是

**Comment by tourze** [comment]
The same

**Comment by nodece** [comment]
```
yarn add @react-native-community/viewpager
```

It is working!
