### ISSUE TITLE
requireNativeComponent:RNCViewPager was not found in the UIManager

### ISSUE THREAD

**Issue by Cassie-Yu** [ant-design/ant-design-mobile-rn#666]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/tabs-cn/](https://rn.mobile.ant.design/components/tabs-cn/)

### Steps to reproduce
-

### What is expected?
正常使用

### What is actually happening?
android项目中引入tabs组件项目直接红屏报错 
Invariant Violation:requireNativeComponent:RNCViewPager was not found in the UIManager

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | "react": "16.8.6",     "react-native": "0.60.5", |
| System | - |
| Browser | - |

**Comment by Cassie-Yu** [comment]
具体原因还是不明确，暂时解决办法
@ant-design/react-native退回3.1.15版本 
项目本地下载@react-native-community/viewpager组件

**Comment by jsbsdbd1025** [comment]
+1

**Comment by kavience** [comment]
这个不打算解决了吗。。。

**Comment by suwu150** [comment]
请问有没有解决方案?

**Comment by inkCrazy** [comment]
https://github.com/ant-design/ant-design-mobile-rn/issues/666
