### ISSUE TITLE
Customize Ant Design Theme in React-Native

### ISSUE THREAD

**Issue by kvnlee777** [ant-design/ant-design-mobile-rn#677]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm trying to customize the Ant Design Theme in React-Native. I only know how to customize the theme for React-Web thru https://ant.design/docs/react/use-with-create-react-app. I cannot find the recommended way for React-Native. I'm using expo-cli for React-Native. 

### What does the proposed API look like?
Should i install less transformer for react-native and customize the theme by overriding variables inside antd.less with another .less file?

**Comment by bang88** [comment]
Hi @kvnlee777 You don't need add less for a react-native project. If you want customize theme you can overwrite the theme variables and pass it to Provider.

You can overwrite part of it https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/style/themes/default.tsx

**Comment by ShiromMakkad** [comment]
A note that I found helpful: The file you've linked to above is found at node_modules/@ant-design/react-native/lib/style/themes/default.js. There's also a default.d.js, but I don't know what it does. 

Also, there's an identical file at node_modules/@ant-design/react-native/es/style/themes/default.js, but it does nothing when I change it. I'm not sure why it's there. 

I'd really appreciate some documentation about this on https://rn.mobile.ant.design/docs/react/introduce.
