### ISSUE TITLE
picker value数据是数字类型时有问题

### ISSUE THREAD

**Issue by banli17** [ant-design/ant-design-mobile-rn#68]
value是字符串没有问题，如果是数字，有问题。

![image](https://user-images.githubusercontent.com/12556069/43177498-2ce81d94-8ffb-11e8-9bb8-951b49d021c4.png)

![image](https://user-images.githubusercontent.com/12556069/43177520-414bf40e-8ffb-11e8-8194-77cadc5e6578.png)

**Comment by youngjuning** [comment]
试试这个：https://github.com/youngjuning/antd-mobile-area-data

**Comment by banli17** [comment]
@youngjuning   value是字符串可以，如果是数字就不行。

**Comment by kirkcola** [comment]
+1 也遇到这个问题 本来以为组件内部是默认都以字符串形式处理了
但这个组件似乎也没有提供格式化value的功能

**Comment by kirkcola** [comment]
目前可以暂时使用`getFieldProps`方法中的`options.normalize`钩子对返回值做一次处理
```javascript
{...getFieldProps('field', {
   normalize: (v,prev)=>{
   /* */
  },
})}
```
see http://react-component.github.io/form/examples/normalize.html

**Comment by bang88** [comment]
这个需要怎么处理
