### ISSUE TITLE
How to change Carousel index  programmability

### ISSUE THREAD

**Issue by genglei01** [ant-design/ant-design-mobile-rn#682]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/carousel-g2t0o)

### Steps to reproduce
 https://codesandbox.io/embed/carousel-g2t0o 

### What is expected?
change selectedIndex or scroll page to switch page  by coding

### What is actually happening?
Change selectedIndex, nothing happens.

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | react-native 0.61 |
| System | ios |
| Browser | no |

**Comment by bang88** [comment]
`selectedIndex` not updated after rendered.

**Comment by lchenfox** [comment]
The same issue. Did you work it out?
