### ISSUE TITLE
从0.57.8升级到0.59.10，Tabs报错

### ISSUE THREAD

**Issue by eyes487** [ant-design/ant-design-mobile-rn#683]
Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager. 
This error is located at: in RNCViewPager (at ViewPagerAndroid.android.js:272) in ViewPagerAndroid (created by Context.Consumer) in RCTView (at View.js:45) in View (created by Context.Consumer) in WithTheme (created by Tabs) in Tabs (at approve/index.js:428) in RCTView (at View.js:45) in View (at approve/index.js:420) in approveQAList (created by Connect(approveQAList)) in Connect(approveQAList) (at SceneView.js:9) in SceneView (at StackViewLayout.js:478) in RCTView (at View.js:45) in View (at StackViewLayout.js:477) in RCTView (at View.js:45) in View (at StackViewLayout.js:476) in RCTView (at View.js:45) in View (at createAnimatedComponent.js:151) in AnimatedComponent (at screens.native.js:71) in Screen (at StackViewCard.js:42) in Card (at createPointerEventsContainer.js:26) in Container (at StackViewLayout.js:507) in RCTView (at View.js:45) in View (at screens.native.js:101) in ScreenContainer (at StackViewLayout.js:401) in RCTView (at View.js:45) in View (at StackViewLayout.js:400) in StackViewLayout (at withOrientation.js:30) in withOrientation (at StackView.js:49) in RCTView (at View.js:45) in View (at Transitioner.js:141) in Transitioner (at StackView.js:19) in StackView (at createNavigator.js:57) in Navigator (at createKeyboardAwareNavigator.js:11) in KeyboardAwareNavigator (at createNavigationContainer.js:376) in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34)

**Comment by zhonggithub** [comment]
> Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
> This error is located at: in RNCViewPager (at ViewPagerAndroid.android.js:272) in ViewPagerAndroid (created by Context.Consumer) in RCTView (at View.js:45) in View (created by Context.Consumer) in WithTheme (created by Tabs) in Tabs (at approve/index.js:428) in RCTView (at View.js:45) in View (at approve/index.js:420) in approveQAList (created by Connect(approveQAList)) in Connect(approveQAList) (at SceneView.js:9) in SceneView (at StackViewLayout.js:478) in RCTView (at View.js:45) in View (at StackViewLayout.js:477) in RCTView (at View.js:45) in View (at StackViewLayout.js:476) in RCTView (at View.js:45) in View (at createAnimatedComponent.js:151) in AnimatedComponent (at screens.native.js:71) in Screen (at StackViewCard.js:42) in Card (at createPointerEventsContainer.js:26) in Container (at StackViewLayout.js:507) in RCTView (at View.js:45) in View (at screens.native.js:101) in ScreenContainer (at StackViewLayout.js:401) in RCTView (at View.js:45) in View (at StackViewLayout.js:400) in StackViewLayout (at withOrientation.js:30) in withOrientation (at StackView.js:49) in RCTView (at View.js:45) in View (at Transitioner.js:141) in Transitioner (at StackView.js:19) in StackView (at createNavigator.js:57) in Navigator (at createKeyboardAwareNavigator.js:11) in KeyboardAwareNavigator (at createNavigationContainer.js:376) in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34)

兄弟找到解决办法了吗

**Comment by gugiu** [comment]
https://reactnative.dev/blog/2019/03/12/releasing-react-native-059
ViewPager 移到  @react-native-community/react-native-viewpager 了

**Comment by inkCrazy** [comment]
> > Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
> > This error is located at: in RNCViewPager (at ViewPagerAndroid.android.js:272) in ViewPagerAndroid (created by Context.Consumer) in RCTView (at View.js:45) in View (created by Context.Consumer) in WithTheme (created by Tabs) in Tabs (at approve/index.js:428) in RCTView (at View.js:45) in View (at approve/index.js:420) in approveQAList (created by Connect(approveQAList)) in Connect(approveQAList) (at SceneView.js:9) in SceneView (at StackViewLayout.js:478) in RCTView (at View.js:45) in View (at StackViewLayout.js:477) in RCTView (at View.js:45) in View (at StackViewLayout.js:476) in RCTView (at View.js:45) in View (at createAnimatedComponent.js:151) in AnimatedComponent (at screens.native.js:71) in Screen (at StackViewCard.js:42) in Card (at createPointerEventsContainer.js:26) in Container (at StackViewLayout.js:507) in RCTView (at View.js:45) in View (at screens.native.js:101) in ScreenContainer (at StackViewLayout.js:401) in RCTView (at View.js:45) in View (at StackViewLayout.js:400) in StackViewLayout (at withOrientation.js:30) in withOrientation (at StackView.js:49) in RCTView (at View.js:45) in View (at Transitioner.js:141) in Transitioner (at StackView.js:19) in StackView (at createNavigator.js:57) in Navigator (at createKeyboardAwareNavigator.js:11) in KeyboardAwareNavigator (at createNavigationContainer.js:376) in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34)
> 
> 兄弟找到解决办法了吗

0.59你是怎么解决的

**Comment by zhonggithub** [comment]
> > > Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
> > > This error is located at: in RNCViewPager (at ViewPagerAndroid.android.js:272) in ViewPagerAndroid (created by Context.Consumer) in RCTView (at View.js:45) in View (created by Context.Consumer) in WithTheme (created by Tabs) in Tabs (at approve/index.js:428) in RCTView (at View.js:45) in View (at approve/index.js:420) in approveQAList (created by Connect(approveQAList)) in Connect(approveQAList) (at SceneView.js:9) in SceneView (at StackViewLayout.js:478) in RCTView (at View.js:45) in View (at StackViewLayout.js:477) in RCTView (at View.js:45) in View (at StackViewLayout.js:476) in RCTView (at View.js:45) in View (at createAnimatedComponent.js:151) in AnimatedComponent (at screens.native.js:71) in Screen (at StackViewCard.js:42) in Card (at createPointerEventsContainer.js:26) in Container (at StackViewLayout.js:507) in RCTView (at View.js:45) in View (at screens.native.js:101) in ScreenContainer (at StackViewLayout.js:401) in RCTView (at View.js:45) in View (at StackViewLayout.js:400) in StackViewLayout (at withOrientation.js:30) in withOrientation (at StackView.js:49) in RCTView (at View.js:45) in View (at Transitioner.js:141) in Transitioner (at StackView.js:19) in StackView (at createNavigator.js:57) in Navigator (at createKeyboardAwareNavigator.js:11) in KeyboardAwareNavigator (at createNavigationContainer.js:376) in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at SceneView.js:9) in SceneView (at SwitchView.js:12) in SwitchView (at createNavigator.js:57) in Navigator (at createNavigationContainer.js:376) in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34) This error is located at: in NavigationContainer (at reduxify-navigator.js:61) in NavigatorReduxWrapper (at router.js:104) in RCTView (at View.js:45) in View (created by Portal.Host) in Portal.Host (created by Provider) in ThemeProvider (created by Provider) in LocaleProvider (created by Provider) in Provider (at router.js:101) in RCTView (at View.js:45) in View (created by MenuProvider) in RCTView (at View.js:45) in View (created by MenuProvider) in MenuProvider (at router.js:100) in Router (created by Connect(Router)) in Connect(Router) (at apps/index.js:23) in Provider (at dva.js:17) in Unknown (at renderApplication.js:35) in RCTView (at View.js:45) in View (at AppContainer.js:98) in ChildrenWrapper (at wrapRootComponent.js:9) in _class (at wrapRootComponent.js:8) in Root (at AppContainer.js:112) in RCTView (at View.js:45) in View (at AppContainer.js:115) in AppContainer (at renderApplication.js:34)
> > 
> > 
> > 兄弟找到解决办法了吗
> 
> 0.59你是怎么解决的

npm install @react-native-community/cameraroll @react-native-picker/picker @react-native-community/segmented-control @react-native-community/slider react-native-pager-view
这些依赖包你装了吗？

**Comment by inkCrazy** [comment]
需要安装这么吗？
  "dependencies": {
    "@ant-design/react-native": "^3.1.11",
    "@react-native-community/async-storage": "^1.5.0",
    "axios": "^0.19.0",
    "dayjs": "^1.8.15",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-gesture-handler": "1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-modal": "^11.1.0",
    "react-native-nfc-manager": "^1.2.2",
    "react-native-selfadapt-modal": "^1.1.3",
    "react-native-splash-screen": "^3.1.1",
    "react-native-storage": "^1.0.1",
    "react-navigation": "3.11.0"
  },
