### ISSUE TITLE
3.2.0-Tabs-RNCViewPager was not found in theUIManager

### ISSUE THREAD

**Issue by liuhuo-qiu** [ant-design/ant-design-mobile-rn#684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mutable-mountain-v2lni)

### Steps to reproduce
Tabs 组件在 android     react ：16.8.6   react-native: 0.60.4 版本下，运行react-native run-android , 会提示  RNCViewPager was not found in theUIManager

### What is expected?
运行正常

### What is actually happening?
RNCViewPager was not found in theUIManager

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 16.8.6/0.60.4 |
| System | android |
| Browser | 7.0 |

**Comment by liuhuo-qiu** [comment]
https://codesandbox.io/s/mutable-mountain-v2lni

![image](https://user-images.githubusercontent.com/29687128/68269309-4c17a800-0094-11ea-8b0a-20f106e65327.png)

**Comment by holyhuhaihh** [comment]
我也碰到了

**Comment by bang88** [comment]
需要link一下

**Comment by holyhuhaihh** [comment]
react-native link @ant-design/react-native 后 依然同样错误

**Comment by liuhuo-qiu** [comment]
是版本问题，应该是最新版本的不兼容导致的，我更换为

**Comment by liuhuo-qiu** [comment]
> 需要link一下

是版本问题导致的，我更换为 "react": "^16.6.0" ，"react-native": "0.60.4", "@ant-design/react-native": "3.1.15",  之后就正常了，没有link

**Comment by liuhuo-qiu** [comment]
> 需要link一下

你们判断一下，如果这个不属于bug的话我就把issue关闭了

**Comment by holyhuhaihh** [comment]
已解决 属于ViewPagerAndroid问题  现在无法从'react-native‘ 中导入 将tabs源码中相关引用删除 ,
if (Platform.OS === 'android') 相关屏蔽 就可以了 统一用scrollview来做

**Comment by holyhuhaihh** [comment]
@ant-design/react-native/tabs/lib/tabs/Tabs.js 下      
 // if (_reactNative.Platform.OS === 'android') {
            //     if (_this.viewPager) {
            //         if (animated) {
            //             _this.viewPager.setPage(index);
            //         } else {
            //             _this.viewPager.setPageWithoutAnimation(index);
            //         }
            //         return;
            //     }
            // }

以及
    // if (_reactNative.Platform.OS === 'android') {
            //     return _react2['default'].createElement(
            //         _viewpager2['default'],
            //         { key: '$content', keyboardDismissMode: 'on-drag', initialPage: currentTab, scrollEnabled: _this.props.swipeable || usePaged, onPageScroll: function onPageScroll(e) {
            //                 _this.state.scrollX.setValue(e.nativeEvent.position * _this.state.containerWidth);
            //             }, style: { flex: 1 }, onPageSelected: function onPageSelected(e) {
            //                 var index = e.nativeEvent.position;
            //                 _this.setState({
            //                     currentTab: index
            //                 }, function () {
            //                     // tslint:disable-next-line:no-unused-expression
            //                     _this.props.onChange && _this.props.onChange(tabs[index], index);
            //                 });
            //                 _this.nextCurrentTab = index;
            //             }, ref: function ref(_ref) {
            //                 return _this.viewPager = _ref;
            //             } },
            //         content
            //     );
            // }

**Comment by peisenmann** [comment]
It would be nice to see a fix for this get deployed some time soon.

**Comment by bang88** [comment]
Please see the install instructions of viewPager https://github.com/react-native-community/react-native-viewpager#linking

**Comment by holyhuhaihh** [comment]
亲测楼上 解决方法完美解决 需要添加 额为react-native-community/viewpager
yarn add @react-native-community/viewpager
改源码的方法最终是有bug的 在设置initialPage 的时候安卓会失效

**Comment by chj-damon** [comment]
我安装了viewpager之后安卓直接crash，现在连界面都进不去了。Rn是0.61.5

**Comment by qduck** [comment]
是否支持@react-native-community/viewpager 3.X ？ 使用3.X出现tab无法点击
