### ISSUE TITLE
Modal Alert

### ISSUE THREAD

**Issue by GS-LiuYang** [ant-design/ant-design-mobile-rn#687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
AlertContainer bodyStyle 参数 是 写死的 我无法自定义

### What does the proposed API look like?
modal.alert(tiltle,content:{
style:{},
element:<View/>
})

**Comment by bang88** [comment]
这个API 可能不能这样改了。 用的太多，可以考虑在theme里面添加 alert的主题样式

**Comment by bang88** [comment]
这个建议用Portal写个自定义的 Alert，AlertContainer 要传递太多层次的参数。

**Comment by GTuooa** [comment]
> 这个建议用Portal写个自定义的 Alert，AlertContainer 要传递太多层次的参数。
Portal 有暴露出来吗 ？如果是react的Portal 那么要将其添加到哪个节点？
