### ISSUE TITLE
Error: Looks like you forgot to wrap your root component with `Provider` component from `@ant-design/react-native`.

### ISSUE THREAD

**Issue by luyouwei66** [ant-design/ant-design-mobile-rn#689]
### 产生的问题
点击时间选择组件闪退

### 代码地址
[项目测试地址](https://github.com/luyouwei66/err-rn)

### 各种相关依赖
    "@ant-design/icons-react-native": "^1.0.2",
    "@ant-design/react-native": "^3.2.0",
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-gesture-handler": "^1.5.0",
    "react-navigation": "^3.8.1",
    "react-navigation-stack": "^1.10.3",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.4",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.2",
    "redux-thunk": "^2.3.0"

### 详细错误：
Error: Looks like you forgot to wrap your root component with `Provider` component from `@ant-design/react-native`.

This error is located at:
    in PortalConsumer (created by Context.Consumer)
    in Portal (created by RCModal)
    in RCModal (created by _a)
    in RCTView (created by _a)
    in _a (created by PopupDatePicker)
    in PopupDatePicker (created by Context.Consumer)
    in WithTheme (created by DatePicker)
    in DatePicker (at page.js:18)
    in RCTScrollContentView (at ScrollView.js:1038)
    in RCTScrollView (at ScrollView.js:1178)
    in ScrollView (at page.js:17)
    in page (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:889)
    in RCTView (at StackViewLayout.tsx:888)
    in RCTView (at StackViewLayout.tsx:887)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:975)
    in RCTView (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:384)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:374)
    in PanGestureHandler (at StackViewLayout.tsx:367)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:430)
    in NavigationContainer (at App.js:24)
    in Provider (at App.js:23)
    in Apps (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

**Comment by asoni14593** [comment]
Hi I am facing this issue, could you please help me
![image](https://user-images.githubusercontent.com/42136170/122416194-29ef4700-cfa6-11eb-9be7-558203278f23.png)

**Comment by luyouwei66** [comment]
render() {
    return (
      <Provider>
