### ISSUE TITLE
tabs err in android mobile.  Invariant Violation: View config not found for name RNCViewPager. ios display normally

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design-mobile-rn#694]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
this error happen in honer mobile, not happen in codesandbox
### Steps to reproduce
主要代码按照官网例子走就可以，我的如下：

```javascript
import React from 'react';
import {View, StyleSheet, Text} from 'react-native';
import {Tabs} from '@ant-design/react-native';
export default class ApprovalPendingListScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      tabs: [{title: '已发起'}, {title: '待处理'}, {title: '已处理'}],
    };
  }
  render() {
    const {tabs} = this.state;
    return (
      <View style={styles.container}>
        <Tabs tabs={tabs}>
          <View>
            <Text>Content of First Tab</Text>
          </View>
          <View>
            <Text>Content of Second Tab</Text>
          </View>
          <View>
            <Text>Content of Third Tab</Text>
          </View>
        </Tabs>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
```

### What is expected?
正常显示

### What is actually happening?
error like this:
![image](https://user-images.githubusercontent.com/17545551/68724948-e8433100-05f7-11ea-91d8-f679896dc226.png)

Invariant Violation: View config not found for name RNCViewPager.

This error is located at:
    in NavigationContainer (at Router.js:97)
    in App (at Router.js:122)
    in Router (at modules/index.js:66)
    in Main (at App.js:62)
    in RCTView (created by Portal.Host)
    in Portal.Host (created by Provider)
    in ThemeProvider (created by Provider)
    in LocaleProvider (created by Provider)
    in Provider (at App.js:61)
    in MobXProvider (at App.js:60)
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | "react-native": "0.61.4" |
| System | android 6.0  |
| Browser | 华为荣耀手机 |

**Comment by bang88** [comment]
Please checkout this issue https://github.com/ant-design/ant-design-mobile-rn/issues/684#issuecomment-551350866

**Comment by zhonggithub** [comment]
> Please checkout this issue [#684 (comment)](https://github.com/ant-design/ant-design-mobile-rn/issues/684#issuecomment-551350866)

感谢，怪自己没认真看源码
