### ISSUE TITLE
Tried to register two views with the same name RNCViewPager

### ISSUE THREAD

**Issue by renjinlong** [ant-design/ant-design-mobile-rn#697]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
@ant-design/react-native 使用viewpager1.1.7 另一个组件使用viewpager2.0.1 ，rn0.61.4就会报错说不能注册两个viewpager

### What is expected?
将viewpager放到peerDependencies中

### What is actually happening?
不能正常运行程序

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | react-native 0.61.4 |
| System | android&ios |
| Browser | 非浏览器 |

**Comment by bang88** [comment]
这样每次都要提示用户安装viewpager了 😭

**Comment by bang88** [comment]
如果你用 yarn 的话可以试试在 package.json 里面加上

```
  "resolutions": {
        "@react-native-community/viewpager": "^2.0.1"
  }
```

**Comment by MarkerChen** [comment]
worked

**Comment by xgAnd** [comment]
> 如果你用 yarn 的话可以试试在 package.json 里面加上
> 
> ```
>   "resolutions": {
>         "@react-native-community/viewpager": "^2.0.1"
>   }
> ```

 请教个问题。您说的增加 
 "resolutions": {
        "@react-native-community/viewpager": "^2.0.1"
  }
我理解为是在是在您的项目下的package.json中增加，并重新执行 yaen add 来重新安装node_modules。
但是我在实际的操作中遇到了错误。
![33A2C69D-4FCA-4B33-9919-A53111983A22](https://user-images.githubusercontent.com/27660602/69047792-f4375480-0a36-11ea-880f-0c18a7b66350.png)
![2A35E4C0-1823-4C0C-8D1D-96049A80DCE9](https://user-images.githubusercontent.com/27660602/69048114-a838df80-0a37-11ea-8801-fb0b7f6d6058.png)

但是我在这个报错的文件中并没有找到相关的变量定义。有没有路过的老哥帮忙解惑一下。万分感谢。

**Comment by bang88** [comment]
不是在这里，是在你项目的package.json 里面添加。 然后 在运行 `yarn` 一次。

**Comment by yazhengwang** [comment]
> 不是在这里，是在你项目的package.json 里面添加。 然后 在运行 `yarn` 一次。

嗯，解决了，我是删除node_modules后yarn 才生效的

**Comment by MX8CLUB** [comment]
> 
> 
> 如果你用 yarn 的话可以试试在 package.json 里面加上
> 
> ```
>   "resolutions": {
>         "@react-native-community/viewpager": "^2.0.1"
>   }
> ```

我怎么不行？react-native 0.61.5
"@ant-design/react-native": "^3.2.0"

还是同样报错

**Comment by bang88** [comment]
@MX8CLUB 删掉 node_modules 再重新yarn 一次

**Comment by MX8CLUB** [comment]
> 
> 
> @MX8CLUB 删掉 node_modules 再重新yarn 一次

是我@react-native-community/viewpager不是2.0.1，是3.1.0的。改了重新yarn就好了

**Comment by Evan-Future** [comment]
> 如果你用 yarn 的话可以试试在 package.json 里面加上
> 
> ```
>   "resolutions": {
>         "@react-native-community/viewpager": "^2.0.1"
>   }
> ```

那如果是一直使用npm的话，该如何解决？修改了组件版本后也还是不行。yarn方式有效

**Comment by gaoxiaosong1113** [comment]
我这里按照上面的方法加了这些东西，但是提示其他的错误！

```
Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
```

```
"dependencies": {
    "@ant-design/react-native": "^3.2.0",
    "@react-native-community/async-storage": "^1.7.1",
    "axios": "^0.19.1",
    "babel-plugin-import": "^1.13.0",
    "crypto-js": "^3.1.9-1",
    "moment": "^2.24.0",
    "node-forge": "^0.9.1",
    "pure-render-decorator": "^1.2.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-ezswiper": "^1.3.0",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-image-zoom-viewer": "^2.2.27",
    "react-native-qrcode-svg": "^6.0.3",
    "react-native-reanimated": "^1.5.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-screens": "^2.0.0-alpha.24",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-secharts": "^1.7.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "^10.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.0.3",
    "react-navigation": "^4.0.10",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "rn-fetch-blob": "^0.12.0"
  },
  "resolutions": {
    "@react-native-community/viewpager": "^2.0.1"
   },
```

**Comment by gaoxiaosong1113** [comment]
并且我的 node_modules  project/node_modules/@react-native-community/viewpager 版本号变为2.0.2

**Comment by tourze** [comment]
> 我这里按照上面的方法加了这些东西，但是提示其他的错误！
> 
> ```
> Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
> ```
> 
> ```
> "dependencies": {
>     "@ant-design/react-native": "^3.2.0",
>     "@react-native-community/async-storage": "^1.7.1",
>     "axios": "^0.19.1",
>     "babel-plugin-import": "^1.13.0",
>     "crypto-js": "^3.1.9-1",
>     "moment": "^2.24.0",
>     "node-forge": "^0.9.1",
>     "pure-render-decorator": "^1.2.1",
>     "react": "16.9.0",
>     "react-native": "0.61.5",
>     "react-native-ezswiper": "^1.3.0",
>     "react-native-gesture-handler": "^1.5.3",
>     "react-native-image-zoom-viewer": "^2.2.27",
>     "react-native-qrcode-svg": "^6.0.3",
>     "react-native-reanimated": "^1.5.0",
>     "react-native-router-flux": "^4.2.0",
>     "react-native-safe-area-context": "^0.6.2",
>     "react-native-screens": "^2.0.0-alpha.24",
>     "react-native-scrollable-tab-view": "^1.0.0",
>     "react-native-secharts": "^1.7.0",
>     "react-native-splash-screen": "^3.2.0",
>     "react-native-storage": "^1.0.1",
>     "react-native-svg": "^10.1.0",
>     "react-native-vector-icons": "^6.6.0",
>     "react-native-webview": "^8.0.3",
>     "react-navigation": "^4.0.10",
>     "react-redux": "^7.1.3",
>     "redux": "^4.0.5",
>     "redux-devtools-extension": "^2.13.8",
>     "rn-fetch-blob": "^0.12.0"
>   },
>   "resolutions": {
>     "@react-native-community/viewpager": "^2.0.1"
>    },
> ```

同遇到这个问题，求解决。。。

**Comment by junguoguo2017** [comment]
> > 我这里按照上面的方法加了这些东西，但是提示其他的错误！
> > ```
> > Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
> > ```
> > 
> > 
> > ```
> > "dependencies": {
> >     "@ant-design/react-native": "^3.2.0",
> >     "@react-native-community/async-storage": "^1.7.1",
> >     "axios": "^0.19.1",
> >     "babel-plugin-import": "^1.13.0",
> >     "crypto-js": "^3.1.9-1",
> >     "moment": "^2.24.0",
> >     "node-forge": "^0.9.1",
> >     "pure-render-decorator": "^1.2.1",
> >     "react": "16.9.0",
> >     "react-native": "0.61.5",
> >     "react-native-ezswiper": "^1.3.0",
> >     "react-native-gesture-handler": "^1.5.3",
> >     "react-native-image-zoom-viewer": "^2.2.27",
> >     "react-native-qrcode-svg": "^6.0.3",
> >     "react-native-reanimated": "^1.5.0",
> >     "react-native-router-flux": "^4.2.0",
> >     "react-native-safe-area-context": "^0.6.2",
> >     "react-native-screens": "^2.0.0-alpha.24",
> >     "react-native-scrollable-tab-view": "^1.0.0",
> >     "react-native-secharts": "^1.7.0",
> >     "react-native-splash-screen": "^3.2.0",
> >     "react-native-storage": "^1.0.1",
> >     "react-native-svg": "^10.1.0",
> >     "react-native-vector-icons": "^6.6.0",
> >     "react-native-webview": "^8.0.3",
> >     "react-navigation": "^4.0.10",
> >     "react-redux": "^7.1.3",
> >     "redux": "^4.0.5",
> >     "redux-devtools-extension": "^2.13.8",
> >     "rn-fetch-blob": "^0.12.0"
> >   },
> >   "resolutions": {
> >     "@react-native-community/viewpager": "^2.0.1"
> >    },
> > ```
> 
> 同遇到这个问题，求解决。。。

I'm just like you

**Comment by leeeGreat** [comment]
你们都是说的yarn install，可是用的npm install并不好使啊？

**Comment by leeeGreat** [comment]
> > 如果你用 yarn 的话可以试试在 package.json 里面加上
> > ```
> >   "resolutions": {
> >         "@react-native-community/viewpager": "^2.0.1"
> >   }
> > ```
> 
> 那如果是一直使用npm的话，该如何解决？修改了组件版本后也还是不行。yarn方式有效

这个怎么解决的啊，用的npm，影响远端自动化打包啊

**Comment by ZhangTaoK** [comment]
> > > 我这里按照上面的方法加了这些东西，但是提示其他的错误！
> > > ```
> > > Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
> > > ```
> > > 
> > > 
> > > ```
> > > "dependencies": {
> > >     "@ant-design/react-native": "^3.2.0",
> > >     "@react-native-community/async-storage": "^1.7.1",
> > >     "axios": "^0.19.1",
> > >     "babel-plugin-import": "^1.13.0",
> > >     "crypto-js": "^3.1.9-1",
> > >     "moment": "^2.24.0",
> > >     "node-forge": "^0.9.1",
> > >     "pure-render-decorator": "^1.2.1",
> > >     "react": "16.9.0",
> > >     "react-native": "0.61.5",
> > >     "react-native-ezswiper": "^1.3.0",
> > >     "react-native-gesture-handler": "^1.5.3",
> > >     "react-native-image-zoom-viewer": "^2.2.27",
> > >     "react-native-qrcode-svg": "^6.0.3",
> > >     "react-native-reanimated": "^1.5.0",
> > >     "react-native-router-flux": "^4.2.0",
> > >     "react-native-safe-area-context": "^0.6.2",
> > >     "react-native-screens": "^2.0.0-alpha.24",
> > >     "react-native-scrollable-tab-view": "^1.0.0",
> > >     "react-native-secharts": "^1.7.0",
> > >     "react-native-splash-screen": "^3.2.0",
> > >     "react-native-storage": "^1.0.1",
> > >     "react-native-svg": "^10.1.0",
> > >     "react-native-vector-icons": "^6.6.0",
> > >     "react-native-webview": "^8.0.3",
> > >     "react-navigation": "^4.0.10",
> > >     "react-redux": "^7.1.3",
> > >     "redux": "^4.0.5",
> > >     "redux-devtools-extension": "^2.13.8",
> > >     "rn-fetch-blob": "^0.12.0"
> > >   },
> > >   "resolutions": {
> > >     "@react-native-community/viewpager": "^2.0.1"
> > >    },
> > > ```
> > 
> > 
> > 同遇到这个问题，求解决。。。
> 
> I'm just like you

我是这样解决的：
在你的 package.json 里面升级 viewpager 的版本
```
  "dependencies": {
        "@react-native-community/viewpager": "^4.1.0"
  },
  "resolutions": {
        "@react-native-community/viewpager": "^4.1.0"
  }
```
在通过运行 yarn 即可解决问题。但同样的，我也无法在npm环境下解决这个问题

**Comment by bang88** [comment]
如果你们用的是4.0.0 的话可以自己安装Peer依赖了，4.0 里面没有强制依赖某一个版本。如果还出现这个问题就不是ANT这边的问题了。  关于怎么link相应的模块 去对应的repo查看即可。

**Comment by marlti7** [comment]
我只想知道 npm 怎么解决？ 没问yarn

**Comment by inkCrazy** [comment]
"dependencies": {
    "@ant-design/react-native": "^3.1.11",
    "@react-native-community/async-storage": "^1.5.0",
    "axios": "^0.19.0",
    "dayjs": "^1.8.15",
    "react": "16.8.3",
    "react-native": "0.59.10",
    "react-native-gesture-handler": "1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-modal": "^11.1.0",
    "react-native-nfc-manager": "^1.2.2",
    "react-native-selfadapt-modal": "^1.1.3",
    "react-native-splash-screen": "^3.1.1",
    "react-native-storage": "^1.0.1",
    "react-navigation": "3.11.0"
  },
  我加了"resolutions": {
        "@react-native-community/viewpager": "^2.0.1"
  }也没用
  你们都怎么解决的？

**Comment by inkCrazy** [comment]
> 并且我的 node_modules project/node_modules/@react-native-community/viewpager 版本号变为2.0.2

兄弟你最后怎么解决的？

**Comment by lbx2015** [comment]
我现在还是遇见这个错误，好奇怪，不知道哪里的问题，另外一个问题就没事，这个项目还是有这个问题Tried to register two views with the same name RNCViewPager



怎么解决？，这个报错的项目用的react native 0.59.9
+-- @ant-design/react-native@3.3.0
| `-- @react-native-community/viewpager@1.1.7
+-- @react-native-community/viewpager@2.0.2
`-- react-native-scrollable-tab-view@1.0.0
  `-- @react-native-community/viewpager@2.0.2

下面是我的package.json文件
{
  "name": "JKSmartHome",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "release": "cd android && ./gradlew clean assembleRelease"
  },
  "dependencies": {
    "@ant-design/react-native": "^3.1.9",
    "@ptomasroos/react-native-multi-slider": "^1.0.0",
    "@react-native-clipboard/clipboard": "^1.11.2",
    "@react-native-community/async-storage": "^1.5.0",
    "@react-native-community/cameraroll": "^1.4.0",
    "@react-native-community/datetimepicker": "^3.0.1",
    "@react-native-community/slider": "^2.0.0",
    "@react-native-community/viewpager": "2.0.2",
    "abortcontroller-polyfill": "^1.7.5",
    "jcore-react-native": "^1.9.9",
    "jpush-react-native": "^2.9.9",
    "prop-types": "latest",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-actionsheet": "^2.4.2",
    "react-native-amap-geolocation": "^1.2.0",
    "react-native-audio": "^4.3.0",
    "react-native-camera": "^3.40.0",
    "react-native-chart-kit": "^3.10.0",
    "react-native-circular-slider": "^1.0.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-device-info": "^10.7.0",
    "react-native-drag-sort": "^2.4.2",
    "react-native-easy-toast": "^1.2.0",
    "react-native-fs": "^2.13.2",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-crop-picker": "^0.25.0",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-image-picker": "^1.0.2",
    "react-native-image-zoom-viewer": "^2.2.27",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-md5": "^1.0.0",
    "react-native-motion-slider": "^1.0.3",
    "react-native-picker": "^4.3.7",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-slider": "^0.11.0",
    "react-native-sound": "^0.11.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-switch-pro": "^1.0.5",
    "react-native-tcp-socket": "^1.4.0",
    "react-native-udp": "^2.7.0",
    "react-native-webview": "^11.4.0",
    "react-native-wifi-reborn": "^4.5.0",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.1.0",
    "redux": "^4.0.1",
    "redux-actions": "^2.6.5",
    "redux-thunk": "^2.3.0",
    "victory-native": "^30.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "@types/react-native": "^0.64.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "jetifier": "^1.6.5",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3",
    "redux-devtools": "^3.5.0",
    "redux-logger": "^3.0.6"
  },
  "jest": {
    "preset": "react-native"
  },
  "resolutions": {
    "@react-native-community/viewpager": "2.0.2"
  },
  "overrides": {
    "@react-native-community/viewpager": "2.0.2"
  }
}

**Comment by 1uokun** [comment]
> 我现在还是遇见这个错误，好奇怪，不知道哪里的问题，另外一个问题就没事，这个项目还是有这个问题Tried to register two views with the same name RNCViewPager
> 
> 怎么解决？，这个报错的项目用的react native 0.59.9 +-- @ant-design/react-native@3.3.0 | `-- @react-native-community/viewpager@1.1.7 +-- @react-native-community/viewpager@2.0.2 `-- react-native-scrollable-tab-view@1.0.0 `-- @react-native-community/viewpager@2.0.2

项目版本太老了，可提供付费解答
