### ISSUE TITLE
Search Bar Cancel Button does not hide itself when pressed 按取消键只清空，无法把取消键藏起来

### ISSUE THREAD

**Issue by 1kvnlee** [ant-design/ant-design-mobile-rn#698]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/kvnlee777/antd-rn-issue](https://github.com/kvnlee777/antd-rn-issue)

### Steps to reproduce
yarn ios

### What is expected?
Cancel button should hide itself when press
按取消键应该要能藏起来

### What is actually happening?
Cancel button only clears the search field but does not hide itself when press
按取消键只清空，无法把取消键藏起来

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 0.61.4 |
| System | MacOS Catalina 10.15.1 |
| Browser | Google Chrome 78.0.3904.97 (Official Build) (64-bit) |

**Comment by bang88** [comment]
By design. Sorry.
