### ISSUE TITLE
Modal transparent 参数无效

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design-mobile-rn#701]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/modal-cn/](https://rn.mobile.ant.design/components/modal-cn/)

### Steps to reproduce
使用trasnsparnt参数看背景

### What is expected?
使用trasnsparnt参数看背景

### What is actually happening?
使用trasnsparnt参数看背景

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 0.61.4 |
| System | win10 |
| Browser | 无 |

**Comment by ouzhou** [comment]
@bang88 官方案例的modal的第一个按钮就是transparent为true, 但是仍然有背景
这个就不需要再提供复现链接了吧

[官方的地址](https://rn.mobile.ant.design/components/modal-cn/)

**Comment by bang88** [comment]
仔细看代码 transparent 默认是false的。要透明的话自己设置为true 你可以改一下 transparent: false 那个例子看看

**Comment by ouzhou** [comment]
![image](https://user-images.githubusercontent.com/7693866/69314022-0fd87000-0c6e-11ea-80f9-e664982b5a6d.png)

仔细看 这个transparent是true的 我没说错呢  ：（

[sad box地址](https://codesandbox.io/s/modal-o9vpu?from-embed)
App.js第118行

**Comment by bang88** [comment]
:cry: 我刚看的是下面那个，你试试...

**Comment by ouzhou** [comment]
还有就是这个东西能顺带设置一下statusbar吗，感觉刘海屏的头秃噜了一块没遮罩背景很奇怪

**Comment by bang88** [comment]
之前有不同的需求..

如果需要自定义太多的可以自己写一个，可以用 Portal 来创建一个自定义的层

**Comment by ouzhou** [comment]
我的意思是刘海屏的耳朵遮罩层是遮不到的，就很丑，需要同时把statusbar处理一下

扯远了，这个transparent是真的无效。。。

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/69315225-fdac0100-0c70-11ea-9e21-0a8e3dc4cdc2.png)
可能不是你要的那种透明吧。

**Comment by ouzhou** [comment]
。。。那这个参数能搞成透明度吗 0-1范围是数字

**Comment by bang88** [comment]
@ouzhou :cry: 只是做了特殊的样式（mobile的版本就有了吧）

**Comment by ouzhou** [comment]
我就是在rn上试的，transparent无效

**Comment by bang88** [comment]
最近翻看了之前的代码。 这个属性确实是乱用了，误导了大家，他的本意可能是居中显示Modal，正常这个属性应该控制Modal的背景为透明的。

后面会去掉这个属性，改成其他名字。
