### ISSUE TITLE
Stepper 步进器readOnly=true加减号也会禁用

### ISSUE THREAD

**Issue by zhishuai** [ant-design/ant-design-mobile-rn#704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/stepper-cn/](https://rn.mobile.ant.design/components/stepper-cn/)

### Steps to reproduce
Stepper 步进器
设置属性 readOnly=true
加减号也会禁用

### What is expected?
按照文档描述，readOnly=true 只是禁用 TextInput 不应该禁用加减号.

### What is actually happening?
按照文档描述，readOnly=true 只是禁用 TextInput 不应该禁用加减号.

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 16.9.0/0.61.3 |
| System | mac |
| Browser | 谷歌 |

**Comment by bang88** [comment]
By design
