### ISSUE TITLE
TS 下根本跑不起来 antui  很多地方都报错

### ISSUE THREAD

**Issue by zhangchenna** [ant-design/ant-design-mobile-rn#71]
这是配置文件信息

`"dependencies": {
    "@types/react-native-drawer-layout": "^1.3.4",
    "antd-mobile-rn": "^2.2.1",
    "axios": "0.18.0",
    "big-integer": "1.6.31",
    "jshashes": "1.0.7",
    "lodash": "4.17.10",
    "mobx": "5.0.3",
    "mobx-react": "5.2.3",
    "prop-types": "15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-drawer-layout": "^2.0.0",
    "react-navigation": "2.8.0",
    "teaset": "0.5.9"
  },
  "devDependencies": {
    "@types/jest": "23.1.6",
    "@types/prop-types": "15.5.3",
    "@types/react": "16.4.6",
    "@types/react-native": "0.55.5",
    "@types/react-test-renderer": "16.0.1",
    "babel-core": "6.26.3",
    "babel-jest": "23.4.0",
    "babel-plugin-import": "1.8.0",
    "babel-plugin-transform-decorators-legacy": "1.3.5",
    "babel-plugin-transform-remove-console": "6.9.4",
    "babel-preset-env": "1.6.1",
    "babel-preset-react-native": "4.0.0",
    "eslint": "4.0.0",
    "jest": "23.4.1",
    "prettier": "^1.13.7",
    "react-test-renderer": "16.3.1",
    "ts-jest": "23.0.0",
    "typescript": "2.4.0"
  },`

`{
  "include": [
    "app/*",
    "app/**/*",
    "typings/index.d.ts"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ],
  "compilerOptions": {
    "typeRoots": [
      "node_modules/@types"
    ],
    "strictPropertyInitialization": false,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "strictFunctionTypes": false,
    "module": "esnext",
    "strict": true,
    "rootDir": "./",
    "target": "es6",
    "allowJs": true,
    "jsx": "react-native",
    "outDir": "./dist",
    "sourceMap": false,
    "noImplicitAny": true,
    "types": [
      "react",
      "react-native"
    ],
    "lib": [
      "dom",
      "es5",
      "es6",
      "es7",
      "es2015.promise"
    ],
    "pretty": true
  },
  "compileOnSave": false
}
`

**Comment by bang88** [comment]
Please checkout `2.3.0`
