### ISSUE TITLE
Expo demo app could not open

### ISSUE THREAD

**Issue by liudonghua123** [ant-design/ant-design-mobile-rn#711]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/433259/50051494-1c934080-014e-11e9-82b2-b18c6b727443.png](https://user-images.githubusercontent.com/433259/50051494-1c934080-014e-11e9-82b2-b18c6b727443.png)

### Steps to reproduce
在安装有Expo客户端的IPhone手机上扫码，提示 There was a problem......
![](https://user-images.githubusercontent.com/433259/50051494-1c934080-014e-11e9-82b2-b18c6b727443.png)

### What is expected?
可以正常打开

### What is actually happening?
不能打开

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | n.a. |
| System | n.a. |
| Browser | n.a. |

**Comment by bang88** [comment]
好麻烦，expo 升级client后就不能用了

**Comment by liudonghua123** [comment]
我发现要想独立运行rm-kitchen-sink非常困难，能不能提供一种友好、独立的方式来运行示例程序呢

**Comment by bang88** [comment]
@liudonghua123 现在运行有什么问题吗

**Comment by liudonghua123** [comment]
@bang88 我想使用expo的snack来运行rn-kitchen-sink，首先rn-kitchen-sink没有package.json依赖项不明确，我只能使用上一层的package.json里面的依赖，其次依赖很多rn-kitchen-sink外部文件夹components里面的js文件，我把外部的components合并到rn-kitchen-sink下面的components里面，发现还需要tsc编译生成js才行...
我想要的仅仅是可以方便点在expo或者expo snack中展示ant-design-mobile-rn的示例，如果示例中一定要很方便的链接正在开发的components中的组件，可以使用npm link来实现吧

**Comment by bang88** [comment]
@liudonghua123 在expo分支

**Comment by liudonghua123** [comment]
嗯，我看到 `expo` 分支了，但看代码变化不大，`rn-kitchen-sink` 还是会依赖于外面的一些文件，如果直接把 `demoList.js` 中的 `require('../components/picker/demo/basic')` 替换为 `require('@ant-design/react-native/lib/picker/demo/basic')` ，其实也还是有问题的——`@ant-design/react-native`中没有打包`data.json`，例外 react-navigation 已经变化很多了，现在这个demo里面还在使用1.x非常古老了，现在都是4.x、5.x了。

希望可以做到类似于 https://github.com/callstack/react-native-paper/tree/master/example https://github.com/akveo/kittenTricks 这样相对独立的示例。

**Comment by bang88** [comment]
直接require 代码是为了开发的时候 方便调试。

**Comment by liudonghua123** [comment]
嗯，个人感觉更优雅的方式是 使用 npm link，这样就可以 require('../components/picker/demo/basic') 替换为 require('@ant-design/react-native/lib/picker/demo/basic'), 代码耦合性较低

**Comment by bang88** [comment]
话说 react-native 在这方面做的真的很麻烦，开发别的lib的时候也是用npm link来做的。 各有利弊吧，如果你想尝试升级 导航，或者重新规划一下这个demo也可以。

**Comment by liudonghua123** [comment]
嗯，我尝试着修改一下代码来分离一下示例程序 rn-kitchen-sink. 😃

**Comment by vee2046** [comment]
> 嗯，我尝试着修改一下代码来分离一下示例程序 rn-kitchen-sink. 😃

老大，有运行起来的方法吗。我就想看看这个UI效果。。。

**Comment by bang88** [comment]
直接运行iOS 或者Android都可以看效果的啊……

Wei Wu <notifications@github.com>于2019年12月24日 周二13:20写道：

**Comment by vee2046** [comment]
@bang88 有快速的方法吗，expo client最新版只能打开界面，然后就没反应了
您意思是要把项目clone，然后各种安装后运行起来看吗？

**Comment by bang88** [comment]
嗯嗯 我理解错你的意思了

Wei Wu <notifications@github.com>于2019年12月24日 周二13:31写道：

**Comment by bang88** [comment]
@liudonghua123 你有在看吗？

**Comment by liudonghua123** [comment]
@bang88 我尝试着去修改，一直没有成功，依赖关系有点多，而且有一些和新的react native库不怎么兼容，我看根目录里面package.json 里面的依赖能不能清理一下，有很多看上去是自己私有的类库 @bang88/* bisheng* ，这些能不能清理或者相关代码不要放在核心依赖里面？

**Comment by bang88** [comment]
这种倒还好，只是以前版本的数据 方便web 预览的时候弄的

liudonghua <notifications@github.com>于2019年12月28日 周六22:55写道：

**Comment by bang88** [comment]
后面没有expo的预览了。 升级到62后 example可以本地直接预览
