### ISSUE TITLE
Version 2.x Documentation page not loading

### ISSUE THREAD

**Issue by lovelyKarthi** [ant-design/ant-design-mobile-rn#712]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Version 2.x Documentation page not loading: 

This site can’t provide a secure connection
2x.rn.mobile.ant.design uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### What does the proposed API look like?
web protocol issue, please fix

**Comment by bang88** [comment]
2.x no longer maintenance  please upgrade to the latest version.  Thank you .
