### ISSUE TITLE
TypeError: undefined is not an object _reactNative.TabBarIOS.Item

### ISSUE THREAD

**Issue by liudonghua123** [ant-design/ant-design-mobile-rn#716]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://snack.expo.io/@liudonghua/ant-design-antd-mobile-samples-rn-expo](https://snack.expo.io/@liudonghua/ant-design-antd-mobile-samples-rn-expo)

### Steps to reproduce
1. 使用expo init 一个blank项目
2. 复制https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo的代码到新的项目里
3. 更新相应的一些依赖

或者在expo的snack中导入 https://github.com/ant-design/antd-mobile-samples/tree/master/rn-expo 这里的代码，更新相应的一些依赖库

### What is expected?
rn-expo 这个 demo可以正常运行

### What is actually happening?
提示 TypeError: undefined is not an object _reactNative.TabBarIOS.Item

![image](https://user-images.githubusercontent.com/2276718/70593476-360f8100-1c18-11ea-8e97-2ce751524c91.png)

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | ~16.9.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by liudonghua123** [comment]
Finally, I found it was the old dependences react-native issue, see more on https://github.com/facebook/react-native/issues/24781, https://github.com/expo/expo/issues/4560.

I should not use the out of date code and `antd-mobile-rn` dependences.

**Comment by bang88** [comment]
Yep. Please switch to the latest one
