### ISSUE TITLE
TabBar 与Tabs

### ISSUE THREAD

**Issue by MX8CLUB** [ant-design/ant-design-mobile-rn#718]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tabs的tabBarPosition为Top时，下面会出现一条无法消失的灰色横线，TabBar的上面会出现一条无法消失的灰色横线

### What does the proposed API look like?
现希望能够提供参数删除横线

**Comment by bang88** [comment]
@MX8CLUB 所有样式均支持通过styles 覆盖，具体的你可以inspect一下是哪一个样式。

**Comment by MX8CLUB** [comment]
> 
> 
> @MX8CLUB 所有样式均支持通过styles 覆盖，具体的你可以inspect一下是哪一个样式。

找到样式了，我该怎么覆盖呢？直接修改代码？
