### ISSUE TITLE
how to support custom styles with checkbox

### ISSUE THREAD

**Issue by ImHeXin** [ant-design/ant-design-mobile-rn#719]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. The style of check-square icon is too simple to satisfy users. Maybe users want check-circle icon, or custom icon, but I found no API for this. 
2.The location of check icon is in the left in default. Maybe users want in the right, or other location, but I found no API for this, too.

### What does the proposed API look like?
    <Checkbox.CheckboxItem
                                checked={...}
                                extra={...}
                                key={...}
                                defaultIcon={<CustomDefaultIcon />}       // hope to add
                                checkedIcon={<CustomCheckedIcon/>}   // hope to add
                                iconLocation='right'                              // hope to add
                                onChange={(event: any) => { ... }}>
                                {content}
    </Checkbox.CheckboxItem>

**Comment by bang88** [comment]
Sorry. there is no options for such use case. You can implement a customized Checkbox use YOUR  own icon

**Comment by 1uokun** [comment]
> @bang88 @ImHeXin I have the same requirement. I need to implement rounded checkbox instead of squared one. Would be really helpful if its added as a feature request.

https://github.com/ant-design/ant-design-mobile-rn/tree/checkbox/radio-feature 

join us
