### ISSUE TITLE
扫二维码查看效果存在缺陷性的bug,会不停的重复提交渲染页面，无法显示出正常的效果

### ISSUE THREAD

**Issue by lazy1523** [ant-design/ant-design-mobile-rn#72]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
OS X 10.13.3 Chrome 

### Reproduction link
[http://new-issue.ant.design?repo=ant-design-mobile-rn](http://new-issue.ant.design?repo=ant-design-mobile-rn)

### Steps to reproduce
Chrome 中 F12 选择任意手机模拟器

### What is expected?
正常的InputItem效果

### What is actually happening?
会不停的重复提交网络请求，而无法渲染页面，无法显示出正常的效果

**Comment by Meow-z** [comment]
Android 7.0 Mi Note 2 QQ浏览器最新版本 也存在相同的问题。

**Comment by linrz** [comment]
Android 8.1 MI 8 任意浏览器 也存在相同的问题，扫描二维码后会不停的重复提交网络请求。

**Comment by bang88** [comment]
预览效果3.0会重新弄一下，请 track #119
