### ISSUE TITLE
toast duration is not work in Android but ios is ok

### ISSUE THREAD

**Issue by yqyily** [ant-design/ant-design-mobile-rn#721]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/toast-cn/#components-toast-demo-basic](https://rn.mobile.ant.design/components/toast-cn/#components-toast-demo-basic)

### Steps to reproduce
import React, {Component} from 'react';
import {View, Text, StyleSheet, TouchableHighlight} from 'react-native';
import {portal, Provider, Toast} from '@ant-design/react-native';

export default function UserIndex() {
    const showToast = () => {
        Toast.info("duration props not work in Android, however ios is ok",5);
    }
    return(
        <Provider>
            <View>
                <TouchableHighlight
                    onPress={showToast}>
                    <Text>Toast</Text>
                </TouchableHighlight>
            </View>
        </Provider>

    )
}
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },

});

### What is expected?
duration prop is ok

### What is actually happening?
duration prop is not work

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 16.9.0/0.61.5 |
| System | Android |
| Browser | none |

**Comment by bang88** [comment]
Cannot reproduce it on my Pixel 3.

**Comment by WozHuang** [comment]
我开启 debug 的时候 settimeout 有问题，关掉 debug 就正常了
