### ISSUE TITLE
当键盘出现的时候,Modal视图可以做成自动调节到中间吗?

### ISSUE THREAD

**Issue by Magrider** [ant-design/ant-design-mobile-rn#722]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当键盘出现的时候,Modal视图可以做成自动调节到中间吗? 有的时候modal做大了,键盘出现后会把modal界面遮住. 如果能自动调节成顶端和键盘的中间就完美了!
各位大佬辛苦啦!

### What does the proposed API look like?
Modal

**Comment by bang88** [comment]
这个没想好 怎么做合适点。

**Comment by 1uokun** [comment]
要考虑到更新依赖包代码后 用户的远古老代码样式仍能正常的话很难作出改变。
**建议只复用`RCModal`内的动画效果，内部弹框自己写**

just like:
```jsx
import RCModal from '@ant-design/react-native/lib/modal/ModalView'



<RCModal style={[{flex:1, justifyContent:'center', alignItems:'center', backgroundColor:'transparent'}]}
         visible={true}
>
 <KeyboardAvoidingView behavior="padding" enabled={Platform.OS==="ios"}>
  <View style={[styles.innerContainer]} ref={this.saveRoot}>
   <Text style={[styles.header]}>

     {title}

   </Text>
   <View style={[styles.body]}>

     {children}

   </View>

   {footerDom}

   {closableDom}

   </View>
  </KeyboardAvoidingView>
</RCModal>
```
