### ISSUE TITLE
InputItem 可以覆盖container样式

### ISSUE THREAD

**Issue by wkeylin** [ant-design/ant-design-mobile-rn#726]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前InputItem组件container的样式无法覆盖，会有paddingRight、marginLeft、borderBottom存在，以前的版本可以覆盖，不知道什么时候开始就不行了

### What does the proposed API look like?
提供containerStyle属性覆盖

**Comment by bang88** [comment]
请通过自定义 styles 覆盖 container的值

**Comment by mack-wang** [comment]
确实存在@wkeylin 所说的问题，无法通过自定义 styles 覆盖 container的值，想消除container的borderBottom，就是无法实现，所以只能放弃使用InputItem

**Comment by 1uokun** [comment]
> 确实存在@wkeylin 所说的问题，无法通过自定义 styles 覆盖 container的值，想消除container的borderBottom，就是无法实现，所以只能放弃使用InputItem

```jsx
<InputItem 
  styles={{
    container: {
      paddingRight:0,
      marginLeft:0,
      borderBottom:0
    },
  }}
/>
```
试一试呢🥺

**Comment by mack-wang** [comment]
> 

![image](https://user-images.githubusercontent.com/21222317/144199259-f874050c-26e1-4045-8e84-7db9c58ad6a6.png)

已尝试你提供的代码，paddingRight，marginLeft已失效，但是borderBottom，borderBottomWidth都无效。
我的RN版本0.66，ant design版本4.2.0，也许老的ant design版本可以，但至少4.2.0还有问题

**Comment by Vladimirrr666** [comment]
still cannot resolve this problem  "@ant-design/react-native": "^5.0.5",
