### ISSUE TITLE
The props `style` and `accept` on ImagePicker don't do anything

### ISSUE THREAD

**Issue by gianpaj** [ant-design/ant-design-mobile-rn#73]
https://github.com/ant-design/ant-design-mobile-rn/blob/b553adbb691d36067be1f01ec49ff363505e0e60/components/image-picker/PropsType.tsx#L4-L12

See https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/image-picker/ImageRoll.native.tsx

Please also update the docs accordingly

**Comment by gianpaj** [comment]
@bang88 , may I ask why this issue was closed? those props are not connected or used in the imageRoll component

**Comment by bang88** [comment]
Sorry I didn't get what do you want. If you want remove it or fix it please
let me know. I will add it back.

Gianfrancø Palumbo <notifications@github.com>于2018年10月21日 周日00:45写道：

**Comment by gianpaj** [comment]
Hi Qibang,

I'll try to rephrase my concerns. Let me know if I'm explaining it better, or what exactly it's confusing.

There's not only one way to go here.
We can either add the functionality for those [props](https://reactjs.org/docs/components-and-props.html), or we can remove them from the PropType files.

I can remove those, though it depends on the maintainers of the project how much functionality do they want these Components (ImagePicker) to have, etc.

Cheers,
Gianfranco

**Comment by bang88** [comment]
@gianpaj Ok then just remove it from the source file if they don't in use. Thanks PR are always welcome
