### ISSUE TITLE
Modal.alert(title, message, actions?, platform?).close()不能生效

### ISSUE THREAD

**Issue by 37Jayden** [ant-design/ant-design-mobile-rn#732]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/modal-cn/](https://rn.mobile.ant.design/components/modal-cn/)

### Steps to reproduce
Modal alert显示之后，不能手动close

### What is expected?
能手动close

### What is actually happening?
Modal.alert(title, message, actions?, platform?)返回的是undefined

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 0.57.4 |
| System | android |
| Browser | android |

---
Modal.alert(title, message, actions?, platform?)返回的是undefined，我想要在跳转到下个页面关闭这个modal，现在不能手动关闭

**Comment by Iongtao** [comment]
这个问题没有后续的吗，现在我也需要主动关闭alert的需求，该怎么实现？

**Comment by 1uokun** [comment]
文档已更新； 需要用到`Portal.remov`；
```jsx
import { Modal, Portal } from '@ant-design/react-native'

const key = Modal.alert({})

// close the Modal.alert
Portal.remove(key)
```

**Comment by 1uokun** [comment]
文档已更新

**Comment by 1uokun** [comment]
文档已更新发自我的 iPhone在 2024年8月6日，17:23，桃子拌饭 ***@***.***> 写道：﻿
这个问题没有后续的吗，现在我也需要主动关闭alert的需求，该怎么实现？
