### ISSUE TITLE
InputItem not honoring textAlign

### ISSUE THREAD

**Issue by lgyeresi** [ant-design/ant-design-mobile-rn#736]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/lgyeresi/pen/bGNLrLa](https://codepen.io/lgyeresi/pen/bGNLrLa)

### Steps to reproduce
              <InputItem
                value={this.state.jobName}
                style={styles.inputItem}
                onChange={value => this.onChange('jobName', value)}>
                <Text>Job Name</Text>
              </InputItem>

    const styles = StyleSheet.create({
      inputItem: {
        textAlign: 'right',
        backgroundColor: 'red',
      },

the background color will be red, however the textAlign property will not be honored. The input is still left-aligned.

### What is expected?
Text input is aligned to the right

### What is actually happening?
Text input is aligned to the left

| Environment | Info |
|---|---|
| antd | undefined |
| React | 0.61 |
| System | 3.2.2 |
| Browser | iOS 12.4 |

**Comment by bang88** [comment]
@lgyeresi Sorry about that. 2.x are no longer maintained. Please upgrade to the latest version

Thank you
