### ISSUE TITLE
tabs内嵌FlatList时，无法阻止滑动事件的冒泡

### ISSUE THREAD

**Issue by truejiang** [ant-design/ant-design-mobile-rn#737]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/truejiang/full/qBEoqQm](https://codepen.io/truejiang/full/qBEoqQm)

### Steps to reproduce
tabs开启滑动切换时，标签页内容有横向滑动的FlatList，因为无法阻止冒泡，所以FlatList无法正常使用。

### What is expected?
横向滑动FlatList时，tabs不切换

### What is actually happening?
tabs开启滑动切换时，标签页内容有横向滑动的FlatList，因为无法阻止冒泡，所以FlatList无法正常使用。

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | react 16.8.3 / react-native 0.59.10 |
| System | Android |
| Browser | ReactNative APP |

**Comment by truejiang** [comment]
解决了，把swipeable 用一个状态去控制，然后给需要冒泡的组件上添加了一个onTouchStart 和 onTouchCancel去切换 这个状态值的就可以了。
大概原理就是触摸到需要冒泡滑动的组件时，把tabs的滑动关掉，触摸结束时，再重新启动，有点取巧，希望对其他人有帮助，谢谢。

**Comment by zinete** [comment]
> 解决了，把swipeable用一个状态去控制，然后给需要冒泡的组件上添加了一个onTouchStart和onTouchCancel去切换这个状态值的就可以了。
> 大概原理就是触摸到需要冒泡滑动的组件时，把tabs的滑动关掉，触摸结束时，再重新启动，有点取巧，希望对其他人有帮助，谢谢。

老哥有么有示例代码参考下。我也遇到这个问题了
