### ISSUE TITLE
Modal自定义样式的问题

### ISSUE THREAD

**Issue by masteronelight** [ant-design/ant-design-mobile-rn#746]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
react native官网文档没有提供自定义Modal样式的属性，但在实际使用中测试bodyStyle是可以生效的。

### What does the proposed API look like?
希望可以完善文档

**Comment by bang88** [comment]
谢谢你的提议，很多组件的样式都可以覆盖，所以没有一一列举出来
