### ISSUE TITLE
SwipeAction 滑动操作组件隐藏操作按钮问题

### ISSUE THREAD

**Issue by usedlife** [ant-design/ant-design-mobile-rn#763]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/swipe-action/demo/basic.tsx](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/swipe-action/demo/basic.tsx)

### Steps to reproduce
1. 将Item向左/右滑动在屏幕一侧唤出操作。
2. 点击空白处无法隐藏该Item唤出的操作。

### What is expected?
期望如[规则](https://rn.mobile.ant.design/components/swipe-action-cn/#%E8%A7%84%E5%88%99)描述：
> 点击任意按钮之外处或往回滑动该列表可隐藏操作。

### What is actually happening?
点击任意按钮之外不可隐藏该列表唤出的操作。

| Environment | Info |
|---|---|
| antd | 3.2.0 |
| React | 16.8.3/0.59.8 |
| System | Mac os 10.14.6 |
| Browser | chrome 80.0.3987.116（正式版本）（64 位） |

---
[官方组件地址](https://rn.mobile.ant.design/components/swipe-action-cn/)

**Comment by bang88** [comment]
源码里面使用了 https://github.com/dancormier/react-native-swipeout ，你去那边看看有没有这些配置
