### ISSUE TITLE
列表项组件的箭头图标显示异常

### ISSUE THREAD

**Issue by guhuangjin** [ant-design/ant-design-mobile-rn#765]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/guhuangjin/react-native-test/tree/master/AwesomeProject](https://github.com/guhuangjin/react-native-test/tree/master/AwesomeProject)

### 环境
  1.  "@ant-design/react-native": "3.1.15",
  2.  "react": "16.8.6",
  3.  "react-native": "0.60.5",

### 操作步骤
1. 在react-native最简单的演示项目AwesomeProject中，把入口App.js修改为以下内容，来测试Item的箭头显示。
项目地址：https://github.com/guhuangjin/react-native-test/tree/master/AwesomeProject
```
    <View>
      <List>
        <Item disabled extra="箭头向右" arrow="horizontal" onPress={() => { }}>
          标题文字
        </Item>
      </List>
    </View>
```

2. 在android上测试发现箭头显示异常，如图：

https://github.com/guhuangjin/react-native-test/blob/master/AwesomeProject/public/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20200302111446.png

### What is expected?
List.Item的箭头图标正常

### What is actually happening?
List.Item的箭头图标显示异常

| Environment | Info |
|---|---|
| antd | 3.1.15 |
| React | 16.9.0 |
| System | Android 9 |
| Browser | react-native：“ 0.61.5” |

**Comment by bang88** [comment]
看不到图片

**Comment by zhyafe** [comment]
@ant-design/icons-react-native 版本用1.0.2 然后link下

**Comment by zhyafe** [comment]
react-native link @ant-design/icons-react-native

**Comment by guhuangjin** [comment]
我开放了我的项目，现在应该能看到图片了。 

> react-native链接@ ant-design / icons-react-native

这个方法也没有效果

**Comment by nm-1216** [comment]
文档的升级指南里面用
react-native link @ant-design/react-native 这个命令加载字体.

**Comment by nm-1216** [comment]
> 文档的升级指南里面用
> react-native link @ant-design/react-native 这个命令加载字体.

只不过 图标乱七八糟的,对应不上

**Comment by bang88** [comment]
抱歉 icons 那边单独发布了，这边没有更新文档 
`icons` 2.0.0 有不兼容的icon，修复了之前的icon名称错误的情况，但是项目里面也可以继续使用 1.x，只是 rn > 0.60 以上会提示auto link的警告。

**Comment by bang88** [comment]
@guhuangjin link（rn < 60) 后需要重启安装到设备才行正确显示， xcode 或者 Android studio 。

另外我更新了 icons 到2.0.0，xcode run 后， 没有发现你说的这个问题，看下图：


![image](https://user-images.githubusercontent.com/433259/76159656-baad6500-615d-11ea-9ed0-88f851efc57d.png)

**Comment by bang88** [comment]
> > 文档的升级指南里面用
> > react-native link @ant-design/react-native 这个命令加载字体.
> 
> 只不过 图标乱七八糟的,对应不上

😢 因为用的就是RN的组件在web上面直接渲染，所以有点乱。 可以来个PR单独修改一下demo 如果可以的话。

**Comment by guhuangjin** [comment]
通过下面两步解决了问题：
* npm i @ant-design/icons-react-native@1.0.2
* react-native link @ant-design/icons-react-native

**Comment by wubo49494** [comment]
![image](https://user-images.githubusercontent.com/48856419/76377812-d47dc080-6386-11ea-920c-c5728c504ebf.png)
麻烦问下，RN 0.61.5  连接antd 而不是 icon 的话可以正常使用了，但是会出现上面图片的代码，说componentWillreceptprops 过时了

**Comment by BianXuerui** [comment]
![image](https://github.com/ant-design/ant-design-mobile-rn/assets/50104688/d1ef7017-27fd-4805-beb7-938c1bdfdc8d)
箭头显示异常
"@ant-design/icons-react-native": "2.2.1",
"@ant-design/react-native": "4.0.2",
"react-native": "0.62.2",
