### ISSUE TITLE
icon组件显示的图标，名称和图标对不上，import显示成别的图标了！

### ISSUE THREAD

**Issue by qduck** [ant-design/ant-design-mobile-rn#772]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/qduck/xio_mes_app.git](https://github.com/qduck/xio_mes_app.git)

### Steps to reproduce
查看页面即可

### What is expected?
可能是图标和react-native-vector-icons冲突导致

### What is actually happening?
图标名称和显示对应不上

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.61.5 |
| System | Android |
| Browser | ReactNative  APP |

**Comment by Jeepeng** [comment]
same issue

**Comment by Jeepeng** [comment]
发现`react-native link @ant-design/icons-react-native`无法自动复制fonts文件，
需要手动复制`node_modules/@ant-design/icons-react-native/fonts`到`app/android/app/src/main/assets/fonts`更新一下fonts文件

**Comment by bang88** [comment]
> 发现`react-native link @ant-design/icons-react-native`无法自动复制fonts文件，
> 需要手动复制`node_modules/@ant-design/icons-react-native/fonts`到`android/app/src/main/assets/fonts`更新一下fonts文件

`react-native link @ant-design/react-native` 试试

**Comment by qduck** [comment]
link应该没有问题，因为图标都是出来的，我觉得应该是和react-native-vector-icons组件图标冲突的原因。临时的话，可以删除react-native-vector-icons link的图标即可解决。

**Comment by Jeepeng** [comment]
> link应该没有问题，因为图标都是出来的，我觉得应该是和react-native-vector-icons组件图标冲突的原因。临时的话，可以删除react-native-vector-icons link的图标即可解决。

解决方案我说了，手动复制node_modules/@ant-design/icons-react-native/fonts到android/app/src/main/assets/fonts更新一下fonts文件

**Comment by qduck** [comment]
我重新安装@ant-design/icons-react-native  
1. yarn install @ant-design/icons-react-native
2. 手动复制node_modules/@ant-design/icons-react-native/fonts到android/app/src/main/assets/fonts更新一下fonts文件
问题得到解决，谢谢大家分享@Jeepeng

**Comment by bang88** [comment]
应该不用手动啊 我都是直接link的

**Comment by Jeepeng** [comment]
> 应该不用手动啊 我都是直接link的

是的，之前按照文档`react-native link @ant-design/icons-react-native`无效，所以我通过手动copy解决。`react-native link @ant-design/react-native`是可以的，建议更新一下文档

**Comment by silentzone** [comment]
拷贝了字体到assets 目录还是不行,和楼主一样的问题，显示的icon 对不上，环境："@ant-design/react-native": "^3.3.0"（高） ，  "@ant-design/icons-react-native": "^1.0.2",  难道要降 react-native包版本？？
