### ISSUE TITLE
strongly suggest to add a prop in Modal, like onRequestClose

### ISSUE THREAD

**Issue by bimbox-open** [ant-design/ant-design-mobile-rn#773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
in many many case, I can only deal with android device back button in Modal.alert(title, message,actions,onBackHanlder), or Modal.prompt(...). 
But in <Modal {...props}/>, I have no idea about dealing with android device back button.
In my project, there are a lot of <Modal ... /> component, but after Pressing the device back button, how to close the modal? 
I don't understand why to delete onRequestClose prop in RN. 
hope your reply.

### What does the proposed API look like?
<Modal  onRequestClose={...} />

**Comment by bang88** [comment]
@bimbox-open I remember  that we don't  have a props named `onRequestClose`.

**Comment by bang88** [comment]
@1uokun 可以顺便看看这个吗？
