### ISSUE TITLE
网址打不开了

### ISSUE THREAD

**Issue by trytony** [ant-design/ant-design-mobile-rn#779]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/docs/](https://rn.mobile.ant.design/docs/)

### Steps to reproduce
https://rn.mobile.ant.design/docs/

### What is expected?
修复https证书，正常访问

### What is actually happening?
目前无法访问

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 0.61 |
| System | ios13 |
| Browser | chrome |

**Comment by bang88** [comment]
GitHub pages的问题，国外IP可以正常访问。

**Comment by trytony** [comment]
@bang88 https://rn.mobile.ant.design/docs/可以访问？为什么我这里提示证书不安全
