### ISSUE TITLE
@react-native-community/viewpager版本升级请求

### ISSUE THREAD

**Issue by Evan-Future** [ant-design/ant-design-mobile-rn#800]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前@react-native-community/viewpager版本较低，为1.1.7，但是第三方组件都进行了升级到2.x，3.x，由于版本不一致导致冲突，而且目前只能用yarn方式的resolutions来解决。

### What does the proposed API look like?
能够解决版本冲突问题

**Comment by bang88** [comment]
现在 resolution 不能解决问题吗？ 这是原生的模块，升级容易导致 app crash。如果发布到app store 的都要重新发布才能使用

react-native 的依赖太碎片化了 现在有什么问题吗？

**Comment by Evan-Future** [comment]
> 现在 resolution 不能解决问题吗？ 这是原生的模块，升级容易导致 app crash。如果发布到app store 的都要重新发布才能使用
> 
> react-native 的依赖太碎片化了 现在有什么问题吗？

yarn的resolution方式可以解决，不过如果有第三方组件存在兼容性的话，重复yarn会覆盖改动的组件。npm则不会有这个问题。但是npm 方式下 resolution方式无效

**Comment by bang88** [comment]
#797
