### ISSUE TITLE
icon图标显示的是错误的图标

### ISSUE THREAD

**Issue by silentzone** [ant-design/ant-design-mobile-rn#805]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/273957/78516056-ce92c800-77ea-11ea-803b-d23a10c11573.png](https://user-images.githubusercontent.com/273957/78516056-ce92c800-77ea-11ea-803b-d23a10c11573.png)

### Steps to reproduce
1.npm install @ant-design/react-native --save 
2.将node-module目录中 icons-react-native/fonts 拷贝到 android/main/assets目录之后

### What is expected?
期望和示例一样的icon

### What is actually happening?
https://user-images.githubusercontent.com/273957/78516056-ce92c800-77ea-11ea-803b-d23a10c11573.png
![TIM截图20200406092958](https://user-images.githubusercontent.com/273957/78517602-778ff180-77f0-11ea-9a1e-be19154a13cd.png)

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.61.5 |
| System | win10 |
| Browser | 无 |

---
 @ant-design/icons-react-native@1.0.2 版本和 icons-react-native@2.0 也是一样的显示错误？是否需要降@ant-design/react-native 版本到3.2.2？？

**Comment by bang88** [comment]
项目里面是不是有装过另外一个icon 库。 https://github.com/oblador/react-native-vector-icons

**Comment by silentzone** [comment]
> 项目里面是不是有装过另外一个icon 库。 https://github.com/oblador/react-native-vector-icons

  "dependencies": {
    "@ant-design/react-native": "^3.2.2",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/masked-view": "^0.1.7",
    "npm": "^6.14.4",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-code-push": "^6.1.1",
    "react-native-storage": "^1.0.1",
    "react-navigation": "^4.3.6",
    "react-navigation-stack": "^2.3.10"
  },
  "devDependencies": {
    "@ant-design/icons-react-native": "^1.0.2",
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "prop-types": "^15.7.2",
    "rc-form": "^2.4.11",
    "react-native-exception-handler": "^2.10.8",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.7.1",
    "react-native-restart": "0.0.14",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-navigation-drawer": "^2.4.11",
    "react-test-renderer": "16.9.0"
  }
没有只有这个icon 库而且我删除这个字体文件，就无法显示了，这样可以判断引用的字体文件确实就是来自这两个字体文件，我尝试降级了@ant-design/react-native 版本到3.2.2 重新安装了应用还是不行，这一个小问题折腾的我要崩溃了

**Comment by bang88** [comment]
icon react native 不需要单独安装。 ant里面已经有依赖了的 你把Dev里面的删掉 重新安装再link看看

**Comment by silentzone** [comment]
我package.json里面不声明，link 时候会报错，要么就在package.json里面声明icon那我只能手动拷贝到assets目录去了。
```
react-native link @ant-design/icons-react-native
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.
```
现在我又删除package.json里面所有的声明，只执行了npm install @ant-design/react-native --save，然后拷贝 node_modules\@ant-design\icons-react-native\fonts  到 main/assets目录下，可以了！！！！ @bang88 ,谢谢你

**Comment by silentzone** [comment]
难道是 @ant-design/react-native的包版本和@ant-design/icon-react-native 包版本不一致导致的？感谢你花时间解答。
![TIM截图20200406123937](https://user-images.githubusercontent.com/273957/78523617-f5112d00-7803-11ea-925a-22d3279bc8b1.png)

**Comment by bang88** [comment]
正常react-native link @ant-design/react-native 就可以了的。可能文档没有更新到，因为之前的react native是可以单独link一个包不在package里面的。 升级太快 😭

**Comment by BianXuerui** [comment]
> 

非常感谢，解决了我的问题！
