### ISSUE TITLE
组件toast在componentDidMount中无法显示   Toast component cannot be displayed in componentdidmount. Click the button to trigger it

### ISSUE THREAD

**Issue by czwsxmy** [ant-design/ant-design-mobile-rn#813]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/czwsxmy/temporary.git](https://gitee.com/czwsxmy/temporary.git)

### Steps to reproduce
componentDidMount() {
Toast.loading('Loading...',5);
}
showToast= () => {
Toast.loading('Loading...',5);
};
render() {
return (
< Text onPress={this.showToast}>显示Toast< /Text>
);
}

### What is expected?
解决在componentDidMount中显示toast

### What is actually happening?
toast组件在componentDidMount中无法显示

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | "react": "16.11.0","react-native": "0.62.0", |
| System | windows |
| Browser | 谷歌 版本 79.0.3945.88（正式版本） （32 位） |

**Comment by bang88** [comment]
有没有使用`Provider`

**Comment by czwsxmy** [comment]
> 有没有使用`Provider`

用了，在入口处用Provider包裹了，页面的点击事件可以显示这个loading

**Comment by bang88** [comment]
我在IOS上不能复现这个问题。
![image](https://user-images.githubusercontent.com/433259/79705409-33b8e400-82e8-11ea-96cd-d189953d39d9.png)

**Comment by bang88** [comment]
有问题再开。
