### ISSUE TITLE
The Home Page link is not working 

### ISSUE THREAD

**Issue by de1mat** [ant-design/ant-design-mobile-rn#825]
It is ok if this issue is closed I just want you to be aware that the home page link keeps redirecting constantly in an endless loop. I am not really familiar with the antd ecosystem yet as I am just casually reading at his stage so this is the easiest way for me to reach out.

The home page link
https://rn.mobile.ant.design/

**Comment by bang88** [comment]
@de1mat I am sorry  about this.  But I can open it on my side.  Could you clear your browser  cache and try again then.  Thank you 

![image](https://user-images.githubusercontent.com/433259/79813454-4ac20980-83ae-11ea-8a9c-d2626d1a3239.png)

**Comment by de1mat** [comment]
Still doing it for me. I should have clarified that the issue was on my iPhone using the Safari browser. When I try loading the site on macOS using Chrome or Safari it is fine.

I tried clearing the browser cache on my iPhone, and then to visit the site again - same problem. 

I [recorded a video](https://share.getcloudapp.com/geuWrlDe) so you could see me doing this. I am in New Zealand. Not sure what else to share to help with this.

**Comment by bang88** [comment]
It seems like a network issue. I think I can do nothing with this.  We are using github pages  to serve the static files.

 Sorry about that. You may access it using a PC browser ATM.
