### ISSUE TITLE
没有.podspec文件ios中如何引用咱们的字体图标呢？

### ISSUE THREAD

**Issue by SineYing** [ant-design/ant-design-mobile-rn#829]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
yarn add @ant-design/react-native

### What is expected?
可以跟react-native-vector-icons一样pod install后即可使用图标

### What is actually happening?
Unrecognized font family 'antfill'

 [RCTFont updateFont:withFamily:size:weight:style:variant:scaleMultiplier:]
    RCTFont.mm:316
-[RCTTextAttributes effectiveFont]
-[RCTTextAttributes effectiveTextAttributes]
-[RCTBaseTextShadowView attributedTextWithBaseTextAttributes:]
-[RCTTextShadowView attributedTextWithMeasuredAttachmentsThatFitSize:]
-[RCTTextShadowView textStorageAndLayoutManagerThatFitsSize:exclusiveOwnership:]

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.62.2 |
| System | mac |
| Browser | 模拟器 |

**Comment by bang88** [comment]
但是我们的字体图标不在这里，是另外一个库。

**Comment by bang88** [comment]
还是需要你手动 link 一下的。 这个暂时不能加pod 处理
