### ISSUE TITLE
Picker cascade属性探讨

### ISSUE THREAD

**Issue by 1uokun** [ant-design/ant-design-mobile-rn#834]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/index.tsx](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/picker/index.tsx)

### Steps to reproduce
无

### What is expected?
取消该参数，通过传递的数据结构自动判断是否使用联动

### What is actually happening?
当数据结构为【多维数组】并设置`cascade={true}`时数据显示为undefined

当数据结构为【级联数据】并设置`cascade={false}`时会crash

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | react-native |
| System | android/ios |
| Browser | 无 |

**Comment by 1uokun** [comment]
@bang88

**Comment by bang88** [comment]
这个看看有没有别的方式做个兼容，尽量不要 breaking changes 就好。
