### ISSUE TITLE
if use gird component and then set isCarousel to true, the parent props couldn't passed to carousel component.

### ISSUE THREAD

**Issue by raulwin** [ant-design/ant-design-mobile-rn#84]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
react-native android

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn](https://github.com/ant-design/ant-design-mobile-rn)

### Steps to reproduce
if use gird component and then set isCarousel to true, the parent props couldn't passed to carousel component.
如果设置grid并且isCarousel为true, Carousel组件无法继承props.

### What is expected?
if use gird component and then set isCarousel to true, the parent props couldn't passed to carousel component.
如果设置grid并且isCarousel为true, Carousel组件无法继承props.

### What is actually happening?
if use gird component and then set isCarousel to true, the parent props couldn't passed to carousel component.
如果设置grid并且isCarousel为true, Carousel组件无法继承props.

**Comment by bang88** [comment]
来点代码，不太明白啥意思。

**Comment by kangkang721** [comment]
请问这个问题解决了么？我也遇到了那？

**Comment by bang88** [comment]
`2.3.2`

**Comment by bang88** [comment]
`carouselProps`  http://rn.mobile.ant.design/components/grid/#API
