### ISSUE TITLE
plus icon 异常小

### ISSUE THREAD

**Issue by helsonxiao** [ant-design/ant-design-mobile-rn#856]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
```
<Icon name="plus" size="lg" />
```

codepen 上面 icon 也显示不出来

### What is expected?
大小和其它图标一样正常

### What is actually happening?
➕图标在模拟器上小到几乎看不见，其它图标正常显示

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.61.4 |
| System | Android 8.0 |
| Browser | null |

**Comment by bang88** [comment]
codepen ？

**Comment by helsonxiao** [comment]
> codepen ？

~我按照你们指引的步骤创建 codepen 示例，结果什么都显示不出来~（因为指引里提供的不是 rn 版本，所以参数名是 `type` 而不是 `name`）

这个问题在网页上恐怕无法复现，你们 demo 都是正常的，但实际模拟器里就只显示非常小一个加号➕。
https://rn.mobile.ant.design/components/icon-cn/#components-icon-demo-basic

这是实际机器上的情况，lg size 的 plus icon，大小和正常加号比起来也只有一点点。
![image](https://user-images.githubusercontent.com/26411634/81247785-794a1080-904d-11ea-8e2c-db47486d1b43.png)

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/81248874-f5ddee80-904f-11ea-865e-90dad59b2a95.png)

看到了，这个有点奇葩了，不知道 antd 那边会不会，用一套字体的。

**Comment by bang88** [comment]
调试了一番，没找到哪里的问题，font-size 也是一样的。

**Comment by helsonxiao** [comment]
临时解决办法，下载 svg 然后直接用
```
curl -O https://raw.githubusercontent.com/ant-design/ant-design-icons/master/packages/icons-svg/svg/outlined/plus.svg
```

**Comment by bang88** [comment]
合并svg 到font的时候有问题，在看。

**Comment by bang88** [comment]
2.1.0

**Comment by bang88** [comment]
@helsonxiao 2.2.0

**Comment by helsonxiao** [comment]
在使用 `@ant-design/react-native` 3.3.0 的情况下直接 install `@ant-design/icons-react-native` 2.2.1 会造成 Icon 混乱。

`<Icon style={{ fontSize: 16 }} name="plus" />` 变成了 
![image](https://user-images.githubusercontent.com/26411634/81396473-0e393080-9158-11ea-9fce-ad4425e418b3.png)

需要全部使用 icons-react-native 的 `<IconOutline style={{ fontSize: 16 }} name="plus" />` 才显示正常

**Comment by helsonxiao** [comment]
重新 `npx react-native link` 以后可以了，`npx react-native link @ant-design/icons-react-native` 不行

**Comment by helsonxiao** [comment]
> 在使用 `@ant-design/react-native` 3.3.0 的情况下直接 install `@ant-design/icons-react-native` 2.2.1 会造成 Icon 混乱。
> 
> `<Icon style={{ fontSize: 16 }} name="plus" />` 变成了
> ![image](https://user-images.githubusercontent.com/26411634/81396473-0e393080-9158-11ea-9fce-ad4425e418b3.png)
> 
> 需要全部使用 icons-react-native 的 `<IconOutline style={{ fontSize: 16 }} name="plus" />` 才显示正常

清理了缓存以后还是这个问题，如果 `@ant-design/react-native 3.3.0` 和 `@ant-design/icons-react-native 2.2.1` 混合使用的话，图标显示不正常，已经 link 过。 @bang88

**Comment by bang88** [comment]
看起来是组件里面用的code跟font对应不上 要更新ant-design/react-native 你方便试试最新测试版吗？

安装的时候加个@next 4.0.0-3

**Comment by bang88** [comment]
但好像也不是这个问题
