### ISSUE TITLE
Popover 没有完全 dismiss 就跳转页面的话，会影响下个页面的 TextInput autoFocus

### ISSUE THREAD

**Issue by helsonxiao** [ant-design/ant-design-mobile-rn#857]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
1. 在 A 页面使用 Popover
2. 点击 A 页面中 Popover 的某个 item，进行跳转 B 页面
3. B 页面的 TextInput autoFocus 先生效，打开键盘，然后出发 blur 自动关闭键盘

如果不点击 popover 中的 item 跳转则是正常的

### What is expected?
popover 的关闭不会影响下个页面的 autoFocus

### What is actually happening?
popover 的关闭影响下个页面的 autoFocus

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.61.4 |
| System | Android 8.0 |
| Browser | null |

---
强烈要求支持 react-native-modal-popover 中的动画效果以及动画速度的属性

**Comment by bang88** [comment]
popover的关闭 并不知道你要做什么其他操作。

**Comment by helsonxiao** [comment]
> popover的关闭 并不知道你要做什么其他操作。

是不应该知道。但应该提供一种不影响下个页面的关闭方法，显然目前的关闭会影响下个页面。而点击 popover item 进入一个输文本的页面是个很常见的需求。

**Comment by bang88** [comment]
那你觉得应该怎样做？欢迎PR

**Comment by helsonxiao** [comment]
> 那你觉得应该怎样做？欢迎PR

react-native-modal-popover 的默认 duration 稍微有点长，导致跳转到下个页面的时候组件还在缓慢消失，所以会引发问题。最起码应该先把这些可配参数开放出来，业务开发的时候可以在 onDismiss 之后再跳转页面。

**Comment by bang88** [comment]
可以来个PR。 :smile:

**Comment by bang88** [comment]
@helsonxiao 来个PR？

**Comment by helsonxiao** [comment]
> @helsonxiao 来个PR？

下周一定 🐶

**Comment by helsonxiao** [comment]
@bang88 https://github.com/ant-design/ant-design-mobile-rn/pull/865

**Comment by helsonxiao** [comment]
升级 v4 后测试没问题了，onSelect 和 onDismiss 需要结合使用，等待动画结束再进入下个页面，这时 autoFocus 就没问题了

**Comment by helsonxiao** [comment]
测试发现 onDismiss 在安卓上无效（参考 RN Modal 文档），可以通过关闭动画 + onSelect 实现同样的效果。
