### ISSUE TITLE
cameraRoll has been removed from React Native

### ISSUE THREAD

**Issue by liumin007** [ant-design/ant-design-mobile-rn#858]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/image-picker-cn/](https://rn.mobile.ant.design/components/image-picker-cn/)

### Steps to reproduce
点击ImagePicker组件   报错：CameraRoll has been removed from React Native

### What is expected?
点击ImagePicker组件选择照片或拍照

### What is actually happening?
点击ImagePicker组件报错：CameraRoll has been removed from React Native

| Environment | Info |
|---|---|
| antd | 2.3.0 |
| React | 16.9.0 |
| System | ios |
| Browser | Chrome 81.0.4044.129 |

**Comment by bang88** [comment]
4.0.0 已经分开还没发布，可以安装next试用后，期待更多反馈。

**Comment by liumin007** [comment]
试用了"@ant-design/react-native": "^4.0.0-2"版本。加载相册的时候有点慢，需要等好几秒照片才能全部加载完成。可在点击选择照片弹出action来选择拍照或者从相册中选取吗？

**Comment by bang88** [comment]
这个自己实现一个比较好一点。 加载慢也有可能是照片多
