### ISSUE TITLE
SearchBar控制输入法键盘右下角文字

### ISSUE THREAD

**Issue by tunshiyu** [ant-design/ant-design-mobile-rn#861]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
您好。看了下SearchBar内部用的inputText，当我们点击这个输入框时，例如wx、淘宝等输入法键盘右下角显示的是搜索，咱们是不是可以让inputtext加一个type='search'这种的，也让咱们的SearchBar点击输入框后，输入法右下角为搜索呢？
![image](https://user-images.githubusercontent.com/39406845/81272742-774d7500-9080-11ea-8327-557a95dc90fe.png)

### What does the proposed API look like?
可以的话，提供一个boolean属性。

**Comment by bang88** [comment]
input 有个类型配置的。 你看看

**Comment by tunshiyu** [comment]
您好，我即使看input，我也改不了serachBar呀。你们的serachBar并没有暴露input组件呀

**Comment by tunshiyu** [comment]
> input 有个类型配置的。 你看看

您好，我即使看input，我也改不了serachBar呀。你们的serachBar并没有暴露input组件呀

**Comment by tunshiyu** [comment]
> > input 有个类型配置的。 你看看
> 
> 您好，我即使看input，我也改不了serachBar呀。你们的serachBar并没有暴露input组件呀
比如我想这么写
<SearchBar
              onSubmit={value => handleSubmit(value)}
              showCancelButton={false}
              defaultValue={keywords}
     
              returnKeyType='search'
            />
