### ISSUE TITLE
PickerView组件的indicatorStyle属性不起作用

### ISSUE THREAD

**Issue by suwu150** [ant-design/ant-design-mobile-rn#867]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/picker-pf6zw?file=/src/App.js)

### Steps to reproduce
添加属性,点击展开

### What is expected?
能够正常显示结果

### What is actually happening?
不起作用,属性不起作用

| Environment | Info |
|---|---|
| antd | 3.2.2 |
| React |   "react": "16.9.0",     "react-native": "0.61.5", |
| System | ios,android  |
| Browser | 谷歌浏览器 |

---
添加下面属性,不起作用:
```    

    indicatorStyle={{
          backgroundColor: '#f000ff',
          color: 'rgba(0,0,0,0.85)',
          height: 200,
          fontSize: 18,
        }}
```

**Comment by bang88** [comment]
看了代码应该是RN没有实现这个属性的。 😢

**Comment by 1uokun** [comment]
需要添加ActivityIndicator提示符号（异步加载）

**Comment by dongshuai777** [comment]
请问有什么进展吗？
这个属性依旧不能用是吗？
