### ISSUE TITLE
Checkbox在小米mix Android8.0 手机上不显示左侧复选框

### ISSUE THREAD

**Issue by Hackerofshi** [ant-design/ant-design-mobile-rn#872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://note.youdao.com/yws/api/personal/file/WEB888fdfc55ec491df86a9c547cd0cd54d?method=getImage&version=12755&cstk=XwikLbqS](https://note.youdao.com/yws/api/personal/file/WEB888fdfc55ec491df86a9c547cd0cd54d?method=getImage&version=12755&cstk=XwikLbqS)

### Steps to reproduce
```
<Checkbox checked={isSelected}>Checkbox</Checkbox>
```
![image](https://note.youdao.com/yws/api/personal/file/WEB888fdfc55ec491df86a9c547cd0cd54d?method=getImage&version=12755&cstk=XwikLbqS)

### What is expected?
可以显示

### What is actually happening?
不显示

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.62.0 |
| System | Android |
| Browser | 无 |

---
小米mix，Android8.0 手机用rn中的Checkbox出现不显示复选框的情况

**Comment by bang88** [comment]
能不能来一个截图看看。

**Comment by Hackerofshi** [comment]
https://note.youdao.com/yws/api/personal/file/WEB888fdfc55ec491df86a9c547cd0cd54d?method=getImage&version=12755&cstk=2IL_jggq

**Comment by Hackerofshi** [comment]
https://note.youdao.com/yws/api/personal/file/WEB888fdfc55ec491df86a9c547cd0cd54d?method=getImage&version=12755&cstk=2IL_jggq
这个地址可以查看图片

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/82850732-1a7f0500-9f30-11ea-8fb0-11f5f371a5a7.png)

**Comment by bang88** [comment]
@Hackerofshi 看不了呢

**Comment by xfeng-github** [comment]
> https://note.youdao.com/yws/api/personal/file/WEB888fdfc55ec491df86a9c547cd0cd54d?method=getImage&version=12755&cstk=2IL_jggq
> 这个地址可以查看图片



> @Hackerofshi 看不了呢

![image](https://user-images.githubusercontent.com/57913284/90483931-16960400-e168-11ea-8c42-72462c5e5648.png)
我这边无法显示多选框

**Comment by xfeng-github** [comment]
Environment | Info
-- | --
antd | 4.0.5
React | 0.61.5
System | Android
Browser | 无
