### ISSUE TITLE
TextareaItem 可以设置点击return收起键盘吗

### ISSUE THREAD

**Issue by liumin007** [ant-design/ant-design-mobile-rn#877]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
点击return收起键盘

### What does the proposed API look like?
点击return收起键盘

**Comment by bang88** [comment]
@liumin007 你试试 设置 `returnKeyType` 为 done 试试

**Comment by liumin007** [comment]
`    return (
      <TextareaItem
        style={{ paddingTop: 10 }}
        title='标题'
        placeholder={this.props.placeholder}
        returnKeyType='done'
        rows={4}
        count={500}
        clear={true}
        onChange={(text) => {
          this.props.onChange(text)
        }}
      >
      </TextareaItem>`
在iPhone X12.1模拟器上点击done是换行

**Comment by bang88** [comment]
@liumin007 自己调用 Keyboard.dismiss 关闭键盘。
