### ISSUE TITLE
同时使用Tabs和SwipeAction组件后，SwipeAction仍可以进行滑动操作

### ISSUE THREAD

**Issue by SunshineH2** [ant-design/ant-design-mobile-rn#879]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tabs组件和SwipeAction组件可以共存，实现删除效果

### What does the proposed API look like?
Tabs和SwipeAction的滑动操作不应该冲突，可以正常使用

**Comment by bang88** [comment]
@SunshineH2 swipe 那个组件很久没更新了，建议你试试这个 https://github.com/jemise111/react-native-swipe-list-view
