### ISSUE TITLE
NoticeBar on android error "Cannot add a child that doesn't have a YogaNode to a parent without a measure function!(Tring to add a 'RCTRawText[text: ]' to a 'RCTView')"

### ISSUE THREAD

**Issue by popogao** [ant-design/ant-design-mobile-rn#88]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
OS: android 6.0,react-native:0.55.4，expo:29.0

### Reproduction link
[https://codepen.io/popogao/pen/xJoOBY](https://codepen.io/popogao/pen/xJoOBY)

### Steps to reproduce
只是用了demo的例子而已

### What is expected?
与ios有同样的效果

### What is actually happening?
报错
"Cannot add a child that doesn't have a YogaNode to a parent without a measure function!(Tring to add a 'RCTRawText[text: ]' to a 'RCTView')"

**Comment by popogao** [comment]
![248893654](https://user-images.githubusercontent.com/1617536/44198149-2cd0ea00-a173-11e8-8405-1ef6941288c5.jpg)

**Comment by bang88** [comment]
Can not re-produce with `2.3.0`.  Please checkout the demo page or clone the repo run `yarn android`
