### ISSUE TITLE
link不成功

### ISSUE THREAD

**Issue by showtan001** [ant-design/ant-design-mobile-rn#885]
react-native link @ant-design/icons-react-native

返回信息: 
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

版本信息：
"@ant-design/icons-react-native": "^2.2.1",
"@ant-design/react-native": "^3.3.0",
 "react-native": "0.62.2",

有没有手动配置的文档？

**Comment by showtan001** [comment]
> @showtan001 可以试用一下`"@ant-design/react-native": "4.0.0"`吗？期待更多的反馈，升级4.0.0 后 在项目目录 执行 `npx react-native link`即可。

周末升级试试   应该是link成功了  Toast.fail、success的icon都显示出来了

**Comment by bang88** [comment]
@showtan001 有没有试试。

**Comment by showtan001** [comment]
> @showtan001 有没有试试。

试过 RN最新、Antd最新  没问题 👍

**Comment by codering** [comment]
mark.

**Comment by tunshiyu** [comment]
借楼，根据bang88大佬启发解决了个问题。
"@ant-design/react-native": "4.0.0"中,安卓Icon不显示,npx react-native link一下重新编译即可
