### ISSUE TITLE
Toast Font Error

### ISSUE THREAD

**Issue by bmbknds** [ant-design/ant-design-mobile-rn#886]
@

![image](https://user-images.githubusercontent.com/29396046/82522543-f5ffe300-9b53-11ea-9f6f-949c09717038.png)
1, When i install version **3.3.0**, I cant link anything, even when i tried to install ant-design/ant-design-icons and link again.
2, When i install version **3.1.15** like demo website and download "https://unpkg.com/@ant-design/icons-react-native@1.0.2/fonts/antoutline.ttf", add font manually. It works.
3. When i upgrade to **3.3.0** and use "https://unpkg.com/@ant-design/icons-react-native@1.0.2/fonts/antoutline.ttf" or copy antoutline.ttf from 3.3.0/4.0.0 source , I got unknow icon like picture.
I see note that you upgraded icon to 2.0.0 version but I cant find where to download. Please check it.
Thank you.

**Comment by gaboluque** [comment]
Any solution to this?
