### ISSUE TITLE
Getting mutiple props error

### ISSUE THREAD

**Issue by deathemperor** [ant-design/ant-design-mobile-rn#888]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://N/A](http://N/A)

### Steps to reproduce
Running @ant-design/react-native on expo (SDK 37.0.1). Use InputItem component as
```
<InputItem
        clear
        error
        value={username}
        onChange={setUsername}
        placeholder="Nhập số điện thoại"
      >
        Số điện thoại
      </InputItem>
```

### What is expected?
No error

### What is actually happening?
```
index.js:1 Warning: React does not recognize the `labelPosition` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelposition` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
```
Warning: React does not recognize the `textAlign` prop on a DOM element
```

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 0.61.4 |
| System | Mac OS 10.14.6 (18G4032) |
| Browser | Chrome 77.0 |

**Comment by deathemperor** [comment]
The button also has no default color when I use. screenshot: https://snipboard.io/rLCfjA.jpg
`<Button onPress={() => {}}>Tiếp tục</Button>`

**Comment by bang88** [comment]
@deathemperor  Does this warning came from browser ? Please running it on a real device and check the logs again. Thank you
