### ISSUE TITLE
Picker组件只能接收 Array<{value, label, children: Array}>类型的数据源吗？

### ISSUE THREAD

**Issue by liumin007** [ant-design/ant-design-mobile-rn#898]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以修改数据源的key的值 eg: Array<{value, name, children: Array}>

### What does the proposed API look like?
 Array<{value, name, children: Array}>

**Comment by bang88** [comment]
TS 比较灵活的，你可以自己cast 自己想要的类型。
