### ISSUE TITLE
Tabs Click change slow

### ISSUE THREAD

**Issue by wangfpp** [ant-design/ant-design-mobile-rn#907]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
点击tabs title切换tab选项卡时 切换的非常慢 大概需要5s的时间才能完成切换

### What does the proposed API look like?
我不知道这是不是bug  但是使用过程中确实非常满

**Comment by helsonxiao** [comment]
+1, Tabs 的动画有一些 bug

**Comment by bang88** [comment]
> +1, Tabs 的动画有一些 bug

新版 用的是ViewPager了，也有问题吗？

**Comment by helsonxiao** [comment]
> > +1, Tabs 的动画有一些 bug
> 
> 新版 用的是ViewPager了，也有问题吗？

明天我测一下，具体问题再更新在这里。

**Comment by wuazhu** [comment]
> > +1, Tabs 的动画有一些 bug
> 
> 新版 用的是ViewPager了，也有问题吗？

如何切换到4.0的 ant-rn

**Comment by bang88** [comment]
> > > +1, Tabs 的动画有一些 bug
> > 
> > 
> > 新版 用的是ViewPager了，也有问题吗？
> 
> 如何切换到4.0的 ant-rn

还不是正式版 但是你可以 `yarn add @ant-design/react-native@next`，但是需要安装peer 依赖，以及link 具体可以看 repo 的readme

**Comment by inkCrazy** [comment]
原来我的版本是3.x,点击tabitem切换时，页面不能切换，左右滑动可以。更新到4.0.0-3可以暂时解决问题了。

**Comment by wuazhu** [comment]
> > > > +1, Tabs 的动画有一些 bug
> > > 
> > > 
> > > 新版 用的是ViewPager了，也有问题吗？
> > 
> > 
> > 如何切换到4.0的 ant-rn
> 
> 还不是正式版 但是你可以 `yarn add @ant-design/react-native@next`，但是需要安装peer 依赖，以及link 具体可以看 repo 的readme

正式上线有时间计划节点吗~~

**Comment by helsonxiao** [comment]
```
<Tabs
  tabs={tabs}
  animated
/>
```
tab 切换的动画似乎没了。在 3.3.0 的时候还有的，在外部控制 page 的情况下还会存在 tab 底部指示条的位置错误，动画卡顿问题。现在没有动画，没法复现。

**Comment by bang88** [comment]
待会发布4.0.0 现在在准备更新日志，希望多测试一下

**Comment by Evan-Future** [comment]
更新到4.0.5后，RN0.63.2，问题依旧，Tabs切换无动画，切换有明显卡顿，特别是Android上。之前3.x版本只有Android卡顿和下划线错位问题，IOS是有动画，也很流畅的
