### ISSUE TITLE
listView自动加载更多

### ISSUE THREAD

**Issue by liumin007** [ant-design/ant-design-mobile-rn#912]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/components/](https://rn.mobile.ant.design/components/)

### Steps to reproduce
首次进入列表页加载10行数据， 上拉加载更多

### What is expected?
首次进入列表页加载10行数据， 上拉加载更多

### What is actually happening?
首次进入列表页加载10行数据， 自动加载更多数据

| Environment | Info |
|---|---|
| antd | 4.0.0-2 |
| React | 16.9.0 |
| System | ios |
| Browser | Chrome 81.0.4044.129 |

**Comment by Thetiso** [comment]
4.0.5版本依旧存在这个问题，RN 0.63.2。
上拉加载不会自动出发onFetch方法。

and more:

如果再listview外面嵌套一个View
`		const style = {
			alignItems: 'center',
			justifyContent: 'center',
			height: 150,
			backgroundColor: '#fff',
		};
`
首次加载的listview没有文本居中，下来加载后却居中显示了。
listView的renderItem为
`
	renderItem = (item) => {
		return (
		  	<View style={{ padding: 10 }}>
				<Text>{item}</Text>
		  	</View>
		);
	};
`
