### ISSUE TITLE
【iOS】在Carousel的内容只有1组图片的时候，iOS上无法正常显示图片的内容

### ISSUE THREAD

**Issue by Bruce-zxy** [ant-design/ant-design-mobile-rn#913]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/bruce-zxy/pen/ExPVjxG](https://codepen.io/bruce-zxy/pen/ExPVjxG)

### Steps to reproduce
// ...
import {Carousel} from '@ant-design/react-native';

const arr = [{id:1, uri: 'https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1155094793,592129984&fm=26&gp=0.jpg'}];

const Swiper = banners => {
  return (
    <Carousel
      autoplayInterval={5000}
      autoplay
      infinite>
      {banners?.map(b => (
          <TouchableOpacity
            key={b.id}
            style={sliderContentStyle}
            onPress={onPressLinkImage(b)}>
            <Image
              source={{ uri: b.uri }}
              style={sliderImageStyle}
            />
          </TouchableOpacity>
        ))}
    </Carousel>
  )
}

const sliderContentStyle = {
    flexGrow: 0,
    flexShrink: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 260,
    borderRadius: 8,
    overflow: 'hidden',
    paddingHorizontal: 20,
}
const sliderImageStyle = {
  width: '100%',
  height: '100%',
};

### What is expected?
在只有一张图片的情况下，能够在图片加载完成后正常地显示出图片的内容。

### What is actually happening?
【Android】：正常；
![1591606731801417](https://user-images.githubusercontent.com/22904758/84012548-4e374180-a9aa-11ea-8778-3f247efcf377.gif)

【iOS】：不正常，在图片加载完成后显示为全白，在手指触摸<Carousel />组件区域并且轻微滑动以后才能正常显示出图片的内容；
![1591607044694051](https://user-images.githubusercontent.com/22904758/84012649-77f06880-a9aa-11ea-9c66-ce52422cbcf3.gif)

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | react-native@0.62.2 |
| System | iOS |
| Browser | 无 |

**Comment by Bruce-zxy** [comment]
#905 相同问题

**Comment by inkCrazy** [comment]
"@ant-design/react-native": "^4.0.0-3",
"react-native": "0.62.2",
<ScrollView style={[Style.container, {backgroundColor: '#fff'}]}>
          <Carousel
            style={styles.wrapper}
            // selectedIndex={0}
            dots={dotsShow}
            autoplay
            // infinite
            // afterChange={this.onHorizontalSelectedIndexChange}
          >
            {/*{homeHeaderImageControl}*/}

            <Image
              style={{
                width: screenWidth - bannerMargin * 2,
                height: 200, // 组件网络获取的图片必须在样式中声明图片的宽和高。如果没有声明，则图片将不会被呈现在界面上
                marginTop: 2,
                marginLeft: bannerMargin,
                marginRight: bannerMargin,
              }}
              source={require('../../res/img/home_header.png')}
            />
          </Carousel>
...
wrapper: {
    width: 200,
  },
为啥我都不显示

**Comment by bang88** [comment]
提issue 的时候代码格式化一下.

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/84587606-33097d80-ae53-11ea-9e3b-8406287497e3.png)

**Comment by Bruce-zxy** [comment]
这样就把issue给关了？
能把你的示例代码通过某种方式共享出来吗？
这个问题一方面我测试的条件是在真机的情况下进行的，另一方面，我自己在这边用模拟器确认了一下也还是有问题的

**Comment by bang88** [comment]
代码在图片里面。 请看一眼？

**Comment by qiujie8092916** [comment]
@Bruce-zxy 解决了吗
