### ISSUE TITLE
warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.

### ISSUE THREAD

**Issue by yuanbolin** [ant-design/ant-design-mobile-rn#915]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[rn:'0.62.2' link报错warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.](rn:'0.62.2' link报错warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.)

### Steps to reproduce
link报错导致@ant-design/icons-react-native无法启用,checkbox等组件显示为错叉

### What is expected?
提供一下手动改如何link

### What is actually happening?
自动link被弃用

| Environment | Info |
|---|---|
| antd | 3.3.0 |
| React | 16.11.0 |
| System | window |
| Browser | 谷歌 |

**Comment by bang88** [comment]
晚点试试 4.0.0 吧，link 简化了一下
