### ISSUE TITLE
Modal.prompt怎么支持系统拼音输入法

### ISSUE THREAD

**Issue by jay4900** [ant-design/ant-design-mobile-rn#92]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
2.2.0

### Environment
iOS, react-native:0.55.3

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/](https://github.com/ant-design/ant-design-mobile-rn/)

### Steps to reproduce
弹出Modal.prompt，切换输入法为系统自带的拼音输入法，输入拼音

### What is expected?
文本框内显示中文字符

### What is actually happening?
文本框内显示的是拼音字母

---
TextInput输入中文的时候也存在这种问题，但只要不使value={this.state.text}就可以用拼音输入中文，Modal.prompt中的输入框有什么办法解决

**Comment by bang88** [comment]
可能是React Native的问题，可以升级React Native试试
