### ISSUE TITLE
4.0升级指南

### ISSUE THREAD

**Issue by wuazhu** [ant-design/ant-design-mobile-rn#920]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
大佬。。升级4.0的指南有没有，是否有文档页面。目前官网的文档还是3.x

### What does the proposed API look like?
文档链接，。升级指南。。。

**Comment by wuazhu** [comment]
@bang88

**Comment by bang88** [comment]
@wuazhu 也没啥升级指南，就是readme里面说的要安装 rn拆分后的组件，然后link。 文档 运行不起来，还在调试。。。

**Comment by wuazhu** [comment]
> @wuazhu 也没啥升级指南，就是readme里面说的要安装 rn拆分后的组件，然后link。 文档 运行不起来，还在调试。。。

@bang88  好的。。组件修改主题的一直找不到，看到里面说的用ant-mobile的，又有说新的不这么弄了。有demo么，或者文档说明。。

**Comment by bang88** [comment]
![image](https://user-images.githubusercontent.com/433259/84593510-34e93600-ae7f-11ea-8fef-8e05844f77b0.png)

估计一时半会不知道什么问题。 react 半年不搞一下都运行不起来的。。

**Comment by bang88** [comment]
> > @wuazhu 也没啥升级指南，就是readme里面说的要安装 rn拆分后的组件，然后link。 文档 运行不起来，还在调试。。。
> 
> @bang88 好的。。组件修改主题的一直找不到，看到里面说的用ant-mobile的，又有说新的不这么弄了。有demo么，或者文档说明。。

主题修改？

两种方式 一是通过Provider 另外一个是通过每个组件各自的 styles 覆盖样式

**Comment by wuazhu** [comment]
> > > @wuazhu 也没啥升级指南，就是readme里面说的要安装 rn拆分后的组件，然后link。 文档 运行不起来，还在调试。。。
> > 
> > 
> > @bang88 好的。。组件修改主题的一直找不到，看到里面说的用ant-mobile的，又有说新的不这么弄了。有demo么，或者文档说明。。
> 
> 主题修改？
> 
> 两种方式 一是通过Provider 另外一个是通过每个组件各自的 styles 覆盖样式

provider方式有文档或者demo么。。
provider传入的theme的配置项是什么样的。。有配置文件么。

**Comment by bang88** [comment]
https://rn.mobile.ant.design/components/locale-provider/

可覆盖的变量 https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/style/themes/default.tsx

... 这个感觉不是很复杂

**Comment by wuazhu** [comment]
OK了，就是找不到文档😅。多谢~~
