### ISSUE TITLE
图标显示为x  图标加载不出来 react-native init 项目 非expo

### ISSUE THREAD

**Issue by lingroid** [ant-design/ant-design-mobile-rn#934]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/icon/demo/basic.md](https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/icon/demo/basic.md)

### Steps to reproduce
react-native init 
yarn "@ant-design/icons-react-native": "^2.2.1",
    "@ant-design/react-native": "^4.0.0",
    "@react-native-community/cameraroll": "^2.0.0",
    "@react-native-community/picker": "^1.6.3",
    "@react-native-community/segmented-control": "^2.0.0",
    "@react-native-community/slider": "^3.0.0",
    "@react-native-community/viewpager": "^4.0.1",
https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/icon/demo/basic.md
yarn
yarn start

android studio run

### What is expected?
icon show

### What is actually happening?
icon not show

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | "react": "16.11.0",     "react-native": "0.62.2" |
| System | android |
| Browser | android |

**Comment by curiousbabyMz** [comment]
解决了吗？

**Comment by 1uokun** [comment]
Duplicate of https://github.com/ant-design/ant-design-mobile-rn/issues/1016
