### ISSUE TITLE
RN4.0版本Grid的isCarousel开启则不能正常显示

### ISSUE THREAD

**Issue by fv0008** [ant-design/ant-design-mobile-rn#937]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://none.com](http://none.com)

### Steps to reproduce
无

### What is expected?
正常显示

### What is actually happening?
不显示

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | "react-native": "^0.61.4", |
| System | mac os 14.5 |
| Browser | 无 |

**Comment by bang88** [comment]
来点代码

**Comment by MrLaibin** [comment]
> 来点代码

有4.0计划内容吗？
如何贡献代码？

**Comment by bang88** [comment]
我的意思是 提供一下复现的代码。

**Comment by fv0008** [comment]
render() {
    minluckyyear=["辛未 1991", "壬申 1992", "癸酉 1993", "甲戌 1994", "乙亥 1995", "丙子 1996", 
    "丁丑 1997", "戊寅 1998", "己卯 1999", "庚辰 2000", "辛巳 2001", "壬午 2002", "癸未 2003", 
    "甲申 2004", "乙酉 2005", "丙戌 2006", "丁亥 2007", "戊子 2008", "己丑 2009", "庚寅 2010", 
    "辛卯 2011", "壬辰 2012", "癸巳 2013", "甲午 2014", "乙未 2015", "丙申 2016", "丁酉 2017", 
    "戊戌 2018", "己亥 2019", "庚子 2020", "辛丑 2021", "壬寅 2022", "癸卯 2023", "甲辰 2024", 
    "乙巳 2025", "丙午 2026", "丁未 2027", "戊申 2028", "己酉 2029", "庚戌 2030", "辛亥 2031", 
    "壬子 2032", "癸丑 2033", "甲寅 2034", "乙卯 2035", "丙辰 2036", "丁巳 2037", "戊午 2038", 
    "己未 2039", "庚申 2040", "辛酉 2041", "壬戌 2042", "癸亥 2043", "甲子 2044", "乙丑 2045", 
    "丙寅 2046", "丁卯 2047", "戊辰 2048", "己巳 2049", "庚午 2050", "辛未 2051", "壬申 2052", 
    "癸酉 2053", "甲戌 2054", "乙亥 2055", "丙子 2056", "丁丑 2057", "戊寅 2058", "己卯 2059", 
    "庚辰 2060", "辛巳 2061", "壬午 2062"]
    return (
      <View style={styles.container} >
        <ScrollView ref="location" style={{ backgroundColor: '#ffffff' }}>
              <Accordion onChange={this.onChange} activeSections={this.state.activeSections}>
                <Accordion.Panel header="流年信息">
                  <Grid
                    data={minluckyyear}
                    columnNum={3}
                    itemStyle={{ height: 35 }}
                    isCarousel={true}
                    carouselMaxRow={6}
                    onPress={(_el: any, index: any) => this.changeyear("", Number(_el.split(" ")[1]))}
                    renderItem={(dataItem, itemIndex) => (this.renderminyearItem(dataItem))}
                  />
                </Accordion.Panel >
              </Accordion>
        </ScrollView>
      </View>
    )
  }

**Comment by bang88** [comment]
@fv0008 给Grid加个宽高看看？ 你是看不见内容还是怎样？

**Comment by fv0008** [comment]
itemStyle={{ height: 35,width:300 }} 一样不行，什么也看不到
删除isCarousel={true}就都能看到了
@bang88 bang

**Comment by bang88** [comment]
@fv0008 试试这样设置宽高

```tsx
<Grid
  data={data}
  columnNum={3}
  isCarousel
  carouselProps={{
    style: {
      width: "100%",
      height: 320
    }
  }}
  onPress={(_el: any, index: any) => alert(index)}
/>
```

**Comment by fv0008** [comment]
@bang88 这样是可以的，height调整下就正常了
