### ISSUE TITLE
Portal.remove() cannot hide Toast in async functions

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design-mobile-rn#938]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
```js
const checkLogin = async () => {
  const key = Toast.loading('开始检查', 0);
  const result = await isUserLogin();
  Portal.remove(key);
  // 其他逻辑
}
```

### What is expected?
期望结果是Toast在接口请求成功之后可以消失

### What is actually happening?
接口请求成功，但是Toast并没有消失

| Environment | Info |
|---|---|
| antd-mobile-rn | 4.0.0 |
| React-Native | 0.62.2 |
| System | MacOS Majave |

**Comment by bang88** [comment]
再Remove之前有没有其他Toast出现的，或者你试试Toast.removeAll() 看看会不会移除掉。

**Comment by chj-damon** [comment]
Toast的各种方法我都试过了。不管是Toast.remove(key), Portal.remove(key), Toast.removeAll()，都没什么用。而且奇怪的是在模拟器上反而是没问题的。真机上面不行，我准备一个重现demo吧
