### ISSUE TITLE
Carousel 组件跳转到指定页面

### ISSUE THREAD

**Issue by lpf123lpf** [ant-design/ant-design-mobile-rn#939]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1:在我的项目中可替换createMaterialTopTabNavigator，使用左右切换的功能，方便样式定制，但是无法跳转到指定页面
2:实际所需，用户想要看到某个轮播图点击下方指示点可可直接跳转

### What does the proposed API look like?
添加一个类似于antd 跳转到指定位置的API即可

**Comment by bang88** [comment]
@lpf123lpf Carousel 下面的圆点没有点击事件。太小了 设计之初也没想让点击

**Comment by bang88** [comment]
你可以自己实现一个dot。 自带的dot 禁用掉

**Comment by lpf123lpf** [comment]
@bang88  你好，我看了下Carousel  的源码，没有那个方法可以实现点击跳转到指定页面。只有一个scrollNextPage调用跳转到下一个页面，但是仅仅就是跳转到下一个页面。
我是把原有的dot禁用掉了，但是没有一个方法让我可以去跳转

**Comment by lpf123lpf** [comment]
顺便问下tabs 修复了吗？

**Comment by bang88** [comment]
@lpf123lpf

-  获取ref 后有个 `goTo` 的方法可以使用
- 可以通过设置 `current` 改变当前项

**Comment by bang88** [comment]
你用的是4.0.0 吧？

**Comment by lpf123lpf** [comment]
@bang88  antd 版本3.3.0， RN版本0.62.2

**Comment by bang88** [comment]
4.0.0 修复了tabs。 还有Carousel

**Comment by lpf123lpf** [comment]
@bang88  好的 我去试试，感谢回复

**Comment by bang88** [comment]
升级到4.0.0 请参考README。

**Comment by lpf123lpf** [comment]
@bang88  您好 我更新到了4.0 但是Carousel 不显示了，4.0的Carousel是需要设置额外的参数吗？很抱歉，我没有找到4.0的文档

**Comment by bang88** [comment]
@lpf123lpf Carousel style 给个宽高 Release 里面有说明，线上文档还没弄好。

**Comment by lpf123lpf** [comment]
@bang88  谢谢

**Comment by ideazhao** [comment]
> @lpf123lpf
> 
> * 获取ref 后有个 `goTo` 的方法可以使用
> * 可以通过设置 `current` 改变当前项

5.17.2表示，文档里有，但没得作用，后来换别家方案了。
