### ISSUE TITLE
ImagePicker 图片选择器 更改宽高大小

### ISSUE THREAD

**Issue by WQMDC** [ant-design/ant-design-mobile-rn#94]
请问，怎么才能更改imagePicker的宽高大小呢？我给这个标签上加style样式，并且设置flex:1，父级有设置flex属性，且宽高很大，但是这个组件却还是原来的大小。希望有人看到后，给个建议……急等！！！感激不尽！！！

**Comment by bang88** [comment]
cameraPickerProps = {{
  imagesPerRow: 4 // 每行图片数量控制大小
}}
