### ISSUE TITLE
你好，能维护下antd mobile rn中的switch组件吗

### ISSUE THREAD

**Issue by xupeng1232** [ant-design/ant-design-mobile-rn#945]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd mobile rn中的switch组件样式可以和antd mobile中的switch一样吗

### What does the proposed API look like?
。

**Comment by bang88** [comment]
@xupeng1232 这个没办法同步了
