### ISSUE TITLE
tabs 组件, 删除下划线

### ISSUE THREAD

**Issue by wuazhu** [ant-design/ant-design-mobile-rn#949]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.是否可以增加 tabs 组件的下面灰线的 api, 设计里很多的 tab 是没有下划线样式的, 说的是那一根灰色的边框线.
2.是否可以支持下 tab 下划线(蓝色)的长度的配置

### What does the proposed API look like?
```ts
<tabs
  borderBottomHidden={true}
  underLineStyle={{width: 20}}
/>
```

**Comment by bang88** [comment]
> - [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.
>
> ### What problem does this feature solve?
>
> 1.是否可以增加 tabs 组件的下面灰线的 api, 设计里很多的 tab 是没有下划线样式的, 说的是那一根灰色的边框线. 2.是否可以支持下 tab 下划线(蓝色)的长度的配置
>
> ### What does the proposed API look like?
>
> ```ts
> <tabs borderBottomHidden={true} underLineStyle={{ width: 20 }} />
> ```

@wuazhu 颜色可以修改

```tsx
<Tabs
  tabs={tabs}
  styles={{
    topTabBarSplitLine: {
      borderBottomColor: "red"
    }
  }}
>
  ...
</Tabs>
```

很多样式都可以覆盖的

```ts
export default (theme: Theme) =>
  StyleSheet.create<TabsStyle>({
    container: {
      flex: 1,
    },
    topTabBarSplitLine: {
      borderBottomColor: theme.border_color_base,
      borderBottomWidth: 1,
    },
    bottomTabBarSplitLine: {
      borderTopColor: theme.border_color_base,
      borderTopWidth: 1,
    },
  });
···
```

2. 是动态计算的宽度，所以没办法自己设置了。

**Comment by bang88** [comment]
样式覆盖适用于所有组件 有`styles` 属性的。

**Comment by wuazhu** [comment]
> 样式覆盖适用于所有组件 有`styles` 属性的。

那样式的 class 名称是在哪里可以查看呢. 是需要在源码里找么...

@bang88

**Comment by bang88** [comment]
> > 样式覆盖适用于所有组件 有`styles` 属性的。
> 
> 那样式的 class 名称是在哪里可以查看呢. 是需要在源码里找么...
> 
> @bang88

`styles` 会有提示，有哪些字段，目前如果想看全部的话估计得看看代码，因为样式没办法全部发到文档上面。

**Comment by wuazhu** [comment]
> > > 样式覆盖适用于所有组件 有`styles` 属性的。
> > 
> > 
> > 那样式的 class 名称是在哪里可以查看呢. 是需要在源码里找么...
> > @bang88
> 
> `styles` 会有提示，有哪些字段，目前如果想看全部的话估计得看看代码，因为样式没办法全部发到文档上面。

ok, 谢谢~

**Comment by iCodeAnt** [comment]
> > * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.
> > 
> > ### What problem does this feature solve?
> > 1.是否可以增加 tabs 组件的下面灰线的 api, 设计里很多的 tab 是没有下划线样式的, 说的是那一根灰色的边框线. 2.是否可以支持下 tab 下划线(蓝色)的长度的配置
> > ### What does the proposed API look like?
> > ```ts
> > <tabs borderBottomHidden={true} underLineStyle={{ width: 20 }} />
> > ```
> 
> @wuazhu 颜色可以修改
> 
> ```tsx
> <Tabs
>   tabs={tabs}
>   styles={{
>     topTabBarSplitLine: {
>       borderBottomColor: "red"
>     }
>   }}
> >
>   ...
> </Tabs>
> ```
> 
> 很多样式都可以覆盖的
> 
> ```ts
> export default (theme: Theme) =>
>   StyleSheet.create<TabsStyle>({
>     container: {
>       flex: 1,
>     },
>     topTabBarSplitLine: {
>       borderBottomColor: theme.border_color_base,
>       borderBottomWidth: 1,
>     },
>     bottomTabBarSplitLine: {
>       borderTopColor: theme.border_color_base,
>       borderTopWidth: 1,
>     },
>   });
> ···
> ```
> 
> 1. 是动态计算的宽度，所以没办法自己设置了。

感恩，谢谢！
