### ISSUE TITLE
how to change List borderTop&borderBottom color

### ISSUE THREAD

**Issue by liuqing520it** [ant-design/ant-design-mobile-rn#951]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paranoidjk/pen/LWpaKe](https://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
step1: set List styles not working; borderTop&borderBottom Line  i do not want; how to removed?

### What is expected?
List remove borderTop&borderBottom Line;

### What is actually happening?
List set styles not working

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.11.0 |
| System | iOS 13.5 |
| Browser | Simulator |

**Comment by bang88** [comment]
@liuqing520it If you want remove the `Item's`bottom line you can do it like this.

```tsx
<Item
  styles={{
    Line: {
      borderBottomColor: "transparent"
    }
  }}
>
  Text1
</Item>
```

If you want remove the`List's`border style. you can overwrite it like below:

```tsx
<List
  renderHeader={"basic"}
  styles={{
    BodyBottomLine: {
      borderBottomColor: "transparent"
    },
    Body: {
      borderTopColor: "transparent"
    }
  }}
>
  <Item>Text</Item>
</List>
```
