### ISSUE TITLE
可以定制Tabs,bar的样式吗？

### ISSUE THREAD

**Issue by woshiqiang1** [ant-design/ant-design-mobile-rn#96]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
经常需要改变Bar的宽度，目前设置width权限等级不够无法覆盖，也需要自己居中。

### What does the proposed API look like?
暴露一个renderBar属性，或者可以在style中设置tabBarUnderlineStyle的样式（宽度等）

**Comment by zihuahuahua** [comment]
agree

**Comment by bang88** [comment]
`tabs` 有个 `renderTabBar` 的属性，支持自定义 `DefaultTabBar`
