### ISSUE TITLE
Can't resolve '../../Utilities/Platform' in 'path/to/project/node_modules/react-native/Libraries/Components/TextInput'

### ISSUE THREAD

**Issue by f4z3k4s** [ant-design/ant-design-mobile-rn#963]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/f4z3k4s/ant-design-rn-minimal-repro](https://github.com/f4z3k4s/ant-design-rn-minimal-repro)

### Steps to reproduce
Try to run project on web with `npm run web` which runs `expo start --web`. Compliation fails with this error:
```
path/to/project/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js
Module not found: Can't resolve 'path/to/project/node_modules/react-native/Libraries/Components/TextInput'
```

### What is expected?
It is expected that package supports expo's web platform.

### What is actually happening?
Error occurs when trying to use package on web.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.9.0/0.61.5 |
| System | MacOS Catalina (10.15.5) |
| Browser | Version 83.0.4103.106 (Official Build) (64-bit) |

Edit: I do think it could very well be an issue with `@react-native-community/viewpager` that you use as peer-dependency based on [this](https://github.com/expo/web-examples/issues/73) issue.

**Comment by bang88** [comment]
@f4z3k4s Help wanted. I don't know where the issue come from and how to resolve it. This package have some native dependencies I think it will not working on website.

**Comment by gponsinet** [comment]
related to https://github.com/expo/web-examples/issues/73

**Comment by gponsinet** [comment]
I'm trying to resolve it with https://github.com/ricardoribas/expo-react-native-web/blob/master/packages/app/webpack.config.js

**Comment by gponsinet** [comment]
Solution I found is to use antd-mobile as alias for react-native-web
```
const createExpoWebpackConfigAsync = require('@expo/webpack-config')
const paths = require("@expo/config/paths");

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv)

  config.resolve.alias = {
    ...config.resolve.alias,
    '@ant-design/react-native': 'antd-mobile',
  }

  // Maybe you want to turn off compression in dev mode.
  if (config.mode === "development") {
    config.devServer.compress = false;
  }

  // Or prevent minimizing the bundle when you build.
  if (config.mode === "production") {
    config.optimization.minimize = false;
  }

  // FIXME: ../../Utilities/Platform not found for react-native-web
  config.module.rules = [
		...config.module.rules,
  ];

	return config
}
```

**Comment by sreekanth-14** [comment]
Can you please let me know in which file should I set this configuration

**Comment by gponsinet** [comment]
Find the webpack.config.js file, it should be on the root of your project

**Comment by sreekanth-14** [comment]
Thank you. But I have babel.config.js file. There is no webpack.config.js in my root folder

**Comment by gponsinet** [comment]
Okay you can add one to override the expo webpack config https://docs.expo.io/guides/customizing-webpack/

**Comment by sreekanth-14** [comment]
Ohh thanks! I'll try that. By the way did that fix the antd-mobile-rn issue?

**Comment by gponsinet** [comment]
Nope it doesn't, because it seems antd-mobile-rn wants file that doesn't appear to exists in react-native-web

**Comment by gponsinet** [comment]
Pay attention to difference that could exists between https://mobile.ant.design (web) and https://rn.mobile.ant.design (react-native)

**Comment by sreekanth-14** [comment]
Ok thanks

**Comment by ZeroJian** [comment]
same problem, I try @gponsinet webpack config, but still error

**Comment by gponsinet** [comment]
It should work. Try to clean the cache, and don't forget to install antd-mobile.
My current config that works:
```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config')
const paths = require('@expo/config/paths')

module.exports = async function (env, argv) {
	const config = await createExpoWebpackConfigAsync(env, argv)

	config.resolve.alias = {
		...config.resolve.alias,
		'@ant-design/react-native': 'antd-mobile',
		'@ant-design/icons-react-native': '@ant-design/icons-react',
	}

	// Maybe you want to turn off compression in dev mode.
	if (config.mode === 'development') {
		config.devServer.compress = false
	}

	// Or prevent minimizing the bundle when you build.
	if (config.mode === 'production') {
		config.optimization.minimize = false
	}

	return config
}
```

**Comment by ZeroJian** [comment]
@gponsinet wen i install antd-mobile, is works, thanks

**Comment by Nishant-Karki** [comment]
use dedicated emulator for your project instead of web shit😂😂😂

**Comment by alfogo** [comment]
> config.module.rules = [
> 		...config.module.rules,
>   ];

Hi,

Can you please comment on the `config.module.rules` and the Utilities/Platform issue?
How do I tell my componentes from react-native in node_module that they need to point to `./react-native-web/src/exports/Platform` instead of .`./../Utilities/Platform`?

Thx

**Comment by 1uokun** [comment]
> Hi,
> 
> Can you please comment on the `config.module.rules` part and the Utilities/Platform issue? How do I tell my componntes from react-native in `node_modules` that they need to point to `./react-native-web/src/exports/Platform` instead of .`./../Utilities/Platform`?

@alfogo  You should config `config.resolve.alias`,
```js
  config.resolve.alias = {
    ...config.resolve.alias,
    'react-native': 'react-native-web',
    '../../Utilities/Platform': './react-native-web/src/exports/Platform'
  }
```
or require `@expo/webpack-config` like this https://github.com/ant-design/ant-design-mobile-rn/blob/feature/webpack.config.js

-----
By the way ,we will support expo/react-native-web soon

**Comment by alfogo** [comment]
Hi,
Thanks for the response but this still doesn't work:

[image: image.png]

**Comment by SirNameWdl** [comment]
> I'm trying to resolve it with https://github.com/ricardoribas/expo-react-native-web/blob/master/packages/app/webpack.config.js

it is 404
