### ISSUE TITLE
Carousel组件滑动直接触发内部包裹的 TouchableOpacity组件的 onPress事件

### ISSUE THREAD

**Issue by wuazhu** [ant-design/ant-design-mobile-rn#967]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/carousel-s41l4?from-embed=&file=/src/App.js)

### Steps to reproduce
```ts
<Carousel>
  <TouchableOpacity
                          activeOpacity={0.96}
                          key={carousel.url}
                          onPress={() => clickCarousel(carousel)}
                          style={[styles.containerHorizontal]}>
    <Image
       style={{
         width: '100%',
         height: 150
      }}
      source={carousel.img}
      />
  </TouchableOpacity>
</Carousel>
```

### What is expected?
修复该问题

### What is actually happening?
 安卓下一手动滑动Carousel就触发点击了

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 0.62.2 |
| System | macOS |
| Browser | Google Chrome |

**Comment by jpdan** [comment]
same problem

**Comment by 1uokun** [comment]
## Code
```js
import { TouchableOpacity } from 'react-native-gesture-handler'
```

## Refer to 
https://github.com/react-native-community/react-native-viewpager/issues/164#issuecomment-636360923

**Comment by wuazhu** [comment]
> ## Code
> ```js
> import { TouchableOpacity } from 'react-native-gesture-handler'
> ```
> 
> ## Refer to
> [react-native-community/react-native-viewpager#164 (comment)](https://github.com/react-native-community/react-native-viewpager/issues/164#issuecomment-636360923)

谢谢!

**Comment by mack-wang** [comment]
```
import { TouchableOpacity } from 'react-native-gesture-handler'
```
这个方法已经尝试，原以为可以，但真机上发现手指滑动切换，很困难，要慢慢的滑，才能切换，稍快一点，就无法捕捉滑动的手势。
