### ISSUE TITLE
requireNativeComponent: "RNCViewPager"was not found in UIManger

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design-mobile-rn#969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http:// www.XXX.com](http:// www.XXX.com)

### Steps to reproduce
anyWhere use Carousel component  will show this problem

### What is expected?
not show this bug,,,,,,,,,,,,

### What is actually happening?
not show this bug what..

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 0.62.2 |
| System | windows |
| Browser | chorme |

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/87243131-f89cfb80-c465-11ea-9186-a8f14b5c243c.png)
![image](https://user-images.githubusercontent.com/22631753/87243140-005ca000-c466-11ea-8d7b-329dad7fdeaa.png)

**Comment by 1uokun** [comment]
需要卸载并重新打debug包，这样`RNCViewPager`才会自动link并（原生代码才能）生效

**Comment by huan0118** [comment]
![image](https://user-images.githubusercontent.com/22437483/87528381-08178100-c6c0-11ea-85a0-c17d6db67f5d.png)

**Comment by 1uokun** [comment]
@yehoan @huan0118 能发下`package.json`吗

**Comment by huan0118** [comment]
"dependencies": {
    "@ant-design/icons-react-native": "^2.2.1",
    "@ant-design/react-native": "^3.3.0",
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/cameraroll": "^4.0.0",
    "aliyun-oss-react-native": "^1.0.0-alpha.7",
    "axios": "^0.19.0",
    "buffer": "^5.4.3",
    "jcore-react-native": "1.3.2",
    "jpush-react-native": "2.2.13",
    "lodash": "^4.17.15",
    "md5": "^2.2.1",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-android-location-services-dialog-box": "^2.8.2",
    "react-native-barcode": "https://github.com/357280841/react-native-barcode.git",
    "react-native-calendars": "^1.217.0",
    "react-native-circular-progress": "^1.3.6",
    "react-native-code-push": "^6.2.1",
    "react-native-communications": "^2.2.1",
    "react-native-contacts": "^5.2.3",
    "react-native-device-info": "^5.4.0",
    "react-native-drag-sort": "^1.3.6",
    "react-native-dropdownalert": "^4.2.0",
    "react-native-fs": "^2.16.2",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-idle-timer": "^2.1.6",
    "react-native-image-marker": "^0.6.1",
    "react-native-image-picker": "^1.1.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-permissions": "^2.1.5",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-render-html": "^4.2.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-sound": "^0.11.0",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "^12.0.3",
    "react-native-svg-uri": "^1.2.3",
    "react-native-webview": "^8.0.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/plugin-proposal-decorators": "^7.7.4",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^24.0.23",
    "@types/react": "^16.9.16",
    "@types/react-native": "^0.60.25",
    "@types/react-redux": "^7.1.5",
    "@types/react-test-renderer": "^16.9.1",
    "babel-jest": "^24.9.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "16.9.0",
    "typescript": "^3.7.3"
  },

**Comment by 1uokun** [comment]
`dependencies`内必须有`@react-native-community/viewpager`才会自动`link`

**Comment by huan0118** [comment]
> `dependencies`内必须有`@react-native-community/viewpager`才会自动`link`

@react-native-community/viewpager 使用那个版本匹配"@ant-design/react-native": "^3.3.0" ？

**Comment by yehoan** [comment]
之前我使用的5.0.0版本发现这个问题&nbsp; 依赖是正常的&nbsp; 后面听别人说改成3.2.0了&nbsp; 然后重新安装 重新打包 才好的&nbsp;



---Original---

**Comment by huan0118** [comment]
> 之前我使用的5.0.0版本发现这个问题&nbsp; 依赖是正常的&nbsp; 后面听别人说改成3.2.0了&nbsp; 然后重新安装 重新打包 才好的&nbsp;
> […](#)
> ---Original--- From: "dahuan"<notifications@github.com&gt; Date: Wed, Jul 15, 2020 18:13 PM To: "ant-design/ant-design-mobile-rn"<ant-design-mobile-rn@noreply.github.com&gt;; Cc: "Daven"<595249325@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; Subject: Re: [ant-design/ant-design-mobile-rn] requireNativeComponent: "RNCViewPager"was not found in UIManger (#969) dependencies内必须有@react-native-community/viewpager才会自动link @react-native-community/viewpager 使用那个版本匹配"@ant-design/react-native": "^3.3.0" ？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@react-native-community/viewpager ^4.1.0  安卓运行直接崩溃

**Comment by huan0118** [comment]
![image](https://user-images.githubusercontent.com/22437483/87617369-efec4400-c749-11ea-87fe-805e2c1b114f.png)


@ant-design/react-native 依赖已经指定"@react-native-community/viewpager" "^1.1.7"

**Comment by 1uokun** [comment]
# 版本依赖关系图
|@ant-design/react-native|@react-native-community/viewpager|react-native|版本说明|
|--|--|--|--|
|3.0.0到3.1.15|未使用|0.57.7||
|3.2.0+|1.x|0.57.7|AndroidX support|
|4.0.0+|3.x|0.62.2|react-native内置组件ViewPagerAndroid被移除|


## @react-native-community/viewpager 4.x版本更新说明
新版本引用了`androidx.viewpager2`。
如果一定要使用4.x版本，请在自己项目的`app/build.gradle`dependencies中添加(4.x版本文档估计还没写完)
```diff
dependencies {
    ...
+   implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

}
```

**Comment by yehoan** [comment]
我现在的依赖这样的  
![image](https://user-images.githubusercontent.com/22631753/87619560-0a74ec00-c74f-11ea-94da-bc5e26d7efa4.png)
目前没有问题 只是一开始可能升级的5.0X 然后发现这个问题

**Comment by huan0118** [comment]
![image](https://user-images.githubusercontent.com/22437483/87619955-efef4280-c74f-11ea-8ae9-047e350dc800.png)

"dependencies": {
"@ant-design/icons-react-native": "^2.2.1",
"@ant-design/react-native": "^3.3.0",
"@react-native-community/async-storage": "^1.7.1",
"@react-native-community/cameraroll": "^4.0.0",
"aliyun-oss-react-native": "^1.0.0-alpha.7",
"axios": "^0.19.0",
"buffer": "^5.4.3",
"jcore-react-native": "1.3.2",
"jpush-react-native": "2.2.13",
"lodash": "^4.17.15",
"md5": "^2.2.1",
"moment": "^2.24.0",
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-android-location-services-dialog-box": "^2.8.2",
"react-native-calendars": "^1.217.0",
"react-native-circular-progress": "^1.3.6",
"react-native-code-push": "^6.2.1",
"react-native-communications": "^2.2.1",
"react-native-contacts": "^5.2.3",
"react-native-device-info": "^5.4.0",
"react-native-drag-sort": "^1.3.6",
"react-native-dropdownalert": "^4.2.0",
"react-native-fs": "^2.16.2",
"react-native-gesture-handler": "^1.5.2",
"react-native-idle-timer": "^2.1.6",
"react-native-image-marker": "^0.6.1",
"react-native-image-picker": "^1.1.0",
"react-native-image-zoom-viewer": "^3.0.1",
"react-native-permissions": "^2.1.5",
"react-native-progress": "^4.1.2",
"react-native-reanimated": "^1.4.0",
"react-native-render-html": "^4.2.0",
"react-native-screens": "^1.0.0-alpha.23",
"react-native-sound": "^0.11.0",
"react-native-storage": "^1.0.1",
"react-native-svg": "^12.0.3",
"react-native-svg-uri": "^1.2.3",
"react-native-webview": "^8.0.0",
"react-navigation": "^4.0.10",
"react-navigation-stack": "^1.10.3",
"react-navigation-tabs": "^2.6.2",
"react-redux": "^7.1.3",
"redux": "^4.0.4",
"redux-devtools-extension": "^2.13.8",
"redux-thunk": "^2.3.0"
},
"devDependencies": {
"@babel/core": "^7.6.2",
"@babel/plugin-proposal-decorators": "^7.7.4",
"@babel/runtime": "^7.6.2",
"@react-native-community/eslint-config": "^0.0.5",
"@types/jest": "^24.0.23",
"@types/react": "^16.9.16",
"@types/react-native": "^0.60.25",
"@types/react-redux": "^7.1.5",
"@types/react-test-renderer": "^16.9.1",
"babel-jest": "^24.9.0",
"jest": "^24.9.0",
"metro-react-native-babel-preset": "^0.56.0",
"react-native-typescript-transformer": "^1.2.13",
"react-test-renderer": "16.9.0",
"typescript": "^3.7.3"
},


现在我的依赖是这样  还是报 "RNCViewPager"was not found in UIManger  

因为我的react-native是0.61.5所以使用@ant-design/react-native 3.3.0会有问题对吧

**Comment by huan0118** [comment]
显示 yarn add @react-native-community/viewpager@1.1.7
![image](https://user-images.githubusercontent.com/22437483/87621767-1adb9580-c754-11ea-968b-b4355de3e4a5.png)

就ok了

**Comment by inkCrazy** [comment]
https://github.com/ant-design/ant-design-mobile-rn/issues/666
