### ISSUE TITLE
Toast 4.0怎么用? 原来的方法都废弃了

### ISSUE THREAD

**Issue by huapeng222** [ant-design/ant-design-mobile-rn#973]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
4.0使用文档

### What does the proposed API look like?
如何使用4.0的Toast

**Comment by helsonxiao** [comment]
好像网站文档没更新。原来的方法都可以用的，只是推荐用新的。
