### ISSUE TITLE
NoticeBar文字长了就会报错

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design-mobile-rn#974]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pan.baidu.com/s/1fS2vXj-GPO-8iy1XfhY2Lw](https://pan.baidu.com/s/1fS2vXj-GPO-8iy1XfhY2Lw)

### Steps to reproduce
```<NoticeBar
          style={{backgroundColor: '#fff', marginVertical: 5}}
          icon={customIcon}
          hasLine={false}
          isCarousel={false}
          marqueeProps={{loop: true, style: {fontSize: 14, color: '#444'}}}
          // mode="link"
          // action={<Text style={styles.noticeBarMoreBtn}>更多</Text>}
        >
          {测试通知栏文字测试通知栏文字测试通知栏文字测试通知栏文字测试通知栏文字测试通知栏文字测试通知栏文字}
        </NoticeBar>
```

### What is expected?
无报错

### What is actually happening?
准确无误可以复现的报错：
2020-07-15 17:26:02.860 [error][tid:com.facebook.react.JavaScript] Error: Style property 'left' is not supported by native animated module
2020-07-15 17:26:02.875 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: Error: Style property 'left' is not supported by native animated module

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.11.0 |
| System | iOS12.4 |
| Browser | 版本 83.0.4103.116（正式版本） （64 位） |

---
链接: https://pan.baidu.com/s/1fS2vXj-GPO-8iy1XfhY2Lw 提取码: ykct 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by bang88** [comment]
@1uokun 来的真及时。 Thank you 😢

**Comment by bang88** [comment]
需要一个PR。

**Comment by bang88** [comment]
我这几天刚好要把一个APP升级到最新版，快把我搞残了。 各种报错。

**Comment by 1uokun** [comment]
> 我这几天刚好要把一个APP升级到最新版，快把我搞残了。 各种报错。

工作嘛，忙完就轻松了😉。用到`Animated`的组件好多都把AnimatedValue放在state里性能非常不好，这个之前我都没注意到得找时间优化了吧

**Comment by bang88** [comment]
嗯嗯。 你有空也多看看
