### ISSUE TITLE
[Request] Add custom components to Grid data 

### ISSUE THREAD

**Issue by LauraBeatris** [ant-design/ant-design-mobile-rn#979]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Enables to provide custom components to the Grid component data. Currently, it's only possible to provide icons and texts. 

### What does the proposed API look like?
```
const data = [
 {
  component: <Title>Some text</Title>
 }
];
```

**Comment by bang88** [comment]
You can add what you want inside data field. here is the type definition of `DataItem`

```ts
export interface DataItem {
  icon?: any;
  text?: any;
  [key: string]: any;
}
```
