### ISSUE TITLE
Modal,Toast等不能显示在最前端

### ISSUE THREAD

**Issue by cloudychen** [ant-design/ant-design-mobile-rn#983]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/modal/demo/basic.tsx]( https://github.com/ant-design/ant-design-mobile-rn/blob/master/components/modal/demo/basic.tsx)

### Steps to reproduce
使用react-native 的Modal，打开Modal后调用antd的Modal，Toast，都显示在react-native的Modal下面，只有关掉react-native的Modal才能显示。

### What is expected?
新打开的Modal，Toast都能显示在最前端。

### What is actually happening?
无法显示在最前端。

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react-native 0.62 |
| System | mac os 10.15.6 |
| Browser | chrome 84.0.4147.105 |

**Comment by bang88** [comment]
这个没办法解决的。 但是你可以用antd的modal 就支持显示在上一层

**Comment by cloudychen** [comment]
> 这个没办法解决的。 但是你可以用antd的modal 就支持显示在上一层

好的，非常感谢

**Comment by dearGodBless** [comment]
@BANG88 你好，请问我用了antd的modal 替换rn的moal后里面包SafeAreaView似乎不生效，请问有什么处理方式吗？安卓环境
