### ISSUE TITLE
react-native:0.63.2 Super expression must either be null or a function

### ISSUE THREAD

**Issue by DemaHamson** [ant-design/ant-design-mobile-rn#996]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://undefined.com](http://undefined.com)

### Steps to reproduce
import {Toast} from '@ant-design/react-native';

### What is expected?
compile right

### What is actually happening?
Error: Requiring module "node_modules/@ant-design/react-native/lib/index.js", which threw an exception: TypeError: Super expression must either be null or a function

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.11.0/0.63.2 |
| System | android6.0 |
| Browser | dalvik/2.1.0 |

**Comment by bang88** [comment]
@DemaHamson Please upgrade to the latest version and try again.

**Comment by DemaHamson** [comment]
upgrade to 4.0.5 still unresolved

**Comment by DemaHamson** [comment]
> @DemaHamson Please upgrade to the latest version and try again.

still unresolved

**Comment by 1uokun** [comment]
Let us see your `package.json`😊

**Comment by DemaHamson** [comment]
> Let us see your `package.json`😊
{
  "name": "hello",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "GetuiConfigure": "node node_modules/react-native-getui/GetuiConfiguration.js",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@ant-design/icons-react-native": "^2.2.1",
    "@ant-design/react-native": "^4.0.5",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/eslint-config": "^1.1.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^4.0.0",
    "@react-native-community/viewpager": "^3.3.0",
    "@react-navigation/bottom-tabs": "^5.2.7",
    "@react-navigation/material-top-tabs": "^5.1.9",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.13",
    "ansi-styles": "^3.2.1",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "create-react-class": "^15.6.3",
    "es6-symbol": "^3.1.3",
    "has-ansi": "^4.0.0",
    "hermes-engine": "0.1.1",
    "immutable": "^4.0.0-rc.12",
    "lodash": "^4.17.15",
    "lottie-react-native": "^3.3.2",
    "moment": "^2.24.0",
    "pingpp-react-native": "^1.1.0",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-device-info": "^0.21.2",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-getui": "^1.1.38",
    "react-native-image-progress": "^1.1.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^2.6.0",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-swiper": "^1.6.0",
    "react-native-tab-view": "^2.14.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^6.3.1",
    "react-navigation-backhandler": "^2.0.0",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-redux": "^7.2.0",
    "react-relay": "^9.0.0",
    "react-timer-mixin": "^0.13.4",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-persist-immutable": "^4.3.1",
    "redux-saga": "^1.1.3",
    "strip-ansi": "^6.0.0",
    "styled-components": "^5.1.0",
    "supports-color": "^7.1.0",
    "webpack": "^4.36.1"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "babel-jest": "^25.4.0",
    "eslint": "^6.8.0",
    "jest": "^25.4.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by bang88** [comment]
remove node modules and yarn.lock then try again.

**Comment by DemaHamson** [comment]
> remove node modules and yarn.lock then try again.

solved, thanks. missing @react-native-community/cameraroll @react-native-community/segmented-control @react-native-community/slider
