### ISSUE TITLE
文档无法访问 https://rn.mobile.ant.design/

### ISSUE THREAD

**Issue by songs777** [ant-design/ant-design-mobile-rn#997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rn.mobile.ant.design/](https://rn.mobile.ant.design/)

### Steps to reproduce
https://rn.mobile.ant.design/   无法访问

### What is expected?
https://rn.mobile.ant.design/    无法访问

### What is actually happening?
https://rn.mobile.ant.design/     无法访问

| Environment | Info |
|---|---|
| antd | undefined |
| React | 62 |
| System | Mac OS |
| Browser | iOS 12.4 |

**Comment by songs777** [comment]
> Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
> 
> ## 官网
> * Ant Design: https://ant.design
> * Ant Design Pro: https://pro.ant.design
> * Ant Design Pro Preview : https://preview.pro.ant.design
> * Ant Design Mobile: https://mobile.ant.design
> * Ant Motion: https://motion.ant.design
> 
> ## 国内镜像
> * Ant Design: http://ant-design.gitee.io
> * Ant Design 3.x: http://ant-design-3x.gitee.io
> * Ant Design 2.x: http://ant-design-2x.gitee.io
> * Ant Design 1.x: http://ant-design-1x.gitee.io
> * Ant Design Pro: http://ant-design-pro.gitee.io
> * Ant Design Mobile: http://antd-mobile.gitee.io
> * Ant Motion: http://ant-motion.gitee.io
> * Ant Design Pro Preview : https://prosite.z23.web.core.windows.net

antd mobile React Native 组件文档 无法访问

**Comment by weizhanzhan** [comment]
是啊 文档都看不了
