### ISSUE TITLE
Toast Global Config

### ISSUE THREAD

**Issue by songs777** [ant-design/ant-design-mobile-rn#998]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Toast Global Config duration

### What does the proposed API look like?
Toast.success(content, duration, onClose, mask)

**Comment by bang88** [comment]
@songs777 If have > 4.0.0 installed you can configure it via `Toast.config({options})`
